### ISSUE TITLE
File does not contain a valid CIL image.

### ISSUE THREAD

**Issue by KELPETEN** [Splamy/TS3AudioBot#1000]
Cannot open assembly 'TS3AudioBot.exe': File does not contain a valid CIL image.
can you help me how can i fix this error

**Comment by Splamy** [comment]
What did you download and on which platform are you trying to run it

**Comment by KELPETEN** [comment]
I solved my mistake as a result of research
background run command
**ÇÖZÜM**
screen -mdS audiobotname dotnet TS3AudioBot.dll
**don't look at background workers**
screen -ls
audiobotname **stop**
screen -ls
screen -X -S audiobotname quit
