### ISSUE TITLE
How can I build the AudioBot as a executable linux file?

### ISSUE THREAD

**Issue by itseyup** [Splamy/TS3AudioBot#1003]
Hello, as you see in the title, How can I build the AudioBot as a executable linux file?

**Comment by itseyup** [comment]
Still searching for answer...
@Flakebi Maybe you can help me?

**Comment by Splamy** [comment]
This is how we build it in our Ci:
https://github.com/Splamy/TS3AudioBot/blob/develop/appveyor.yml#L46

`dotnet publish TS3AudioBot -c Release --framework net6.0 --self-contained --runtime linux-x64 -p:PublishSingleFile=true,PublishTrimmed=true,IncludeNativeLibrariesForSelfExtract=true`
For other architectures see here: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids
