### ISSUE TITLE
Trying to reconnect

### ISSUE THREAD

**Issue by Litox908** [Splamy/TS3AudioBot#1017]
Hi, I have Teamspeak 3 with Vokility, but the TS3 Audio bot can't connect. I manage to connect them to another TS that is not hosted by Vokility, but not to me. Can someone help me?
![host 1](https://user-images.githubusercontent.com/99780049/203146367-a03a9a4c-4b7b-40b7-98ac-2df96c75baab.png)

**Comment by devangerpl** [comment]
Verify that your teamspeak server is not blocked by the country or hosting from which you allow the music bot. Additionally, add music bots ip to whitelist in teamspeak server files, it helps too.

**Comment by Litox908** [comment]
I contacted Hosting and they said no. I can't whitelist the IP because Hosting doesn't want to.

**Comment by Flakebi** [comment]
Sounds like a problem with your hosting. There’s nothing we can do about that on the audiobot side, so I’ll close this issue.
