### ISSUE TITLE
Bot does PSST ?

### ISSUE THREAD

**Issue by iiAlphaWolf01** [Splamy/TS3AudioBot#102]
Everytime the bot is playing a sound, and it losing connection or something idk, it does PSST. Also when next song is comming it makes same sound psst. why is this? or what is it and can we remove it?

**Comment by davlast** [comment]
the psst is teamspeak3 itself, you can either go "tools" "options" "whisper" and untick "play notify sound when recieving a whisper" or you can edit your config file and change the mode from whisper to voice

**Comment by iiAlphaWolf01** [comment]
Oh I see lmao never used whisper feature in ts3 so didn't knew that but thanks my friends and me thought it was something with rendering but thanks.

_Sent from my Samsung SM-N910F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
