### ISSUE TITLE
how to allow everyone in audiobot

### ISSUE THREAD

**Issue by KELPETEN** [Splamy/TS3AudioBot#1035]
How to allow anyone on audiobot. Can you help me

**Comment by Splamy** [comment]
This to your rights toml

```toml
[[rule]]
"+" = "*"
```

**Comment by KELPETEN** [comment]
groupid or useruid are not connected people. I want it to start on unauthorized people

**Comment by KELPETEN** [comment]
> 

this is what I want. Can you make a sample Rights.toml file and post it?

**Comment by Splamy** [comment]
Clear your entire file and just put this:

```toml
[[rule]]
"+" = "*"
```

should allow everything to everyone

**Comment by KELPETEN** [comment]
Thank you ♥
