### ISSUE TITLE
I urgently need help with using the sendAudio function of the TSLib.dll.

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#1037]
First of all, I am aware that the TS3Audiobot has not been actively maintained for some time now. However, I would greatly appreciate a response from you, as the TS3Audiobot still holds potential for the usage and development of TeamSpeak bots. For my issue, I require knowledge that is only available to the developers (@Splamy ) of this software. I kindly request your assistance once again, as I am unable to resolve the problem on my own. Any other useful advice would also be highly appreciated.

In the past, I have already asked about this issue here (#1028 ). After quickly resolving the problem using the TSLib.dll, I attempted to use the sendAudio() function for playing audio from a bot on a TeamSpeak server for over two more months. The audio file is converted to OPUS format using FFMpeg and then passed to the sendAudio() function in separate pieces. Unfortunately, I only hear fragmented or distorted sounds that sounded like a robot. I have also tried various packet sizes and mixed variations from the master and develop code, but each time with the same result.

Please assist me with my issues by providing an explanation or guidance on how to use the sendAudio() function, or by sharing any examples you may have stored from past development.

**Comment by Flakebi** [comment]
TeamSpeak is based on UDP and that can have packet loss, so you can’t just take an opus stream, split it at a certain size and send this over TS.

You need to take the raw audio stream, *split that* into chunks of e.g. 20 ms (the size that teamspeak picks by default) and for each of the chunks, encode it as an *opus frame* and send each frame with `sendAudio`.

In the AudioBot, such a chunk is converted to an opus frame in the `OpusEncoder`:
https://github.com/Splamy/TS3AudioBot/blob/4c6be03646d78cdbfe007ecc697596256ec23617/TSLib/Audio/Opus/OpusEncoder.cs#L75-L87

**Comment by marv-th** [comment]
Very Thank you for your prompt response. I was already aware that TeamSpeak requires a packet size of 20ms, but I did not know that this fragmentation needs to happen before the Opus conversion. I have decided to do this using the OpusEncoder, but I still haven't achieved any results. Apparently, there are issues with the memory, and I cannot explain them even with the best of intentions.

When executing the playFile() function that I defined, I encounter the following error.

Error: 
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at TSLib.Audio.Opus.NativeMethods.opus_encode(IntPtr, Byte ByRef, Int32, Byte ByRef, Int32)
--------------------------------
   at TSLib.Audio.Opus.OpusEncoder.Encode(System.ReadOnlySpan`1<Byte>, Int32, System.Span`1<Byte>)
   at TS_Bot_TSLib.TSLibBotNewIssue.playFile(TSLib.Full.TsFullClient)
   at TS_Bot_TSLib.TSLibBotNewIssue+<create>d__5.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

Code:
```csharp
public void playFile(TsFullClient tsfullCl)
{


    string inputFilePath = "song.mp3";


    byte[] rawAudioStream = GetRawAudioStream(inputFilePath);
    int sampleRate = 48000;
    int channels = 2;
    int chunkDurationMs = 20;
    List<byte[]> audioChunks = SplitAudioIntoChunks(rawAudioStream, sampleRate, channels, chunkDurationMs);

    var opusEncoder = OpusEncoder.Create(48000, 2, TSLib.Audio.Opus.Application.Audio);

    var encoderPipe = new EncoderPipe(Codec.OpusVoice);


    foreach (ReadOnlySpan<byte> audioChunk in audioChunks)
    {
        try
        {
            int audioChunkLength = audioChunk.Length;
            byte[] encodedBuffer = null;
            Span<byte> encodedBufferResult = opusEncoder.Encode(audioChunk, audioChunkLength, encodedBuffer);


            tsfullCl.SendAudio(encodedBufferResult, Codec.OpusVoice);
            Thread.Sleep(1); //todo Task
        }
        catch (Exception ex)
        {
            Console.WriteLine("ex: " + ex);
        }
                
    }
}


public List<byte[]> SplitAudioIntoChunks(byte[] rawAudioStream, int sampleRate, int channels, int chunkDurationMs)
{
    int bytesPerSample = (16 / 8) * channels;
    int chunkSize = (int)((sampleRate * bytesPerSample * chunkDurationMs) / 1000.0);
    int totalSamples = rawAudioStream.Length / bytesPerSample;

    List<byte[]> audioChunks = new List<byte[]>();

    for (int i = 0; i < totalSamples; i += chunkSize)
    {
        int remainingSamples = totalSamples - i;
        int currentChunkSize = Math.Min(chunkSize, remainingSamples);

        byte[] chunk = new byte[currentChunkSize * bytesPerSample];
        Buffer.BlockCopy(rawAudioStream, i * bytesPerSample, chunk, 0, chunk.Length);

        audioChunks.Add(chunk);
    }

    return audioChunks;
}

public byte[] GetRawAudioStream(string audioFilePath)
{
    using (var audioFile = new AudioFileReader(audioFilePath))
    {
        var format = audioFile.WaveFormat;
        var byteArray = new byte[audioFile.Length];
        int bytesRead;

        using (var memoryStream = new MemoryStream())
        {
            while ((bytesRead = audioFile.Read(byteArray, 0, byteArray.Length)) > 0)
            {
                memoryStream.Write(byteArray, 0, bytesRead);
            }

            return memoryStream.ToArray();
        }
    }
}
```
The playFile() function will only called if bot is created and connected to the server.


I hope you can help me again to solve my problem.

**Comment by Flakebi** [comment]
```C#
byte[] encodedBuffer = null; 
Span<byte> encodedBufferResult = opusEncoder.Encode(audioChunk, audioChunkLength, encodedBuffer);
```

I don’t know which opus library you are using, but you should pass a large enough array instead of null.

**Comment by marv-th** [comment]
Thank you once again for your prompt response to my issue. Your suggestion has definitely helped me make progress like never before. When playing it back, I suspect I can recognize the song again, but it could also be my imagination. However, the audio is very distorted and full of static.

```csharp
int chunkDurationMs = 20;
```
20 ms doesn't work. Although there is no error message, there is also no sound in TeamSpeak. I have tried all values up to 1, and except for 20, 10, and 5, there was an error.
```exception
System.Exception
  HResult=0x80131500
  Nachricht = Encoding failed - BadArg
  Quelle = TSLib
  Stapelüberwachung:
   bei TSLib.Audio.Opus.OpusEncoder.Encode(ReadOnlySpan`1 inputPcmSamples, Int32 sampleLength, Span`1 outputEncodedBuffer)
   bei TS_Bot_TSLib.TSLibBotNewIssue.<>c__DisplayClass6_2.<playFile>b__1() in C:\VisualStudioProjekte\TS-Bot-TSLib\TS-Bot-TSLib\TSLibBotNewIssue.cs: Zeile126
```
In frame size 10, the speech symbol of the bot was blinking, and the aforementioned issues occurred at 5.

I have installed Opus through NuGet packages. The package is called OpusDotNet.opus.win-x64, as it is the only package I found on NuGet that is compatible with my project. I also believe that if there were an issue with the Opus package, an error would be raised by Opus in the TSLib. If I am mistaken, please let me know.

Based on another assumption that it could be due to an incorrect format, I made sure to use a WAV file with a sample rate of 48kHz, 16 bits, and 2 channels. However, it did not solve the problem at all.

I would greatly appreciate it if you could assist me once again in resolving this long-standing issue, so that it can be fixed.

**Comment by Flakebi** [comment]
Sorry, no idea what’s going wrong.

**Comment by marv-th** [comment]
No Problem.
The Package  OpusDotNet.opus.win-x64 wasn't the right and fixing a couple of structure misstakes solved my problem.
Thank you :-)
