### ISSUE TITLE
Default Channel

### ISSUE THREAD

**Issue by iiAlphaWolf01** [Splamy/TS3AudioBot#104]
Would it be possible to make a setting so we can have a default channel for the music bot :D. would be pretty nice to have.

**Comment by Splamy** [comment]
This is a duplicate of #85
Yes, this feature will come, but I can't work on the Bot for the next ~2 weeks. After that I can resume as normally

**Comment by Splamy** [comment]
Just an update here, linking to #85 as resolved.
