### ISSUE TITLE
Error: Auto setup failed!

### ISSUE THREAD

**Issue by igoredm** [Splamy/TS3AudioBot#105]
When i try !bot setup i get this error

**Comment by davlast** [comment]
you need to edit the rights.toml file, just add the group id or the userid u want

https://github.com/Splamy/TS3AudioBot/wiki/Rights

**Comment by davlast** [comment]
you need to edit rights.toml file, and add your group id or user id under the admin part

https://github.com/Splamy/TS3AudioBot/wiki/Rights
