### ISSUE TITLE
pre populate the server ip address in a file

### ISSUE THREAD

**Issue by F4R4N** [Splamy/TS3AudioBot#1054]
I wanted to know if there is a way to pre-populate the IP address of the server in a file or as an env variable or not.
I am using docker to deploy it on my server and I have trouble running the script to configure the IP address manually.
if not I am asking for this feature.
thanks

**Comment by Flakebi** [comment]
There’s no pre-population of any kind in the audiobot, but you should be able to create bot config files before starting the bot.
