### ISSUE TITLE
Is it passible for us to build a teamspeak web client instead of using a desktop client

### ISSUE THREAD

**Issue by newton-miku** [Splamy/TS3AudioBot#1055]
I was wondering that is it passible to build a web client just like discord.

**Comment by Flakebi** [comment]
tl;dr not without a server that translates from a browser-supported protocol to the teamspeak protocol.

It is of course possible to build a web interface, however it is impossible for a website to connect to a teamspeak server. The teamspeak server waits for udp connections, but for good reasons, browsers do not allow web pages to open arbitrary udp connections.
So, one would need a proxy-server of some kind that translates from webrtc for the browser to a udp connection for the teamspeak server.

**Comment by newton-miku** [comment]
ok,I got it,
so it means i need to design a udp proxy-server and a web server(like nginx).That's too much work to do for me.
