### ISSUE TITLE
 Error: Could not load (Failed to run youtube-dl)

### ISSUE THREAD

**Issue by igoredm** [Splamy/TS3AudioBot#106]
How i fix it?

**Comment by Splamy** [comment]
Does your bot have an active internet connection?
Can you give me the few relevant log lines

**Comment by igoredm** [comment]
Yes, have connection! Soundclound works perfectly.

in a youtube link just show this error!


[18:42:49]  Debug: MB Got message from zxxIgãOxxz: !play [URL]https://www.youtube.com/watch?v=Ssvu2yncgWU[/URL]
[18:42:50]Warning: TH Request timed out

**Comment by Splamy** [comment]
- Does this happen with every youtube link?
- Do you have youtube-dl configured for the bot?

**Comment by igoredm** [comment]
Yes any link and no, i don't know how configure youtube-dl

**Comment by Splamy** [comment]
You can add ytdl by downloading the git repo or binary (either is fine) and adding the path in the config to the setting `YoutubeFactory::youtubedlpath`

**Comment by igoredm** [comment]
what archive of youtube-dl i need to copy the path and put on config file?

**Comment by Splamy** [comment]
`Rule has no matcher` indicates that you might have a useless rule in your rights.toml

On the other hand, can you post a few more lines after that (if there are any) ?

**Comment by igoredm** [comment]
Yeah work! Thanks for the help! 
Sorry for the english!

**Comment by davlast** [comment]
you need to create a folder called Playlists in the bot folder,(make sure bot has write access) you can change the location of folder in configTS3AudioBot.cfg file if you want it in a different location, PlaylistManager::PlaylistPath=

!list get <youtube playlist>              (gets playlist from youtube)
!list save <name>                             (saves playlist with name)
!list load <name>                             (loads playlist name from saved playlists)
!list play                                            (plays playlist from song 1)
!list play <#>                                    (plays playlist from song number)
!list list                                               (shows all playlists in playlist folder
