### ISSUE TITLE
How can i to modify the bot's default cannel?

### ISSUE THREAD

**Issue by Hu-XiaoYan** [Splamy/TS3AudioBot#1062]
**Describe the problem**
This is my ts3audiobot's web interface. How can i to modify the bot's default cannel?

**System Information**
- **Platform**: Windows 10 Professional Edition

**Additional Logs, Exceptions, etc**
![image](https://github.com/user-attachments/assets/0de56c6b-2fd0-4625-8f60-b95ebd4425c3)

**Comment by Flakebi** [comment]
Hi, it’s not implemented in the web interface, so you need to do it in the config: https://github.com/Splamy/TS3AudioBot/wiki/Configuration
