### ISSUE TITLE
Is there a way to talk as an audio bot on webpage?

### ISSUE THREAD

**Issue by RyougiShiki-214** [Splamy/TS3AudioBot#1063]
While I was configuring the audio bots on TS3AudioBot admin webpage, I realized that it's quite like a simple teamspeak web client. Is there a way to talk as an audio bot on webpage?

I mean... if this is possible, maybe we could talk to other teamspeak users directly on TS3AudioBot admin webpage instead of using teamspeak client, which is so convience for server administrator.

Or whether there's an API or something that streaming voice in and out of an audiobot from another software or webapp like [free4chat](https://github.com/i365dev/free4chat)?

**Comment by Flakebi** [comment]
Hi, transmitting audio over the webpage is currently not possible and not planned.
The easiest way to got something like this working is probably creating an audio stream via some other software and playing that stream with the audio bot.

**Comment by RyougiShiki-214** [comment]
> Hi, transmitting audio over the webpage is currently not possible and not planned. The easiest way to got something like this working is probably creating an audio stream via some other software and playing that stream with the audio bot.

Thanks for your reply! Anyway I'm still confused that if there have been a software creating an audio stream as you said, how to play that stream through TS3AudioBot?

**Comment by Flakebi** [comment]
> Anyway I'm still confused that if there have been a software creating an audio stream as you said, how to play that stream through TS3AudioBot?

Just `!play http://<address of stream>`
