### ISSUE TITLE
msbuild issue

### ISSUE THREAD

**Issue by MrBilbo** [Splamy/TS3AudioBot#112]
Hi there, when i try to run the msbuild I always get the issue below, can you please help. Thanks!
```
root@My-VPS:/home/TS3AudioBot# msbuild /p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln
Microsoft (R) Build Engine version 15.3.0.0 ( Mon Aug 14 21:03:24 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: TS3AudioBot.sln

For switch syntax, type "MSBuild /help"
```

**Comment by Splamy** [comment]
Huh, strange, you could try to only run `msbuild /p:Configuration=Release /p:Platform=x86`

**Comment by MrBilbo** [comment]
Hi sorry, I then get this issue

```
root@My-VPS:/home/TS3AudioBot# msbuild /p:Configuration=Release /p:Platform=x86
Microsoft (R) Build Engine version 15.3.0.0 ( Mon Aug 14 21:03:24 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/27/2017 11:59:10 PM.
Project "/p:Configuration=Release" on node 1 (default targets).
/p:Configuration=Release(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
Done Building Project "/p:Configuration=Release" (default targets) -- FAILED.

Build FAILED.

"/p:Configuration=Release" (default target) (1) ->
  /p:Configuration=Release(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.21
```

**Comment by Splamy** [comment]
what happens when you just execute `msbuild`
can you also try `bash -c "msbuild /p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln"`

**Comment by MrBilbo** [comment]
if I put in msbuild i get this back

```
root@My-VPS:~# msbuild
Microsoft (R) Build Engine version 15.3.0.0 ( Mon Aug 14 21:03:24 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
root@My-VPS:~#
```


then when using `bash -c "msbuild /p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln"`
I get this
```
root@My-VPS:/home/TS3AudioBot# bash -c "msbuild /p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln"
Microsoft (R) Build Engine version 15.3.0.0 ( Mon Aug 14 21:03:24 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: TS3AudioBot.sln

For switch syntax, type "MSBuild /help"
root@My-VPS:/home/TS3AudioBot#
```

**Comment by Splamy** [comment]
call `msbuild` again in the `/home/TS3AudioBot` folder

**Comment by MrBilbo** [comment]
Whoops sorry :0
It's a lot of code so here is a paste link
https://pastebin.com/p2K5Q0ev

**Comment by Splamy** [comment]
did you do a `nuget restore` inbefore?

**Comment by MrBilbo** [comment]
Just reinstalled the whole file, did `nuget restore` then `msbuild`
now i get this: https://pastebin.com/9D14sM2e

**Comment by Splamy** [comment]
seems fine, you should have the binary in `TS3AudioBot/TS3AudioBot/bin/Debug/` from there you can continue with the normal setup

if you want to try to get rid of that last error and are on ubuntu: try installing `libcurl3`

**Comment by MrBilbo** [comment]
Thank you, it seems to be working now! Your support is 10/10!

**Comment by MrBilbo** [comment]
Just noticed something, I don't have the file `TS3AudioBot/bin/Release` so I can't do the rights thing?

**Comment by Splamy** [comment]
since you cant build the release version, you have the debug version, erverything is the same with the path `TS3AudioBot/bin/Debug`

**Comment by MrBilbo** [comment]
Ah yes, so it is thank you!

**Comment by Splamy** [comment]
Since this issue is older than 2 weeks with no open questions I will close it.

As a small notice if you still have problems compiling you can always download the project precompiled from our [github release page](https://github.com/Splamy/TS3AudioBot/releases) or [our nightly server](http://splamy.de/Nightly#ts3ab).

Feel free to reopen or open a new issue if you have any further questions or problems.
