### ISSUE TITLE
Can not compile with 'AnyCPU'

### ISSUE THREAD

**Issue by Synergyst** [Splamy/TS3AudioBot#113]
Hello.

I have attempted to compile the TS3AudioBot solution using msbuild on the Raspberry Pi 3 (armv7l).
[However when compiling I get this output](https://pastebin.com/S8U3v1cE)

I am compiling with these options: `msbuild /p:Configuration=Release /p:Platform=AnyCPU TS3AudioBot.sln`

msbuild version: Microsoft (R) Build Engine version 15.3.0.0 ( Mon Aug 14 21:03:24 UTC 2017) for Mono
Mono version: Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 16:59:51 UTC 2017)
CSC version: 2.3.0.61801 (3722bb71)

[TS3AudioBot.sln contents](https://pastebin.com/GgWSdH3v)

[Issue where this was mentioned previously](https://github.com/Splamy/TS3AudioBot/issues/107#issuecomment-325192692)

Please tell me if I have missed anything that would pertain to this issue. :)

**Comment by Splamy** [comment]
can you try to install `libcurl3`
btw I'm currently working on a proper AnyCPU config too

**Comment by Synergyst** [comment]
Hello.

I already have libcurl3 installed.

After deleting the old TS3AudioBot.exe file it seems to start without crashing after recompiling.
This is odd since I would imagine msbuild would overwrite the file; perhaps it was skipping some steps since the project was built previously?

Even more oddly it seems to have poor audio performance as opposed to running TS3AudioBot.exe through QEMU (obviously the overhead lag when sending commands is an issue with QEMU still..)
This is not related to this issue, and more so to the fact the Raspberry Pi 3 is probably not fast enough to handle stream transcoding.

However the point of this issue post was to get it compiled and running on another architecture.
The solution for me was to delete the old *.exe files and recompile disregarding the exit code of 255 from msbuild, which seems odd.
