### ISSUE TITLE
Multi-instance version?

### ISSUE THREAD

**Issue by luzzbe** [Splamy/TS3AudioBot#115]
Hello,
I was wondering if a multi-instance version was still planned? I realize that it takes a lot of work and I am very grateful for that.

PS: I hope your exams have gone well.

------
Sorry for my english

**Comment by Splamy** [comment]
Yes multi instance is still planned, but this will need a lot of rework an planning

**Comment by GooG2e** [comment]
I think this will be very inresting, because one of the main applications is radio retranslation
Thank you very much

**Comment by blackjack4494** [comment]
You can actually run multiple instances. There are multiple ways but the easiest one would be this (I am using ubuntu btw):
`

1. Freshly build TS3AudioBot (better to keep one backup untouched).

2. create a dir for every instance and copy the untouched build into it.

3. start and do the config stuff or you can provide specific configs before first start if u want.

`

I am having no problems running multiple instances so far. Unfortunately I found this project lately and just started playing around with it. Hopefully I can contribute a bit.

**Comment by Synergyst** [comment]
Wouldn't that be a bit cumbersome on storage space?

You can already do what you're saying, however there is a switch to specify where a non-default configuration file is to be used.

**Comment by JABirchall** [comment]
to solve the storage issue you can use symlinks for the botfiles and media, and have diffrent configs for each. 
Link symlinking: https://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux
Symlinks on windows 10: https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

As far as im aware, symlinks for windows only works on windows 10 since they added the Linux subsystem.

**Comment by Synergyst** [comment]
I'm not even sure if symlinking everything except the configuration files is really required though..
As far as I understand the end-user would only need to start each bot with a switch to specify where each bot's configuration file is at; `mono TS3AudioBot.exe --Config configTS3AudioBot.cfg`

However, again.. I might be missing something which can cause an issue(s) with running the bots like this.

**Comment by Splamy** [comment]
Note that starting from 0.7.0 the launch parameter has changed to `--config` to be more consistent.

Sure at the moment the most doable thing would be the following way.
With this folder structure
```
root
 |`- bin
   `- <data>
 |`- bot1
   `- bot.cfg
 |-` bot2
   `- bot.cfg
```

call from root/bot1: `mono ../bin/TS3AudioBot.exe --config bot.cfg`
or from root/bot2: `mono ../bin/TS3AudioBot.exe --config bot.cfg`, etc...

make sure to keep relative paths to other files in the cfg correct. So if you want to share one rights.toml across all bots youd for example could put the rights.toml in root/bin, and the cfg: ../bin/rights.toml, or for per instance in each bot1, bot2,.. and in the cfg: ./file.foo

**Comment by Splamy** [comment]
I've pushed a very early development version of multi-instances on the develop branch.
Not that this version breakes the web-api, might be unstable and has missing a lot of configurability to properly use.
