### ISSUE TITLE
Reconnect on server Shutdown

### ISSUE THREAD

**Issue by GooG2e** [Splamy/TS3AudioBot#116]
Hello!
As I understand now bot instance is disconnecting on it's shutdown and doesn't try to reconnect again.
It will be awesome to add feature to trying reconnect bot on server disconnect - for examples, m times with n seconds between reconnects.
Thank you!

**Comment by Synergyst** [comment]
I second this as a useful feature which can be enabled!

For now I just made a BASH script which daemonizes the process which can check if it is online or not as a solution.
It's based on the TeamSpeak 3 server start script.
You can find it here: [TS3AudioBot_startscript.sh](https://gist.github.com/Synergyst/82ec520bd31238d2ba98187cf40ca385)

Kind regards.

**Comment by GooG2e** [comment]
Thank you!

**Comment by Splamy** [comment]
Yeah auto recoonect should be a nice feature, I'll see what I can do

**Comment by Synergyst** [comment]
It would be a much better solution than my BASH script which must be manually invoked..

**Comment by Bluscream** [comment]
It would be neat if the following was in the config

```cs
# Wether the bot should try to reconnect after any kind of connection interruption
QueryConnection::AutoReconnect=True
# The amount of retries for AutoReconnect before giving up (-1 means infinite)
QueryConnection::AutoReconnectMaxRetries=-1
# The delay between reconnect attempts in milliseconds
QueryConnection::AutoReconnectDelay=5000
```

**Comment by Splamy** [comment]
Since multiinstance the bot will automatically reconnect.
