### ISSUE TITLE
Some plugins :)

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#127]
Here i've made some plugins GLHF ;)

https://github.com/Bluscream/TS3AudioBotPlugins

**Comment by Bluscream** [comment]
# SimpleTTS Plugin

**Compability**: 0.10.0-alpha.67/develop/3365ee0f

**Description**: Lets the bot say something for you using a TTS (Text-To-Speech) engine

**Commands**: `!say {text}`,`!broadcast {text}`(Whisper to all clients),`!tts {setting} {...}`

**Notes**: Make sure to load the plugin once to generate the config file, edit it and load it again

**Download**: [SimpleTTS.zip](https://github.com/Splamy/TS3AudioBot/files/2659313/SimpleTTS.zip)

**Comment by Bluscream** [comment]
# Youtube Seach Plugin

**Compability**: 0.10.0-alpha.67/develop/3365ee0f

**Description**: Lets you play and search Youtube videos.

**Commands**: `!yt {query}`,`!search yt {text}`

**Notes**: Make sure to install the dependencies correctly

**Download**: [YoutubeSearchPlugin.zip](https://github.com/Splamy/TS3AudioBot/files/2659338/YoutubeSearchPlugin.zip)

**Comment by Bluscream** [comment]
# Anti AFK Plugin

**Compability**: 0.10.0-alpha.67/develop/3365ee0f

**Description**: Lets you set up the bot to do certain stuff to not get marked as AFK for too long.

**Commands**: `!antiafk`,`!antiafk list`, `!antiafk set {setting} {value}`

**Example `AntiAFK.ini`**:
```ini
[uSggaC3Um04QqMB8vrrQJrAMz5Y=]
Message = Sobald Sie für 10 Minuten inaktiv sind, werden Sie in den AFK-Channel verschoben!
Bot UID = 9Xx3ciS1+gktsG6Z6MSGM6Z3974=
Command = clientupdate

[serveruid]
Min Seconds = 28800
Max Seconds = 32400
```

**Notes**:
Make sure to load the plugin once to generate the config file (SimpleTTS.ini), edit it and load it again

**Download**: [AntiAFK.zip](https://github.com/Splamy/TS3AudioBot/files/2659340/AntiAFK.zip)

**Comment by Bluscream** [comment]
# Auto Pause Plugin

**Compability**: 0.10.0-alpha.67/develop/3365ee0f

**Description**: Let's your server/bot save some traffic by pausing Playback while the bot is alone. **Currently only the mode** `Pause` **and** `Channel` **are working.**

**Example `AutoPause.ini`**:
```ini
[General]
Stop or Pause or Silent = Pause
Channel or Server = Channel
```

**Notes**:
Make sure to load the plugin once to generate the config file (AutoPause.ini), edit it and load it again. **This plugin requires the** `b_virtualserver_client_list` **permission as a result of how TS3AB has no bookkeeping yet.**

**Download**: [AutoPause.zip](https://github.com/Splamy/TS3AudioBot/files/2659439/AutoPause.zip)

**Comment by Flakebi** [comment]
I would say this topic fits more a wiki page than an issue.

**Comment by Bluscream** [comment]
Splamy had something like a pluginrepo planned for his website. This is just a temporary solution for the most requested plugins
