### ISSUE TITLE
Would it be possible to include documentation on how to use TS3Client separately?

### ISSUE THREAD

**Issue by Doldol** [Splamy/TS3AudioBot#133]
I would like to use the included TS3Client in my own project, which I'm assuming is possible.

**Comment by Bluscream** [comment]
Maybe a simple example console app with input/output would be nice, indeed.

**Comment by Splamy** [comment]
Yeah, I will see if I can add a few blocks and some examples out.
When there's a bit more doc I will also generate (or more hopefully set up a automatically generated) doxygen site.

**Comment by Splamy** [comment]
I added a bunch of documentation in hope that it will help a bit looking around.
I have added a manually set up doxygen doc site here: http://splamy.de/TabDoc/namespace_t_s3_client.html
I will add a few examples once I have time.

**Comment by Doldol** [comment]
Okay thanks, looking forward to it.
