### ISSUE TITLE
AFK Function

### ISSUE THREAD

**Issue by iiAlphaWolf** [Splamy/TS3AudioBot#135]
Hey,

I cant really explain what i want so let me try my best:
What if musicbot always goes to the AFK channel and when you type in any channel: !music
then music bot moves to that channel. but it can only move from afk to other channal not from channel to channel.. oftherwise you can steal the bot from your friends lol. and if you type !end it goes back to AFK??
would be funny because then i can host 5 bots and everyone can request one if they are "sleeping"

Do you know what i mean?

**Comment by Splamy** [comment]
Yeah I kind of get the idea. It's just i think (hope) that the multi-instance feature will solve this problem better. That way you wont have 5 bots afk but just 1. Whenever a group wants to get the bot they can write something like `!fork (!play music.mp3)` and it will spawn a new client dynamically. When he stops playing for a while all instances will "decay" (disconnect) until only the master/last bot is left

**Comment by iiAlphaWolf** [comment]
Would be pretty cool, is there also a download site where i can find other versions? betas ect? maybe make us as users able to turn on and off features you make.

**Comment by Splamy** [comment]
The develop branch is alwayts the latest version/progress available. I'm planning on creating a server which will autmatically build nighly versions from the latest dev and master branch

**Comment by iiAlphaWolf** [comment]
what about being able to turn on and off features in config file?

**Comment by Splamy** [comment]
What features for example ?

**Comment by iiAlphaWolf** [comment]
Idk like for example you implement a feature that allows the bot to have a default channel. And a user like me doesn't like that.. are we able to turn this on or off?

**Comment by Splamy** [comment]
You can simply leave this field empty, then nothin will happen.

**Comment by iiAlphaWolf** [comment]
alrighty thanks

**Comment by Splamy** [comment]
if there are any features you dont like you can always request a switch for it. But i already try to make eveything i add as customizable as i can

**Comment by baralalas** [comment]
Great idea, i was thinking about something like this. A command like !come to move the bot to your channel without moving permissions.
Anyway, the multi-instance feature looks a lot better

**Comment by Splamy** [comment]
There is already one, it's called `!bot come`
