### ISSUE TITLE
TS3Client cannot reconnect

### ISSUE THREAD

**Issue by VerHext** [Splamy/TS3AudioBot#137]
I use the client e.g. with the TS3ClientTest. I can connect with the bot once and then disconnect. I try to connect the bot again, it triggers an exception: "Org.BouncyCastle.Crypto.InvalidCipherTextException" in BouncyCastle.Crypto.dll

I hope the error help to fix the problem.

**Comment by Splamy** [comment]
can you give me a stacktrace?

**Comment by VerHext** [comment]
This is the only information:
![](https://i.gyazo.com/e67cba1290cbbf94bd11eabfef78580d.png)

Data: Ts3Crypt.cs Line 388

**Comment by Splamy** [comment]
Tu den haken bei "Bei Auslösen dieses Ausnahmetypes..." raus dann sollte es nicht mehr unterbrechen.

**Comment by VerHext** [comment]
Den habe ich ja für den Fehler extra rein getan. Er läuft ja weiter, es funktioniert jedoch nicht.

**Comment by Splamy** [comment]
Achso, hmm, es könnte sein das da pakete noch von der alten Verbindung ankommen, aber ich hab auch oft bemerk dass der client nach dem zweiten mal nich so ganz willig is wieder zu verbinden. Ich werd mal reinschauen

**Comment by VerHext** [comment]
Ja das kann sein den der Fehler wird im Sekunden takt ausgelöst, nach dem ich die Disconnected bin.
Danke dir.

**Comment by Splamy** [comment]
Reconnect should be fixed on the latest dev branch, please reopen if any further problems persist.
