### ISSUE TITLE
Idea: Restart Function call via WebApi

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#139]
Hello!
A useful function would be to call the bot to exit and retry enter to the server via WebApi.

**Comment by Splamy** [comment]
This might get a bit complicated, can you elaborate what you would want this feature exactly for?
There will be a multi-instance feature comming soon™ which will allow to 'fork'/'connect' and 'close' multiple clients.

**Comment by Mareczin** [comment]
I would want this feature because my hosting server provider have a specific firewall rules and bot can connect to server only after 2 attempts, one after two.

**Comment by Splamy** [comment]
Hmm does this happen with normal clients too?
If you want you can pm me your server address and I can try to find out why he doesnt connect the fist time.

**Comment by Mareczin** [comment]
No, normal users can connect normal. I sent a address to your email.

**Comment by Splamy** [comment]
Thanks, will look when I have time

**Comment by Mareczin** [comment]
hello, how progress?

**Comment by Mareczin** [comment]
> This might get a bit complicated, can you elaborate what you would want this feature exactly for?
There will be a multi-instance feature comming soon™ which will allow to 'fork'/'connect' and 'close' multiple clients.
@Splamy you think about that feature? Its really nice if we can restart a bot from api level, for developers.

**Comment by Splamy** [comment]
The webapi is utterly broken since the multi instance update, but i will work on it next to get it back up and extend it.

**Comment by Splamy** [comment]
Just a quick update I fixed the connecting problem.
Nonetheless I will continue to get the webapi back as soon as possible.

**Comment by Splamy** [comment]
The bot will now loop trying to connect until it works.
Furthermore there now is the api command `/api/connect` to connect a bot to the server
