### ISSUE TITLE
[Avatar]Multiple bots one avatar

### ISSUE THREAD

**Issue by baralalas** [Splamy/TS3AudioBot#143]
Hello Splamy.

I have 3 bots running at same server, when 1 bot change it's avatar the other 2 bots change it too.

What am i doing wrong?

I have 3 diferent bots in 3 diferent folders.

Thx again.

**Comment by Flakebi** [comment]
In TeamSpeak, avatars are set per identity.
To give your bots a different identity, you can just remove the line starting with `QueryConnection::Identity=` so a new one will be generated when they are started.
This should fix your issue.

**Comment by baralalas** [comment]
Worked. Thx.
