### ISSUE TITLE
rights configuration 

### ISSUE THREAD

**Issue by shoxie** [Splamy/TS3AudioBot#145]

**Comment by Splamy** [comment]
If you need an example/default, there's one included in the project here: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Rights/DefaultRights.toml

**Comment by shoxie** [comment]
@Splamy, what about the !history command. Its seems not working .

**Comment by Splamy** [comment]
What do you mean with, it's not working?

**Comment by shoxie** [comment]
@Splamy, it says "Error: No matching function could be found" everytime i try to use it

**Comment by Splamy** [comment]
Which version are you using? Can you upgrade to the lastest dev branch?

**Comment by shoxie** [comment]
@Splamy sorry its my fault. i was misunderstanded. i will close this shortly

**Comment by Splamy** [comment]
Ok, feel free to ask if something is still unclear
