### ISSUE TITLE
Voice Recognition

### ISSUE THREAD

**Issue by blackjack4494** [Splamy/TS3AudioBot#147]
We used our Decoder for Voice Recognition (System.Speech.Recognition). If anyone is interested tell me. We haven't commit anything in the recent ~5 weeks. We implemented some basic keywords like play, pause, stop for testing purposes. Actually we had some kind of Roadmap what to do but due to lack of time and losing some interest in the project we would like to find someone else who is especially interested in voice recognition.
Currently the bot only works if there are only a really few users in the channel since we haven't implemented that the bot separates the voice packets and create a new thread for every user to distinguish between the users and process the voice input correctly.

**Comment by shoxie** [comment]
Can i have ur rights.toml for example ? Cuz i cant make my own one :<

**Comment by iiAlphaWolf** [comment]
Wow, that's a n amazing idea! Tell me when you have released something.
What if the voice commands only work for people with a special rank in the server?
would be amazing!

**Comment by Bluscream** [comment]
@shoxie https://raw.githubusercontent.com/Splamy/TS3AudioBot/master/TS3AudioBot/Rights/DefaultRights.toml

**Comment by VerHext** [comment]
@blackjack4494 I'm interested in your speech recognition implementation and would like to test it.
