### ISSUE TITLE
Save token 

### ISSUE THREAD

**Issue by MrBn100ful** [Splamy/TS3AudioBot#148]
Hi,
first thanks you for all the work you have put in Ts3AudioBot !
So my question is how to save a token and does token are still link to a user ?

Thanks you :)

**Comment by Splamy** [comment]
What do you mean with 'save'? Whenever you call `!api token` you will get a new token which is stored in the database. It will overwrite your last one.
Yes tokens are still bound to user, but you can filter by tokens in the rights system now.
