### ISSUE TITLE
Bot cant Connect and Shut down

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#164]
I'm using Develop Bot, fresh install:

```
[03:08:01]   Info: [============ TS3AudioBot started =============]
[03:08:01]   Info: [=== Date/Time: Sunday, November 19, 2017 3:08:01 AM
[03:08:01]   Info: [=== Version: 0.8.0-unstable.22/develop/02d7d9d3
[03:08:01]   Info: [==============================================]
[03:08:01]   Info: [============ Initializing Modules ============]
[03:08:02]   Info: [=========== Initializing Factories ===========]
[03:08:02]   Info: [================= Finalizing =================]
[03:08:02]   Info: Bot connecting...
[03:08:02]   Info: Using opus version: libopus 1.1.3 (x64)
[03:08:06]   Info: TS3AudioBot shutting down.
[03:08:46]   Info: TS3AudioBot shutting down.
```

**Comment by VerHext** [comment]
Today I found the same problem. On many servers cant connect the Bot.
He could do it in the past... e.g. Server from ts.g-portal.com or other big TeamSpeak server hoster...

When I activate the exceptions, I get the following error:

![](https://i.gyazo.com/79ce30ae0f3145e35f8c17f9d75ebc1f.png)
I hope it helps to fix the problem ...

**Comment by Splamy** [comment]
I've added a debug log to the current dev branch, please try out if this one gives any additional info

**Comment by Splamy** [comment]
I think I see a problem, hmm, I'll post updates when I find out what causes that...

**Comment by VerHext** [comment]
Sorry but the master branch has the self error.

**Comment by Splamy** [comment]
Since when does this happen?

**Comment by VerHext** [comment]
Sorry i don't know

**Comment by Splamy** [comment]
I found a tiny bug and fixed it. Please try the latest dev branch to see if iconnecting works again.

**Comment by VerHext** [comment]
Yes the bot is now connecting... What was the bug?

**Comment by Splamy** [comment]
the tsdnsresolver checked if a port was added with the target address. Accoding to the tsdns standard if yes this port would override the port returned from the srv dns entry. Unfortunately I checked the wrong value and always overwrote the port. So yeah...

**Comment by robotrono** [comment]
This is fixed now? Because cant connect the bot, im using the develop branch.

> $ mono  TS3AudioBot.exe
> [01:44:57]   Info: [============ TS3AudioBot started =============]
> [01:44:57]   Info: [=== Date/Time: Tuesday, December 5, 2017 1:44:57 AM
> [01:44:57]   Info: [=== Version: 0.8.0-unstable.33/develop/6078a0f5
> [01:44:57]   Info: [=== Plattform: Ubuntu 16.04 (64bit)
> [01:44:57]   Info: [==============================================]
> [01:44:57]   Info: [============ Initializing Modules ============]
> [01:44:57]   Info: Using opus version: libopus 1.1.3 (x64)
> [01:44:57]   Info: [==================== Done ====================]
> [01:44:57]   Info: Bot connecting...
