### ISSUE TITLE
Add MAX_CHARs to Clientlib

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#166]
- http://forum.teamspeak.com/threads/78118-Max-channel-name-description-message-poke-length
- https://pytson.4qt.de/ts3defines-module.html#TS3_MAX_SIZE_AWAY_MESSAGE
- https://github.com/svenpaulsen/ts3client-pluginsdk/blob/master/include/teamspeak/public_definitions.h#L7
- https://github.com/svenpaulsen/ts3client-pluginsdk/blob/master/include/teamspeak/public_rare_definitions.h#L7

**Comment by Splamy** [comment]
I messed up, rewrote last commit
