### ISSUE TITLE
Question TS3ClientTest

### ISSUE THREAD

**Issue by HeroinGyrl** [Splamy/TS3AudioBot#172]
I can only conect 50 clients,can I make more?
regards

**Comment by Splamy** [comment]
So apparently you found this line already:
https://github.com/Splamy/TS3AudioBot/blob/master/Ts3ClientTests/Program.cs#L19
You can set it to the number of clients you want to connect

**Comment by HeroinGyrl** [comment]
Thanxs,
I have a last question, how I can control all clients? I want that all clients mute the input, but only 1 works..
best regards

**Comment by Splamy** [comment]
Use the on connect event, each client call this when he connected:
https://github.com/Splamy/TS3AudioBot/blob/master/Ts3ClientTests/Program.cs#L42
to set your client muted look into the query manual and set the appropriate value with clientupdate

**Comment by HeroinGyrl** [comment]
I mean when I write in the console example disconnect then I want that all clients disconnecting
Is this right?
`	
private bool godisconnect = false;
private static void Client_OnConnected(object sender, EventArgs e)
		{
			var client = (Ts3FullClient)sender;
                        if (godisconnect == true) {
                        client.Disconnect();
                            }
		}`
