### ISSUE TITLE
How to use a newer version of the client?

### ISSUE THREAD

**Issue by ReconV** [Splamy/TS3AudioBot#175]
Hi, the bot is great, it fulfills its task 100% (I do not hide missing a few functions ...).
But I have a problem because in the configuration there is "Query Connection :: Client Version =" or as the name suggests changing the Client's version, but what should I do to change (linux)

**Comment by Splamy** [comment]
You can either use a predefined version from [here](https://github.com/Splamy/TS3AudioBot/blob/master/TS3Client/Full/VersionSign.cs#L35-L58) by using for exmple `WIN_3_1` or `LIN_3_1_6` (more will follow some time) or by manually defining a version from the list [here](https://r4p3.net/threads/client-builds.499/) by writing `<version build>|<plattform>|<version sign>` for example: `3.0.19.4 [Build: 1468491418]|Windows|ldWL49uDKC3N9uxdgWRMTOzUuiG1nBqUiOa+Nal5HvdxJiN4fsTnmmPo5tvglN7WqoVoFfuuKuYq1LzodtEtCg==`

**Comment by ReconV** [comment]
Thank you for your answer!
I am sorry that I did not answer for so long. It works :)

**Comment by Splamy** [comment]
No problem
