### ISSUE TITLE
Latest Dev Branch Lost connection.. so loop?

### ISSUE THREAD

**Issue by RalphStoop** [Splamy/TS3AudioBot#180]
Hey buddy,

I had some problems with the hook error but i fixed it by downloading the latest Developing branch and build that one from visual studio 2017. But here is another problem i found, when ever a youtube song is done playing it says lost connection so retrying at 00:00:00, basically its an loop.
Did i do something wrong or is there an setting any advise?

PS, so far I know it didn't lose connection but the song just ended :/

Kind regards,

-Ralph
  
![capture](https://user-images.githubusercontent.com/17458806/34729223-660a1a58-f55c-11e7-9e7d-f0e4686186cf.PNG)

**Comment by Splamy** [comment]
Will look into it

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/4c4511cb8db47fa5168063825b8bc1794f6d2890/TS3AudioBot/Audio/FfmpegProducer.cs#L111
lol, I simply forgot to readd a line I already had... anyway, should be fixed now.

**Comment by RalphStoop** [comment]
How can i apply this the best way? i tried to download the latest dev but still same problem.
Ill try something else and let you know the results

**Comment by RalphStoop** [comment]
nope same results did i do something wrong?

**Comment by Splamy** [comment]
you sure? what do you get with `!version` or `TS3AudionBot.exe -V`

**Comment by RalphStoop** [comment]
Well its odd, because when I play a 5 seconds long video it will just stop and don't give any error or loop, but when i play a song like this one: 
**https://www.youtube.com/watch?v=pBkHHoOIIn8&list=PLrWdXJsUG2qGy3z-fcUrmAWYZkEJbuRvf&index=5**
i will loop.

**results !version:**
Version: <?>
Branch: <?>
CommitHash: <?>
**results: TS3AudioBot.exe -V:**
Version: <?>
Branch: <?>
CommitHash: <?>

Lol we cant see its version?! i downloaded the latest dev branch and builded it in visual

**Comment by RalphStoop** [comment]
Could it be because the song link from youtube is out of a playlist and not directly a link to the song?
if you want me to i can test it?

**Comment by Splamy** [comment]
I will see if I find something. Usually the playlist part from youtube is ignored completely

**Comment by Splamy** [comment]
Unfortunately I cant really reproduce this anymore.
(Although I have found another bug)
Can you ensure you are on the correct commit (git status/git log -1), (kinda stange that the version doesnt get included correctly)
If you want you can set the loglevel in the NLog.config to Trace:
```xml
<logger name="TS3AudioBot.*" minlevel="Trace" writeTo="console" />
```
to get a few more log lines from the ffmpeg module.

**Comment by RalphStoop** [comment]
Ill try other versions and see which will work for me.
If you want i can zip this one and send it so you can test it if you want?

**Comment by Splamy** [comment]
Have you tested the latest branch with trace log output?
If nothing else helps you can zip me the project but I dont expect to see anything special...

**Comment by RalphStoop** [comment]
Cant find anything either, I'll send the project asap.

**Comment by RalphStoop** [comment]
[Bot__MusicB.zip](https://github.com/Splamy/TS3AudioBot/files/1628480/Bot__MusicB.zip)

ive sended the password @ splamyn@gmail.com
