### ISSUE TITLE
Setting up the Bot - Setup Guide

### ISSUE THREAD

**Issue by L4rry2k** [Splamy/TS3AudioBot#182]
Hi Everyone,

I recently found this new Bot, and I have to say I'm really impressed. It at first took me hours to get it working as I ran into a number of issues. I now have it running so I will post this to help others. Below are 2 links. One is a Zip with all the files you need including the latest youtube-dl and the latest dev build of the bot. This is the only version working with YouTube I found. The other file is just the setup guide if you would rather that, but you will have to download the bot, ffmpeg and the youtube-dl files yourself.

Complete Zip with Guide: http://www10.zippyshare.com/v/9N8uv8Tm/file.html
Setup Guide: https://pastebin.com/K9LvKkrK

If you read this Splamy you are more than welcome to use this information in the setup guide on the front page of the project. I just thought I'd make this to help others. This is not really an issue but I though this would be the best place to post it.

Good Luck!

**Comment by Bluscream** [comment]
You should only try to help others when you know how it works yourself.

```
      > MainBot::BotGroupId="ServerAdmin UID or Bot group UID"
```

**Comment by Splamy** [comment]
> MainBot::BotGroupId="ServerAdmin UID or Bot group UID"

You usually shouldn't set this value manually, the `!bot setup` step will do this for you. Only set this value if you already have a group and you want the bot to modify this group and set all permissions there.

**Comment by L4rry2k** [comment]
I have a basic understanding of how the bot works and how to set it up. I wasn't aware that the command set that for you, I will change it. And I am working on the video but haven't released it yet, this is why there is no link yet. 

I only made the guide because I found it quite confusing and my YouTube channel is based on helping other do things like this. i believe the guide, though basic, will help set the bot up quickly.

Thanks for the feedback though.

**Comment by Bluscream** [comment]
Could you be so kind and make a tutorial how to install pytson scripts? Many people ask me that question and i have to help them all manually

**Comment by Splamy** [comment]
The background info for this settings value is that you could run the setup command again and the bot will simply update his group instead of creating a new one.

**Comment by Camando** [comment]
maybe include a tutorial on how to build the project using visual studio

**Comment by Splamy** [comment]
Press `F6` ? :P

**Comment by JABirchall** [comment]
If you don't know how to build it, just download the nightly builds https://splamy.de/Nightly
