### ISSUE TITLE
Soundcloud works but youtube doesn't

### ISSUE THREAD

**Issue by yuvali1337** [Splamy/TS3AudioBot#185]
Hi, i just downloaded the bot and i could set it up to work with soundcloud but youtube doesnt work 
![image](https://user-images.githubusercontent.com/15331028/34918942-531b5a90-f964-11e7-9f77-0a1fc081c781.png)

Windows 10 

config - **https://yuv41artworkz.xyz/img/hosting/35J2EJOd.txt**
And a photo of my Audiobot folder
![image](https://user-images.githubusercontent.com/15331028/34918956-7892b93a-f964-11e7-9312-b3bffae97cdc.png)

**Comment by Splamy** [comment]
as you are already using develop, can you update to the latest version unstable.55 ?

**Comment by yuvali1337** [comment]
@Splamy I've fixed it already. But for some reason i cant get the playlist function to work, 
Im writing !playlist add "https://www.youtube.com/watch?v=4LfJnj66HVQ&list=PLuUrokoVSxlfB8EIhy6Jdi9_aszGD5Grb" for example and it just plays the first song

**Comment by davlast** [comment]
Hi
you use ```!list get <playlist link>``` to fetch playlist
then ```!list play``` to play optional you can add ```!list play 5``` to select song number in playlist

**Comment by yuvali1337** [comment]
@davlast Woah. thank you! you may close the topid @Splamy

**Comment by Bluscream** [comment]
You can close the issue yourself
