### ISSUE TITLE
TeamSpeak server 3.1.0

### ISSUE THREAD

**Issue by VerHext** [Splamy/TS3AudioBot#187]
Hey,

i think teamspeak has changed the init protocol in the new teamspeak version. They add a  the line

```
[OUT] clientinitiv alpha=i06Dri9boREG+w== omega=ME0DAgcAAgEgAiEAgt1VXYYXKoUpIgDbmbq7Aw24IclySyv7ye5iFzvYc9QCIQCut+9nN6Z0hiQzWAC86b57Hge95GbN0HGq\/g== ot=1 ip=18.***.**:*
[IN ] initivexpand2 l=AQA1hUFJiiSs0wFXkYuPUJVcDa6XCrZTcsvkB0Ffzz4CmwIITRXgCqeTYAcAAAAgQW5vbnltb3VzAACiIBip9hQaK6P3QhwOJs\/BkPn0ioyIDPaNgzJ6M8x0kiAJf4hxCYAxMQ== beta=Tc+pN4wdDNZQs9aVJ76SxAR8UoP53GjlG98QJ7XtX4HDV34ZMwZqg+ZI7F7XuYwh4as535mK omega=MEsDAWCAwdX3C2n46yvx+hQhEVV19yt1BzRR2j6ueBxgcAAgEgAiAQGpMwIgYD1PbjT0XQZyzD+OzFvyYTUvytG9Ic3\/SDDjvglJZzQ= ot=1 proof=MEUC28oygs6uRIAWuoQ35x+4vasMokRAu\/HtRbHMDUH+QAiEAwunoC0j6sEOBCouIOeNxR1pFcBIh3smjNmiHgWJTpS5x+k= tvd time=1516372945
[OUT] clientek ek=JGMXLO+UsgcdkyPjVPrzjnsdvrtYlcLux07dgdgISYI= proof=MEYCIQDfcjD3+XK0VUV1YA4tulhHAmuNTPXH9Qs+0sycpZvg6wIhAOEx23QU2GQ0t4M1xek4Wqpj8K\/ZWzKQONPrhz0p9HVN

```

I think you can find a good solution. Then the Audiobot can't connect to the server.

**Comment by Splamy** [comment]
I know, I'm working on it...

**Comment by ReconV** [comment]
How are the works on the new version going?

**Comment by Splamy** [comment]
I'm making slowly progress

**Comment by Splamy** [comment]
Small update, although I'm really far, I will have to put work on hold till roughly the end of the month due to exams.

**Comment by SkilxGames** [comment]
Any updates?

**Comment by Splamy** [comment]
not yet
I'm also not dead :P
I will write it here when there's progress.

**Comment by Splamy** [comment]
IT WORKS !!!!!!

![3 1](https://user-images.githubusercontent.com/6502527/37567521-8e576c8a-2ac8-11e8-965b-337b594abbf9.gif)

I will polish everything up, remove spaghetti, add spaghetti, eat spaghetti. And we should be ready for release this evening or tomorrow.
Stay tuned!

**Comment by syncu2** [comment]
Congrats! Can you also update the protocol description paper?

**Comment by Splamy** [comment]
It will be updated shortly after

**Comment by SkilxGames** [comment]
Oh boy oh boy please don't make me wait any longer
<img src="https://i.imgur.com/m7lzLQ2.gif">

**Comment by Splamy** [comment]
3.1 is now live on develop branch. Please report any issues you encounter.

**Comment by SkilxGames** [comment]
<img src="https://d3higte790sj35.cloudfront.net/images/eu/jm/c12e495cae6191a563aa3fdac0c89e33.png" width="300px">

Cough cough, sum bugg

**Comment by Splamy** [comment]
fix is already up :P

**Comment by SkilxGames** [comment]
Sh*t man, you are too fast with these updates

**Comment by Splamy** [comment]
Update: I've finally completely integrated the new crypto library. The connection should now be blazing fast again (from ~700ms to <1ms)

**Comment by robotrono** [comment]
@Splamy im trying to compile the develop branch but I get this: 

```
Build FAILED.

"/home/akira/Documents/TS3AudioBot/TS3AudioBot.sln" (default target) (1) ->
"/home/akira/Documents/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj" (default target) (2) ->
"/home/akira/Documents/TS3AudioBot/TS3Client/TS3Client.csproj" (default target) (3:2) ->
(CoreCompile target) -> 
  CSC : error CS1617: Invalid option '7.2' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6. [/home/akira/Documents/TS3AudioBot/TS3Client/TS3Client.csproj]

    0 Warning(s)
    1 Error(s)

```

**Comment by robotrono** [comment]
@Splamy I get this loop error, the bot connects and disconnects:

```
04:39:46.2804|DEBUG Got message from Akira: !play [URL]https://www.youtube.com/watch?v=QJMTLsoMX0Q[/URL]
04:39:46.3708|DEBUG User Akira created session with the bot
04:39:46.7941|DEBUG Falling back to youtube-dl!
04:39:49.2927|DEBUG youtube-dl succeeded!
04:39:49.3010|DEBUG AudioResource start: youtube ID:QJMTLsoMX0Q
04:40:12.9183|DEBUG Bot disconnected. Reason: Timeout
04:40:12.9201| INFO Bot disconnecting.
04:40:12.9243| WARN custom_error: the command failed to execute: Connection closed
04:40:12.9260| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
04:40:13.4519| INFO Bot connecting...
04:40:40.3731|DEBUG Got message from Akira: !play [URL]https://www.youtube.com/watch?v=QJMTLsoMX0Q[/URL]
04:40:40.4577|DEBUG User Akira created session with the bot
04:40:40.6556|DEBUG Falling back to youtube-dl!
04:40:43.2892|DEBUG youtube-dl succeeded!
04:40:43.2917|DEBUG AudioResource start: youtube ID:QJMTLsoMX0Q
04:40:46.9200|DEBUG Bot disconnected. Reason: Timeout
04:40:46.9205| INFO Bot disconnecting.
04:40:46.9221| WARN custom_error: the command failed to execute: Connection closed
04:40:46.9236| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
04:40:47.3541| INFO Bot connecting...
04:41:20.6419|DEBUG Bot disconnected. Reason: Timeout
04:41:20.6433| INFO Bot disconnecting.
04:41:20.6433| WARN Internal error (me==null)
04:41:20.6451| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
04:41:21.2829| INFO Bot connecting...

```

**Comment by Splamy** [comment]
@robotrono Hey, please open a seperate issue, as this seems unrelated to 3.1.
To the problem: please post me a debug log with trace level:
```
<logger name="TS3AudioBot.*" minlevel="Trace" writeTo="logfile" />
<logger name="TS3AudioBot.*" minlevel="Trace" writeTo="console" />
<logger name="TS3Client.*" minlevel="Debug" writeTo="logfile" />
<logger name="TS3Client.*" minlevel="Debug" writeTo="console" />
```

**Comment by Splamy** [comment]
Since 3.1 seems stable i'll close this.

**Comment by syncu2** [comment]
Hi, any news on the protocol paper?

**Comment by Splamy** [comment]
@syncu2 The new proto paper is now, up, i'll let someone proof read it the next few days

**Comment by syncu2** [comment]
Many thanks!

**Comment by syncu2** [comment]
Thanks for the great work, is it okay to ask questions about the new protocol here, or should I rather open a new issue at the ts3declarations repo?

Anyways, I am experimenting a little in Python and got the following license block from the server:

(without the license header byte)
```
00000000: 00 AF 6C 71 53 40 36 3F  B5 EA CF 7A 29 6B A7 F1  ..lqS@6?...z)k..
00000010: 02 53 DC 42 1F 95 37 C4  2F 76 95 84 CD 69 8F F4  .S.B..7./v...i..
00000020: 29 00 09 16 E7 80 6B 36  EC 80 00 00 00 25 54 65  ).....k6.....%Te
00000030: 61 6D 53 70 65 61 6B 20  53 79 73 74 65 6D 73 20  amSpeak Systems 
00000040: 47 6D 62 48 00 00 61 97  D8 30 95 AF D4 26 9D 84  GmbH..a..0...&..
00000050: B3 3B 2D F5 34 55 5C EF  CF 78 4E 9A E9 DF 82 4C  .;-.4U\..xN....L
00000060: 8E 8F 83 B3 84 56 00 09  73 90 AB 2F 83 61 F2 00  .....V..s../.a..
00000070: 00 00 24 54 65 61 6D 53  70 65 61 6B 20 73 79 73  ..$TeamSpeak sys
00000080: 74 65 6D 73 20 47 6D 62  48 00 00 89 72 87 6B B7  tems GmbH...r.k.
00000090: B4 D1 C2 86 8E 3E 72 10  E9 C7 2C DA D8 C1 9F 50  .....>r...,....P
000000A0: 67 78 2B 1B AF 93 16 F2  5A 65 3B 02 09 74 82 00  gx+.....Ze;..t..
000000B0: 0A 1D 42 00 05 00 00 00  00 4C 69 76 69 6E 67 2D  ..B......Living-
000000C0: 42 6F 74 73 2E 6E 65 74  00 00 E8 28 2C 10 B2 2A  Bots.net...(,..*
000000D0: 31 D5 74 EE 93 AE 61 D6  91 73 20 9A FC CC B3 4F  1.t...a..s ....O
000000E0: 3A 88 29 AA 43 B6 8E E9  79 40 20 09 DA 75 36 09  :.).C...y@ ..u6.
000000F0: DB 1D F6                                          ...
```

I noticed that for type 00 licenses, there are an additional 4 bytes between the NotValidAfter timestamp and issuer name string, so the actual name string starts at byte 46 rather than 42, right? 
Furthermore, the last license seems to be of type 00 as well but is only 42 bytes long, so it has no name?!

Another question regarding the calculation of IV and MAC: How do I calculate `sharedData`? Like in the old protocol? Does this mean that I need to calculate
`sharedSecret         = ECDH(serverPublicKey, ownPrivateKey)` first, with `serverPublicKey` being the last `next_key` from the license procedure, and what would be `ownPrivateKey`? My TS identity private key or the private key of the ephermal keypair I just created? 

Thank you

**Comment by Splamy** [comment]
Yeah I would prefer a new issue in the other repo.

To your question, yes there is a mistake, I will fix it immediately in the doc.
The 'intermediate' has 4 bytes before the issuer.
The 'server' has 5 bytes before the issuer.

The part for the new sharedData is obviously missing, I will add it too. 
it should be `sharedData = next_key * client_private_key`

**Comment by Splamy** [comment]
Ok fixes are up

**Comment by syncu2** [comment]
In what repository? The file at the tsdeclarations repo seems not to have been updated...

**Comment by Splamy** [comment]
https://github.com/ReSpeak/tsdeclarations
