### ISSUE TITLE
Getting started on implementing a custom TeamSpeak client?

### ISSUE THREAD

**Issue by bloc97** [Splamy/TS3AudioBot#190]
Where can I find enough information about the TeamSpeak protocol and start writing a client?
I'm trying to write a simple client in Java for better IoT integration (I don't need anything fancy, just simple text send/receive and sending voice packets), but I can't find any documentation about how I should start.

Any help or hints would be greatly appreciated, thanks.

**Comment by Splamy** [comment]
You can read our protocol documentation paper here:
https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md
Also this repo contains various concepts in easily parsable formats.

it was previously [here](https://github.com/Splamy/TS3AudioBot/blob/master/TS3Client/ts3protocol.md) but it will be removed since it is a weired place for this file now since we set up our doc repo.

**Comment by bloc97** [comment]
Thanks, that will be very helpful. However, does TS3 use UDP packets for all communications? Looking at the specifications it seems that it is all UDP since it is necessary to resend unacknowledged packets with exponential falloff.

**Comment by Splamy** [comment]
yes, it's all udp

**Comment by bloc97** [comment]
For the 

> 2.5 Packet 4 (Client -> Server)
'y' which is the result of x ^ (2 ^ level) % n

The level I get from the server is [0x00, 0x00, 0x39, 0x16] = 10000
(x ^ (2 ^ 10000)) mod n is impossible to calculate, am I doing something wrong?

Note : 2 ^ 10000 is 3011 digits long.

**Comment by bloc97** [comment]
Or is the ^ here referring to the XOR operation?

**Comment by bloc97** [comment]
Here is the raw packet3 from the server, the 140 to 144th byte is highlighted. The header is in italics.
[*84, 83, 51, 73, 78, 73, 84, 49, 0, 101, -120,* 3, 99, 64, 28, -30, 83, -70, 117, -53, -113, 63, -13, 97, -86, 79, 47, 70, 29, 76, -108, -105, -62, -68, -116, -8, 65, -88, -105, 4, -44, 122, 122, 19, 27, -53, -125, -90, -121, 24, -115, 103, 42, 32, -47, 36, -97, 33, -81, 12, -60, -127, -80, -3, 64, -120, 46, 107, 108, 88, -68, -36, 61, -4, -21, -39, -110, -57, 75, 5, 77, 34, -92, 86, -85, -104, 22, 87, -112, 99, -59, -86, 88, 74, 67, 96, 41, -26, -43, 102, 12, 106, 56, -128, -58, 61, 13, -43, 86, 48, 28, 32, -20, 60, 52, -121, -64, 125, -64, 10, -55, 105, 107, 4, -25, -119, 85, -19, 6, 17, -87, 88, -1, -50, 104, 106, -121, -62, -34, 65, **0, 0, 39, 16,** -21, -116, -6, -33, 63, 117, -8, 113, -36, 89, -19, -73, -47, -36, 104, 84, -27, 25, -127, 112, 9, 37, 26, 4, 45, 18, 84, 26, 83, 67, 42, -95, 127, 121, -119, -13, -88, 48, 12, 72, 110, 90, -39, -66, -106, 71, 21, -85, 42, 33, 120, -31, -32, 79, 84, -41, 5, -8, -30, 38, -32, 69, -103, -100, 95, 1, 49, -74, -100, 44, -18, 119, -116, 126, 118, -11, -91, 61, -73, 87, -18, 62, 89, 10, 99, -102, -124, 101, -88, -98, 108, -68, -69, 120, 119, 83, 0, 0, 0, 0]

**Comment by bloc97** [comment]
Ok, solved the problem. What I assumed is that the exponent is too big, but it is possible to significantly reduce its size using Euler's theorem.

For future reference, the algorithm is:

Define g(x) as Euler's totient function.
x ^ (2 ^ k) mod n == x ^ ((2 ^ k) mod g(n)) mod n
And then it is trivial to just apply the common modular exponentiation algorithm.

**Comment by bloc97** [comment]
Nevermind, n is a huge number, it is impossible to calculate the totient of such a large number... So either I'm reading the wrong values or there is wizardry going on...

**Comment by Splamy** [comment]
just use BigInteger in Java.

**Comment by Flakebi** [comment]
Yeah, computing φ(n) (the eulersche phi/totient function) is the problem that RSA is based on and being able to compute it would brake RSA encryption (and some more), so you should have a hard time computing that ;)

What you can do is taking `mod n` each step after multiplying x.
So you compute `(x^2 mod n) ^ 2 mod n …` (I hope I described this somehow understandable).

If you seek more efficiency, montgomery reduction is the way to go (this goes more into math, as Splamy commented you can simply use some library that has it).

**Comment by bloc97** [comment]
Ah, I was unaware that java already implemented Montgomery reduction in its modPow() function. I thought it was only simple modular exponentiation. Thanks for the information.

The following code runs in about 22ms on my computer.

```Java
        BigInteger x = new BigInteger("32878006774570359216307190512414453734815024711845858985814302013359906676224571864057517441898232179839316906470039235887748992902358250854400787652810336070530280967470770997285440429053186803879037");
        BigInteger n = new BigInteger("77898130960070341501772069500669364440519531421534783575397763758775619778096560479521554583192022357575799725548012588149166448319424189949242058358050730052508358466295626425829884371399991831978634");
        int k = 10000;
        
        System.out.println(x.modPow(new BigInteger("2").pow(k), n));```

**Comment by bloc97** [comment]
When I generate a CipherParameter object what do I pass in as the "header"? Is it the MAC+PID+CID+etc. or is it just the PID+CID+PT without the MAC?

Specifically this part of the code
`CipherParameters parameters = new AEADParameters(new KeyParameter(keyNonce.getKey()), CryptoUtils.MAC_LENGTH * 8, keyNonce.getNonce(), packet.getHeader());`

I'm getting an `org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed t org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)` and I can't seem to find what is causing this.

**Comment by bloc97** [comment]
This works perfectly well, so I must have made a mistake somewhere...
```

        String data = "TS3INIT1    clientinitiv alpha={test==} omega={test=} ip";
        byte[] command = data.getBytes(StandardCharsets.US_ASCII);
        byte[] header = new byte[] {0x0, 0x0, 0x0, 0x0, 0x2};
        
        KeyNonce keyNonce = CryptoUtils.DUMMYPAIR;
        EAXBlockCipher eaxCipher = new EAXBlockCipher(new AESEngine());
        CipherParameters parameters = new AEADParameters(new KeyParameter(keyNonce.getKey()), CryptoUtils.MAC_LENGTH * 8, keyNonce.getNonce(), header);
        
        
        byte[] result;
        int len;
        eaxCipher.init(true, parameters);
        result = new byte[eaxCipher.getOutputSize(command.length)];
        try {
            len = eaxCipher.processBytes(command, 0, command.length, result, 0);
            len += eaxCipher.doFinal(result, len);
        } catch (Exception ex) {
            throw new IllegalStateException("Internal encryption error!");
        }
        
        parameters = new AEADParameters(new KeyParameter(keyNonce.getKey()), CryptoUtils.MAC_LENGTH * 8, keyNonce.getNonce(), header);
        
        byte[] decryptResult;
        
        try {
            eaxCipher.init(false, parameters);
            decryptResult = new byte[eaxCipher.getOutputSize(result.length)];

            len = 0;
            len += eaxCipher.processBytes(result, 0, result.length, decryptResult, 0);
            len += eaxCipher.doFinal(decryptResult, len);
            System.out.println(new String(decryptResult));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
```

**Comment by bloc97** [comment]
Fixed the problem for encrypting then decrypting immediately, but decrypting data from the server still yield EAX failed error

**Comment by Splamy** [comment]
Good to hear that everything works.
Btw if you think something isn't specified detailed enough or some paragraphs are written in a confusing manner just let me so so we can discuss how to make it better. The goal of the paper is to have a solid human-readable and -understandable protocol explanation.

**Comment by bloc97** [comment]
Thanks. But I have a few questions:
1- Why is the **Ack** packet's "resend" column ticked in the 1.11 table? In which cases the **Ack** packets needs to be resent? The server doesn't acknowledge **Ack** packets.
2- What is the use of the "Generation id"? Isn't it just the Packet Id's higher 8 bits if we were to treat it as an unsigned integer?
3- How should I format the string for the `clientinit` command? (And also subsequent commands) Do I replace each word by its value or do I use the same scheme as before where we do "alpha=test" so it becomes `client_nickname=test`. What about spaces? is it `client_nickname=test 1 2` or `client_nickname="test 1 2"`?

**Comment by Splamy** [comment]
1. The resend flag means the you can send the exact same packet again if the corresponding action requires it.
Or simpler explained, your ack will be sent to acknowledge a command packet from the server. But when your ack packet gets lost, the server doesnt know if his command or your ack got lost. So he will simply send the same command packet again, and you can answer with the same ack packet.
2. Yeah more or less, just not an integer but an long, since the generation id is internally an int. (not that a connection will be ever kept long enough to reach that limit anyways :P)
3. I dont know how familiar you are with the query protocol from the server, but the commands are built exactly the same. So you have to ts3 escape them with the `\s`, `\t`, `\r`, etc... and the final command will be built like `commandname param1=value param2=value param3=value\swith\sspaces numberparam=4`
