### ISSUE TITLE
Bot not connecting to server

### ISSUE THREAD

**Issue by SkilxGames** [Splamy/TS3AudioBot#192]
When I attempt to start the bot after configuring the server I receive this:

> [10:51:39]   Info: [============ TS3AudioBot started =============]
> [10:51:39]   Info: [=== Date/Time: 03 February 2018 10:51:39
> [10:51:39]   Info: [=== Version: <?>/<?>/<?>
> [10:51:39]   Info: [==============================================]
> [10:51:39]   Info: [============ Initializing Commands ===========]
> [10:51:39]   Info: [============ Initializing Modules ============]
> [10:51:39]   Info: Using opus version: libopus 1.2.1-fixed (x64)
> [10:51:39]   Info: Database table "audioLogEntries" upgraded to 1
> [10:51:39]   Info: [=========== Initializing Factories ===========]
> [10:51:39]   Info: [=========== Registering callbacks ============]
> [10:51:39]   Info: [================= Finalizing =================]
> [10:51:39]   Info: No rights file found. Creating default.
> [10:51:40]   Info: [==================== Done ====================]
> [10:52:10]  Debug: Bot disconnected. Reason: Timeout
> [10:52:10]   Info: Exiting...
> [10:52:10]Warning: Internal error (me==null)
> [10:52:10]Warning: Could not save avatar: custom_error: the command failed to execute: Connection closed
> [10:52:10]   Info: Closing QueryConnection...
> [10:52:10]   Info: Closing QueryConnection...

The bot just doesn't connect to the server and about after 10 seconds it throws this error and turns off
I tried using different client versions, etc etc. I am running the latest build on Github.
Does anyone know why's this?

(ps. The latest nightly 0.8.0-unstable.55 build works for some reason, but I need a version with the access to the source code)

**Comment by Splamy** [comment]
The source for the develop branch is available right here: https://github.com/Splamy/TS3AudioBot/tree/develop

**Comment by SkilxGames** [comment]
O, thanks, everything's working fine now, yay!
