### ISSUE TITLE
Cannot run on Ubuntu 16.04

### ISSUE THREAD

**Issue by SkilxGames** [Splamy/TS3AudioBot#193]
Hello, I created a issue earlier on this day, and was resolved as the compiled program worked on Windows, but when I throw it to Ubuntu 16.04, it doesn't quite work.

> 21:42:17.0169| INFO [============ TS3AudioBot started =============]
> 21:42:17.0358| INFO [=== Date/Time: Saturday, February 3, 2018 9:42:17 PM
> 21:42:17.0374| INFO [=== Version: <?>/<?>/<?>
> 21:42:17.0512| INFO [=== Plattform: Ubuntu 16.04 (64bit)
> 21:42:17.0516| INFO [==============================================]
> 21:42:17.0516| INFO [============ Initializing Modules ============]
> 21:42:17.0530| INFO Using opus version: libopus 1.1.2 (x64)
> 21:42:17.1381| INFO No rights file found. Creating default.
> 21:42:17.2210| INFO [==================== Done ====================]
> 21:42:17.2232| INFO Bot connecting...
> 21:42:17.4550| INFO Database table "audioLogEntries" upgraded to 1
> 21:42:18.1569|FATAL Critical program failure!.
> 21:42:18.1599| INFO TS3AudioBot shutting down.
> 21:42:18.1613| INFO Bot disconnecting.
> 21:42:18.1688| WARN Internal error (me==null)
> 21:42:18.1733| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
> 21:42:47.7291| INFO TS3AudioBot shutting down.

I added

> <logger name="TS3Client.PacketHandler.Raw" minlevel="Trace" writeTo="console" />
> <logger name="TS3Client.PacketHandler.Raw" minlevel="Trace" writeTo="logfile" />

and got

https://pastebin.com/qZt1n3dD
(Yep this is a patebin link as it's a little of a spam)

I'm running the development build

**Comment by Splamy** [comment]
I guess you don't have mono 5.0+, update to the latest mono version: http://www.mono-project.com/download/

**Comment by SkilxGames** [comment]
Haha you have answers for everything!
