### ISSUE TITLE
Error return from player: Unable to create stream

### ISSUE THREAD

**Issue by RalphStoop** [Splamy/TS3AudioBot#195]
just reinstalled the bot and got this:
http://prntscr.com/icxpi1
http://prntscr.com/icxppk

**Comment by Splamy** [comment]
The master youtube factory is broken, please use develop

**Comment by RalphStoop** [comment]
when i use develop i get these messages:
http://prntscr.com/icz6kp
http://prntscr.com/icz6p0

**Comment by RalphStoop** [comment]
i decided to use new config ect. and got this:
http://prntscr.com/icz8qy

`23:32:58> "AudioBot": Error: Internal player error (Unable to create stream (The system cannot find the file specified))`

**Comment by RalphStoop** [comment]
Problem solved!

Kinda my fault. i deleted everything also old configure files, and re downloaded the youtube-dl and ffmpeg thingy and now its working. odd
