### ISSUE TITLE
3.1.8 Version

### ISSUE THREAD

**Issue by DanonekTM** [Splamy/TS3AudioBot#197]
Hello,
I'm trying to connect to my server, it has been updated to 3.1.0 - and I can't quite get it to work. I'm running the development build.
These are the logs:
https://pastebin.com/1hYLNtH4

**Comment by ReconV** [comment]
Protokół został zmieniony, trwają badania nad nowym.

**Comment by SkilxGames** [comment]
Dokładnie

**Comment by Splamy** [comment]
The 3.1.0 protocol is different and I haven't completely reversed it, yet.
All 3.1 relevant stuff will be in #187.

Nie mam tak duzo czasu teraz. Ale sprobuje to zrobisz ni szybky ni umie.
(sry for my bad polish xD)

**Comment by ReconV** [comment]
I have no problem, we wait and we cheer.
