### ISSUE TITLE
Error: Could not load (No factory wanted to take it or could load it)

### ISSUE THREAD

**Issue by Zane-Does-Games** [Splamy/TS3AudioBot#198]
Hey Splamy,
I know this is probably an issue only I am having (My Luck), or it's something I messed up with youtube-dl.
Whenever I do the command "!Play SongName" It shoots out this error: "Error: Could not load (No factory wanted to take it or could load it)" Any Ideas?
Thanks!
I'm using this version: 0.8.0-unstable.60/develop/119a0e3a 
I'm using this version of windows: Windows 6.2.9200.0 (64bit)

EDIT: I have also tried with the latest release "Version: 0.7.0-unstable.33/develop/0d1d081c" on github, but I still get the same error

**Comment by SkilxGames** [comment]
Which OS are you running on?
Have you installed ffmpeg?

**Comment by Splamy** [comment]
Can you add these lines into your NLog.config into the `<rules>` section
```
<logger name="TS3AudioBot.ResourceFactories.ResourceFactoryManager" minlevel="Trace" writeTo="console" />
<logger name="TS3AudioBot.ResourceFactories.ResourceFactoryManager" minlevel="Trace" writeTo="logfile" />
```
and see if it prints anything interesting

**Comment by Zane-Does-Games** [comment]
Sure. This is what I get `15:31:34.2675|DEBUG Got message from Zane: !play Epic Sax Guy
15:31:34.3839|DEBUG User Zane created session with the bot
15:31:35.0042|TRACE Factory media tried, result: MediaFileNotFound
15:31:35.1133|DEBUG Command Error`

**Comment by Splamy** [comment]
You do realize you cant just simply play a name like "Epic Sax Guy". You'll have to provide a link to either youtube or a local mp3 file or similar...

**Comment by Zane-Does-Games** [comment]
That makes so much more sense. I'm so stupid, Thank you so much
