### ISSUE TITLE
Ability to change hwid in the config

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#199]
Otherwise other users of the same bot can get you banned

```
Input parse of QueryConnection::IdentityOffset failed [Ignoring]
02:32:11.2166| INFO [============ TS3AudioBot started =============]
02:32:11.2882| INFO [=== Date/Time: Monday, February 19, 2018 2:32:11 AM
02:32:11.2882| INFO [=== Version: 0.8.0-unstable.60/develop/119a0e3a
02:32:11.3142| INFO [=== Platform: Windows 6.2.9200.0 (64bit)
02:32:11.3242| INFO [=== Runtime: .NET Framework 4.0.30319.42000
02:32:11.3412| INFO [=== Opus: libopus 1.2.1-fixed (x64)
02:32:11.3527| INFO [==============================================]
02:32:11.3527| INFO [============ Initializing Modules ============]
02:32:11.6672|DEBUG Cyclic core module dependency
02:32:11.6927| INFO [==================== Done ====================]
02:32:11.7217| INFO Bot connecting...
02:32:12.2848| INFO Calculating up to required security level: 25
02:32:46.9112| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
02:32:46.9217| INFO Bot disconnecting.
02:32:46.9402| WARN Internal error (me==null)
02:32:47.5948| INFO Bot connecting...
02:32:47.7898| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
02:32:47.7898| INFO Bot disconnecting.
02:32:47.8138| WARN Internal error (me==null)
02:32:48.6909| INFO Bot connecting...
02:32:48.9079| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
02:32:48.9189| INFO Bot disconnecting.
02:32:48.9189| WARN Internal error (me==null)
02:32:49.4680| INFO TS3AudioBot shutting down.
```

**Comment by CM2Walki** [comment]
Is there any workaround to this available?

**Comment by Bluscream** [comment]
@CM2Walki you can compile ts3client.dll with a different hwid but you would have to do it everytime you want to update

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CM2Walki** [comment]
Well that is a pretty dirty fix. The problem with my setup is that the bot is on a server that has a daily restart. So worst case I would need to recompile the client every day which in turn would give it a new identity each time as far as I can tell, right?

**Comment by Splamy** [comment]
I will push a fix today. It's not that difficult.
Any problems when i tie the hwid, to the uid? This would mean when you want to change your hwid, you'll have to change your identity.
It would kinda defeat the purpose of a hwid, but a changeable hwid in a config file is nothing better.
It's one less config option, and maybe prevent some stupid spammers; when they have to swap their uid along with the hwid.

**Comment by Bluscream** [comment]
I think the whole "hwid" banning of teamspeak is kinda useless, the only thing that can't really be generated is the IP since there's a fixed amount of IP's in this world (Just ignore IPv6). Anyone with bad intentions can just compile his own `ts3client.dll` with random hwid's or provide a precompiled one
