### ISSUE TITLE
Retrieve mp3/icecast tags from online streams

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#200]
- https://stackoverflow.com/questions/5085677/extracting-id3-tags-from-mp3-over-http-live-streaming
- https://gist.github.com/fracasula/5781710
- https://social.msdn.microsoft.com/Forums/windowsapps/en-US/751719a3-4bd7-484d-868d-8d567c651e88/get-mp3-tags-from-a-stream-in-c?forum=wpdevelop

**Comment by Splamy** [comment]
Icecast tags are now loaded as song title.
This feature is on the current develop branch.
Please test if there are any problems.

**Comment by User-RU** [comment]
In 91-dev version not in all bots radio-stream turn on. Also warnings and some errors in the console. 

> <21:40:34> "Админ": !play http://wargaming.fm/1
> <21:40:39> "❉ Wargaming FM ❉1": Error: Could not load. (media: Unknown request error.)
> 
[91_develop_0d4ddda5.log](https://github.com/Splamy/TS3AudioBot/files/3009755/91_develop_0d4ddda5.log)
Configs bots - [Configs.zip](https://github.com/Splamy/TS3AudioBot/files/3009800/Configs.zip)


In version 81-dev everything works without errors.
Working bots (Dev.81)
[81_develop_01607501.log](https://github.com/Splamy/TS3AudioBot/files/3009754/81_develop_01607501.log)

**Comment by User-RU** [comment]
Where I can prescribe user-agent? Preferably for a specific thread (radio-stream).

**Comment by Splamy** [comment]
> FfmpegProducer.StartFfmpegProcessIcy Unable to create icy-stream (Время ожидания операции истекло)

is it possible that the stream was down or not reachable? The bot simply could not get a web response.

> Where I can prescribe user-agent?

Could you give an example for that?

**Comment by User-RU** [comment]
> is it possible that the stream was down or not reachable? The bot simply could not get a web response.

  Radio-stream 100% working. He now play in version 81-dev without somebody problems. The error appeared in version 91-dev. 
  If the bot did not start the stream, then it does not start any station. At the same time, the rest of the bots work good.


> Could you give an example for that?

#EXTINF:-1,ФМ-на-Дону\160-MP3 (Potokovoe.Ru)
#EXTVLCOPT:http-user-agent=PotokovoeRu
http://95.188.107.89:8008/FM-na-donu.mp3

`_Bots seem not accept for playlists station from .m3u files_`

**Comment by User-RU** [comment]
None bot not playback radio-stream.
Version 92-dev
[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/3016810/ts3audiobot.log)

**Comment by Splamy** [comment]
I have a slight idea what the problem could be. I'll try a bit around the newx few days

**Comment by User-RU** [comment]
> I have a slight idea what the problem could be. I'll try a bit around the newx few days

Good. 


In version 93, the bot does not start the second time. 
[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/3040616/ts3audiobot.log)

**Comment by Splamy** [comment]
it's a work in progress commit which isnt finished yet

**Comment by Splamy** [comment]
I rechecked your log; is it possible that you forgot to adjust your ffmpeg path? Because the bot cant find the ffmpeg binary:
```log
2019-03-28 11:08:08.1662| WARN|FfmpegProducer.StartFfmpegProcessInternal Ffmpeg could not be found (Не удается найти указанный файл)
System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
   в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   в TS3AudioBot.Audio.FfmpegProducer.StartFfmpegProcessInternal(FfmpegInstance instance, String arguments)
```
(I'm currently improving on the error message in such case)

**Comment by User-RU** [comment]
> Because the bot cant find the ffmpeg binary:

In 92 - my fail.)

More than 2 the same streams simultaneously does not playing.
`PlayManager.StartResource Error return from player: Unable to create icy-stream (Время ожидания операции истекло)`
[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/3055685/ts3audiobot.log)
Demonstrate work in 81 versions and 96: https://cloud.mail.ru/public/4SH7/ZdAcB9EHS

**Comment by Splamy** [comment]
Thanks for the detailed report. It's fixed.

**Comment by User-RU** [comment]
Thank! Working.

**Comment by User-RU** [comment]
Seem to be, if occur the radio-stream interrupt, then the TS client crashes. Backward the client is not restored. Maybe not because of a radio-stream interrupt.

**Comment by Splamy** [comment]
I've pushed a fix, should be fixed

**Comment by User-RU** [comment]
Good!)

**Comment by User-RU** [comment]
Hi. Crash(
[ts3audiobot_99.log](https://github.com/Splamy/TS3AudioBot/files/3076381/ts3audiobot_99.log)

**Comment by Splamy** [comment]
Seems like me recentent changes to the library resolving broke it. I reverted that change and it should work now again.

**Comment by User-RU** [comment]
Hello! Yet another 'mini-crash')
`|ERROR|FfmpegInstanceReadStreamLoop Failed too many times trying to access ffmpeg. Closing stream.`

[ts3audiobot_102.log](https://github.com/Splamy/TS3AudioBot/files/3077136/ts3audiobot_102.log)

**Comment by NurLutix** [comment]
What about SHOUTcast tags?

**Comment by Splamy** [comment]
shouldn't that be the same ICY tags? At least that's what i found from a google search

**Comment by NurLutix** [comment]
Maybe. How do I set it up so that the current title is there?
