### ISSUE TITLE
Question: Multiple Instances

### ISSUE THREAD

**Issue by P-Kito** [Splamy/TS3AudioBot#204]
Hey!

I want to know what multiple instances give me, when the bot runs under the same identity on ts3. 

When you message it, you message all the bots, so basically they all play the same music, no?

Greetz

**Comment by Najsr** [comment]
Just close chat with the bot and open a new chat windows with the desired one.

**Comment by Splamy** [comment]
They will get own identities each soon.
I'm working on a new config format which will improve this.
