### ISSUE TITLE
3.1.1 Fix?

### ISSUE THREAD

**Issue by c-sakel** [Splamy/TS3AudioBot#205]
Hallo, wann wird es einen Bugfix für die Init1(3.1.1 Server) Version geben?

**Comment by ReconV** [comment]
Look at [https://github.com/Splamy/TS3AudioBot/issues/187](https://github.com/Splamy/TS3AudioBot/issues/187)

**Comment by Splamy** [comment]
Wie gesagt, das wird noch n bissl dauern, das neue protokoll is nich ganz trivial.
Alle updates zu 3.1.X server bezogenen sachen werden wie von ReconV erwähnt in #187 getrackt.
