### ISSUE TITLE
WEBINTERFACE

### ISSUE THREAD

**Issue by blackzon333** [Splamy/TS3AudioBot#208]
when i start the bot with webserver = true 
Give me this error 
http://prntscr.com/imj1mq

**Comment by Splamy** [comment]
Okay I changed it. If you want to enable and use the webinterface you'll have to put ` WebInterface`  folder in the same folder as the bot. (Or up to 4 directories 'over' it)
The `WebInterface` folder is now located at the [root of the repository](https://github.com/Splamy/TS3AudioBot/tree/develop/WebInterface)
