### ISSUE TITLE
How to use Web Interface?

### ISSUE THREAD

**Issue by ReconV** [Splamy/TS3AudioBot#213]
Where I can find the key authorization for Web Interface in TS3AudioBot?
![fsd](https://user-images.githubusercontent.com/22893288/37691854-1d44085c-2cb5-11e8-8d78-f5176d74ebba.png)

**Comment by Splamy** [comment]
The webinterface currently isnt functional. It's more a prototype/mockup.
If it would work you can access it with the same key as for the api. Which you can get with `!api token`
