### ISSUE TITLE
Add Funcionality for Autoplay and More

### ISSUE THREAD

**Issue by HellBz** [Splamy/TS3AudioBot#215]
Add in Config and complete Bor Possible

**Comment by Splamy** [comment]
Mind explaining that a bit?

**Comment by HellBz** [comment]
Ich schreib es mal auf Deutsch, da du ja aus München bist.

Ich habe keine Funktion gefunden, dass wenn der Bot startet, er automatisch beginnt einen Stream, der vordefiniert ist abzuspielen.

Des weiteren wäre es an sich Gut, wenn man dem bot mit einem Paramater bei dem Startbefehl eine andere Config Laden lassen könnte, somit könnte man mehrere Bots aus einem Ordner heraus starten.

Und evtl. Die Funktion einer Fallback Playliste/Streams,
Falls das was mit !play abgespielt wurde zuende ist,
Um das der Bot nicht stumm rumsitzt.

Und ich habe gemerkt,
Wenn der Bot aus Whisper ist und man mit !play was abspielt, 
Dann Whisper er einen Automatisch an, und es gibt keinen weg per !unsub , das er aufhört, nur kicken..

**Comment by Bluscream** [comment]
Off-topic: das sieht eher nach Google Übersetzer statt T9 aus :o

**Comment by HellBz** [comment]
Wieso sollte ich Google Übersetzter nehmen?

Wenn ich doch aus Villingen komme.

Habe übrigens über meinen PHP-TS3 bot das so gemacht, sobald ein Radio Bot kommt, wird er mit !play [Streamlink]  angeschrieben

:wink:

**Comment by Splamy** [comment]
> mit einem Paramater bei dem Startbefehl eine andere Config Laden lassen könnte
das geht bereits mit `-c <datei>` bzw. `--config <datei>`.

> und es gibt keinen weg per !unsub
doch ,`!unsub chan`; er whispert nämlich den channel an nicht dich. Wenn du willst dass er über voice spielt kannst du auch in der config `AudioFramework::AudioMode` auf `voice` stellen.

zu den idle/start funktionen, ja dazu gibts auch schon issues die in planung sind.

Und wo/was genau crasht eig. dev/master sollten beide stabil funktionieren
