### ISSUE TITLE
Invalid parameter size

### ISSUE THREAD

**Issue by KD148** [Splamy/TS3AudioBot#220]
Bot is crashing when you set a nickname greater than 32 chars.

**Comment by Splamy** [comment]
Can you give me a  name example ?
`"AudioBud": Error: The new name is too long or invalid`
```
{
    "ErrorCode": 10,
    "ErrorName": "CommandError",
    "ErrorMessage": "The new name is too long or invalid"
}
```
the bot gives me a safe error.
