### ISSUE TITLE
WebAPI - CommandPlay

### ISSUE THREAD

**Issue by mediabot24** [Splamy/TS3AudioBot#223]
Hi,

i use the newest developer branch and get the following error(422) when try to play a file or stream via WebAPI:

> {
> 	"ErrorCode": 17,
> 	"ErrorName": "MissingContext",
> 	"ErrorMessage": "Command 'CommandPlay' missing execution context 'InvokerData'"
> }

I call the WebAPI with: 

> http://localhost:10001/api/bot/use/0/(/play/test.mp3

If i try to play via TextChat (!play test.mp3) it works perfectly.
Functions like change name also works via WebAPI.

Is it my fault or a (known) bug?

Kind regards

**Comment by Flakebi** [comment]
From the error message, I would guess that the !play command needs to know the invoker,
so it should work if you authenticate yourself with your access token (you can get it with !token).

But that’s just a guess, I could be wrong.
