### ISSUE TITLE
Error: Internal player error 

### ISSUE THREAD

**Issue by Saguare** [Splamy/TS3AudioBot#224]
`
Error: Internal player error (Ffmpeg could not be found (ApplicationName='ffmpeg.exe', CommandLine=' -hide_banner -nostats -i "https/r8---sn-u2oxu-f5fr.googlevideo.com/videoplayback?lmt=1522324442561648&expire=1522766599&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&pl=24&mn=sn-u2oxu-f5fr%2Csn-f5f7lnel&mm=31%2C29&dur=191.781&requiressl=yes&id=o-AAkWUm1V34Q4ipHf-NUGcDtCxql0Wm9jrcd2UwPTxnR1&mv=u&mt=1522744552&ms=au%2Crdu&ip=77.55.221.231&c=WEB&ei=pz7DWpjGBcjr7QSj-ri4Dg&fvip=6&itag=251&source=youtube&keepalive=yes&clen=3202412&gir=yes&key=yt6&mime=audio%2Fwebm&signature=6A2BBAA2850A9DB969FB341D320EC0965041C340.94ACFBBAC02A3518D152C3C306A56D2527C02987&ratebypass=yes" -ac 2 -ar 48000 -f s16le -acodec pcm_s16le pipe:1 ', CurrentDirectory='', Native error= Cannot find the specified file))
`

I have this problem, can I ask for help? I have TS3 AudioBot on linux (Debian).

**Comment by Flakebi** [comment]
As the error says, ffmpeg could not be found.

1. Make sure you have ffmpeg installed (something like `apt-get install ffmpeg` should do the job)
1. What is the value of `QueryConnection::FfmpegPath` in your `configTS3AudioBot.cfg`?
  It should be `QueryConnection::FfmpegPath=ffmpeg`.

**Comment by Saguare** [comment]
apt-get install ffmpeg
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ffmpeg : Depends: libavcodec56 (>= 10:2.6.9) but it is not going to be installed
          Depends: libavdevice56 (>= 10:2.6.9) but it is not going to be installed
          Depends: libavfilter5 (>= 10:2.6.9) but it is not going to be installed
          Depends: libavformat56 (>= 10:2.6.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Flakebi** [comment]
According to https://stackoverflow.com/questions/45965716/unable-to-install-ffmpeg-on-raspbian, you can try to

1. `apt-get update`
1. `apt-get install -f` to fix some package problems
1. `apt-get install libav-tools`
1. Put `QueryConnection::FfmpegPath=avconf` into the config because for whatever reasons, debian calls ffmpeg avconf

**Comment by Saguare** [comment]
14:13:52.6631| INFO [============ TS3AudioBot started =============]
14:13:52.6941| INFO [=== Date/Time: Tuesday, April 3, 2018 2:13:52 PM
14:13:52.7621| INFO [=== Version: 0.9.0-unstable.25/develop/f9264e02
14:13:52.7628| INFO [=== Platform: Linux <?> (64bit)
14:13:52.7628| INFO [=== Runtime: Mono (5.10.1.20 (tarball Thu Mar 29 11:13:12 UTC 2018))
14:13:52.7660| INFO [=== Opus: libopus 1.2~alpha2 (x64)
14:13:52.7660| INFO [==============================================]
14:13:52.7666| INFO [============ Initializing Modules ============]
14:13:53.0814| INFO [==================== Done ====================]
14:13:53.0861| INFO Bot connecting...
14:13:53.5398| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
14:13:53.5424| INFO Bot disconnecting.
14:13:53.5473| WARN Internal error (me==null)
14:13:53.5572| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed

**Comment by Flakebi** [comment]
As the log says `you are banned`.
If the server admin did not ban you, it can happen because of flood prevention by the ts server so waiting some time automatically removes the temporary ban again.

**Comment by Saguare** [comment]
Error: Internal player error (Ffmpeg could not be found (ApplicationName='avconf', CommandLine=' -hide_banner -nostats -i "http/djmixes.radioparty.pl:8035/" -ac 2 -ar 48000 -f s16le -acodec pcm_s16le pipe:1 ', CurrentDirectory='', Native error= Cannot find the specified file))

**Comment by Splamy** [comment]
`apt-get install ffmpeg`

**Comment by Splamy** [comment]
Since this issue hasn't been active for a long time I'll will close it for now.
If you still have any problems feel free to reopen this or open a new issue.
