### ISSUE TITLE
Playlist over API

### ISSUE THREAD

**Issue by KD148** [Splamy/TS3AudioBot#227]
Add possibility to use playlist commands over API. Currently I get this error:

```
{
	"ErrorCode": 17,
	"ErrorName": "MissingContext",
	"ErrorMessage": "Command 'CommandListGet' missing execution context 'UserSession'"
}
```

**Comment by JagueXE** [comment]
Yes would be really helpful to add it to the api.

**Comment by Splamy** [comment]
Playlist over api alpha is ready for testing on develop.
Anyone interested can try it out and give feedback.
Please note, that this will probably not be final yet.
You can check out the live generated api as always [here](https://tab.splamy.de/openapi/index.html#/list/)
