### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by Splamy** [Splamy/TS3AudioBot#229]
Add resource packs to easily translate to bot to different languages.

**Comment by ReconV** [comment]
+1 _It will certainly be useful, but I would leave a graphic sign_

**Comment by Splamy** [comment]
What do you mean with "graphic sign" ?

**Comment by JABirchall** [comment]
Think he might mean the Thumbs up emoji.

**Comment by Bluscream** [comment]
@JABirchall yeah probably just some google translate. Btw you're working at epicgames?

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Splamy** [comment]
No, I'm not, you just got access to their private repos when you subscribed back then.

**Comment by Splamy** [comment]
I have prepared everything for localization.
If there are any new issues please write them here.
You can also write me here when I missed any strings.

If you want to help translate the bot into a different language sing up on this website, and ask for an invite:
https://www.transifex.com/respeak/ts3audiobot/

If you want to translate to a new language, email me and I will add it to the translation list.

I dont know yet how I will distribute the localization files. If you have a good idea let me hear it.
I'll probably let them auto-update on splamy.de but we will see.

**Comment by Najsr** [comment]
Please add Czech language, I'd like to contribute

**Comment by Bluscream** [comment]
Willst du deutsch alleine machen?

**Comment by MrBn100ful** [comment]
I can you add french ?

**Comment by Splamy** [comment]
@Bluscream Deutsch is scho fertig, du kannst aber gerne nochmal drüber schauen.
@MrBn100ful I've added you and the language.

**Comment by MrBn100ful** [comment]
I have finish french.

**Comment by Bluscream** [comment]
@MrBn100ful Two languages at once? Awesome :thumbsup:

**Comment by ReconV** [comment]
Please upgrade strings.resx on transifex.com thank you

**Comment by Splamy** [comment]
There will be about ~5 or 6 additional texts, I will update it immediately when I'm done

**Comment by koznov** [comment]
@Splamy done with russian, please add it in nearest nighlty build. i will test and make some corrects after test. thanks!

**Comment by Splamy** [comment]
Language Packs can now be downloaded here: https://splamy.de/TS3AudioBot
And in the next patch the bot will automatically download a language pack when selecting a language.

**Comment by koznov** [comment]
@Splamy Thanks a lot. I've got some troubles in setting language on latest nightly build:

`2018-07-23 07:53:09.6044|ERROR|Ts3Client.SetupRights Adding permissions failed (permissions_insufficient_permission_power: the command failed to execute: insufficient permission modify power)`

```
Version: 0.9.0-alpha.74
Branch: develop
CommitHash: f29bc469b1abe4e5dbc9b2359b82ec9e5a5fce81
```
I've created folder ru inside root of bot's folder:
![image](https://user-images.githubusercontent.com/16073136/43058001-e84f49e0-8e4d-11e8-99c9-e9c91edaf76c.png)
Inside it there is renamed strings.dll from Russian archive from site to TS3AudioBot.resources.dll:
![image](https://user-images.githubusercontent.com/16073136/43058023-051ee4fe-8e4e-11e8-8ede-b437256d6359.png)
When i'm trying to change language via  !bot.language "ru" - no reaction in log and in chat no changes, but if i'm trying to check language via !settings get language it shows "ru"
`<07:58:36> "TS3 Support": !settings set language "\"en\""
<07:58:39> "TS3 Support": !settings get language
<07:58:39> "Music Bot": en`

Any ideas?

**Comment by koznov** [comment]
When i'm trying to setup language with command !bot.language "ru" it gives me:
` Error: Not enough arguments for function CommandBotAvatar` 
With en option no error in chat but in logs : 
`2018-07-23 08:01:23.7633|ERROR|Ts3Client.SetupRights Adding permissions failed (permissions_insufficient_permission_power: the command failed to execute: insufficient permission modify power)`

**Comment by koznov** [comment]
@Splamy Thanks! now it works. Can i make some changes into translation after test on this build to make more accurate translation ? =)

**Comment by Splamy** [comment]
Sure just notify me and I'll restart the language build script

**Comment by koznov** [comment]
@Splamy please restart the language build script for me - i will made some changes into it. Also you add missing phrases to Transifex ?

**Comment by Splamy** [comment]
thanks for remembering me, I will update the strings.resx file

**Comment by Splamy** [comment]
Language packs are now downloaded automatically if set in the settings.
This concludes this issue.
For more discussions, join request, rebuild requests, etc... please use our gitter.
