### ISSUE TITLE
Grade UpSecurity Level

### ISSUE THREAD

**Issue by DoktorDuckyy** [Splamy/TS3AudioBot#232]
Hello,
how can I grade up my security Level for examle to 25

**Comment by ReconV** [comment]
Take a look `configTS3AudioBot.cfg` next look  `QueryConnection::IdentityLevel=` change the value to the one indicated by you.

**Comment by Splamy** [comment]
As ReconV said, you can set the config value to the level you want, or set it to `auto` and let the bot generate the required level on demand.

**Comment by Splamy** [comment]
Since this issue hasn't been active for a long time I'll will close it for now.
If you still have any problems feel free to reopen this or open a new issue.
