### ISSUE TITLE
Bot takes long to start playing.

### ISSUE THREAD

**Issue by AdriaanBoshoff** [Splamy/TS3AudioBot#233]
It only plays the song 10 seconds after it says AudioResource start: youtube ID:xxxxxxxxxxxx and then skips the first 10 secs of the song.

Ubuntu server 16.04

**Comment by Splamy** [comment]
Maybe there is a timing issue, i will look into it.

**Comment by JABirchall** [comment]
I have experianced this too, But I didnt think it was a bug. Always though it was just the bot downloading and processing the video to play the audio?

**Comment by Splamy** [comment]
Some technical insight: the bot has an internal timer to track the song position and read the sound buffer. When a song gets started the might be a delay until ffmpeg actually starts producing data, but the timer is already running. I suspect this as the problem.

**Comment by Splamy** [comment]
Due to a lot of internal code changes this problems probably isn't relevant anymore. If there are still problems pleas open a new issue instead
