### ISSUE TITLE
API Not working

### ISSUE THREAD

**Issue by ricosw** [Splamy/TS3AudioBot#236]
I executed the !play command via the API and got this error:
Executed API Route:
`http://localhost:8180/api/play/http%3A%2F%2F%2Fmysupercoolmusicstream.com%2Fstream`
```
{
    "ErrorCode": 17,
    "ErrorName": "MissingContext",
    "ErrorMessage": "Command 'CommandPlay' missing execution context 'IPlayerConnection'"
}
```

**Comment by Splamy** [comment]
You need to switch to a bot before you can use a bot specific command;
`http://localhost:8180/api/bot/use/0/(/play/http%3A%2F%2F%2Fmysupercoolmusicstream.com%2Fstream`

**Comment by ricosw** [comment]
Thank you it's working!
