### ISSUE TITLE
Song name

### ISSUE THREAD

**Issue by PortStone** [Splamy/TS3AudioBot#237]
Hey,

if I type in !song it just says the link it streams:

<20:42:23> "AudioBot": http://stream01.iloveradio.de/iloveradio1.mp3

But SinusBot actually says the name: 
<20:43:46> "Musikbot #1": Now playing: AXWELL INGROSSO - DREAMER

Also on SinusBot you can select the actual song name as description and you can announce songs.

Could you add those features as well? I don't really like SinusBot (not open source and so on)

**Comment by Splamy** [comment]
Yes, this is planned.

Since this is a duplicate of #200 please continue further discussion there.

**Comment by lgund** [comment]
Is here now more informations?

**Comment by Splamy** [comment]
As you can see in #200, yes everything basically works. There might still pop up some weird warnings and stuff but I hope to patch everything out until relese.
