### ISSUE TITLE
Autostart playing

### ISSUE THREAD

**Issue by KD148** [Splamy/TS3AudioBot#238]
Add that the bot starts the last played audio whether it's reconnected to the server after a timeout, kick, ...

**Comment by SorryDudeGotcha** [comment]
Deutsch:
Sie könnten das "Autostart-Modul" in der Config unterbringen so, dass ich z.B. nur einen Stream- oder Youtube Link (wir nehmen jetzt mal als Beispiel den von I Love Radio) einfügen muss und dieser dann nach dem Start direkt abgespielt wird. Das könnte in der Config dann so aussehen. 

# Hier können Sie einen gewünschten Stream- oder Youtube Link einfügen um diesen nach dem Start sofort abzuspielen. 
autostart-link= "http://stream01.iloveradio.de/iloveradio1.mp3"

Ich hoffe Sie können dem was ich Ihnen zu erklären versuche folgen.

Mit freundlichen Grüßen
André


English:
You can add the "Autostart-Feature" into the config. The people that wants to use the feature can add a Stream or Youtube Link that will automatically played when the bot starts. The Feature can look like the following example. 

# Here you can add an Stream or Youtube Link that will played automatically if the bot starts.
autostart-link= "http://stream01.iloveradio.de/iloveradio1.mp3"

Sorry for my bad English ^^
Your Andrè

**Comment by TomGamerTV** [comment]
Und wie geht das genau? Wo finde ich den Autostart Feature?

**Comment by Splamy** [comment]
Gar nicht, weil es noch nicht existiert.

**Comment by SorryDudeGotcha** [comment]
@TomGamerTV Das war ein Vorschlag, weshalb ich dort auch das Wörtchen "könnte" benutze. Das war nur eine sagen wir mal option für das hoffentlich bald kommende "Autostartmodul".

**Comment by TheBlackDevWarPixel** [comment]
Wann soll es denn kommen?

**Comment by Splamy** [comment]
You can automatically start/run stuff by settings the `events.onconnect` setting:
For example:
```toml
[events]
#Called when the bot is connected.
onconnect = "!play https://www.youtube.com/watch?v=Mf9WroOPCwI"
```

**Comment by TomGamerTV** [comment]
Wie mache ich es dann wenn ich dann ein zweiten Comand eingeben will beispielsweise !loop on ?

**Comment by Splamy** [comment]
`!xecute (!play song.mp3) (!loop on) (!bot commander on)` etc

**Comment by TomGamerTV** [comment]
Wie genau trage ich es ein?

**Comment by TomGamerTV** [comment]
Was bedeutet das: #Called when the bot does not play anything for a certain amount of time.
onidle = ""

**Comment by Splamy** [comment]
https://translate.google.com/?oe=utf-8&client=firefox-b-ab&um=1&ie=UTF-8&hl=en&client=tw-ob#en/de/Called%20when%20the%20bot%20does%20not%20play%20anything%20for%20a%20certain%20amount%20of%20time.
Or what do you mean?

**Comment by Bluscream** [comment]
https://github.com/Splamy/TS3AudioBot/blob/673e0afb19424101304e515ec2d5d15ccf961a3f/TS3AudioBot/Config/ConfigStructs.cs#L230-L241

**Comment by Manius1988** [comment]
Hello! How to run bot commander and autoplay?
Because as I add:
[events]
#Called when the bot is connected.
onconnect = "!play https://www.youtube.com/watch?v=Mf9WroOPCwI"
onconnect = "!bot commander on"
It does not work...

**Comment by Splamy** [comment]
@Manius1988 you can't put the same field twice in a toml file.
Instead chain the commands like this:
`!xecute (!bot commander on) (!play https://www.youtube.com/watch?v=Mf9WroOPCw )`
