### ISSUE TITLE
Ffmpeg could not be found

### ISSUE THREAD

**Issue by szewiorek** [Splamy/TS3AudioBot#246]
Hello i have a error like this: <16:08:52> "AudioBot1": Error: Internal player error (Ffmpeg could not be found (Odmowa dostępu)). How to fix this?

**Comment by szewiorek** [comment]
PL: cały czas Odmowa dostępu.
EN: Still access denied.

**Comment by tadzu** [comment]
Konto na którym uruchamiasz bota jest w grupie users?
Masz dobre uprawnienia? 
Na koncie root też masz ten problem?

**Comment by Splamy** [comment]
What does it say in the logs, there should be more details I think.
