### ISSUE TITLE
Could not compile :(

### ISSUE THREAD

**Issue by Samistine** [Splamy/TS3AudioBot#26]
http://pastebin.com/j17EKWmy

**Comment by Splamy** [comment]
From your logs I take that only the unit-tests failed to build, so there should be no problem.
Nonetheless you should (and for future releases probably need to) run NuGet restore for the project.
There are plenty of tutorials how to get NuGet (commandline tools) for mono.
When you have it call it with `mono NuGet.exe restore TS3AudioBot.sln`
