### ISSUE TITLE
Error when joining the Server

### ISSUE THREAD

**Issue by DoktorDuckyy** [Splamy/TS3AudioBot#263]
Hi,
when i try to let the bot join on a server i get the following error

http://prntscr.com/jhsb5s

**Comment by Splamy** [comment]
Can you give me a (debug log)[https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs]

**Comment by DoktorDuckyy** [comment]
https://pastebin.com/FwxvCUhN

**Comment by Splamy** [comment]
Which version did you download? I can connect without any problems to this server.
