### ISSUE TITLE
How to add more Instances

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#264]
How to add more Instances? I don't see a command or tutorial.

**Comment by preterive** [comment]
I see no option to create a second instance in the config...

**Comment by Splamy** [comment]
For now call `!connect`, it will connect a second instance to the same server. After the config rework I will also allow to connect to other server

**Comment by preterive** [comment]
ok, i wait for the update...
or is config rework a command?

**Comment by Flakebi** [comment]
You have to wait, @Splamy is working on it.

**Comment by CuzImCloud** [comment]
How can I add more Bots? With another Instance.

And how can I add this in a Webinterface to Control the Bots?

**Comment by Splamy** [comment]
Reading the 4 comments in this issue woud've already answered your question.

You can control the bot via the web api, see in the wiki for more information: https://github.com/Splamy/TS3AudioBot/wiki/WebAPI

**Comment by CuzImCloud** [comment]
@Splamy ich habe dir eine E-Mail gesendet, könnte man sich mal über TS unterhalten?
