### ISSUE TITLE
Frage zum TS3 protocol

### ISSUE THREAD

**Issue by VerHext** [Splamy/TS3AudioBot#268]
Hey,

wenn dann mache ich was falsch, oder du hast bei deiner Dokumentation ein kleiner Fehler drinnen.
Wenn  ich das Packer `initivexpand2` entschlüssel mit dem key und nonce von dir, erhalte ich folgenden Output:

```
initivexpand2 l=AQA1hUFJiiSs0wFXkYuPUJVcDa6XCrZTcsvkB0Ffzz4CmwIITRXgCqeTYAcAAAAgQW5vbnltb3VzAAD+oQ5S6ojmHPLM3Pv2\/yNiCZxhauwlc8cBjilO+NLn9CAKHrp0Ch9jNA== beta=tJqfj3rwcM8TlNBHk8oTy0rJjRFYjzUj2Vr4o3HZLBQKrE6nJa36wyrOTOaCXwfNpDQe1Hae omega=MEwDAgcAAgEgAiEA0Aa40YagOCf50cWne1ksYa4lVx+tew+S0mynjabu7gsCIFv6sqVxlAc8Xt1SxcjTIC3Z\/JHSc8deDN2HEzeyrYfc ot=1 proof=MEQCIG8HZML9XCguHw4E6epQdKji9NrBSVzdnYLcJnH\/c45RAiBjpudZLsS8b5FTid64uQdevZdSfVGwBahia7WJ3V+xbg== tvd time=1526805972
 ```

von dieser time Angabe, ist in der Doku nichts drinnen. Brauche ich die? Oder kann ich die einfach ignorieren?

TeamSpeak Server: 3.2.0 on Linux

**Comment by Splamy** [comment]
Uhm: https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md#32-initivexpandinitivexpand2-client---server
bzw: https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md#322-initivexpand2-client---server

**Comment by VerHext** [comment]
jap, bei dir in der Doku steht:

```
initivexpand2 l={l} beta={beta} omega={omega} ot={ot} proof={proof} tvd={tvd}
```
ich bekomme aber folgenden command:

```
initivexpand2 l={l} beta={beta} omega={omega} ot={ot} proof={proof} tvd={tvd} time={time}
```

ich gehe mal davon aus, das ich das nicht brauche oder?

**Comment by Splamy** [comment]
Ne, der time parameter gibt dir nur den unix timestamp vom server. Theoretisch sollte ein client eine verbindung ablehnen wenn seine zeit mehr als 6h davon abweicht. Aber es is nich für den verbindungsaufbau notwendig

**Comment by VerHext** [comment]
ok, danke

**Comment by Bluscream** [comment]
> Ne, der time parameter gibt dir nur den unix timestamp vom server. Theoretisch sollte ein client eine verbindung ablehnen wenn seine zeit mehr als 6h davon abweicht. Aber es is nich für den verbindungsaufbau notwendig
Zu welchen problemen kann das führen und kann man das dann auch mit dem Hook replacen mit der time vom client oder ganz strippen?

**Comment by Splamy** [comment]
> Zu welchen problemen kann das führen

Keine besondere die ich kenn. Und falls es dich doch im inneren stört kannst im hook das auf die aktuelle uhrzeit ersetzen, dann isses immer egal.

**Comment by VerHext** [comment]
Also noch ne kleine Frage, bzw. ein kleines Problem.

das entschlüsseln habe ich problemlos hinbekommen genauso wie der Schlüsseltausch... 
Aber beim verschlüsseln habe ich noch das ein oder andere Problem...

mit Libtomcrypt versuche ich die Nachricht so zu verschlüsseln: (im Beispiel ein Ack packet)

```
        unsigned char Pid[2];
        int Header[5] = {0x00, 0x00, 0x00, 0x00, 0x06};
        memcpy(Pid, &byte[8], 2);
        unsigned char ct[64];
        eax_addheader(&eax, reinterpret_cast<unsigned char*>(Header), sizeof(Header));
        eax_encrypt( &eax, reinterpret_cast<unsigned char*>(Pid), ct, 2);
        std::cout << "Ack byte :: " << byte_2_str_c(reinterpret_cast<char*>(ct), sizeof(ct)) << std::endl;
//byte_2_str_c gibt den content nur als hex aus. könnte genauso std::hex sein...
```

und natürlich hier noch die Init function:

```
    int err;
    unsigned char nonce[16] = {0x6D, 0x5C, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6C, 0x6C, 0x33, 0x32, 0x2E, 0x63, 0x70, 0x6C};
    unsigned char key[16] = {0x63, 0x3A, 0x5C, 0x77, 0x69, 0x6E, 0x64, 0x6F, 0x77, 0x73, 0x5C, 0x73, 0x79, 0x73, 0x74, 0x65};

    if (register_cipher(&rijndael_desc) == -1) {
        printf("Error registering Rijndael");
        return;
    }

    if ((err = eax_init( &eax, find_cipher("rijndael"), key, 16, nonce, 16, NULL, 0)) != CRYPT_OK) {
        printf("Error eax_init: %s", error_to_string(err));
        return;
    }

```

Wenn ich jetzt also (00-00) verschlüssele bekomme ich von Libtomcrypt folgenden output: 
`EB-B1-00-00-00-00-00-00-9B-0A-8D-6F-0B-7F-00-00-01-3F-F3-98-33-56-00-00-A0-71-46-97-33-56-00-00-A0-71-46-97-33-56-00-00-20-B7-24-6F-0B-7F-00-00-E0-73-24-6F-0B-7F-00-00-BC-64-EE-6E-0B-7F-00-00`

Ich kenne mich im verschlüssel noch nicht also gut aus. Aber für meinen Geschmack ist das zu lange. Splamy weißt du vlt was mein Fehler ist?

**Comment by Splamy** [comment]
`byte_2_str_c(reinterpret_cast<char*>(ct), sizeof(ct))`
Statt `sizeof(ct)` nur die länge der daten.

**Comment by VerHext** [comment]
Ok, und woher bekomme ich die MAC?

**Comment by Splamy** [comment]
Da hab keine ahnung mehr von tomcrypt. Ich errinner mich noch dass es ne methode gab die in etwa `eax_encrypt_authenticate` und `eax_decrypt_verify_memory` oder so ähnlich gab. Ich glaub das waren auch die die ts benutzt hat.
