### ISSUE TITLE
!volume fehler

### ISSUE THREAD

**Issue by FlipAnimated** [Splamy/TS3AudioBot#269]
Ich habe ein kleines Problem. Jeder(der auch keine PERMISSION hat) kann diesen befehlt bentzen

**Comment by Splamy** [comment]
Kann ich die `rights.toml` sehen?

**Comment by FlipAnimated** [comment]
``# Rights declaration file
# For more information about syntax and structure see here:
# https://github.com/Splamy/TS3AudioBot/wiki/Rights

"+" = [
	# Basic stuff
	"cmd.pm",
	"cmd.subscribe",
	"cmd.unsubscribe",
	"cmd.kickme",
	
	# Getting song info
	"cmd.link",
	"cmd.song",
	"cmd.loop",
	"cmd.random",
	"cmd.random.seed",
	"cmd.volume",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
	"cmd.json.merge",
	"cmd.xecute",
	"cmd.getmy.*",

	# Changing bot context in the api
	"cmd.bot.use",
]

# Admin rule
[[rule]]
	# Set your admin Group Ids here
	groupid = []
	# And/Or your admin Client Uids here
	useruid = [ "---" ]

	"+" = "*"


# Playing rights
[[rule]]
	# Set Group Ids you want to allow here
	groupid = []
	# And/Or Client Uids here
	useruid = [ "---" ]
	# Or remove groupid and useruid to allow for everyone

	"+" = [
		# Play controls
		"cmd.play",
		"cmd.pause",
		"cmd.stop",
		"cmd.seek",
		"cmd.volume",

		# Playlist management
		"cmd.list.*",
		"cmd.add",
		"cmd.clear",
		"cmd.previous",
		"cmd.next",
		"cmd.random.*",
		"cmd.repeat.*",
		"cmd.loop.*",

		# History features
		"cmd.history.add",
		"cmd.history.from",
		"cmd.history.id",
		"cmd.history.last",
		"cmd.history.play",
		"cmd.history.till",
		"cmd.history.title",
	]

	# Remove this if you want to allow users to save playlist locally
	"-" = [ "cmd.list.save" ]
``

**Comment by FlipAnimated** [comment]
Das ``---`` steht für zensierung

**Comment by FlipAnimated** [comment]
Ich möchte das niemand nichts kann nur die angegeben ids

**Comment by Splamy** [comment]
dann entfern einfach den oberen `"+"` block
```
"+" = [
	# Basic stuff
	"cmd.pm",
	"cmd.subscribe",
	"cmd.unsubscribe",
	"cmd.kickme",
	
	# Getting song info
	"cmd.link",
	"cmd.song",
	"cmd.loop",
	"cmd.random",
	"cmd.random.seed",
	"cmd.volume",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
	"cmd.json.merge",
	"cmd.xecute",
	"cmd.getmy.*",

	# Changing bot context in the api
	"cmd.bot.use",
]
```

**Comment by FlipAnimated** [comment]
Ok danke

**Comment by Splamy** [comment]
Achja client uid's müssen nicht geheim sein, jeder kann sie auf deinem server einsehen

**Comment by FlipAnimated** [comment]
Ist mir auch aufgefallen xD :D

**Comment by FlipAnimated** [comment]
Klappt !
