### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Samistine** [Splamy/TS3AudioBot#27]
How do I connect if the server has a port number?

Am I suppose to put the query port or regular port for QueryConnection::host=

**Comment by Splamy** [comment]
Just write the ip addres/hostname of the server. It will connect to the default query port (10011)

**Comment by Samistine** [comment]
My server doesn't use the default server query port. :(

**Comment by Splamy** [comment]
I've pushed an update to master, you should be aber to set the port via QueryConnection::port=1234

**Comment by Samistine** [comment]
Thanks so much :)

**Comment by Samistine** [comment]
The bot never connects for me, the query works but bob never connects

**Comment by Splamy** [comment]
Can you provide me the log output of the bot?
How does your `StartTsBot.sh` look like?
This is our one as example:
```
#!/usr/bin/env bash
cd /home/splamy/Bot/TeamSpeak3-Client-linux_amd64
export DISPLAY=:1
#exec ./ts3client_runscript.sh

# Original runscript
export KDEDIRS=
export KDEDIR=
export QTDIR=.
export QT_PLUGIN_PATH=.
export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"

#D1=$(readlink -f "$0")
#D2=$(dirname "${D1}")
#cd "${D2}"

if [ -e ts3client_linux_x86 ]; then
        exec ./ts3client_linux_x86 $@
else
        exec ./ts3client_linux_amd64 $@
fi
```
Do you have set the start script in the config?
BobController::startTSClient=path/to/start.sh
