### ISSUE TITLE
AudioBot is not working

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#270]
Meine Bots lassen sich nicht mehr starten. Habe das Gefühl, dass es sich vlt auf das alte bekannte Problem bezieht, wo es nicht möglich war, Bots mit TS Versionen ab 3.1 verbinden zu lassen. Der Bot wurde dennoch vor 3 Tagen auf GitHub heruntergeladen. 
Eine weitere Sache ist auch noch, dass es nicht möglich ist weitere bots per !connect verbinden zu lassen, da diese wieder nach einigen Sekunden austimen. 

18:49:16.7784| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned

Die Konsole komplett sieht so aus: 
18:49:16.5805| INFO Bot connecting...
18:49:16.7784| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
18:49:16.7789| INFO Bot disconnecting.
18:49:16.7816| WARN Internal error (me==null)
18:49:16.7823| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
18:49:17.8562| INFO TS3AudioBot shutting down.

Ich hoffe ihr könnt mir weiterhelfen;) '/

**Comment by Splamy** [comment]
Siehe mail.

**Comment by marv-th** [comment]
Hey! Wie ich bereits in der E-Mail zuletzt gesagt habe was mein Problem weiterhin ist würde ich mich über eine Antwort zum Behebung des Problems freuen

**Comment by Splamy** [comment]
Sorry ich habe keine Frage in der letzten mail gelesen.
Kannst du genau das Problem beschreiben, bzw den entsprechenden log auszug?

**Comment by marv-th** [comment]
Ein genauen Log kann ich erst morgen schicken. Mein Problem ist, dass durch einen kleinen Programmierfehler der GOSBots, direkt der TS3 Audio Bot gebannt wurde. Das Löschen der Identität in der config bewirkt nichts. Nur eine neu Installation des TeamSpeak Servers. Ist bei meinen Test Server kein Problem gewesen... Nur das auf unserem Hauptserver dies auch ist und wir diesen Server nicht neu aufsetzen können. 

Wenn du willst bzw. Wenn du TeamSpeak hast, können wir gerne morgen über TeamSpeak reden und das Problem darüber klären.

**Comment by ReconV** [comment]
look at this 
https://github.com/Splamy/TS3AudioBot/issues/242#issuecomment-385179021

**Comment by Splamy** [comment]
Yo, du könntest die alternative von dem issue von ReconV probieren wenn du die rechte aud dem server dafür hast. Alternativ ich bin oft auf unserem ts splamy.de

**Comment by marv-th** [comment]
Problem selber behoben! Trotzdem Danke nochmals ;)
