### ISSUE TITLE
Api does not work correctly

### ISSUE THREAD

**Issue by mhalterbeck** [Splamy/TS3AudioBot#272]
I can control my bot via API but I cant play via WebAPI Commands if there is any possibility please send me a Message. 
If i will play the song i will get following message:
{"ErrorCode":17,"ErrorName":"MissingContext","ErrorMessage":"Command 'CommandPlay' missing execution context 'IPlayerConnection'"}

Please send me a api usage. This is my Example:
<?php
$login = 'ts3public id';
$password = 'WrU00IVZUhoej9eLjrGZxkgeYMBA3NiR';
$url = 'http://localhost:8000/api/(/play/https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DpZGlZxGpJ9M))';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, "$login:$password");
$result = curl_exec($ch);
curl_close($ch);  
echo($result);
?>

you can also answer in German :-P

**Comment by Flakebi** [comment]
A quick search for this error message on the issue tracker reveals this: #236
Does this fix your issue?

**Comment by mhalterbeck** [comment]
Yeah this is working fine. Thank you!
