### ISSUE TITLE
TS3AudioBot Playlist management

### ISSUE THREAD

**Issue by DiBaDu** [Splamy/TS3AudioBot#273]
Guten Tag,

Bot funktioniert super aber ich möchte eine Playlist erstellen und dies klappt nicht. Ich habe mir bereits diesen eintrag durchgelesen: https://github.com/Splamy/TS3AudioBot/wiki/Playlists aber anscheinend übersteigt dies meine geistige kompetenz.

Ich möchte eine Playlist erstellen,  die man aufrufen und abspielen lassen kann, bei der die Stream URL von I love Radio wiedergegeben wird, oder ich direkt eine IloveRadioStream.m3u datei wiedergeben kann. 
Aber das klappt alles nicht so wie ich mir das vorstelle.

In der config habe ich `PlaylistManager::PlaylistPath=playlist` aktualisiert. Ich habe einen neuen Ordner erstellt im verzeichness des Bots mit dem namen playlist (https://www.pic-upload.de/view-35382786/bot.png.html)

Mit welchem Befehl kann ich explizit eine Playlist erstellen, eine IloveRadio Stream URL hinzufügen und diese Playlist wiedergeben?

Wäre sehr froh über hilfe.

MfG

**Comment by Splamy** [comment]
Du musst keine Playlist erstellen, eine private editierbare playlist ist immer bereit für jeden nutzer.
Du kannst anfangen deine eigene playlist aufzulisten mit `!list show`
Wenn sie nich leer ist kannst du sie vorher leeren mit `!list clear`
Ein neues lied kann dann mit `!list add lied.mp3` hinzugefügt werden.
Zum speichern kann du sie erst umbennenen mit `!list name <name>` und speicher mit `!list save`; oder beides in einem mit `!list save <name>`
Abspielen einfach mit `!list play`

**Comment by DiBaDu** [comment]
Okey vielen dank hat geklappt. Habe noch einmal 1 Befehl Frage,

habe gesehen, mann kann Befehle zusammenführen.

Gibt es eine Möglichkeite diese 3 Befehle mit einer Textnachricht auszuführen?
https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem#existing-commands

!bot commander on
!list load stream
!list play

habe schon paar varianten versucht, geht aber nicht
