### ISSUE TITLE
Bot kann keine Musik mehr spielen

### ISSUE THREAD

**Issue by mhalterbeck** [Splamy/TS3AudioBot#275]
Hey, wenn ich über die API oder den Command Musik oder Streams Youtube Videos, etc spielen möchte, dann bekomme ich in der Console folgenden Fehler:

18:37:26.5334| INFO Neue Aktion: /api/bot/use/0/(/play/http:/stream01.iloveradio.de/iloveradio1.mp3)
18:37:27.1971|DEBUG Command Error (Could not convert to UInt64)
18:37:27.2106|DEBUG AudioResource start: media ID:http://stream01.iloveradio.de/iloveradio1.mp3

Bitte um schnelle Hilfe

Danke im Voraus

**Comment by Splamy** [comment]
Ich bräuchte den debug log mit stacktrace aus der datei. Der sollte bei der standard nlog config in die datei mit ausgegeben werden.

**Comment by mhalterbeck** [comment]
Du kannst den Fehler schliessen. Habe den Fehler gefunden! Nochmal an alle lasst die Bitrate bei maximal 92 ansonsten kann er keine Musik mehr spielen.

**Comment by Splamy** [comment]
48 is mehr als genug, ich wette du würdest nichtmal den unterschied hören :P
Und du kannst issues gerne selber schließen wenn ein problem behoben is.
