### ISSUE TITLE
Twitch Stream

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#280]
I get this 

> <19:57:46> "Akira": !play https://www.twitch.tv/relaxbeats
> <19:57:47> "MusicBot2": Error: Could not load. (twitch: No connection could be established.)

Twitch Streams not working?

**Comment by Splamy** [comment]
I get the same behaviour. I will look into this.

**Comment by Splamy** [comment]
Should be fixed in the latest develop.
(Warning: the dev branch uses the new config system layout. There shouldn't be any huge problems but it's rather fresh and untested)

**Comment by robotrono** [comment]
Im trying to install develop branch but I get an error. In the branch main is not working:

```
01:12:50.7967|DEBUG Got message from Akira: !play [URL]https://www.twitch.tv/relaxbeats[/URL]
01:12:50.8868|DEBUG User Akira created session with the bot
01:12:51.6187|DEBUG Command Error (Could not load (twitch: NoConnection))
```

**Comment by Splamy** [comment]
@robotrono as said, there is a bug on master which should be fixed on develop. You can try the suggested solution from me in your other issue.
