### ISSUE TITLE
QueryConnection::ClientVersion= help

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#287]
Hallo,
Mein config diesbezüglich sieht so aus:

`QueryConnection::ClientVersion=5680278000|Windows|+/BWvueikGg4YkO1v2uuZB5vtJJgUZ5bL8cRfxAstfnCVdro2ja+4a+8rGUzDx8/vvTZOUVD6U95hnWb638MCQ==`

Eine idee, warum das nicht geht??

**Comment by Splamy** [comment]
`QueryConnection::ClientVersion=3.1.10 [Build: 1528537615]|Windows|+/BWvueikGg4YkO1v2uuZB5vtJJgUZ5bL8cRfxAstfnCVdro2ja+4a+8rGUzDx8/vvTZOUVD6U95hnWb638MCQ==`

**Comment by preterive** [comment]
Achsooo... Danke

**Comment by preterive** [comment]
Kann man irgendwie die client_hacked Geschichten abschalten? Also um ein eigenes OS zu erfinden?

**Comment by preterive** [comment]
Edit: funktioniert nicht. Bekomme immer client_hacked

**Comment by Bluscream** [comment]
> Kann man irgendwie die client_hacked Geschichten abschalten? Also um ein eigenes OS zu erfinden?

Ja mit TeaSpeak
