### ISSUE TITLE
Wie funktioniert die webAPI?

### ISSUE THREAD

**Issue by CuzImCloud** [Splamy/TS3AudioBot#288]
Guten Tag,

kann mir jemand erklären wie die WEBAPI Funktioniert?
Wenn ich in der Config die API auf "True" stelle und meine IP eingebe und dann im Browser mit meiner IP:port versuche zu Verbinden passiert nichts.

Kann mir da jemand helfen?

**Comment by Splamy** [comment]
Wir haben ein wiki das die Basics ganz gut erklärt: https://github.com/Splamy/TS3AudioBot/wiki/WebAPI

**Comment by CuzImCloud** [comment]
Aber genau dann passiert leider nichts.

**Comment by Splamy** [comment]
Dir is klar dass das eine json/rest api is und nicht eine webseite?
Wenn du einwenig die anfragen rumtesten willst kann ich dir tool wie zb [Postman](https://www.getpostman.com/apps) empfehlen.
