### ISSUE TITLE
Generelle Frage

### ISSUE THREAD

**Issue by iLukeOff** [Splamy/TS3AudioBot#291]
Ich weiß der Bot wurde in C# programmiert, leider würde ich gerne so etwas ähnliches in Java umsetzten. Ich weiß das es funktioniert, finde aber im Internet rein gar keinen Ansatz. Da du dieses Projekt ja schon einmal umgesetzt hast kannst du mir vielleicht helfen.

Ich weiß das ist hier keine richtige Issue, aber nimm dir bitte trotzdem kurz Zeit mir zu helfen. Das wäre unglaublich nett.

Also ich weiß das man mit der Teamspeak SDK einen solchen Bot programmieren kann, jedoch funktioniert diese SDK nur für C# meines Wissens nach, kennst du eine Art API oder gar jemanden der dieses Projekt schon einmal in Java umgesetzt hat? Wenn nein,  nicht schlimm, hast du vielleicht trotzdem eine Ahnung wie man das machen könnte? Alles was mir irgendwie helfen könnte wäre super lieb wenn du mir das schreibst.

Vielen vielen Dank fürs Verständnis. 
:)

**Comment by Flakebi** [comment]
Mit dem offiziellen TeamSpeak SDK, das für C/C++ gedacht ist, kann man leider keinen Bot programmieren, der auf normale TS-Server verbinden kann. Mit dem Plugin-SDK von TeamSpeak geht das eher, dann muss aber immer ein richtiger TS-Client laufen.
Im `TS3Client` Unterordner von diesem Projekt findest du die C#-Bibliothek, die einen TS-Client implementiert. Wenn du einfach einen Bot schreiben willst, ist es das einfachste diese Bibliothek zu verwenden (und wenn du Java kannst, ist C# nicht schwierig, das kann man praktisch genauso schreiben).

Falls du wirklich einen vollständigen Client/Bot in Java schreiben willst, musst du das [TeamSpeak Protokoll](https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md) selbst implementieren.
Ich kenne keine Java-Implementierung davon, aber [dieser Python-Client](https://github.com/syncu2/PyTS3Bot) kann dir vielleicht weiterhelfen.

**Comment by iLukeOff** [comment]
Okay vielen vielen Dank für deine Hilfe, die du eigentlich nicht leisten müsstest!
Ich werde mich mal etwas ausprobieren.
