### ISSUE TITLE
Rawbots?

### ISSUE THREAD

**Issue by officialtaxz** [Splamy/TS3AudioBot#292]
Hi,
I just found a Bot called "RawBot" by RawNetworks ( https://www.youtube.com/watch?v=cJtsbWZO-pw ) which does exactly include the same functions as the TS3AudioBot. Maybe it's furthermore a copie. He also is selling "his" Bot. I actually don't know If this is legit or not, that's why I want to inform you.

**Comment by JABirchall** [comment]
Under the [License](https://github.com/Splamy/TS3AudioBot/blob/master/LICENSE) of TS3AudioBot, nothing they are doing is in violation of the grants given publicly by @Splamy.

**Comment by Splamy** [comment]
Well I'd say half, half. The basic idea of what he is doing is allowed.
However in execution, I'd say his tool falls under the category of 'external deployment' which is treated as a deriverative work, which means he must disclose the source code as well as include all license notices of all tools this project is using, including our license. Of which neither he is doing right now.
