### ISSUE TITLE
Befehl !connect

### ISSUE THREAD

**Issue by TeamCoore** [Splamy/TS3AudioBot#294]
Hey,

Wie funktioniert der Befehl !connect??

**Comment by Splamy** [comment]
Der `!connect` befehl vom master is veraltet

Die neuen befehle auf dem develop sehen wie folgt aus:
`!bot connect to <template>`
Dies verbindet einen bot aus einer bestehenden config.
Zb wird standardmäßig der default bot generiet (Bots/bot_default.toml); zum verbinden: `!bot connect to default`
`!bot connect new <address>`
Erstellt einen neuen bot und verbindet ihn zu einer addresse, zb. public.teamspeak.de, 127.0.0.1, oder ein server nickname.
Damit der bot mit seiner neuen identität permanent gespeichert wird `!bot save <template>` verwenden.

**Comment by Mareczin** [comment]
Is there any option to start more than one instance at startup? In addition to using the config parameter.

**Comment by Splamy** [comment]
Sure, when you have configured for example `Bots/Bot_abc.toml` and `Bots/Bot_def.toml`
simply add in your `ts3audiobot.toml`:
```
[bots]
"abc" = { run = true }
"def" = { run = true }
```
