### ISSUE TITLE
developh version sign

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#295]
Hi,
wie stelle ich die Version in der dev config ein?
Habe es so probiert:

[bot.connect.client_version]
build = "1525442084"
platform = "OS X"
sign = "WVaMmYPig4eG2JUM8cMMW2MA7+IoRoPUSr74CPe7oS8TLHGjYxPr1FP88op6YsFFQrPJysWmIsnGR7BiFXjHCQ=="

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#set-the-client-version

(Btw, it's written 'develop')
