### ISSUE TITLE
send_mode  !play develop

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#296]
Hi,
in der config vom Develop steht, das !play funktioniert.
Probiere ich send_mode = "!xecute (!whisper subscription) (!unsubscribe temporary) (!subscribe channeltemp 3366) (!play http://stream02.iloveradio.de/iloveradio6.mp3) " , Läuft allerdings z.b. gar nichts.

**Comment by Splamy** [comment]
Was genau erwartest du?
Egal was du mit `!play <...>` wird von dem letzen play in the liste überschrieben und started wieder von vorne, heißt das is ne endlosschleife.
Zudem wird der link nicht richtig erkannt weil er die letzte `)` mit zum link liest; du solltest ein leerzeichen davor einfügen.
Außerdem von "in der config vom Develop steht, das !play funktioniert." steht da nix. Das is ein Beispiel wie man den `!xecute` Befehl verwendet.

**Comment by preterive** [comment]
achso, ok.
!play funktioniert bei mir trotzdem nicht, über diese Funktion. Probiere das mit Internetradio.

**Comment by Splamy** [comment]
Hast du die letzte Zeile meiner Antwort nicht gelesen oder was meinst du mit "diese Funktion" ?

**Comment by preterive** [comment]
Hi,
das mit den leerzeichen habe ich ja bereits probiert. geht trotzdem nicht. "Diese Funktion" ist send_mode

**Comment by Splamy** [comment]
Was genau funktioniert bei `send_mode` bitte nicht?
Nochmal:
- What exactly are/were you doing?
- What did happen?
- What did you expect to happen?

**Comment by Splamy** [comment]
So langsam kommen wir der sache näher.
Ich glaube du misinterpretierst die einstellung `send_mode`.
Die Einstellung gibt dir die Möglichkeit ein skript auszuführen bevor ein lied mit `!play` gestartet wird.
Im Regelfall war es dafür gedacht channel und personen einzurichten an die gewhispert werden soll.
Das ist _nicht_ ein Befehl der beim start des Bots ausgeführt wird; Sondern vor jedem Lied das gestartet wird.

**Comment by preterive** [comment]
achso, ok. Autoplay steht ja schon auf der todo :)

**Comment by Splamy** [comment]
Wenn ein issue gelöst ist kannst du es auch selber schließen.
