### ISSUE TITLE
more then one request at the same time

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#297]
Develop:
I want to send 6 requests at same time to all bots via chat for autoplay. it isn't working.

**Comment by Splamy** [comment]
Please elaborate your issue, my crystal ball to predict the future is currently in repair, so I can't see everything.
- What exactly are/were you doing?
- What did happen?
- What did you expect to happen?

**Comment by preterive** [comment]
Hi,
ich probiere in der Develop Version per ts3bot.de die Bots jeweils mit einen !play command anzuschreiben, damit diese nach den Betreten die Musik spielen. Problem ist nun, das dies bei manchen Bots nicht funktioniert. Es wird zwar im Log ein request Angezeigt, aber es wird einfach nichts gespielt.

Im Log stehe dann häufig: 15:51:21.9740| WARN Request timed out
.

**Comment by Splamy** [comment]
`Request timed out` Bekommt der Bot wenn eine Webanfrage keine Antwort sendet oder zu lange braucht zum Antworten. Kann es sein dass der angefragte Stream bei zu vielen gleichzeitigen Anfragen länger braucht bzw Anfragen limitiert?

**Comment by preterive** [comment]
kann sein. sind 3 Anfragen gleichzeitig. Kann man das irgendwie verzögern? also z.b. das die Bots nacheinander den Server betreten? sonst probiere ich es gleich mit einer Playlist.

**Comment by Splamy** [comment]
!xecute (!list load <name>) (!list play)

**Comment by preterive** [comment]
probiere ich gleich mal, danke.
Es liegt übrigens devenetiv nicht am server. habe es eben mir mehreren Probiert (1live & iloveradio).

**Comment by Splamy** [comment]
Siehe anderes issue von dir.
Wenn es letzendlich um das selbe in beiden issues geht, bitte eins von beiden schließen.
Wenn es nur um den send_mode geht, für das feature gibts schon ein tracking issue: #238
