### ISSUE TITLE
An Icecast senden

### ISSUE THREAD

**Issue by iiVoiX** [Splamy/TS3AudioBot#300]
Hallo,

dies ist eher auf den Client an sich bezogen. Ich habe schon gesehen das es möglich ist einen EchoBot zu machen nun stelle ich mir dir frage kann mann nicht mit z.b bass.net oder so das was der bot "hört" an einen icecast oder shotcast server senden?

**Comment by Splamy** [comment]
Duplicate of #93 please continue further discussion there.

(In referenz zu dem was in #93 steht)
Die plugin api is mittlerweile deutlich besser, heißt da sollte es keine probleme geben.
Audio verarbeitung sollte relativ einfach mit dem audio pipeline system vom client gehen:
https://github.com/Splamy/TS3AudioBot/blob/develop/TS3Client/Full/Ts3FullClient.cs#L438
Einfach einen `IAudioPassiveConsumer` implementieren der die daten zu IceCast sendet und and den `OutStream` anhängen.

Diskussionen bitte wenn möglich in Englisch halten, da dies es einfacher macht allen an issues mitzuschreiben und helfen.
