### ISSUE TITLE
Webinterface

### ISSUE THREAD

**Issue by CuzImCloud** [Splamy/TS3AudioBot#301]
Ich wollte gerne ein Vorschlag machen für den bot.

Könnte man die bots über ein Webinterface Steuern?

Bots erstellen, bots löschen, bots neustarten, Konsole sehen, und die ganzen anderen Optionen beim erstellen?

Bot Name, Instanz Name, Lautstärke, Standard Channel, Server Gruppe(rechte)

Wenn da klappt wäre es verdammt geil!

Gruß!

**Comment by Splamy** [comment]
Duplicate of #301 please continue further discussion there.

Is n guter vorschlag. Is auch schon seit längerem in Planung.
Ich müsste nur mal dazu kommen und n bissl webdesign machen.
Und wenn möglich bitte diskussionen auf Englisch halten.

**Comment by Christian1998** [comment]
Could help you a bit to create a webinterface. Just need a bit help with the api. Will open a new issue if i dont get it solved. Contact me thought "join.shootoo.net" if youre able to talk.

**Comment by Splamy** [comment]
What exactly is the problem?

**Comment by Christian1998** [comment]
Got it solved :) So i dont opened a new issue. Thanks anyway :)
