### ISSUE TITLE
history.db password?

### ISSUE THREAD

**Issue by AdriaanBoshoff** [Splamy/TS3AudioBot#302]
Someone requested a song a few days ago and we can not find it. Is it possible to access the history.db password?

**Comment by Splamy** [comment]
The history has no password.
You can search in the history with `!history title <partial-name>`; like `Wond` will find `Wonderwall`.
Or you can search with `!history last <amount>` which will give you the last `<amount>` of songs played.

**Comment by iiVoiX** [comment]
Try using sqllite viewer if you want to direct open the db file.

**Comment by AdriaanBoshoff** [comment]
It asks for a password

**Comment by Splamy** [comment]
Well that's because it's not a Sqlite db file, but a LiteDb file.
There is a litedb file viewer but it's currently not in a usable state, the developer is working on it.
