### ISSUE TITLE
!settings bug?

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#305]
Hey when use that command:
`!settings set connect.name 123`
Bot reply and looking working fine, but when i use:
`!settings set connect.name 123a` 
reply from bot:
`Error: Failed to set the value (Could not read value: Input string '123a' is not a valid number. Path '', line 1, position 4.).`
or when i used everything with a letter. Number insert i think working but we can not set a name with letter

**Comment by Splamy** [comment]
Fixed on both master/develop as of 4be7c65471513a77238d9a2aa7917f4a29d65fd3
