### ISSUE TITLE
For future api better ids suggestion

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#306]
Hey @Splamy when i develop for private use panel for control bots in multi-instance version i get a little problem.
When we start TS3AdudioBot.exe for example with 5 bots (a, b, c, d, e)
Then bot gets ids from 0 to x+
a = 0
b = 1
c = 2
d = 3
e = 4

But when we use command !dc (disconnect) for example bot with config name "b" (current id: 1) then exit from server and its correct, but when we use command: `!bot connect to b` then bot get id 5 not 1 where this id is free. That is a problem. When we can spawn instance with that same id where they disconnect then this is a cool idea.  Or maybe add parameter to command` !bot connect to b 1` (1 is a number id where we want)

**Comment by Splamy** [comment]
I would find manually selecting id's a bit weird, as id's should be considered volatile.
I'd make you two counter-suggestions:
- `!bot connect new/to ...` already gives you a json object back which contains the assigned id.
- I could add a new named bot access method like `!bot use <name> (!command ...)` which would make access by id redundant.
  Possible drawback: instantiating two times the same template would return a random bot on the named access.

**Comment by Mareczin** [comment]
Hm number two i think is nice idea beacuse now when i edit some values in config via WebApi for example i change a name or default channel id for bot, To see result i must now restart manually all ts3audiobot or kick bot (partization method xD but working)  But if i changed ex. bitrate then that not working without restart all instances

**Comment by Splamy** [comment]
That's weird, how do you change the bitrate? This should apply immediately when setting with `!settings set audio.bitrate 42` for example

**Comment by Mareczin** [comment]
Sorry i think about audio_mode. That option not update live.

**Comment by Splamy** [comment]
Partially. The send_mode is nothing but a command which gets executed when a new song starts. This means to refresh this either play/restart a song.
Or simpy execute the command manually (or api if the case)
You can take a look here what the magic behind the courtain is: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Bot.cs#L289-L290

**Comment by Mareczin** [comment]
Okey thanks @Splamy.
I have a bit more question and i do not want spam :/ I can get better contact to you? Ex. Telegram?

**Comment by Splamy** [comment]
Sorry I don't add people on telegram, steam, etc.
Feel free to ask as many questions as you need here, though. That what issues are there for too.
You can catch my sometimes on my ts3 splamy.de if you're lucky.

**Comment by Splamy** [comment]
Done, added in e4ee3d2b38fc9ae6d75fab7637bb5d0f9589d666 `!bot template <name>` should work now
