### ISSUE TITLE
"Bot sleeping" if nobody is listening

### ISSUE THREAD

**Issue by Christian1998** [Splamy/TS3AudioBot#307]
Hey, is it possible to limit the usage of the ram? Using 6 Instances and its about 4GB. Or to stop it when nobody is in the channel?

**Comment by Splamy** [comment]
4GB seems like a lot. When I run the bot it usually uses like 50-60MB ram.
Are you sure you are looking in the correct htop column?
The actually ram usage is in the second col 'RES'
![image](https://user-images.githubusercontent.com/6502527/41814515-45d3d452-774f-11e8-8d72-a6844b087b7d.png)

If the bot indeed needs that much ram, I'd be happy if you could provide me various mono memory snapshots (I'd give you instructions on how to it).

**Comment by Christian1998** [comment]
They need that much ram maybe when they are running longer (Radio).
Currrently with 7 bots (6 musicbots and 1 standby bot) 
___________total       used       free     shared    buffers     cached
Mem______ 4194304    1697220    2497084      11000          0    1297660
