### ISSUE TITLE
Little question about last song

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#308]
In current develop branch we have a remember last song after kill and start proccess? 
For example:
1. Play song
2. Crash or kill proccess
3. Manually start
4. Bot auto play last song

Regards.

**Comment by Flakebi** [comment]
I’d say this is related to #238. If there was a command that is run at startup, you could set it to `!history last` to play the last song, or `!play xyz` to play an arbitrary song.
One difficulty that I can think of is that this command does not have a person executing it so the history cannot store a song “owner”.
