### ISSUE TITLE
[Bug API] different response when song playing and when no

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#309]
Hey @Splamy i found a bug in api response logic.

used request:
`/api/bot/use/0/(/json/merge/(/volume)/(/song)/(/repeat)`

When song is playing a response from above request is:
`[20.0,"Title",false]`

But when bot is not playing any song the request is:
`{"ErrorCode":10,"ErrorName":"CommandError","ErrorMessage":"There is nothing on right now..."}`

Okey song is empty and not playing, but volume is not returned.

**Comment by Splamy** [comment]
That's not quite a bug but by design.
When no song is playing the return is an error, and errors will interrupt call chains.
This way the api can return an error code like 500 instead of 200.
Although I could see that in the json.merge command this might not be the optimal behaviour

**Comment by Splamy** [comment]
Yes I know, that's becuase the json.merge with all subcommands is just a big call chain. When one call of the call chain errors the entire call is invalid.
what would you expect? Excluding `[20,false]` would be very confusing when the element 3 is suddenly at pos 2. Nulling `[20,null,false]` would be an option but would loose the meaning that the second parameter failes, it also might just regularly return null.
In the case of json.merge I think the second option might be ok.

**Comment by Mareczin** [comment]
Second option is a solution for this problem in my opinion.
