### ISSUE TITLE
Get nickname from the bot

### ISSUE THREAD

**Issue by SossenSystems** [Splamy/TS3AudioBot#310]
Hi, how i can get the nickname of the ts3audiobot instance?
Like: xxx:xxx/bot/use/0/(/bot/info/nickname)

**Comment by SossenSystems** [comment]
Wenn ich zum Beispiel das hier ausführe "http://xxx/api/bot/use/0/(/settings/get/connect.name/)", kriege ich kein Content zurück. Ich denke in diesem moment 'crasht' die API. Nach diesem ausführen lässt sich die API nicht mehr anwenden, diese scheint daraufhin Offline zu sein.

**Comment by bennetgallein** [comment]
Is it possible to get the current nickname of the instance? From what i've read in the source of develop I think not.

**Comment by Splamy** [comment]
Currently not, but there will be a general info command for the bot.

**Comment by Splamy** [comment]
Closed, tracked in #319
