### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Arkadiusz342** [Splamy/TS3AudioBot#312]
Hi, How can I change the language to Polish

**Comment by Kici33** [comment]
You need to download source code 
and edit https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainCommands.cs

**Comment by Splamy** [comment]
@Kici33 That would be the old way before we added resource packs.
@Arkadiusz342 For how to manually set it up I can point you to this older issue: #255
To just add the resource pack I have attached the dll.
1. extract this dll [TS3AudioBot.resources.dll.zip](https://github.com/Splamy/TS3AudioBot/files/2141431/TS3AudioBot.resources.dll.zip) and put this file in `.../bin/Release/pl/` with the name `TS3AudioBot.resources.dll` 
2. change the `bot.language` setting to `"pl"`. Alternatively call `!settings set language "\"pl\""` which will do this.

**Comment by Arkadiusz342** [comment]
Is there a possibility to explain where to insert this file because I do not understand too much

**Comment by Splamy** [comment]
Ah, when you downloaded the bot from our nightly server you have got a folder with a few dll's and the TS3AudioBot.exe
Lets say you have put all that files into a folder called TS3AudioBot
```
└ TS3AudioBot/
  └ TS3AudioBot.exe
  └ TS3Client.dll
  └ ....
  └ pl/     <- place the folder here
    └ TS3AudioBot.resources.dll
```

**Comment by Arkadiusz342** [comment]
Is it possible to edit this language file

**Comment by Splamy** [comment]
You'd have to download the resx file from transifex https://www.transifex.com/respeak/ts3audiobot/stringsresx/pl/download/for_use/
and recompile it the way I described in the referenced issue #255

**Comment by Arkadiusz342** [comment]
what permissions must be added to the rights.toml file so that api does not give an error No permission

**Comment by Splamy** [comment]
Depends on what you need.
First of all you should authenticate your call: https://github.com/Splamy/TS3AudioBot/wiki/WebAPI#authentication
Then the same permissions apply as to your identity when you usually call in the teamspeak chat

**Comment by Arkadiusz342** [comment]
Error:   {"ErrorCode":10,"ErrorName":"CommandError","ErrorMessage":"Could not convert to Int32"}

**Comment by Splamy** [comment]
What did you call?

**Comment by koznov** [comment]
Maybe you can use some services for generating all translations and collect them to new builds ? Services such as Lokalise.co? 
I would like to help in bot localisation to Russian language.

**Comment by koznov** [comment]
@Splamy Add request for Russian language in Transifex. Waiting for accepting request. Thanks!

**Comment by Splamy** [comment]
Language packs are now semi-automated built on our nightly server. For more information see here: https://github.com/Splamy/TS3AudioBot/issues/229#issuecomment-406923807
