### ISSUE TITLE
!settings doesn't quite work

### ISSUE THREAD

**Issue by TykooHagen** [Splamy/TS3AudioBot#313]
Hey Splamy, Im using the latest develop build. I've encountered an error with the **!settings set** command

Me:

> !settings set connect.name "Music man"

Da bot:

> Error: Failed to set the value (Could not read value: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.).

It takes booleans for some reason lol

> !settings set connect.name True

The bot takes it lmao

**Comment by TykooHagen** [comment]
Splamy, unfortunately it still doesn't work.

I am no C# expert but I think there is a variable type error as it ACCEPTS booleans such as True or False

> !settings set connect.name True

**Comment by Splamy** [comment]
Look here how to workaround: https://github.com/Splamy/TS3AudioBot/issues/305#issuecomment-399673833
