### ISSUE TITLE
Upload Gif Image

### ISSUE THREAD

**Issue by ricosw** [Splamy/TS3AudioBot#315]
Hello,
is there a way to set an GIF as client image?
If I load/upload an GIF its just an JPG/PNG.
Is this an TS3Client Issue?

I used the ClientConnection.UploadAvatar function.

**Comment by bennetgallein** [comment]
You could try to replace the images in the `TS3AudioBot/Media` folder.

**Comment by Splamy** [comment]
The cover image loading will get a little rework soon; when I'll get to it I can look into it.
Where did you get the image from; or how did you load it?

**Comment by ricosw** [comment]
```
private void LoadImage(string uri)
{

	var imgurl = new Uri(uri);
	if (imgurl == null)
	{
		return;
	}
	Image img = null;
	var resresult = WebWrapper.GetResponse(imgurl, (webresp) =>
	{
	       using (var stream = webresp.GetResponseStream())
		{
			if (stream != null)
			{
				try
				{
					img = Image.FromStream(stream);
				}
				catch (Exception ex)
				{
				     Log.Error(ex.Message);
				}

			}

		}
	});
	if (resresult != ValidateCode.Ok)
	{
		//ERROR
		return;
	}

	if (img == null)
	{
		return;
	}

	DisplayImageFromUrl(img);
}
```

**Comment by ricosw** [comment]
I'm using the [url ](http://image.ricosw.de/images/2018/06/29/8483a5149c186793d826d344b0d847c9.gif)from my server.

**Comment by Splamy** [comment]
As referenced the new image library should handle gifs without any problems. If you have any further questions feel free to reopen

**Comment by Bluscream** [comment]
New code: https://github.com/Splamy/TS3AudioBot/commit/26f25705e92715450a0c63650998c2cce22b6c6a#diff-0bb03c6dc5f710340cdbb4507af9baa3R90
