### ISSUE TITLE
API Permissions

### ISSUE THREAD

**Issue by bennetgallein** [Splamy/TS3AudioBot#316]
Hey there,
What is the correct rights.toml setup so that I can execute any command over the API? Currently the commands I tested didn't worked and I found nothing regarding that in the issues.
Should be a quick fix but i'm searching for 2h straight.

Thanks

**Comment by Bluscream** [comment]
* means all perms

**Comment by bennetgallein** [comment]
pasting my UID into the admin section did the trick :)
