### ISSUE TITLE
[Question] Multiple Bots in "Develop" Branch

### ISSUE THREAD

**Issue by P-Kito** [Splamy/TS3AudioBot#318]
Hey, can you give me some small hints how to connect bots with different identities?

I guess I have to create new identities and put the keys in some files or something and tell the bot to connect... 
but I cannot figure out.

Thanks <3 👍

**Comment by Splamy** [comment]
Use `!bot connect new <ip/nick/addres>` to create and connect a new instance.
Write to this instance `!bot save <name>` if you want to save the new instance as a instance-template.
Use `!bot connect to <name>` to run the template when it's not running.

You can also add a entry into the ts3audiobot.toml to let specific templates run at startup:
```
[bots]
"name" = { run = true }
```

**Comment by bennetgallein** [comment]
@Splamy Do you have an Idea when the development branch gets merged with master? My client has fear using the development branch but I need the features there ^^

**Comment by Splamy** [comment]
I'm finishing up on polishing the config, a bit of cleanup and restoring some feature regressions from the dotnet core migration.
After that I will probably merge back. But don't ask me for any time eta's, it wont be accurate anyway. It will be done when it's done.

**Comment by P-Kito** [comment]
Cool, I did !bot connect new 127.0.0.1 then !bot save zwei
but I got no response, not even from !help on that new instance..?

<00:30:00> "Kito  ( ＾◡＾)っ╯": !bot save zwei
<00:30:31> "Kito  ( ＾◡＾)っ": !help
<00:30:39> "Kito  ( ＾◡＾)っ": !help

**Comment by Splamy** [comment]
Does the bot have texting permissions?

**Comment by P-Kito** [comment]
```
2018-07-01 00:34:05.7480| INFO|Bot.TextCallback User Kito  (     ^     ) ^   ^ ^  ^   ^ ^  ^   requested: !bot connect new 127.0.0.1
2018-07-01 00:34:05.7553| INFO|Bot.InitializeBot Bot connecting...
2018-07-01 00:34:05.8076| INFO|Ts3Client.UpdateIndentityToSecurityLevel Calculating up to required security level: 8
2018-07-01 00:34:05.8437| INFO|Bot.OnBotConnected Bot connected.
2018-07-01 00:34:26.4598| INFO|Bot.TextCallback User Kito  (     ^     ) ^   ^ ^  ^   ^ ^  ^   requested: !bot save zwei
2018-07-01 00:34:26.4619| WARN|Bot.TextCallback Bot is not correctly set up. Some commands might not work or are slower (Unknown Teamspeak Error. (Connection closed)).
2018-07-01 00:34:26.4619| WARN|Ts3Client.GetClientById Slow double request due to missing or wrong permission configuration!
2018-07-01 00:34:26.4631| WARN|Bot.TextCallback Could not create session with user, some commands might not work (No client found.)
```

**Comment by Splamy** [comment]
The `Connection closed` seems strange could you give me a [debug log](https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs)

**Comment by P-Kito** [comment]
http://termbin.com/qcv6

**Comment by P-Kito** [comment]
Okay so I rerun the setup command... and magicly its working now...
I am trying with 3 bots and autorun now.

**Comment by P-Kito** [comment]
Whats the default logging now xD 
Alot of spamerino 💃

**Comment by Splamy** [comment]
You can set it back to `Info`.

**Comment by P-Kito** [comment]
!bot connect new IP
gives me new bots, but they arent using new identities, the first one was using a new one, the second and third were just using the first bots' identity..?

Also:
03:43:15.6535| WARN Could not connect: connect_failed_banned: the command failed to execute: connection failed, you are banned
Even if in query_ip_whitelist..?

**Comment by Splamy** [comment]
The bot is not a query, so query_ip_whitelist won't work.

to identity:
is it possible that you have manually set the identity values in the `ts3audiobot.toml`?
If yes, you should cut it out there and put it into a own `bot_xxx.toml` config

**Comment by P-Kito** [comment]
Yep ts3audiobot.toml had an identity still set.
