### ISSUE TITLE
Feature/Bug request

### ISSUE THREAD

**Issue by SossenSystems** [Splamy/TS3AudioBot#319]
I made a small list:
- [x] **[Bug]** It sometimes happens that there are duplicate entries with the same "Id" in the bot list.
- [x] **[Bug]** My GitHub avatar is not set correctly about 10% of the image are visible and the rest only black.
- [x] **[Feature]** More detailed current track information, for example, how long is the track and/or where the track is in seconds.
- [x] **[Feature]** Extended bot info, for example the current nickname.
- [x] **[Feature]** Set autostart for instance via Command.
- [x] **[Feature]** Set settings when instance is offline.
- [ ] **[Suggestion/Feature]** Complete rights system for the instances, fully configurable via API.
Best would be bot_instance_folder/instance1/config.toml (Already exists, with !settings) and rights.toml (Like !rights).

**Comment by Splamy** [comment]
The image bug will be fixed in mono 5.18, the wont be any other fix for that.

**Comment by ShadowFM** [comment]
To have separate rights for different server is a really good idea!

**Comment by Bluscream** [comment]
> 
> 
> To have separate rights for different server is a really good idea!

You can already do that, read the permission wiki page.

**Comment by SossenSystems** [comment]
@Splamy can you implement that the instances can be deleted via a command?

**Comment by Splamy** [comment]
`!settins delete <name>`, already exists

**Comment by Splamy** [comment]
Since all except one are already done, I'll close this one in favor of an issue with a better title: #612
