### ISSUE TITLE
No answer with info client

### ISSUE THREAD

**Issue by SossenSystems** [Splamy/TS3AudioBot#321]
No response from **!bot info client** to get the nickname
<15:12:34> "Michael": !bot info client
<15:12:37> "Michael": !version
<15:12:37> "DatBot": 
Version: 0.9.0-alpha.63
Branch: develop
CommitHash: 6cc9a911b2c571c81aef81bd7d720aaa4f034a8c

**Comment by SossenSystems** [comment]
It's working with json merge.
Like: http://URI/api/bot/use/0/(/json/merge/(/bot/info/client)

**Comment by Splamy** [comment]
It should also work without json merge. It's just that the command is api-only

**Comment by SossenSystems** [comment]
Right, this issue was too hasty of me. I'm sorry!
