### ISSUE TITLE
!list error

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#322]
If i want to use !list i get 
Error: Command 'CommandListAdd' missing execution context 'UserSession'

I use the last Dev Version on ubuntu 16.04 .

**Comment by Splamy** [comment]
This is probably because the bot has not the permissions for clientinfo or clientlist and therefore can't see you.
I'll try to get a workaround on this soon.

**Comment by Bluscream** [comment]
Bless you, finally :)

**Comment by Splamy** [comment]
@Bluscream lol, didn't know you had the same problem..
