### ISSUE TITLE
Song info bug

### ISSUE THREAD

**Issue by SossenSystems** [Splamy/TS3AudioBot#324]
I do that: `http://xxxx/api/bot/use/0/(/json/merge/(/play/https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DKH4Bb8XB1wY)/(/song/info)/(/song))`
I get back:
```
[
    null,
    {
        "position": "00:00:00",
        "length": "00:00:00"
    },
    "10 sekunden Video xD"
]
```
Actually I had expected as an example about 10 seconds, on 

> "length": "00:00:00"

I think it's a library error.

**Comment by Splamy** [comment]
This might happen because the actual song loading progress is asynchronous, this means the `song info` gets called before the previous call was actually completed. And I guess there is not much I can do about that without slowing the `play` command down.
