### ISSUE TITLE
Bots starten nach reboot nicht mehr

### ISSUE THREAD

**Issue by cayzradio** [Splamy/TS3AudioBot#327]
Hi,

nachdem ich unseren Server restartet habe kam diese Meldung http://prntscr.com/k733kr und die Bots konnten nicht mehr connecten. Muss noch irgendwas gestartet werden?

Mit freundlichen Grüßen / Kind regards
Simon

**Comment by Splamy** [comment]
Which version? Have you restarted the bot? Is the address/port corect?
Can you enable debug log and try again: https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs

**Comment by cayzradio** [comment]
Ah i fixed it thank you
