### ISSUE TITLE
Records in logs

### ISSUE THREAD

**Issue by koznov** [Splamy/TS3AudioBot#333]
Can you add record to log in Info level about what server bot is trying to connect? 

This record is availible in Debug mode:
20:02:17.3401|DEBUG Trying to look up 'ts1.blah-blah.ru:10020'

And when bot gets some ending signal such as 15 or 9 there is no record in log about it. It is possible to add it?
Thanks!

**Comment by Splamy** [comment]
I think debug is enough for this. If you really need it info, you can simply change it yourself.
You can also filer single loggers only, see here: https://github.com/NLog/NLog/wiki/Configuration-file#example-rules

I don't get the signal in c#, but i can add a log when the exit was triggered with ctrl-c

**Comment by Splamy** [comment]
Done
