### ISSUE TITLE
Avatar generation

### ISSUE THREAD

**Issue by koznov** [Splamy/TS3AudioBot#335]
I'm sorry , but if i am right that in stable version on generated avatar of track from youtube there was a track info such as artist and songname. In latest nightly build option generate_status_avatar = true
but no info on avatar. It is bug or some misconfiguration on my side?
Sorry for spaming in last 2 hours 🍡

**Comment by Splamy** [comment]
Yes I removed it. Those information are more or less the same in the description of the bot. It costs more cpu. And it kind of conflicts with the quiz mode :P
