### ISSUE TITLE
How to Install webinterface

### ISSUE THREAD

**Issue by ManuPlaysLP** [Splamy/TS3AudioBot#343]
Wie kann ich das Webinterface Installieren, dass es auch richtig funktioniert?
Ich habe den Bot mit dem Installer von RawNetworks installiert.

**Comment by Splamy** [comment]
The webinterface doesn't work. You'll have to wait until I find someone or have to update it myself.

**Comment by ManuPlaysLP** [comment]
So, du kannst ja auch Deutsch, können wir uns mal treffen, ich habe schon ein Web Panel gemacht, muss aber nur noch mit der API verbinden, und damit habe ich Probleme, ich kenn mich noch garnicht mit der Web-API aus, und hoffe du könntest mir das einrichten. Wie gesagt, das Webpanel habe ich schon, aber du könntest mir, wenn du so nett bist die API mit dem Web-Panel verbinden. Danke!

**Comment by RawNetworks** [comment]
Wer sagt denn das Du es alleine gemacht hast? Ich habe Dir ein Panel geschickt!
Brauchst nicht mehr bei mir anzukommen.
Das wars!

Lizenz gesperrt!

**Comment by lgund** [comment]
Nur so nebenbei. Das nächste Update vom First-Coder Webinterface v2 wird ebenfalls den Musikbot unterstützen. 👍

**Comment by Splamy** [comment]
Wir haben einen guten wiki Artikel wie man die api verwendet: https://github.com/Splamy/TS3AudioBot/wiki/WebAPI

Der aktuelle develop branch hat auch ein openapiv3 generator drinnen, mit dem kann man sich alle befehle anschauen und auch gleich testen. Dafür muss das Webinterface aktiviert sein.
Die seite sieht zb so aus: http://splamy.de:8181//openapi/index.html

**Comment by ManuPlaysLP** [comment]
Danke!
