### ISSUE TITLE
Installation Probleme

### ISSUE THREAD

**Issue by ManuPlaysLP** [Splamy/TS3AudioBot#344]
How can i buy the Open Source Code? And how much kost it?

PS: [GER]

**Comment by Splamy** [comment]
It's.. uh... open source...
The code is right there, just press the download button.

**Comment by WolverinDEV** [comment]
Or give me 10€ and i'll send you the source via E-Mail :)

**Comment by ManuPlaysLP** [comment]
@Splamy Ich habe de nTS3AudioBot mit dem Installer Installiert, und dort ist alles bissle anderst eingeordnet. Ich möcht ja nur das <sleeping> und das Avatar bei sleeping ändern und so kleine sachen halt, wie muss ich das machen, denn bei mir ist halt alles bissle anderst angeordnet, wenn du mal einen Screen von allen Ordnern haben möchtest sag bescheid.

**Comment by Splamy** [comment]
Folg dem ganz normalen compile tutorial auf der readme und ersetz die datei TS3AudioBot\Media\SleepingKitty.png mit der Datei deiner Wahl.

**Comment by JABirchall** [comment]
Im sure splamy would accept a donation 😜

**Comment by ManuPlaysLP** [comment]
Hier ist ein Screen von den ganzen Ordnern, und ich habe kein ts3audiobot Ordner...
https://abload.de/img/unbenanntqffoy.png

**Comment by Splamy** [comment]
Wie vorhin geschrieben, das Bild wird derzeit miteinkompiliert.
Einfach der readme zum compilieren folgen: https://github.com/Splamy/TS3AudioBot/tree/develop#building-manually
und die genannte datei ersetzen.

**Comment by ManuPlaysLP** [comment]
Hast du den Screenshot gesehen? Es gibt dort den genannten Ordner nicht...

**Comment by Splamy** [comment]
Hast du meine Antwort gesehen? Du musst den source code hier von github runterladen und es selbst kompilieren. Der installer script bringt dir hier gar nichts. Und wenn du so darauf bestehst dann wende dich bitte an @RawNetworks.

**Comment by ManuPlaysLP** [comment]
Wenn ich der Anleitung folge der in der README steht, muss ich ja das hier installieren auf Debian: wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
Doch es kommt immer dieser error:

root@CT1003:~# wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
converted 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe' (ANSI_X3            .4-1968) -> 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe' (UTF-8            )
--2018-08-04 08:56:53--  https://dist.nuget.org/win-x86-commandline/latest/nuget            .exe
Resolving dist.nuget.org (dist.nuget.org)... 152.199.19.160
Connecting to dist.nuget.org (dist.nuget.org)|152.199.19.160|:443... connected.
ERROR: The certificate of 'dist.nuget.org' is not trusted.
ERROR: The certificate of 'dist.nuget.org' hasn't got a known issuer.

**Comment by Splamy** [comment]
`sudo apt-get install ca-certificates`

**Comment by ManuPlaysLP** [comment]
ok, habe es jetzt manuell gemacht, ca-certificates sind schon installiert gewesen. Ach und ich habe ja Debian 8 und was für ein compiler muss ich instalieren weil da steht ja "* (Linux only) A C Compiler for Opus"

**Comment by ManuPlaysLP** [comment]
Kannst du mir helfen beim Installieren irgendwie TeamSpeak oder Discord kommen? bei mir kommen immer errors, obwohl ich es so mache wie in der README. Wenn ich jetzt nähmlich `nuget restore` mache, kommt immer:
`Unable to find version '2.1.3' of package 'Fody'.
Unable to find version '3.6.5' of package 'GitVersionTask'.
Unable to find version '4.1.2' of package 'LiteDB'.
Unable to find version '0.9.0' of package 'Nett'.
Unable to find version '11.0.2' of package 'Newtonsoft.Json'.
Unable to find version '4.5.2' of package 'NLog'.
Unable to find version '2.2.1.0' of package 'PropertyChanged.Fody'.
Unable to find version '4.5.0-preview1-26216-02' of package 'System.Memory'.
Unable to find version '4.5.0-preview1-26216-02' of package 'System.Runtime.CompilerServices                                                .Unsafe'.
Unable to find version '4.4.0' of package 'System.ValueTuple'.
Unable to find version '3.8.1' of package 'NUnit'.
Unable to find version '1.8.1' of package 'BouncyCastle'.
Unable to find version '2.0.0' of package 'Heijden.Dns'.
Unable to find version '1.0.2-alpha' of package 'Splamy.Ed25519.Toolkit'.
root@CT1003:~/TS3AudioBot# mono ../Nuget.exe restore
Cannot open assembly '../Nuget.exe': No such file or directory.
root@CT1003:~/TS3AudioBot# nuget restore
WARNING: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
Unable to find version '2.1.3' of package 'Fody'.
Unable to find version '3.6.5' of package 'GitVersionTask'.
Unable to find version '4.1.2' of package 'LiteDB'.
Unable to find version '0.9.0' of package 'Nett'.
Unable to find version '11.0.2' of package 'Newtonsoft.Json'.
Unable to find version '4.5.2' of package 'NLog'.
Unable to find version '2.2.1.0' of package 'PropertyChanged.Fody'.
Unable to find version '4.5.0-preview1-26216-02' of package 'System.Memory'.
Unable to find version '4.5.0-preview1-26216-02' of package 'System.Runtime.CompilerServices.Unsafe'.
Unable to find version '4.4.0' of package 'System.ValueTuple'.
Unable to find version '3.8.1' of package 'NUnit'.
Unable to find version '1.8.1' of package 'BouncyCastle'.
Unable to find version '2.0.0' of package 'Heijden.Dns'.
Unable to find version '1.0.2-alpha' of package 'Splamy.Ed25519.Toolkit'.`

**Comment by Splamy** [comment]
Probier mal `sudo nuget update -self`

**Comment by ManuPlaysLP** [comment]
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure

**Comment by Splamy** [comment]
https://stackoverflow.com/questions/15181888/nuget-on-linux-error-getting-response-stream#16589218

**Comment by ManuPlaysLP** [comment]
geht immernoch nicht

**Comment by ManuPlaysLP** [comment]
@Splamy kannst du mir mal helfen bei der Installation, wielleicht mach ich einfach was falsch

**Comment by Splamy** [comment]
Kann ich raten du hast Debian 6, oder so in der richtung? Ich hab keine ahnung was bei Debian schief is aber ich habs selbst nie bei anderen zum laufen bekommen. Probier n aktuelles ubuntu, probier mal alles zu aktualisieren oder google einwenig nach den Fehlermeldungen...

**Comment by ManuPlaysLP** [comment]
Ich habe Debian 8

**Comment by ManuPlaysLP** [comment]
uups

**Comment by ManuPlaysLP** [comment]
klar, aber vielleicht mache ich auch was falsch, wo ich nicht bemerke. Deswegen könntest du mir das mal installieren und schauen ob es bei dir geht.

**Comment by ManuPlaysLP** [comment]
Also nachdem ich msbuild /p:Configuration=Release TS3AudioBot.sln gemacht habe ist das hier gekommen, das ist der letzte teil denn ich kann nicht alles ansehen es kamen aufjedenfall gelbe WARNIGS:

`      Fody/PropertyChanged:     Removing reference to 'PropertyChanged'.
      Fody/PropertyChanged:   Finished 'PropertyChanged' in 239ms

    Fody:   Adding weaving info
    Fody:   Finished in 1ms

    Fody:   Writing assembly to '/root/TS3AudioBot/TS3AudioBot/obj/Release/TS3AudioBot.exe'.
    Fody:   Finished writing assembly 230ms.
    Fody:   Finished Fody 1038ms.
_CopyFilesMarkedCopyLocal:
  Copying file from "/root/TS3AudioBot/packages/LiteDB.4.1.2/lib/net40/LiteDB.dll" to "bin/Release/LiteDB.dll".
  Copying file from "/root/TS3AudioBot/packages/Nett.0.9.0/lib/Net40/Nett.dll" to "bin/Release/Nett.dll".
  Copying file from "/root/TS3AudioBot/packages/Newtonsoft.Json.11.0.2/lib/net45/Newtonsoft.Json.dll" to "bin/Release/Newtonsoft.Json.dll".
  Copying file from "/root/TS3AudioBot/packages/NLog.4.5.2/lib/net45/NLog.dll" to "bin/Release/NLog.dll".
  Copying file from "/root/TS3AudioBot/packages/PropertyChanged.Fody.2.2.1.0/lib/net452/PropertyChanged.dll" to "bin/Release/PropertyChanged.dll".
  Copying file from "/root/TS3AudioBot/packages/System.Memory.4.5.0-preview1-26216-02/lib/netstandard1.1/System.Memory.dll" to "bin/Release/System.Memory.dll".
  Copying file from "/root/TS3AudioBot/packages/System.Runtime.CompilerServices.Unsafe.4.5.0-preview1-26216-02/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll" to "bin/Release/System.Runtime.CompilerServices.Unsafe.dll".
  Copying file from "/root/TS3AudioBot/packages/System.ValueTuple.4.4.0/lib/netstandard1.0/System.ValueTuple.dll" to "bin/Release/System.ValueTuple.dll".
  Copying file from "/root/TS3AudioBot/TS3Client/bin/Release/TS3Client.dll" to "bin/Release/TS3Client.dll".
  Copying file from "/root/TS3AudioBot/TS3Client/bin/Release/Heijden.Dns.dll" to "bin/Release/Heijden.Dns.dll".
  Copying file from "/root/TS3AudioBot/TS3Client/bin/Release/Chaos.NaCl.dll" to "bin/Release/Chaos.NaCl.dll".
  Copying file from "/root/TS3AudioBot/TS3Client/bin/Release/BouncyCastle.Crypto.dll" to "bin/Release/BouncyCastle.Crypto.dll".
  Copying file from "/root/TS3AudioBot/TS3Client/bin/Release/TS3Client.pdb" to "bin/Release/TS3Client.pdb".
  Copying file from "/root/TS3AudioBot/packages/LiteDB.4.1.2/lib/net40/LiteDB.xml" to "bin/Release/LiteDB.xml".
  Copying file from "/root/TS3AudioBot/packages/Nett.0.9.0/lib/Net40/Nett.pdb" to "bin/Release/Nett.pdb".
  Copying file from "/root/TS3AudioBot/packages/Nett.0.9.0/lib/Net40/Nett.xml" to "bin/Release/Nett.xml".
  Copying file from "/root/TS3AudioBot/packages/Newtonsoft.Json.11.0.2/lib/net45/Newtonsoft.Json.xml" to "bin/Release/Newtonsoft.Json.xml".
  Copying file from "/root/TS3AudioBot/packages/NLog.4.5.2/lib/net45/NLog.xml" to "bin/Release/NLog.xml".
  Copying file from "/root/TS3AudioBot/packages/PropertyChanged.Fody.2.2.1.0/lib/net452/PropertyChanged.xml" to "bin/Release/PropertyChanged.xml".
  Copying file from "/root/TS3AudioBot/packages/System.Memory.4.5.0-preview1-26216-02/lib/netstandard1.1/System.Memory.xml" to "bin/Release/System.Memory.xml".
  Copying file from "/root/TS3AudioBot/packages/System.Runtime.CompilerServices.Unsafe.4.5.0-preview1-26216-02/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml" to "bin/Release/System.Runtime.CompilerServices.Unsafe.xml".
  Copying file from "/root/TS3AudioBot/packages/System.ValueTuple.4.4.0/lib/netstandard1.0/System.ValueTuple.xml" to "bin/Release/System.ValueTuple.xml".
  Creating "/root/TS3AudioBot/TS3AudioBot/obj/Release/TS3AudioBot.csproj.CopyComplete" because "AlwaysCreate" was specified.
_CopyOutOfDateSourceItemsToOutputDirectory:
  Copying file from "/root/TS3AudioBot/TS3AudioBot/NLog.config" to "bin/Release/NLog.config".
_CopyAppConfigFile:
  Copying file from "obj/Release/TS3AudioBot.exe.config" to "bin/Release/TS3AudioBot.exe.config".
CopyFilesToOutputDirectory:
  Copying file from "obj/Release/TS3AudioBot.exe" to "bin/Release/TS3AudioBot.exe".
  TS3AudioBot -> /root/TS3AudioBot/TS3AudioBot/bin/Release/TS3AudioBot.exe
  Copying file from "obj/Release/TS3AudioBot.pdb" to "bin/Release/TS3AudioBot.pdb".
AfterBuild:
  Creating directory "bin/Release/x86".
  Copying file from "lib/x86/libopus.dll" to "bin/Release/x86/libopus.dll".
  Creating directory "bin/Release/x64".
  Copying file from "lib/x64/libopus.dll" to "bin/Release/x64/libopus.dll".
FodyVerifyTarget:
    Fody: Found path to weavers file '/root/TS3AudioBot/TS3AudioBot/FodyWeavers.xml'.
    Fody:   Skipped Verifying assembly since it is disabled in configuration
    Fody:   Finished verification in 2ms.
Done Building Project "/root/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj" (default targets).
Project "/root/TS3AudioBot/TS3AudioBot.sln" (1) is building "/root/TS3AudioBot/TS3ABotUnitTests/TS3ABotUnitTests.csproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin/Release/".
  Creating directory "obj/Release/".
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: lib/linux/x86_64/libgit2-baa87df.so
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () [0x00006] in <ecba14039ea0427fac6be14e5af4f4d5>:0
  at LibGit2Sharp.Core.NativeMethods..cctor () [0x00058] in <ecba14039ea0427fac6be14e5af4f4d5>:0
   --- End of inner exception stack trace ---
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject.Finalize () [0x00000] in <ecba14039ea0427fac6be14e5af4f4d5>:0
root@CT1003:~/TS3AudioBot#
`

**Comment by ManuPlaysLP** [comment]
Also ich kann den Bot starten aber dann passiert das, ich habe mir zeitweise einen Ubuntu 16.04 gekauft, aber wenn ich die exe dann mit mono ausführe kommt das:



`13:29:33.9393| INFO [============ TS3AudioBot started =============]
13:29:33.9623| INFO [=== Date/Time: Saturday, 04 August 2018 13:29:33
13:29:34.0221| INFO [=== Version: <?>/<?>/<?>
13:29:34.0227| INFO [=== Platform: Ubuntu 16.04 (64bit)
13:29:34.0227| INFO [=== Runtime: Mono (5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018))
13:29:34.0253| INFO [=== Opus: libopus 1.1.3 (x64)
13:29:34.0253| INFO [==============================================]
13:29:34.0257| INFO [============ Initializing Modules ============]
13:29:34.1525| INFO No rights file found. Creating default.
13:29:34.3910| INFO [==================== Done ====================]
13:29:34.3956| INFO Bot connecting...
13:29:34.4843| INFO Database table "audioLogEntries" upgraded to 1
13:29:34.6335|DEBUG Bot disconnected. Reason: LeftServer
13:29:34.6346| INFO Bot disconnecting.
13:29:34.6374| WARN Internal error (me==null)
13:29:34.6448| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:36.5884| INFO Bot connecting...
13:29:36.6253|DEBUG Bot disconnected. Reason: LeftServer
13:29:36.6257| INFO Bot disconnecting.
13:29:36.6257| WARN Internal error (me==null)
13:29:36.6257| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:38.6256| INFO Bot connecting...
13:29:38.6434|DEBUG Bot disconnected. Reason: LeftServer
13:29:38.6438| INFO Bot disconnecting.
13:29:38.6438| WARN Internal error (me==null)
13:29:38.6438| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:40.6437| INFO Bot connecting...
13:29:40.6621|DEBUG Bot disconnected. Reason: LeftServer
13:29:40.6621| INFO Bot disconnecting.
13:29:40.6630| WARN Internal error (me==null)
13:29:40.6630| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:42.6623| INFO Bot connecting...
13:29:42.6784|DEBUG Bot disconnected. Reason: LeftServer
13:29:42.6788| INFO Bot disconnecting.
13:29:42.6788| WARN Internal error (me==null)
13:29:42.6788| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:44.6786| INFO Bot connecting...
13:29:44.6922|DEBUG Bot disconnected. Reason: LeftServer
13:29:44.6926| INFO Bot disconnecting.
13:29:44.6926| WARN Internal error (me==null)
13:29:44.6926| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:46.6924| INFO Bot connecting...
13:29:46.7103|DEBUG Bot disconnected. Reason: LeftServer
13:29:46.7107| INFO Bot disconnecting.
13:29:46.7107| WARN Internal error (me==null)
13:29:46.7107| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:48.7105| INFO Bot connecting...
13:29:48.7245|DEBUG Bot disconnected. Reason: LeftServer
13:29:48.7245| INFO Bot disconnecting.
13:29:48.7245| WARN Internal error (me==null)
13:29:48.7245| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:50.7248| INFO Bot connecting...
13:29:50.7398|DEBUG Bot disconnected. Reason: LeftServer
13:29:50.7398| INFO Bot disconnecting.
13:29:50.7398| WARN Internal error (me==null)
13:29:50.7409| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:52.7401| INFO Bot connecting...
13:29:52.7544|DEBUG Bot disconnected. Reason: LeftServer
13:29:52.7548| INFO Bot disconnecting.
13:29:52.7548| WARN Internal error (me==null)
13:29:52.7548| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:54.7547| INFO Bot connecting...
13:29:54.7698|DEBUG Bot disconnected. Reason: LeftServer
13:29:54.7698| INFO Bot disconnecting.
13:29:54.7698| WARN Internal error (me==null)
13:29:54.7708| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:56.7700| INFO Bot connecting...
13:29:56.7848|DEBUG Bot disconnected. Reason: LeftServer
13:29:56.7848| INFO Bot disconnecting.
13:29:56.7848| WARN Internal error (me==null)
13:29:56.7858| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:29:58.7844| INFO Bot connecting...
13:29:58.8008|DEBUG Bot disconnected. Reason: LeftServer
13:29:58.8008| INFO Bot disconnecting.
13:29:58.8017| WARN Internal error (me==null)
13:29:58.8017| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:30:00.8010| INFO Bot connecting...
13:30:00.8150|DEBUG Bot disconnected. Reason: LeftServer
13:30:00.8166| INFO Bot disconnecting.
13:30:00.8166| WARN Internal error (me==null)
13:30:00.8166| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed
13:30:02.3244| INFO TS3AudioBot shutting down.
13:30:02.8152| INFO Bot connecting...
13:30:03.3663|FATAL Critical program failure!.
13:30:03.3718| INFO TS3AudioBot shutting down.
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at LiteDB.StreamExtensions+<>c__DisplayClass4_0.<TryLock>b__0 () [0x00000] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.FileHelper.TryExec (System.Action action, System.TimeSpan timeout) [0x00010] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.StreamExtensions.TryLock (System.IO.FileStream stream, System.Int64 position, System.Int64 length, System.TimeSpan timeout) [0x00024] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.FileDiskService.Lock (LiteDB.LockState state, System.TimeSpan timeout) [0x00072] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LockService.Write () [0x0009c] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LiteEngine.Transaction[T] (System.String collection, System.Boolean addIfNotExists, System.Func`2[T,TResult] action) [0x00000] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LiteEngine.EnsureIndex (System.String collection, System.String field, System.String expression, System.Boolean unique) [0x000b1] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LiteCollection`1[T].EnsureIndex (System.String field, System.String expression, System.Boolean unique) [0x0001e] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LiteCollection`1[T].EnsureIndex[K] (System.Linq.Expressions.Expression`1[TDelegate] property, System.String expression, System.Boolean unique) [0x00026] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at LiteDB.LiteCollection`1[T].EnsureIndex[K] (System.Linq.Expressions.Expression`1[TDelegate] property, System.Boolean unique) [0x00000] in <763b2b7e3050499a81c0496b75ebcbdb>:0
  at TS3AudioBot.History.HistoryManager.Initialize () [0x00069] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Bot+<>c.<InitializeBot>b__69_0 (TS3AudioBot.History.HistoryManager x) [0x00000] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.DependencyRealm+<>c__DisplayClass6_0`1[TMod].<RegisterModule>b__0 (System.Object x) [0x00000] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.Module.SetInitalized () [0x0002c] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.DependencyRealm.TryResolve (TS3AudioBot.Dependency.Module module, System.Boolean force) [0x00013] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.DependencyRealm.DoQueueInitialize (System.Boolean force) [0x00027] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.DependencyRealm.RegisterModule (System.Object module, System.Action`1[T] onInit) [0x00014] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Dependency.DependencyRealm.RegisterModule[TMod] (TMod module, System.Action`1[T] onInit) [0x00025] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Bot.InitializeBot () [0x00196] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.BotManager.CreateBot () [0x00047] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.BotManager.WatchBots () [0x00031] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Core.Run () [0x00006] in <ced69d8e85ea45349a8715c6f480c788>:0
  at TS3AudioBot.Core.Main (System.String[] args) [0x000c8] in <ced69d8e85ea45349a8715c6f480c788>:0
root@CT1003:~/bot/TS3AudioBot/TS3AudioBot/bin/Release#
`

**Comment by Splamy** [comment]
Probier mal den develop branch `git checkout develop`
und stell den log auf trace https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs

**Comment by ManuPlaysLP** [comment]
ok werde ich mal machen, hast du einen Ts oder Discord wo wir mal reden können

**Comment by ManuPlaysLP** [comment]
Also da kommt
root@CT1003:~# git checkout develop

> fatal: Not a git repository (or any of the parent directories): .git

**Comment by Splamy** [comment]
du musst den befehl schon im TS3AudioBot ordner ausführen

**Comment by ManuPlaysLP** [comment]
Habe ich da stand was mit InstallOpus.sh, das habe ich gemacht, wenn ich nun die exe starte im screen kommt das dauerhaft:
06:05:20.0076|DEBUG Bot disconnected. Reason: LeftServer
06:05:20.0076| INFO Bot disconnecting.
06:05:20.0076| WARN Internal error (me==null)
06:05:20.0076| WARN Could not save avatar: custom_error: the command failed to execute: Connection closed

**Comment by Splamy** [comment]
`root@CT1003:~# git checkout develop`
das sieht zwar eher aus wie dein home ordner aber ok.

Opus kannst du auch über den paketmanager installieren, steht auch in der readme.

Stimmt die addresse? Welchen branch hast du jetzt genommen, master oder develop?

**Comment by ManuPlaysLP** [comment]
Die, die in der Anleitung steht.

**Comment by Splamy** [comment]
Dann probier mal bitte develop

**Comment by ManuPlaysLP** [comment]
Kannst du mal auf deinen TS kommen, ich warte auf dich

**Comment by ManuPlaysLP** [comment]
Welche Datei muss ich in Visual Studio ändern/Bearbeiten, dass ich das Sleeping in der Beschreibung ändern kann?

**Comment by blackjack4494** [comment]
Oh Gott der arme Splamy. ManuPlayLP ist ganz schön anstrengend. Ohne negativ zu werden du scheinst sehr jung und unerfahren. Mach dir doch mal die Mühe und guck dir den Source Code an. Der ist jetzt eigentlich sehr übersichtlich im Vergleich wie vor ca. einem Jahr.
Wenn du Änderungen vornehmen willst musst du dir entweder selber aneignen wie man das macht oder du suchst dir jemanden der es für dich macht, wobei es wohl die aller wenigsten umsonst machen werden.
Und übrigens es gibt auf Github und in Visual Studio eine Suchfunktion. Das wäre der erste Anhaltspunkt wie du Sleeping finden kannst. Ich weiß nur nicht, ob dich eine Suchfunktion bereits überfordern wird.

**Comment by ManuPlaysLP** [comment]
Ich habe in der Bot.cs schon das sleeping ins das avatar.sleeping geändert, wir aber nicht übernommen
