### ISSUE TITLE
Splamy deine Website ist Down [404]

### ISSUE THREAD

**Issue by ManuPlaysLP** [Splamy/TS3AudioBot#345]
Deine Website ist down
http://splamy.de/Nightly#ts3ab

**Comment by Splamy** [comment]
Ja weiß ich, kann ich wegen servermigrierung leider grade nichts tun. Wird ca bis montag oder so dauern.

**Comment by ManuPlaysLP** [comment]
kannst du mal auf deinen Ts kommen, ich möch mal mit dir reden :(

**Comment by ManuPlaysLP** [comment]
@Splamy Kannst du mir dann einen fertig eingerichteten Bot geben. Also das habe ich in einem Video gehört, das das schon Fertige Bots zum Downloaden sind, oder kennst du ein gutes Installerscript das kostenlos ist?

**Comment by Splamy** [comment]
Ich dachte der ganze Sinn vom selbst kompielieren war dass du das Bild austauschen kannst?
Du hast doch ne version die läuft?

**Comment by Splamy** [comment]
Server läuft wieder
