### ISSUE TITLE
TSClient von 3.1.8 auf 3.1.10 updaten

### ISSUE THREAD

**Issue by ManuPlaysLP** [Splamy/TS3AudioBot#346]
Wie kann ich den Client Updaten? 
PS: Funktioniert jetzt alles!

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#set-the-client-version

**Comment by ManuPlaysLP** [comment]
Und wo liegt diese bot_XXX.toml Datei, ich finde die niergends

**Comment by Bluscream** [comment]
Which version do you use?

**Comment by ManuPlaysLP** [comment]
from? AudioBot oder ClientVersion?

**Comment by Bluscream** [comment]
AudioBot

**Comment by ManuPlaysLP** [comment]
master

**Comment by ManuPlaysLP** [comment]
latest

**Comment by Bluscream** [comment]
latest is no version number.

**Comment by ManuPlaysLP** [comment]
where can I see the exact version 
number

**Comment by ManuPlaysLP** [comment]
Version: 0.8.1/master/cb1448a5

**Comment by Bluscream** [comment]
@Splamy your turn now :P

**Comment by ManuPlaysLP** [comment]
Ich wollte ja nur wissen, wo die Datei bot_XXX.toml liegt. Ich weiß was ich darin ändern muss, aber ich finde die Datei nicht. Also währe nett, wen mir jemand den path sageb könnte

**Comment by Splamy** [comment]
Die version im master hat diese datei noch nicht.
Geh zu deiner 'configTS3AudioBot.cfg' und setz den wert `QueryConnection::ClientVersion=` auf
`3.1.10 [Build: 1528537615]|Windows|+/BWvueikGg4YkO1v2uuZB5vtJJgUZ5bL8cRfxAstfnCVdro2ja+4a+8rGUzDx8/vvTZOUVD6U95hnWb638MCQ==` oder welches triple auch immer du aus der versions.csv willst

**Comment by ManuPlaysLP** [comment]
Danke @Splamy und @Bluscream !
Es funktioniert super!
