### ISSUE TITLE
How to get offline settings

### ISSUE THREAD

**Issue by SossenSystems** [Splamy/TS3AudioBot#349]
Hi Splamy,
How i can get the offline settings? :)
If i try this:
`http://{host}:{port}/api/(settings/get/bot_alpha-2-4)`
i become back:
```
{
    "ErrorCode": 17,
    "ErrorName": "MissingContext",
    "ErrorMessage": "Command 'CommandSettingsGet' missing execution context 'ConfBot'"
}
```

**Comment by SossenSystems** [comment]
Leider konnte ich immer noch nicht über die API via. `http://{host}:{port}/api/` die Settings bekommen.
Kannst du eine Example URL senden?

**Comment by SossenSystems** [comment]
Stimmt das habe ich komplett Vergessen...
Es funktioniert jetzt so wie du es mit deinem Tipp schriebst, jedoch nur wenn die Instanz online ist.
Wenn diese Offline ist bekomme ich bei `http://{host}:{port}/api/settings/bot/get/alpha-2-4/connect.name` folgendes zurück:
```
{
    "ErrorCode": 0,
    "ErrorName": "Unknown",
    "ErrorMessage": "Object reference not set to an instance of an object"
}
```

**Comment by Splamy** [comment]
Sicher dass du den aktuellsten develop runtergeladen hast?

**Comment by SossenSystems** [comment]
Ja klar, habe die aktuellste Build (alpha.80 | Branch: Develop) von hier.
