### ISSUE TITLE
Bot Not Connecting 

### ISSUE THREAD

**Issue by DinnerBeef** [Splamy/TS3AudioBot#351]
it keeps saying this

14:44:49.9520| WARN Could not connect: custom_error: the command failed to execute: Cannot connect to server 3.1 yet.

**Comment by DinnerBeef** [comment]
i think i get what it mean

**Comment by SossenSystems** [comment]
Duplicate from #187
Use the newest TS3AudioBot Version!
You can download the latest versions from the Master/Develop Branch here: https://splamy.de/Nightly

**Comment by Splamy** [comment]
Is this problem resolved? As SossenSystems said, it should work with the latest version.
