### ISSUE TITLE
How to get the Bot identity?

### ISSUE THREAD

**Issue by AlexBexDE** [Splamy/TS3AudioBot#352]
I want to use the Identity from the Bot in my Teamspeak³ Client, but the Identity in the Config file is kind of encrypted. anyways I can't import it to my Teamspeak³.

**Comment by Splamy** [comment]
No, it's the other way around. Teamspeaks identities are encrypted/obfuscated. The audiobot can import those identities, but we don't have an export function. So you could use it the other way around, or look at the algorithm and write a little script yourself

**Comment by AlexBexDE** [comment]
Okay, I exported an Identity and it works, thanks!
