### ISSUE TITLE
error Could not convert to UInt64

### ISSUE THREAD

**Issue by Qmis** [Splamy/TS3AudioBot#353]
Hello, I am trying to turn on the music and I get an error message:
12:53:40.5800|DEBUG Got message from Qmis: !play [URL]http://gr-relay-4.gaduradio.pl/2[/URL]
12:53:40.7585|DEBUG Command Error (Could not convert to UInt64)
12:53:40.7606|DEBUG AudioResource start: media ID:http://gr-relay-4.gaduradio.pl/2

 yesterday was good

**Comment by Splamy** [comment]
which ts3ab version?

**Comment by Splamy** [comment]
What was the problem, this could help others in the future?
