### ISSUE TITLE
AB as service graceful quit

### ISSUE THREAD

**Issue by liveuser1** [Splamy/TS3AudioBot#355]
On my system AB wont run in background, idk if it suppose to. Dont really matter but might be relevant to the next question.

When I start ab from console I could `kill -2` it gracefully. But if bot starts as service same command will kill the bot instantly. So there will be phantom clients on ts3 server present for some time.
[This](https://gist.github.com/bigendiansmalls/b38b8ed873c3e3297bbef4725e2c8e05) signal parcer tells me what ab dont catch sigint when running as service. Dont know what to make of it, it is just strange.
running from console:
```
SigPnd:
SigBlk:
SigIgn: PIPE(13)
SigCgt: INT(2) QUIT(3) ILL(4) ABRT(6) BUS(7) FPE(8) SEGV(11) CHLD(17)
   CONT(18) WINCH(28) (32) (33) RTMIN+1(35) RTMIN+2(36) RTMIN+3(37)
```
running as service:
```
SigPnd:
SigBlk:
SigIgn: PIPE(13)
SigCgt: QUIT(3) ILL(4) ABRT(6) BUS(7) FPE(8) SEGV(11) CHLD(17) (32)
   (33) RTMIN+1(35) RTMIN+2(36) RTMIN+3(37)
```

**Comment by blackjack4494** [comment]
Can you show me your init.d script?
So instead of using service ab stop you send a kill command to your service?

**Comment by liveuser1** [comment]
Starting service with input connected to tty helps, ab quits gracefully.

**Comment by Splamy** [comment]
I just tested it, I think this is a technical limitation of mono. When a program is not started from the console it won't receive the sigint and just close.

**Comment by blackjack4494** [comment]
What else you can do is to try screen. I use that personally.
