### ISSUE TITLE
bot stops playing, no ping respond ect

### ISSUE THREAD

**Issue by CrispyHere** [Splamy/TS3AudioBot#356]
As in title, bot playing music and in randomly moments stops playing. No ping respond, no respond for commands, bot need to be restarted to play again. What to do?

**Comment by Splamy** [comment]
Which audiobot version? Which platform/version? Which runtime/version  (mono: mono -V, dotnet: dotnet --info)? Anything in the log?

**Comment by CrispyHere** [comment]
Version: 0.9.0-unstable.35/develop/b529f8eb
Platform: Ubuntu 16.04 (64bit)
Runtime: Mono (5.14.0.177 (tarball Mon Aug  6 09:13:43 UTC 2018))
Opus: libopus 1.1.2 (x64)

Nothing in log, 0 records about crash or something. Bot is on channel but with no response to commands and time out if I checking ping

**Comment by Splamy** [comment]
The version is a bit old and there were a few client fixes until the latest version. Could you update and try again?

**Comment by CrispyHere** [comment]
Sorry, We updated now bot to the newest version and bot still need restars after some tracks. Again nothing in log dear dev. I checked permissions for groups and looks OK but I'm not sure.

**Comment by Splamy** [comment]
Hm, unfortunately such vague information don't help me much trying to find the problem.
You could try to run the bot with [Debug/Trace log](https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs) but this will generate *a lot* of data when running for a while.
If you can find any pattern on when this happens, certain songs, or stuff try to get it in the log, otherwise I would probably need the long log, if possible.

**Comment by CrispyHere** [comment]
So we turned on debug mode. Here is the log from two situations.
https://pastebin.com/XFicrHvS

In second situation I send to bot !pm command and then !play <something>
Bot crashed at 2018-08-17 22:42:52.6909. We were watching logs and its looking just like bot has too much data in one moment, too many packets or something similar to DDOS. Sometimes bot crashing by it self, sometimes after command. Sometimes playing 15 min. sometimes crashing after 2h.

The weirdest thing is that bot logging commands after crash but no responding for them.
Let me know if you want full raw log too

**Comment by Splamy** [comment]
Yes, please attach the full log here.

**Comment by CrispyHere** [comment]
Sure, here https://fallenpro.pl/ts3audiobot.log

**Comment by Splamy** [comment]
I just noticed, this is still running on the old version `Version: 0.9.0-unstable.35/develop/b529f8eb`
The latest version as of today is `0.9.0/master/f7375ff9`, did you maybe run the wrong one?

On another note, you always say 'crash' but describe that 'bot logging commands'.
Crash usually means the applications exits, does the bot exit? Or do you rather mean the bot 'hangs'?
This would be an important differentiation.
If it is the latter, the next time the bot hangs you could try executing `kill -QUIT $PID` where `$PID` is the process id of mono running the bot.
The terminal will dump a lot of data onto stdout which would be helpful in that case.

**Comment by CrispyHere** [comment]
Problem solved, we using now newer version but logs still printing wrong (old version). Anyway everything is fine now. Bot playing 12h at this moment without problems. So you can close the ticket. Thanks for help

**Comment by Splamy** [comment]
Weird, did you download the bot or manually compiled it?

**Comment by CrispyHere** [comment]
yes, we had versions with bugs, now working fine and compilated with this 

sudo apt install nuget msbuild﻿﻿﻿
wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe﻿﻿﻿
apt-get install git﻿
cd /home && mkdir TS3AudioBotCompile && cd TS3AudioBotCompile && git clone --recurse-submodules https://github.com/Splamy/TS3AudioBot.git && cd TS3AudioBot﻿﻿﻿﻿
nuget restore﻿
msbuild /p:Configuration=Release /p:TargetFramework=net46 TS3AudioBot.sln﻿

**Comment by Splamy** [comment]
Ok, I just want to let you know that you can always simply download the latest builds here: https://splamy.de/Nightly#ts3ab
When you don't want to make any changes to the source this saves you a little time.

**Comment by CrispyHere** [comment]
Thx 👍
