### ISSUE TITLE
AuthString?

### ISSUE THREAD

**Issue by CookieCr2nk** [Splamy/TS3AudioBot#357]
Dear Developer and Community

I have installed the new beta client from http://splamy.de/Nightly#ts3abv, but i have one problem. I dont no where i find the authstring, that you can find on the right site on top of the webinterface. or is the webinterface Stucked, because the last change was about 6 months ago.

CookieCr2nk

**Comment by SossenSystems** [comment]
Hello CookieCr2nk,
Just visit this page: https://github.com/Splamy/TS3AudioBot/wiki/WebAPI#authentication

**Comment by CookieCr2nk** [comment]
Yes, Thanks it works now, but can i make on 1 bot instance more bots than one. Where i can find in the wiki the Answer of the Question, or Multi-Instance now doesnt work?

**Comment by Splamy** [comment]
The webinterface is currently on hold and not developed, so don't expect too much from it.

Well we have an [FAQ](https://github.com/Splamy/TS3AudioBot/wiki/FAQ) on various stuff, but I have to agree, that we don't have any 'Getting started' page for an overview of all the most basic features.
Until we create one here's a quickstart for multiinstance:

Use `!bot connect to <ip/address/nickname>` to connect to a new server
Write `!bot save <template name>` to the new instance if you want to store it and the identity with it as a new bot template.
Use `!bot connect template <template name>` to connect a saved template again.
Use `!bot disconnect` to disconnect a bot again.

You can edit in the config which instances (templates) shold be run at startup:
```toml
[bots]
default = { run = true } # will be started
mybot1 = { run = false } # won't  be started
#<template name> = { run = true }
```

**Comment by CookieCr2nk** [comment]
Thanks for the Information, Multi-Instance works now, Now i dont need a Webinterface, because the whole bot can command over ts3chat and the configs.

CookieCr2nk
