### ISSUE TITLE
API extention

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#359]
For someone who want to control the bot over a interface he need more api commands. I am not sure if [this ](https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem#existing-commands)list is up to date but I need full control over the api like connect to this server or disconnect from another server. Is this still planned?

**Comment by rexlManu** [comment]
And how to control multiple bots. "bot/name/(name)" don't work :(

**Comment by Splamy** [comment]
Those features are all already available, for an overview of all command you can look at our autogenerated swagger/openapi site: http://splamy.de:8181/openapi/index.html
Each Ts3ab generates this this automatically when the webinterface is running and available.

To address a specific bot use `!bot use`, so over api like this: `/api/bot/use/0/(/bot/name/myname)` where 0 is the id of the bot. You can get an list of all bots with `!bot list`

**Comment by lgund** [comment]
Ah i got the wrong link. I am currently working on a splamy class and support for our interface v2. Both will be published soon. Thanks for your info. If something is missing I will reopen this post.
