### ISSUE TITLE
PLS Put all DLL's in a seperat Folder

### ISSUE THREAD

**Issue by HellBz** [Splamy/TS3AudioBot#362]
^^

PLS Put all DLL's in a seperat Folder
There to mutch dll-Files in Main Folder of TS3-Aduio Bot..

If Possible

**Comment by JABirchall** [comment]
Why? Thats software, you will have to complain to every other software developer and microsoft.
[1](https://i.imgur.com/Z5Cmkwj.png) [2](https://i.imgur.com/4UFEhIb.png)

**Comment by Splamy** [comment]
As JABirchall hinted, this is not possible.
I also don't see any benefits moving those dlls somewhere else.
