### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#364]
Hallo,

Ich möchte mal fragen wie ein Autostart gehen könnte beim TS3AudioBot der auf Ubuntu 16.04 läuft. Und wann der Autoplay kommt weil das für mein Projekt wichtig ist.

Mit freundlichen Grüßen

Tommy

**Comment by Splamy** [comment]
It will be there when it's done. I'm working on it.
Btw. you know that this is a duplicate of #238.
