### ISSUE TITLE
Command 'CommandPlay' missing execution context 'PlayManager

### ISSUE THREAD

**Issue by AdriaanBoshoff** [Splamy/TS3AudioBot#366]
**Describe the bug**
When trying to run `http://localhost:8180/api/yt/https%3A%2F%2Fyoutu.be%2FCeHtU-iFaNM` with the webapi I get the following: 
```
{
  "ErrorCode":17,
  "ErrorName":"MissingContext",
  "ErrorMessage":"Command 'CommandSong' missing execution context 'PlayManager'"
}
```

**Expected behavior**
To start playing the song and give output from the webapi

**To Reproduce**
Start the webapi. Let the bot connect and try using the following call: `http://localhost:8180/api/yt/https%3A%2F%2Fyoutu.be%2FCeHtU-iFaNM`

**Version**
```
Version: 0.9.0
Branch: master
CommitHash: f7375ff9b359486ba11643e53e2fa38c1782d4a8
```

**Platform**
Windows 10 (Latest and updated)

**Log**
```
2018-08-29 13:16:28.7679| INFO|WebServer.EnterWebLoop ::1 Requested: /api/yt/https%253A%252F%252Fyoutu.be%252FCeHtU-iFaNM
```

**Comment by AdriaanBoshoff** [comment]
In fact I get this type of message with every call. Can't use `song` or `add` or similar stuff.

**Comment by Splamy** [comment]
First of all, `yt` isn't actually a command, it just so happens that it matches on `play` so, while it works I just want to notice that this command has nothing special for youtube.

To actually play something via api you have to select a bot.
See here in the wiki: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#api-missing-context-iplayerconnection
(It says `IPlayerConnection`, but it's the same as `PlayManager`)
So for your example you'd have to write:
`http://localhost:8180/api/bot/select/(/play/https%3A%2F%2Fyoutu.be%2FCeHtU-iFaNM`

**Comment by AdriaanBoshoff** [comment]
The issue I'm getting now is:
```json
{
  "ErrorCode":17,
  "ErrorName":"MissingContext",
  "ErrorMessage":"Command 'CommandBotDisconnect' missing execution context 'Bot'"
}
```

**Comment by Splamy** [comment]
Uh I misstyped, it should've been as in the wiki 'bot use' not 'bot select'
So: http://localhost:8180/api/bot/use/0/(/play/https%3A%2F%2Fyoutu.be%2FCeHtU-iFaNM

But this command still seems weird, what did you call. Exactly the command I previously postet?

**Comment by AdriaanBoshoff** [comment]
Yes. I used the exact command you posted:
[Screenshot](https://i.imgur.com/kxn5oCr.png)

**Comment by Splamy** [comment]
Ah ok, I see, in this case it makes sense, the new command should work as said

**Comment by AdriaanBoshoff** [comment]
Thanks for the help. Just another thing. I think I might be using the URL encoding wrong. I'm trying to play the following URL: `https://youtu.be/CeHtU-iFaNM`. Using https://www.w3schools.com/tags/ref_urlencode.asp I managed to change it to: `https%3A%2F%2Fyoutu.be%2FCeHtU-iFaNM`

However now it gives me this:
```json
{
  "ErrorCode":10,
  "ErrorName":"CommandError",
  "ErrorMessage":"Could not load. (media: The resource could not be found.)"
}
```
I'm really sorry but I'm on the verge of understanding this.

**Comment by Splamy** [comment]
Since this issue hasn't been active for a long time I'll will close it for now.
If you still have any problems feel free to reopen this or open a new issue.
