### ISSUE TITLE
TS3AudioBot !bot save

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#367]
Hallo,

Wie mache ich es das wenn ich den Bot !bot save eingegeben habe. Das er sofort als in die Config gelangt als Botstart also das : = { run = true }

**Comment by Splamy** [comment]
You can change it afterwards with `!settings global set bots.<botname>.run true`

**Comment by Splamy** [comment]
As said, use the second command to create an entry for it

**Comment by Splamy** [comment]
`!settings set connect.channel /42` where `42` is the channel id.

**Comment by TomGamerTV** [comment]
Okay danke :)

**Comment by TomGamerTV** [comment]
Habe ich ausprobiert wird leider nicht eingetragen.

**Comment by Splamy** [comment]
Did you look into your `bot_<name>.toml` ?

**Comment by TomGamerTV** [comment]
Ja habe ich. Können Sie hier auch das in Deutsch hinschreiben?
