### ISSUE TITLE
Bot Avatar entfernen

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#376]
Hallo,

Wie mache ich das wenn ich beim TS3AudioBot einen Avatar hinzugefügt habe. Das die dann vom Befehl dann entfernt wird?

**Comment by CookieCr2nk** [comment]
Moin TomGamerTV, soweit ich informiert bin, kann man momentan noch kein Avatar per  Command entfernen. Du kannst ihn wenn du die Teamspeak3-Berechtigungen hast selbst entfernen. Oder dem Bot die  Avatar Berechtigung entfernen (Weiss nicht die genauen Rechte ). Wenn du einen eigenen Avatar setzen willst. Geht dies mit `!bot avatar <Picture URL>`

**Comment by Splamy** [comment]
I've changed the commands, `!bot avatar` was removed for `!bot avatar set <link>` and `!bot avatar clear`
