### ISSUE TITLE
Neueste TeamSpeak Version von OS X

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#378]
Hallo,

Wann kommt das neue OS X Version von TeamSpeak raus der Stable ist. Also jetzt bei dieser Liste: https://github.com/ReSpeak/tsdeclarations/blob/master/Versions.csv

**Comment by KD148** [comment]
Hello TomGamerTV,

please write your issues in English. Furthermore the versions have no important role for the AudioBot development so please do not open for every small thing a new issue.

**Comment by Splamy** [comment]
Noone of us has a Mac, the OSX versions are usually contributed by the community. if you know someone or want to get your versions more quickly into the rsdeclarations repo, simply connect with a client that has the said version to our server and our bot will automatically add it to the repo within seconds.

**Comment by TomGamerTV** [comment]
Hello Splamy,

How do I find out? Have on my TS server a user of my TeamSpeak version has.

**Comment by Splamy** [comment]
- You can tell the client to connect to our server once, our Bot will automatically push it.
- Can can install the same plugin we have for your Bot if you have one on your server: [VersionDetector.zip](https://github.com/Splamy/TS3AudioBot/files/2427754/VersionDetector.zip)
- You can manually get it with the serverquery command `clientinfo` and submit a pull request in our declarations repo.

**Comment by ShadowFM** [comment]
I can also connect, I‘ve a Mac, where do I need to connect at Monday?

**Comment by Splamy** [comment]
Connect whenever you want: splamy.de
You can check github, it should be pushed within a few seconds if it was successful

**Comment by TomGamerTV** [comment]
Thx @ShadowFM
