### ISSUE TITLE
[Idea]System service to use the Bot at the system boot

### ISSUE THREAD

**Issue by ShadowFM** [Splamy/TS3AudioBot#380]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
A system service for Debian / Ubuntu / CentOS to start the AudioBot at the system boot

**Describe alternatives you've considered**
Create manually a screen and the bot running, like this it isn't possible to use something like (restart, status, stop, start)

Best Regards,
ShadowFM

**Comment by Splamy** [comment]
This is probably not something I can do within my project, but would rather have to be defined/set up as a ubuntu package which installs everything accordingly.

You can however set it up by yourself.
The os you mentioned should all have `systemd`.
This is a little example how you could set it up with systemd:
You have to create file, for eg. `ts3audiobot.service` (the .service ending is necessary), in the path `/etc/systemd/system`.
Then write the following into it and adjust it accordingly
```ini
[Unit]
Description=TS3AudioBot

[Service]
Type=simple
# user and group which should run the process
User=teamspeak
Group=teamspeak
# Set your working directory here
WorkingDirectory=/home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/net46
# And the path to the ts3audiobot binary here
ExecStart=/usr/bin/mono /home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/net46/TS3AudioBot.exe
```

Then run
`sudo systemctl daemon-reload` to reload systemd,
`sudo systemctl start ts3audiobot` to run and check if the service runs properly; and finally
`sudo systemctl enable ts3audiobot` to run it at system start

**Comment by ShadowFM** [comment]
Konnte ich gestern leider erst testen, hat funktioniert, danke!

**Comment by muhammadmoazzam** [comment]
This is my .service file for people who are still looking to run it via systemd.

System is Ubuntu 20.04, with dotnet 3.1 installed


Location: `/etc/systemd/system/ts3audiobot.service`
```console
[Unit]
Description=TS3AudioBot
After=teamspeak.service

[Service]
Type=simple
User=teamspeak
Group=teamspeak
KillSignal=SIGINT
Restart=on-failure
RestartSec=10
WorkingDirectory=/home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/netcoreapp3.1
ExecStart=/usr/bin/dotnet /home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/netcoreapp3.1/TS3AudioBot.dll

[Install]
WantedBy=multi-user.target
```
