### ISSUE TITLE
I can't build the bot

### ISSUE THREAD

**Issue by SaveCodeOriginal** [Splamy/TS3AudioBot#384]
Hello!

Sorry for my english.
I have a problem with building in microsoft visual studio 2017.

This is the error: http://prntscr.com/kzs2mf

Please help me! :/

**Comment by Splamy** [comment]
You can choose one of them, they should all work:
- Download the project with `git clone`
- Delete GitVersionTask (https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#uninstalling-a-package)
- Downgrade GitVersionTask to 3.6.5 (same page)

**Comment by Flakebi** [comment]
If you have trouble with building the bot, you can also download the binaries, as described [in the readme](https://github.com/Splamy/TS3AudioBot#download).

**Comment by Splamy** [comment]
How do you do what? There are 3 options.
