### ISSUE TITLE
After the !settings global set bots command a confirmation

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#385]
Hello,

Can you do it like this if you set this command: !settings global set bots "{\"Botname\" : { \"run\" : true } }" then it appears that the bot has been successfully saved?

**Comment by Splamy** [comment]
If you don't get an answer then the setting has been successfully set.
By the way, I've changed this setting on the current develop branch, as the old one was somewhat bad.
You can now set it simply with `!settings set run true`.
