### ISSUE TITLE
!bot

### ISSUE THREAD

**Issue by SaveCodeOriginal** [Splamy/TS3AudioBot#386]
How do I do that with this command no message comes: !bot

**Comment by Splamy** [comment]
That message is integrated into the command system and automatically generated.
If want to change it go to the source code and change it yourself, or get someone to change it for you. I can't write every little change for you.

**Comment by SaveCodeOriginal** [comment]
Yes, but where can I change that? In which class?

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs#L48-L53 this, or another message?

**Comment by SaveCodeOriginal** [comment]
Yes, I mean that message. But how do I do that that there is no message?

**Comment by Splamy** [comment]
> If want to change it go to the source code and change it yourself, or get someone to change it for you. I can't write every little change for you.

It's open source so 'everyone can change it' and not 'I change it for everyone'.
Take 15 minutes and learn how to change simple strings and calls, you won't regret it.
