### ISSUE TITLE
Send audio stream into client

### ISSUE THREAD

**Issue by bigHapiness** [Splamy/TS3AudioBot#392]
Hi, @Splamy your lib is awesome. I started to writing custom bots instead Server Query.
Today start explore in details client features and have a question: how to put audio stream (file or web stream) to client ?
I didn't use ts3audiobot, only ts3client.
In past coded most time with php and nodejs. C# seems some difficult but i'm learning
Sorry for bad english 😄

**Comment by Splamy** [comment]
I have a few small examples lying around which I haven't got to posting the properly.
The library has a dedicated namespace `TS3Client.Audio` for audio processing.
All processing tools are designed as pipes (and pipe-ends), which means, data comes in, gets processed and pushed to the next pipe.
The client self works as two pipe-ends, one which 'produces' data (incomming voice), and 'receives' data (sending voice)
This is a small example on how to send for example a (file-)stream.
```csharp
// Setup client
var client = new Ts3FullClient(EventDispatchType.AutoThreadPooled);
var data = Ts3Crypt.LoadIdentity("MCkDAgbAAgEgAiBPKKMIrHtAH/FBKchbm4iRWZybdRTk/ZiehtH0gQRg+A==", 64, 0).Unwrap();
con = new ConnectionDataFull() { Address = "pow.splamy.de", Username = "TestClient", Identity = data };

// Setup audio
new StreamAudioProducer(File.OpenRead("bass.mp3"))
	// Reads from a passive output buffer with a fixed timing
	.Into<PreciseTimedPipe>(x => x.Initialize(new SampleInfo(48_000, 2, 16)))
	// Encode to the codec of our choice (codec should match the timed pipe)
	.Chain(new EncoderPipe(Codec.OpusMusic))
	// Define where to send to.
	.Chain<StaticMetaPipe>(x => x.SetVoice())
	// Send it with our client.
	.Chain(client);

// Connect
client.Connect(con);
```

You can connect pipes manually too, but the `Into` and `Chain` fluent extensions make this very convenient.

**Comment by Splamy** [comment]
ah, uh yes, i made a mistake, you obviously cant play mp3 files.
You'd either need a wav file with the 48k/2/16 format, or take a look at the [FFmpegProducer.cs](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Audio/FfmpegProducer.cs)
which wraps the ffmpeg.exe to convert any input to the correct format.

(By the way the packet loss is hardcoded for the lulz, as i haven't gotten to implementing it properly yet)

**Comment by Splamy** [comment]
The class previously linked to, is used to do exactly this in our AudioBot, I think it shows everything you need.
What info would you additionally need?

> And i have a question: is it possible to record audio from channel into file ?

That's possible but with limitations.
- Only opus voice and music work.
- You get all client audio streams mangled (since the `ClientMixdown` doesn't work yet), which means you'd have to write each client stream into a separate file and merge the afterwards with something like audacity, or you fix the `ClientMixdown` :P

```csharp
client
	// This reads the packet meta data, checks for packet order
	// and manages packet merging.
	.Chain<AudioPacketReader>()
	// Teamspeak sends audio encoded. This pipe will decode it to
	// simple PCM.
	.Chain<DecoderPipe>();
	// This will merge multiple clients talking into one audio stream
	// .Chain<ClientMixdown>(); ! Doesn't work right now
	// Write all streams into a file
	// .Chain<FilePipe>(); ! Doesn't exist, you'd have to write one.
```

After this you will have to chain something like a 'FilePipe'. We don't have such a pipe, but it shouldn't be that hard to write one.

**Comment by garko32** [comment]
is there any method to stop this command
```cs
new StreamAudioProducer(File.OpenRead("bass.mp3"))
	// Reads from a passive output buffer with a fixed timing
	.Into<PreciseTimedPipe>(x => x.Initialize(new SampleInfo(48_000, 2, 16)))
	// Encode to the codec of our choice (codec should match the timed pipe)
	.Chain(new EncoderPipe(Codec.OpusMusic))
	// Define where to send to.
	.Chain<StaticMetaPipe>(x => x.SetVoice())
	// Send it with our client.
	.Chain(client);
```

**Comment by Splamy** [comment]
Not in a really nice way. This would probably currently be the easiest way:
```csharp
var sap = new StreamAudioProducer(File.OpenRead("bass.mp3"));
var ptp = new PreciseTimedPipe();
ptp.Initialize(new SampleInfo(48_000, 2, 16));

sap.Into(ptp)
	// Encode to the codec of our choice (codec should match the timed pipe)
	.Chain(new EncoderPipe(Codec.OpusMusic))
	// Define where to send to.
	.Chain<StaticMetaPipe>(x => x.SetVoice())
	// Send it with our client.
	.Chain(client);

// either of those should work, but best used in combination:
// remove input
ptp.InStream = null;
// stop playback thread
ptp.Paused = true;
```
