### ISSUE TITLE
pkill -f 

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#395]
Hello,
Ubuntu 16.04
2.6.32-openvz-042stab125.5-amd64

If i stop the Bot with pkill -f (i use screen) the Bot time out and don't close correctly.

**Comment by Bluscream** [comment]
A kill command never shuts down peacefully

**Comment by preterive** [comment]
It works with sinusbot

**Comment by ShadowFM** [comment]
With pkill you only close all child processes but keeps the parent process alive. 
Why not try to use

> screen -X -S $SCREENNAME kill

**Comment by preterive** [comment]
Thanks, o try it later.

**Comment by preterive** [comment]
The Bot times out like before.

**Comment by ShadowFM** [comment]
Did you try it already with the killing of the PID of the processes?
