### ISSUE TITLE
Option to set own Avatar

### ISSUE THREAD

**Issue by cknost** [Splamy/TS3AudioBot#396]
**Is your feature request related to a problem? Please describe.**
No, it isn't related to a problem.

**Describe the solution you'd like**
That i can upload a Icon in the Bot folder as png and the Bot use this as Avatar.

**Comment by Flakebi** [comment]
There is already a command for that (although it is not documented on the wiki):
In the current develop branch: `!bot avatar set <url>`
In the master branch: `!bot avatar <url>`

(See also  #376)
