### ISSUE TITLE
Own message for !help

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#397]
**Is your feature request related to a problem? Please describe.**
The guests can't use all Commands and the help is not good.

**Describe the solution you'd like**
That i can configure a message that every guest see if they type !help

**Comment by Splamy** [comment]
You can replace this function: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainCommands.cs#L303-L355
and write your own message there.
