### ISSUE TITLE
add! should start the song if nothing is running

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#399]
Hello again @Splamy, where I can see the list from all bot commands?

!bot connect dont work :( 

How I can add a new bot with a new identity? 

I see !bot connect to my.server.com but this dont save a new template 

I'm using "Version: 0.9.1/master/55466f28" in CentOS 7.

**Comment by Splamy** [comment]
`!bot connect to <address>` is already the correct command, you have to write `!bot save <name>` afterwards to the new bot to save it.
To get an overview of all command you can go to http://bot.splamy.de/index.html?page=commands.html
each bot with the webinterface enabled has this page.

**Comment by robotrono** [comment]
@Splamy thanks! works fine now, loop is no longer exists? I remember  set "!loop on" for the bot never stop the music.

**Comment by robotrono** [comment]
Btw: Yotube Streams dont works :( 

`09:33:16.6872| INFO User Akira requested: !play [URL]https://www.youtube.com/watch?v=LsBrT6vbQa8[/URL]`

**Comment by Splamy** [comment]
To `!loop` see here the lowest entry: https://github.com/Splamy/TS3AudioBot/wiki/Changelog#d45044984877fa07fa3675371349c52bda632560---2018-08-30

To youtube streams, yes I haven't gotten to yet, the tracking issue for this is here: #58

**Comment by robotrono** [comment]
@Splamy Im trying to make a public bot for my server, so when the users use the command !add this not play music

**Comment by robotrono** [comment]
> Hmm, I'll think about it if would be better when !add also starts the queue, when nothing is playing right now...

Yes please, or maybe a new command.

**Comment by robotrono** [comment]
@Splamy 
This is normal? The bots had been inactive for a period of time and apparently the process has been killed
```
09:26:54.5980| INFO User Akira requested: !list play
09:26:59.2348| INFO User Akira requested: !play
09:27:10.8575| INFO User Akira requested: !next
09:27:16.0535| INFO User Akira requested: !next
09:27:37.5814| INFO User Akira requested: !add [URL]https://www.youtube.com/watch?v=F1B9Fk_SgI0[/URL]
Killed
```

**Comment by Splamy** [comment]
Usually not, every exit which comes from the ts3ab would at least leave a log, even when crashing. This is probably something like OOM-killer maybe.

**Comment by Splamy** [comment]
Done with the new queue

**Comment by robotrono** [comment]
@Splamy is live in master branch?

**Comment by Splamy** [comment]
Yup it is.
