### ISSUE TITLE
Web API Command info not working

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#400]
**Describe the problem**
If I try to execute the api/bot/info I got following message: `Command 'CommandBotInfo' missing execution context 'Bot'`

**System Information**
- **Platform**: Ubuntu 16.04  
  
- **Mono version**:
5.16.0.179
  
- **Which commit did you download**: 
Version: 0.10.0-alpha.37/develop/90c16858
 

```
15:26:20.0974| INFO 62.75.187.128 Requested: /api/bot/list
15:26:23.6682| INFO 62.75.187.128 Requested: /api/bot/info
```

**Comment by dzinks2009** [comment]
Does api/bot/list work?

**Comment by lgund** [comment]
yes

**Comment by dzinks2009** [comment]
Hmm, try /api/bot/use/<ID_OF_INSTANCE>/(/bot/info

**Comment by lgund** [comment]
I want the version of the bot instance. I want to display it on my interface. It's there a other command to get the information?

**Comment by dzinks2009** [comment]
What do you mean by bot version?;o

**Comment by dzinks2009** [comment]
/api/version?

**Comment by lgund** [comment]
/api/version works fine! Thanks for the info. I will let this issue open cause it´s still a bug right? If not @Splamy pls close this issue. For me it´s resolved.

**Comment by Splamy** [comment]
What do you consider a bug here?
If it's the missing module, that's by desing. You can't call a method which is bot specific, without specifying the bot first (see [wiki](https://github.com/Splamy/TS3AudioBot/wiki/FAQ#api-missing-context))
