### ISSUE TITLE
Group and API Permission.

### ISSUE THREAD

**Issue by Provokan** [Splamy/TS3AudioBot#401]
**System Information**
- **Platform**: 
Debian 8, 
  
- **Mono version**: 
5.16.0.179 
  
- **Which commit did you download**: 
Version: 0.10.0-alpha.37  
  

Hello community, 

after we got the tip with the /api/version, the version query works, but i have another problem, in order for the API to work, it is necessary that i give the group "+" full "*" rights, so that the API works. 

So my question is, is it possible - to create a rights group for the API without having to assign full admin rights to the "+" group? 

It would be cool if you could make the API more customizable, or if it even works fine, because the developer of First-Coder tries to integrate your music bot into his interface.

**Comment by dzinks2009** [comment]
I have my rights like this 

[[rule]]
groupid = 36
useruid = "serveradmin"
apitoken = "xxxxxxxxxxxxxxxxxxxxx"
"+" = ["*"]

That way every admin can talk to bots, every user with uid "serveradmin can talk to bots, and every request with apitoken "xxxxxxxxxxxxxxxxxxxxx" can talk to them.

**Comment by lgund** [comment]
A other way to give just api request full access:

`     [[rule]]
	   isapi = true
	   "+" = "*"`

**Comment by Splamy** [comment]
@lgund You do know that this rule is a big security risk when the api port is exposed to the internet.
You should either definitely make sure that this port isn't accessible from elswhere than localhost (you can specify that in the config `web.hosts`).
Or resolve to something like @dzinks2009 suggested.
