### ISSUE TITLE
bot on more than 1 Teamspeak

### ISSUE THREAD

**Issue by DennisAncelotti** [Splamy/TS3AudioBot#404]
Hey, if i connect with the bot to a second Teamspeak i dont got a permission txt for the Commands ?
is it possible that there is a new permission txt for a second teamspeak with other servergroups?

i hope you know what i mean, for another teamspeak i need a second rights.toml because they are other servergroup ID´s -
- and i connected with the bot to another teamspeak but dont have rights there for commands ^^

**Comment by DennisAncelotti** [comment]
i hope you know what i mean, for another teamspeak i need a second rights.toml because they are other servergroup ID´s -

**Comment by Splamy** [comment]
You can't add a second file currently, but you can match on bots in the permission file,
see here for an example: https://github.com/Splamy/TS3AudioBot/issues/341#issuecomment-412493473

**Comment by DennisAncelotti** [comment]
@Splamy
Can i just paste it under the normal rights settings?

**Comment by DennisAncelotti** [comment]
![grafik](https://user-images.githubusercontent.com/44170131/47012470-93a75b00-d144-11e8-905d-2052b42bb781.png)

have it now so, but it didnt work oh other Teamspeaks

**Comment by Splamy** [comment]
What do you mean with 'other Teamspeaks'?
Did you connect the bot with `!bot connect template UKG`?
Did you check that the group id 132 is correct and that you are in the group.
Are there any warnings in the log? (Maybe the bot has no permissions to check server groups)
The first one of your two `rule.rule`s is redundant.
When you have two sub-rules like this , it's the same as if you would the `+` in the same like:
`"+" = [ "cmd.play", "*" ]`
(Note that whitespaces and linebreaks are irrelevant for arrays in toml)
Furthermore, the `"*"` already includes `"cmd.play"`, as the root-wildcard includes all permissions.
(I don't know whether you are just using this for testing purposes, but just be clear)

**Comment by DennisAncelotti** [comment]
Hello @Splamy now i created a template, changed the IP adress in the template connected via !bot connect template to the other server but still have no permissions

**Comment by Splamy** [comment]
How does the relevant rule look like? (you can post code withing triple backticks like that:

     ```toml
     <code>
     ```
)
Can you make sure that the group id is correct on the server?
