### ISSUE TITLE
TS3AudioBot help Request

### ISSUE THREAD

**Issue by Bastih18** [Splamy/TS3AudioBot#405]
Hallo, ich wollte fragen wie das mit den bot badges funktioniert, da ich da nicht durchsehe.
(also was muss ich da angeben nach !bot badges overwolf=1:badges= (wenn ich noch andere abzeichen als overwolf haben will)  (ich will da das badget Found Tim Speak at Gamescom 2018 noch haben ( 

Code: XJN4WJZEJN
URL-Basis: https://badges-content.teamspeak.com/b9c7d6ad-5b99-40fb-988c-1d02ab6cc130/met_tim 
GUID: b9c7d6ad-5b99-40fb-988c-1d02ab6cc130
 ) )

**Comment by Bastih18** [comment]
Und ich würde gerne auch wissen ob und wie ich die beschreibung vom bot per cmd ändern kann

**Comment by Splamy** [comment]
- `!bot badges b9c7d6ad-5b99-40fb-988c-1d02ab6cc130,b9c7d6ad-5b99-40fb-988c-1d02ab6cc130` eine komma serparierte liste von guids.
- `!bot description set "My desc"`

**Comment by Bastih18** [comment]
ok danke
