### ISSUE TITLE
Webinterface???

### ISSUE THREAD

**Issue by AlexBexDE** [Splamy/TS3AudioBot#406]
Ich blicke nicht durch! Gibt es jetzt ein Webinterface für diesen Bot oder nicht?? Ich kenne jemanden der hat ein funktionierendes Webinterface! Das ist aber irgendwas anders. Kann mich jemand bitte aufklären??!

**Comment by lgund** [comment]
Es gibt die Möglichkeit ein eigenes interface über die Api Schnittstelle zu entwickeln und zu integrieren. Allerdings arbeitet Splamy auch an einem interface, dass vom Hause aus mitgeführt wird. Dieses funktioniert auch schon halbwegs. Einfach das interface über die Konfiguration aktivieren und per Webbrowser den Port öffnen.

Ich selbst würde gerne noch erwähnen, dass First-Coder mit der kommenden Version 2.1.5 ein komplettes Splamy Webinterface mitführen wird.

**Comment by CookieCr2nk** [comment]
Hallo @lgund Ich verfolge das Projekt First-Coder schon seit einer weile und habe erfahren, dass demnächst das Webinterface kommt, doch (Wahrscheindlich) aus Zeitmangel der Release zu einem Späteren Zeitpunkt angesetzt wurde, wollte ich fragen, wann das Webinterface in etwa releast wird?

**Comment by AlexBexDE** [comment]
@lgund Okay. Danke für die Info!

**Comment by lgund** [comment]
@CookieCr2nk das ist korrekt. Das Team sieht sich momentan die closed alpha an. Ich gehe davon aus, dass ich es hoffentlich nächsten Monat zur open beta bringen kann. Weiter kann ich nicht sagen. Die alpha wird allerdings schon den Splamy bot unterstützen.

**Comment by AlexBexDE** [comment]
@lgund Das WebInterface das schon dabei ist. Könntest du mir helfen das zu installieren??
Ich habe folgendes gemacht:

Meine Config sieht so aus: https://hastebin.com/bigibokaqo.ini und ich habe den "WebInterface" Ordner in das gleiche Hauptverzeichnis getan wie die Config. Dann habe ich die gleichen WebInterface dateien auf einen Webserver getan und habe mit mit !bot token einen Token geholt und auf dem auf der Seite vom Webserver eingefügt.

Über den Webserver kann ich nicht zugreifen und bei http://mein-server.de:8180 kommt keine Seite, und sonst weiß ich nicht wie ich zugreifen soll. Währe gut wenn du mir das näherbringen könntest.

**Comment by lgund** [comment]
Du hast die url nach außen hin noch nicht geöffnet. Du solltest daher diese in deiner config ebenfalls öffnen. Trage daher deine url und / order ip adresse im folgenden part mit ein:

> #An array of all urls the web api should be possible to be accessed with.
hosts = ["localhost", "127.0.0.1"]

**Comment by AlexBexDE** [comment]
Wenn du darauf hinaus willst, dass die IP des WebServer dort stehen sollte, das ist bereits der fall, bzw. der Webserver ist auf dem gleichen System wie der Bot. Ich habe dort dann trotzdem mal meine eigene IP eingegeben.
``
#An array of all urls the web api should be possible to be accessed with.
hosts = ["localhost", "127.0.0.1", "31.18.***.***"]``

Dann kommt aber folgender Fehler: https://hastebin.com/izogavucon.css
Wenn du Zeit hast könntest du auch auf meinen Teamspeak Server kommen. IP: ClaimMC.net

**Comment by Splamy** [comment]
Da muss nicht die ip rein, sondern die domain über die dann tasächlich zugegriffen wird, also in deinem Fall `"ClaimMC.net"`

**Comment by ShadowFM** [comment]
Es sollte beides gehen, ich verwende bei mir aber auch nur die IP-Variante:
‘‘‘‘
[
 “127.0.0.1“,
 “<external-ip>“,
 “<internal-ip>“
]
‘‘‘‘

**Comment by Splamy** [comment]
Das sollte definitiv nich gehen. Hast du deinen webserver von nginx oder apache oder so geproxied?

**Comment by AlexBexDE** [comment]
Okay, es hat funktioniert und das Webinterface der Develop-Version ist garnicht mal so schlecht!
Danke an alle hier die mir geholfen haben <3
