### ISSUE TITLE
Config and !name 

### ISSUE THREAD

**Issue by KrecikQ** [Splamy/TS3AudioBot#408]
Hello, Well, I have a problem that I downloaded versions, I built it. I start the bot enter ok. Then it gives him the range and configures rights.toml, I have two config, one in the main catalonia and the other in the / bots directory, In the second config directory generates about 30 lines of which 3/4 are comments. The problem is that after changing the nickname, for example, name nickname nickname changes temporarily. After returning again, the bot has a bot which is in the main config.

Splamy, Could you help me with this? Or send an earlier version (of course Source Code)

**Comment by Splamy** [comment]
Your question is really hard to read. Please re-read your issues before submitting and try to write in simple and concise sentences.
Maybe this helps:
There are a few different `!settings` overloads to work with the configuration.
- `!settings get/set` changes the `!bot_<name>.toml` file of the bot you are *currently* writing with
- `!settings bot get/set <name>` changes the `!bot_<name>.toml` file of the bot you *specified in the command*
- `!settings global get/set` changes the `ts3audiobot.toml`

So for the name:
- `!bot name <name>` changes the name of the current bot *temporarily*
- `!settings set connect.name <name>` changes the name of the *current bot* but will only apply the next time the bot connects (as this is only used for cennecting)
- `!settings global set bot.connect.name <name>` defines the name for *all* bots which *do not* have the `connect.name` field set in their `bot_<name>.toml` file. So it practically provides a 'default' value for bots which don't set the setting explicitely.

**Comment by KrecikQ** [comment]
Ok, soo. thank you for help with config. My next question is... how i can change description of bot ? Np Now Playing: XXX. I want off this description. Thank you

**Comment by Splamy** [comment]
If you want to permanently disable/enable auto-setting the description you can use the config entry
`!settings set set_status_description true/false`
To change it once `!bot description set "<my desc>"`

**Comment by KrecikQ** [comment]
Thank you very much. <3
