### ISSUE TITLE
Automatic loading of the plugin

### ISSUE THREAD

**Issue by Mezir** [Splamy/TS3AudioBot#410]
I wrote a plugin that I would like to automatically load when the bot starts.
My plugin has the name "cmdPomoc.cs".
I also created a file called "cmdPomoc.cs.status", which contains "1".
Unfortunately, the plugin does not load itself.
```
 All available plugins: 
#0|RDY|cmdPomoc (Commands)
```
How do I solve my problem?

**Comment by Flakebi** [comment]
The [wiki article](https://github.com/Splamy/TS3AudioBot/wiki/Plugins) about plugins tells you to create a file called `YourPluginName.Extension.status` with the content 1.

But I am not sure if that is already implemented, because the `PersistentEnabled` variable is not read in the code.

**Comment by Mezir** [comment]
> The [wiki article](https://github.com/Splamy/TS3AudioBot/wiki/Plugins) about plugins tells you to create a file called `YourPluginName.Extension.status` with the content 1.
> 
> But I am not sure if that is already implemented, because the `PersistentEnabled` variable is not read in the code.


Can you show me an example? I do not understand the wiki

**Comment by Mezir** [comment]
> Zgodnie z wiki, `cmdPomoc.cs.status`powinna ona być prawidłową nazwą pliku, tak jak to robiłeś.
> 
> W kodzie wygląda na to, że ta metoda jest przestarzała i już nie działa.
> 
> Nowa metoda prawdopodobnie będzie napisać coś w `[plugins.load]`sekcji w pliku konfiguracyjnym, ale w tej chwili nie ma nic zaimplementowanego.
> 
> Aby obejść ten problem, może być możliwe (ale nie przetestowane), umieszczenie `!plugin load …`polecenia wewnątrz `onconnect`zdarzenia, więc za każdym razem, gdy bot łączy się z serwerem, wtyczka zostanie załadowana ( [zobacz ten komentarz](https://github.com/Splamy/TS3AudioBot/issues/238#issuecomment-416382582) dla przykładu.

It works. :D

**Comment by Splamy** [comment]
Closed for now in favor of #650
