### ISSUE TITLE
Need Quick Help

### ISSUE THREAD

**Issue by FlareNetwork** [Splamy/TS3AudioBot#413]
Hello,

i dont know a lot in C#.

but please say me where the Bot checks the Permission that a user can run a command or not.

**Comment by FlareNetwork** [comment]
How i can pass the User UUID and the Bot ID to the check ?

**Comment by Splamy** [comment]
You know you can simply check for client uid and bot in the normal rights.toml without changing any source code.
If you still want to get it, it's not that simple, [this part]
(https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/MainCommands.cs#L1522-L1530) and [this](https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/Rights/RightsManager.cs#L74-L186) accumulates all necessary information.

**Comment by FlareNetwork** [comment]
I want to remove the toml rights and check perms by my API.
