### ISSUE TITLE
Timeout when bot gets poked

### ISSUE THREAD

**Issue by SuspiciousActivity** [Splamy/TS3AudioBot#414]
The bot timeouts when poked.

I tested it from source and looked at the packets:
```
...
[I] CommandLow 0 (notifyclientpoke)
[O] AckLow 0
...
[I] CommandLow 0 (notifyclientpoke)
[O] AckLow 1
...
[I] CommandLow 0 (notifyclientpoke)
[O] AckLow 2
...
```

So apparently there is a problem with acknowledging the `notifyclientpoke` packet (or `PacketType.CommandLow` in general).

Happens in both pre-compiled and self-compiled version.

**Comment by SuspiciousActivity** [comment]
I used https://github.com/Splamy/TS3AudioBot/commit/55466f287493026b03e877ac1191e2aa905023b9 for both build and pre-compiled, server version is 3.3.1 on Linux. What's strange about it that it only happens on some servers. I tested it on another 3.3.1 server and it worked just fine.

**Comment by Splamy** [comment]
Thanks, I'll try to look into it when I get to

**Comment by Splamy** [comment]
I've pushed a fix on the current dev branch. Apprently the normal client sends acklow's unencrypted, so I'm doing it now too.
After the change, both my old server, and the server on the ip you posted work now.
Please verify for yourself that it works and (hopefully) didn't break on servers which already worked before.

**Comment by SuspiciousActivity** [comment]
I can confirm, it works now. Thanks.
