### ISSUE TITLE
New Command.

### ISSUE THREAD

**Issue by KrecikQ** [Splamy/TS3AudioBot#415]
Hi, its me again. 
So, i have a question... I want to create command "admin"...  and i try on and nothing...
Can you manage me to write this command ?
E.g I want this (down )
<02:02:14> "TS3AudioBot": ===[Its Admin Command ]===
<02:02:14> "TS3AudioBot":!quit - Disconnecting bot 

I want messages to be sent in several messages and not in one.
Yes, i seen your guide and i dont know what do did. 

How can I write to do this in several messages?

**greetings**

**Comment by Splamy** [comment]
Inject a `ExecutionInformation` to your command, and call `Write(string)`. So for example:
```csharp
[Command("admin")]
public static void MyAdminCommand(ExecutionInformation info /*, further arguments*/)
{
    info.Write("hello from");
    info.Write("multiple mesages");
}
```
