### ISSUE TITLE
Automatic start when Linux starts

### ISSUE THREAD

**Issue by SorryDudeGotcha** [Splamy/TS3AudioBot#417]
**Describe the problem**
Hello. So i would like to set up a Autostart. This means that when Linux starts, a new screen is created in which the TS3AudioBot starts automatically.

**System Information**
- **Platform**: Debian 9  

I hope you can help me.

**Comment by Splamy** [comment]
use something like [systemd](https://wiki.archlinux.org/index.php/Systemd):

```ini
[Unit]
Description=TS3AudioBot

[Service]
Type=simple
User=teamspeak
Group=teamspeak
WorkingDirectory=/home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/net46
ExecStart=/usr/bin/mono /home/teamspeak/TS3AudioBot/TS3AudioBot/bin/Release/net46/TS3AudioBot.exe
```

**Comment by SorryDudeGotcha** [comment]
Thank you, now it works!

**Comment by Bluscream** [comment]
Can we change the log output to `/var/log/TS3AudioBot.log` somehow? I have a cleanup cronjob for that directory

**Comment by Flakebi** [comment]
You can just change the file path in [`NLog.config`](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/NLog.config).
Or disable the logfile completely and use [`journalctl`](https://wiki.archlinux.org/index.php/Systemd#Journal) to view the log.
