### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by KrecikQ** [Splamy/TS3AudioBot#418]
How i change avatar ? !avatar has error.

Can I make a file such as Avatar.png in the main directory to read it somehow?

**Comment by Splamy** [comment]
`!bot avatar set <link>` if it is a local file you can either give a absolute  or relative path from your working directory to the file

**Comment by KrecikQ** [comment]
If i use !bot avatar set <link>  -> i have Error: No matching command
if i use !avatar <link> -> avatar change and if i reconnect bot , avatar is again sleppykittyy.

**Comment by KrecikQ** [comment]
is it possible for avatar.png in the main folder to be read as the main avatar

**Comment by Splamy** [comment]
- Which version are you using? The avatar command is only available on the current dev branch iirc.
- If you want to prevent the bot from overwriting your avatar disable the setting: `generate_status_avatar = false` (`!settings set generate_status_avatar false`)
- Yes this is planned but not implemented yet. You can workaround this by setting the `onconnect` event in the settings to for example `!bot avatar set avatar.png`

**Comment by KrecikQ** [comment]
Can I set the path to the avatar? Let me just change the avatar.png file in the bot directory

**Comment by Splamy** [comment]
You can now create a `avatars` folder in each bot directory.
The bot will pick a random file starting with `play*` (any image like jpg, png, gif; e.g `play1.gif`) when playing song without cover.
And a random file starting with `sleep*` when stopped.
Feature is now on develop.

**Comment by Oakza035** [comment]
Can I change the image when it stops working?

**Comment by RewLoad** [comment]
@Splamy 
![image](https://user-images.githubusercontent.com/50944833/145336416-7401b1b5-11e0-4939-b011-1d996be5b981.png)
am i doing it right
