### ISSUE TITLE
Bot Connections Problem

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#420]
I have a server protected at OMGServ's Game DDos. When I start the bot you do not connect to any of the servers. Can one help me with this?

**Comment by Splamy** [comment]
We have a issue template which covers all necessary infos I would need to get started. If you ignore it anyway at least provide more context of your situation.
Are you running the ts3ab on the same server? If not can you connect normal clients from that location? What does the log say? If it doesnt say anything, run with debug log and see if it then prints anything?

**Comment by Bluscream** [comment]
@Splamy https://github.com/apps/stale

**Comment by Splamy** [comment]
This seems to be related to your Server firewall. Check that udp traffic is allowed.
Closed, as not directly a TS3AB problem.
