### ISSUE TITLE
Help with source code.

### ISSUE THREAD

**Issue by KrecikQ** [Splamy/TS3AudioBot#422]
How i can set source to avatar ? Now avatar is in source code and compiled. i want... bot read avatar from file avatar.png where image stay in  main folders. I dont want use !avatar set if i execute command e.g !stop bot reload avatar to sleppykit. Can you help me  to change this?

**Comment by Splamy** [comment]
Go to [TS3AudioBot/Media](https://github.com/Splamy/TS3AudioBot/tree/master/TS3AudioBot/Media) and replace `SleepingKitty.png` with your file. Then recompile.
