### ISSUE TITLE
Web API Commands getmy/* won´t work correctly

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#425]
**Describe the bug**
The Musicbot is successfull connected on my teamspeak server. I´ve full access over the api dosen´t get the correct information above the bot. I don´t get her name or ids.

**To Reproduce**
Try to set the bot api command (My ID is here 0):
`/api/bot/use/0/(/getmy/all)`

The json result looks like this:
`stdClass Object ( [ClientUid] => xZ5Jr0S0oMYJ3YTZLhrxt/a+CiY= [DatabaseId] => 2 [ChannelId] => [ClientId] => [NickName] => [Token] => VQDyiFqMRCSvsD2LSCzaleYD******* [Visibiliy] => [ServerGroups] => [IsAnonymous] => )`

**Version**
0.10.0-alpha.37 (develop)

**Platform**
ubuntu 16.04

**Comment by Splamy** [comment]
`!getmy all` gets information about you -  the caller.
If you want to get basic information about the bot client use  `!bot info`, or rather `!bot info client` which gives you the teamspeak information

**Comment by lgund** [comment]
Ahh - Fail :+1: 

With `/api/bot/use/0/(/bot/info/client)` I got the information I needed. Thanks you your fast feedback!
