### ISSUE TITLE
Bot ignoring path to yt-dl

### ISSUE THREAD

**Issue by elipeF** [Splamy/TS3AudioBot#427]
**Describe the bug**
When custom path to yt-dl is set(absolute path ex. "/home/is/path/to/youtube-dl" and youtube-dl is a file with 777 chmod) bot just ignore it and use yt-dl in "/usr/local/bin/youtube-dl" 

**Version**
0.9.1

**Platform**
Platform
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch

Mono JIT compiler version 5.14.0.177 (tarball Mon Aug 6 09:13:21 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS: __thread
SIGSEGV: altstack
Notifications: epoll
Architecture: amd64
Disabled: none
Misc: softdebug
Interpreter: yes
LLVM: yes(3.6.0svn-mono-/)
GC: sgen (concurrent by default

**Comment by Splamy** [comment]
Hm yes the current behaviour stops searching when it finds youtube-dl in the default location.
But I can see why this might be inconvenient.

**Comment by Splamy** [comment]
Should be fixed. Please verify that on your side.
