### ISSUE TITLE
Best Way to have Plugin Config?

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#430]
Most of the libraries for these tasks are for .net not .netstandard (ex: https://github.com/rickyah/ini-parser)

Can you provide an example on how to use your toml parser to create and read from a custom config file?

**Comment by Splamy** [comment]
.netstandard *includes* .net framework, see here: https://docs.microsoft.com/en-gb/dotnet/standard/net-standard#net-implementation-support

for example if you have a library targeting .net46, and the audiobot is using .netstandard 2.0, you can see in the table .net4.6 implements 1.3 (at the top), and 1.3 < 2.0, so you have no problems using it.

For the toml parser: https://github.com/paiden/Nett#getting-started
