### ISSUE TITLE
Plugin log to file + console

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#431]
My current log function is pretty crappy
```csharp
public void PluginLog(LogLevel logLevel, string Message) { Console.WriteLine($"[{logLevel.ToString()}] {PluginInfo.Name}: {Message}"); }
```
i would prefer to use your NLog thingy. Is it easy? If yes, can you show an example?

**Comment by Splamy** [comment]
https://github.com/nlog/nlog/wiki/Tutorial#log-levels

**Comment by Bluscream** [comment]
Does that mean i have to ship my own NLog.config file with my plugins? And do i have to add nlog as reference even though i have ts3sb as reference already?

**Comment by Splamy** [comment]
no and no.
There's only one nlog.conf per application.
Your plugin automatically also gets a reference to nuget

**Comment by Bluscream** [comment]
I still have no idea how to use this but i am not going to bother anymore

**Comment by Splamy** [comment]
I'll give you a brief summary tomorow, ok?

**Comment by Bluscream** [comment]
Thanks :) :heart:
