### ISSUE TITLE
Check paramaters sent with a event

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#435]
Something like this:

```csharp
		private void OnEachClientUpdated(object sender, ClientUpdated e)
		{
			bool recordStausUpdated = e.hasKey("client_is_recording");
			int.TryParse(e["client_is_recording"], out int newRecordStatus);
			string rawEvent = e.raw();
		}
```

**Comment by Splamy** [comment]
All optional parameters are now nullable and set to `null` when not in the ts3 message.

**Comment by Bluscream** [comment]
Can you mention the commit or give a quick example?

**Comment by Splamy** [comment]
Commit: 698a00d8496667249a21366c5fa72a0537eb6c2d
Take a look here, optional parameters have a `?` which means, values like bool` or `int` can be `null`
https://github.com/Splamy/TS3AudioBot/commit/698a00d8496667249a21366c5fa72a0537eb6c2d#diff-ed81cac12dde02ad1efa80674a8ef260L4764-L4793
