### ISSUE TITLE
Some Dependencies are missing for this plugin

### ISSUE THREAD

**Issue by DerProbber** [Splamy/TS3AudioBot#438]
Hello,

i have some trouble to get my plugin loaded. I probably just forgot something but i cant figure it out right now. I compiled my plugin via NET Core and the Bot shows me in !plugins list that my plugin is ready but when i load my plugin via !plugin load 0 i get the following error: WARN Some dependencies are missing for this plugin.

I also compiled my Plugin via netstandard2.0 and the same error appears, so what do i wrong ? 

best regards

Probber

**Comment by Bluscream** [comment]
Whats your plugin and what Dependencies does it have?

**Comment by DerProbber** [comment]
Its a BotPlugin, i have added the following dependencies to the project: TS3AudioBot.exe, TS3Client.dll, NLog.dll, Nett.dll, LiteDB.dll. I use all these librarys and the project compiles fine. I also added all the librarys in the plugins folder but it also not working.

**Comment by Bluscream** [comment]
Are you sure your plugin doesn't need other dependencies? What is your plugin about?

**Comment by DerProbber** [comment]
Okay its working now. I just used NuGet to get my dependencies now everything works fine. Thank you for helping me out. Regarding your question: Its a alarm plugin it sends a audio alarm if a specific time passed.
