### ISSUE TITLE
AFK mover (Away/Mute/Deaf/Idle)

### ISSUE THREAD

**Issue by wendellcosta** [Splamy/TS3AudioBot#440]
Add AFK mover (Away/Mute/Deaf/Idle)
Moves clients that are set as away, have their speakers/mic muted or are idle to a specified channel

**Comment by Bluscream** [comment]
I am actully working on something like that as a plugin but i have to wait for https://github.com/Splamy/TS3AudioBot/issues/435 to be resolved.
