### ISSUE TITLE
Error: Could not load. (youtube: youtube-dl failed to load the resource.)

### ISSUE THREAD

**Issue by DennisAncelotti** [Splamy/TS3AudioBot#446]
Error: Could not load. (youtube: youtube-dl failed to load the resource.)

I got this error, and the old Issue didnt work for me? ( https://github.com/Splamy/TS3AudioBot/issues/279 )

**Comment by Splamy** [comment]
Make sure you have the latest youtube-dl (https://github.com/rg3/youtube-dl/blob/master/README.md#installation)

Check the youtube video you are trying play with youtube-dl manually like this:
`youtube-dl --no-warnings --get-title --get-url --format bestaudio/best --id -- <the id here>`

so for example for `https://www.youtube.com/watch?v=oHg5SJYRHA0` do `youtube-dl --no-warnings --get-title --get-url --format bestaudio/best --id -- oHg5SJYRHA0`

If this gives you an error, it's a youtube/youtube-dl error; if not please post the log here.
