### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by SorryDudeGotcha** [Splamy/TS3AudioBot#449]
.

**Comment by Bluscream** [comment]
Please use triple backticks (```) for logs. With word wrapping its hard to read it.

**Comment by Bluscream** [comment]
Ausserdem solltest du nicht die zip runterladen sondern `git clone` benutzen

**Comment by Splamy** [comment]
There is a close button to close issues, instead of clearing the post. That way other people who encounter the same problem cant find this.
