### ISSUE TITLE
multiple bots

### ISSUE THREAD

**Issue by Kroseida** [Splamy/TS3AudioBot#451]
How is it possible to create and manage multiple bots?

I already created a new bot with:
	!bot connect nw <address>

I saved him with
        !bot save <name>

But I can't let him reconnect after disconnect...

**Comment by Splamy** [comment]
You have to give him a name with the save `!bot save <name>`
So you can connect him the next time with `!bot connect template <name>`
Btw the bot has a webinterface which covers basic bot managing like this.
