### ISSUE TITLE
Webinterface and rights

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#454]
Hi @Splamy  I'm testing the bot with the new webinterface and it works perfect, but I have noticed the webinterface is missing rights:

https://i.imgur.com/33fWMDH.png

how fix this? add cmd.system.info in rights.toml? (# Conditionals and basic scripting) 

I copied the api token and this dont help for fix that rights, Im so confused 

btw im using "673e0afb19424101304e515ec2d5d15ccf961a3f"

**Comment by Splamy** [comment]
The short answer:
Put `cmd.system.info` into your global `+` rule in your rights config.

The bit longe answer:
The permission system has a non-trivial learning problem. I will try to make everything easier when the webinterface gets a proper menu to edit rights.
See my statement here in this comment: https://github.com/Splamy/TS3AudioBot/issues/433#issuecomment-442767221

**Comment by Splamy** [comment]
Hm I haven't thought about logging out yet :P 
if you want to log out right now, just clear the api token field.

The login information is stored in the localStorage and not as a cookie, so clearing them won't log you out.

**Comment by robotrono** [comment]
@Splamy oh I see, btw the command !add works fine, but maybe this command need a timer setting because an user can spam !add many times and Teamspeak can stop flood for a channel or something (Im testing a bot for public users in voice mode)

**Comment by Splamy** [comment]
I dont't get the problem with !add. Why would it need a timer?

**Comment by robotrono** [comment]
@Splamy user can spam !add many times

**Comment by Splamy** [comment]
Closing in favor of the tracking issue #651
Btw, some kind of 'flooding' system is planned, but not on the roadmap, so this might take some time yet.
