### ISSUE TITLE
Bot wont start (Already started successful but after reboot it wont again)

### ISSUE THREAD

**Issue by Christian1998** [Splamy/TS3AudioBot#455]
**Describe the problem**
Bot wont start (Already started successful but after reboot it wont again)

**To Reproduce**
No need to reproduce xD

**System Information**
- **Platform**:  Ubuntu 18.04.1 LTS (Bionic Beaver) (64bit)
  
- **Mono version**: 
```
***@shootoo:/home/audio# mono -V
Mono JIT compiler version 5.16.0.220 (tarball Mon Nov 26 17:17:59 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
```
***@shootoo:/home/audio# mono TS3AudioBot.exe -V

Version: 0.9.1
Branch: master
CommitHash: 673e0afb19424101304e515ec2d5d15ccf961a3f
```
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
```
***@shootoo:/home/audio# mono TS3AudioBot.exe
19:36:25.0093| INFO [============ TS3AudioBot started =============]
19:36:25.0414| INFO [=== Date/Time: Thursday, December 6, 2018 7:36:25 PM
19:36:25.0461| INFO [=== Version: 0.9.1/master/673e0afb
19:36:25.0461| INFO [=== Platform: Ubuntu 18.04.1 LTS (Bionic Beaver) (64bit)
19:36:25.0461| INFO [=== Runtime: Mono (5.16.0.220 (tarball Mon Nov 26 17:17:59 UTC 2018))
19:36:25.0461| INFO [=== Opus: libopus 1.1.2 (x64)
19:36:25.0475| INFO [==============================================]
19:37:10.5163| INFO Got interrupt signal, trying to soft-exit.
19:37:10.5163| INFO TS3AudioBot shutting down.
```
Already tried to download a fresh version but nothing happens. Same error as configured bot...

Thanks

**Comment by Flakebi** [comment]
You have to add `run = true` at the top of the `bot_config.toml` for the bots you want to start automatically.
The config option got moved from the main config to the bot configs.

**Comment by Christian1998** [comment]
@Flakebi Thanks, seems that if fixed it. Thank you so much :)
