### ISSUE TITLE
ChannelCommander

### ISSUE THREAD

**Issue by TheRealOneEscape** [Splamy/TS3AudioBot#459]
Hello, 
I hope someone can help me.

I wanted to ask if there is a possibility that I can give Channel Commander for every bot I have in the "Bots" folder.
So really for each bot individually.

And then the question how can I have the bot immediately Disconnect.

Currently I start this by screen on Linux and stop it with it
So with screen -S -X ... kill

But he just timed out. He should stop disconnecting immediately.

best regards

**Comment by Christian1998** [comment]
There is a workaround. Usw onConnectfunction to assign the cc

**Comment by TheRealOneEscape** [comment]
How does it Work? 

And How for each Bot?

Example:

Bot 1 - Channel Commander
Bot 2 - No Channel Commander

**Comment by Flakebi** [comment]
1. Extending the answer of Christian1998, as also described in #439, you can add the following to the configuration of the bots which should be commander:
**Bots/bot_default.toml**
```
[events]
onconnect = "!bot commander of"
```

2. You can gracefully stop the bot either by writing `!system quit` to the bot or by pressing `Ctr+C` in your screen console.

**Comment by CuzImCloud** [comment]
Hey kann man auch 2 Befehle beim onconnect Event machen?

Möchte gerne 1x !play und 1x !bot commander. Machen. 

Wie geht das?

**Comment by Splamy** [comment]
`!xecute (!bot commande on) (!play stuff)`
