### ISSUE TITLE
"requested: /api/bot/list" - Bot wird nicht gestartet über das Webinterface

### ISSUE THREAD

**Issue by Verstimmtes** [Splamy/TS3AudioBot#460]
Hey, wenn ich einen Bot über das Webinterface connecten lassen will ist der Status durchgehend auf "connecting" und in der Konsole steht folgendes

`INFO [MEINE IP] Requested: /api/bot/list`,

und das unendlich lang.

wenn ich versuche einen Bot zu erstellen kommt folgendes im Webinterface `Info:
Could not create new instance. (Bot failed to connect (Connect error))`, und folgendes in der Konsole `ERROR There is either a problem with your connection configuration, or the bot has not all permissions it needs.`

Würde mich über eine schnelle Antwort freuen, und dank dir für dieses tolle Projekt.

LG Felix | Verstimmtes

**Comment by TheRealOneEscape** [comment]
@Verstimmtes 

Darf ich dich Fragen wie du Bots über ein Interface erstellst?

Wäre cool wenn du mir das zeigen kannst. Hab es bis jetzt selber auch nicht geschafft.



Gruß

**Comment by Verstimmtes** [comment]
hast du ts ?


> @Verstimmtes
> 
> Darf ich dich Fragen wie du Bots über ein Interface erstellst?
> 
> Wäre cool wenn du mir das zeigen kannst. Hab es bis jetzt selber auch nicht geschafft.
> 
> Gruß

JA hast du ts ?

**Comment by Flakebi** [comment]
Hi, could you please post your bot config (without the identity key)?

**Comment by Splamy** [comment]
Bitte issues in englisch halten. Für deutsch haben wir einen eigenen gitter thread: https://gitter.im/TS3AudioBot/Talk-GER

Zum Problem: Naja es wie die fehlermeldung sagt.
Was steht in deinem connect.address feld in der bot config?

**Comment by Verstimmtes** [comment]
nur die auf die ich connecten will

**Comment by Verstimmtes** [comment]
übrigens der default bot connected nicht.- in der konsole steht nur connecting und dann delay

**Comment by Verstimmtes** [comment]
ok sorry man !

**Comment by Bluscream** [comment]
Wie bereits mehrfach erwähnt bekommst du auf https://gitter.im/TS3AudioBot/Talk-GER Deutschsprachige Hilfe.

**Comment by Verstimmtes** [comment]
//closed because removing the problem
