### ISSUE TITLE
How works the !come command that the bot joins my channel?

### ISSUE THREAD

**Issue by akizzed** [Splamy/TS3AudioBot#461]
Well, the question is in the title c:

**Comment by akizzed** [comment]
http://prntscr.com/ls2re8

**Comment by akizzed** [comment]
18:53:05.6444| INFO User Luke requested: !bot come
18:53:05.6444| WARN Bot is not correctly set up. Some commands might not work or are slower (clientlist:Missing permissions., clientinfo:No client found. (Missing permissions.)).

Do you mean this? If not please tell me where I can find the right ones

**Comment by akizzed** [comment]
okay du kannst deutsch, dann ist das auf jeden Fall einfacher xD @Flakebi

**Comment by Flakebi** [comment]
Thanks, this is the log I wanted.
In general, try to leave the conversation in english for the issue tracker as it is helpful for other people who stumble upon the same problems (and may not be able to understand german).

As said in the log, you did not set up the bot correctly, so he is missing some permissions.
The easiest way is to create a privilege key and send the bot a private message `!bot setup <privilege key>`. The bot will assign himself the rights he needs.

**Comment by akizzed** [comment]
and where can i find this privilege key?

**Comment by akizzed** [comment]
okay fixed it thank you. The bot needed `b_virtualserver_channel_search`
