### ISSUE TITLE
Can't rename bot (REST API)

### ISSUE THREAD

**Issue by Kroseida** [Splamy/TS3AudioBot#462]
Hello,

currently I am trying to rename an bot with the REST API.
I call this endpoints:
"http://HOST/api/settings/set/connect.name/bla"
"http://HOST/api/bot/name/bla"

but I only get an error 422.

The headers are correct, with the same headers I already called
"http://HOST/api/bot/connect/template/bla"

Branch: master

**Comment by Flakebi** [comment]
The answer to your `/bot/name/bla` request should contain the following:
```
{"ErrorCode":17,
"ErrorName":"MissingContext",
"ErrorMessage":"Command 'CommandBotName' missing execution context 'Ts3Client'",
"HelpMessage":"You are trying to call a command which is specific to a bot. Use '!bot use' to switch to a bot instance",
"HelpLink":"https://github.com/Splamy/TS3AudioBot/wiki/FAQ#api-missing-context"}
```

The link https://github.com/Splamy/TS3AudioBot/wiki/FAQ#api-missing-context should contain the answer to your problem.
