### ISSUE TITLE
Logfile for each Bot

### ISSUE THREAD

**Issue by CuzImCloud** [Splamy/TS3AudioBot#467]
Hey,

Is it possible to create a separate log file for each bot?

So that creates a log file when you start the respective bot. That one really has 1 folder log files with the whole logs of each bot its own?

I would be happy if I got an answer.

greeting
CuzImCloud

**Comment by Splamy** [comment]
This is not possible with the current setup. And I don't think this could be easily implemented right now.
NLog is a static Logger, so tracing calles from which bot they initiated can't be done.
