### ISSUE TITLE
built

### ISSUE THREAD

**Issue by Jakubekkk** [Splamy/TS3AudioBot#472]
hello, how to run a bot that was built manually?

**Comment by Bluscream** [comment]
Just start it?

**Comment by djagiello** [comment]
Polish:
Bot domyślnie kompiluje się do pliku: `TS3AudioBot/bin/Release/net46/TS3AudioBot.exe`
Uruchomić możesz go za pomocą komendy: `mono TS3AudioBot.exe`
Osobiście używam troszkę bardziej złożonej komendy:
`cd /home/audio/ && msbuild /p:Configuration=Release /p:TargetFramework=net46 TS3AudioBot.sln && cd TS3AudioBot/bin/Release/net46/ && mono TS3AudioBot.exe`, gdzie `/home/audio/` jest moim katalogiem głównym projektu. Komenda najpierw kompiluje kod, a następnie go uruchamia (przydatne dla osób wprowadzające jakieś zmiany)

english:
Default catalog to compile is: `TS3AudioBot/bin/Release/net46/`
You can run it going to this catalog and using comand: `mono TS3AudioBot.exe`
Personally, I'm using a bit more complex command:
`cd / home / audio / && msbuild / p: Configuration = Release / p: TargetFramework = net46 TS3AudioBot.sln && cd TS3AudioBot / bin / Release / net46 / && mono TS3AudioBot.exe`, where `/home/audio/` is root directory for project. Command first compile project and then runs it (useful for people making some changes)
