### ISSUE TITLE
Add formating for description

### ISSUE THREAD

**Issue by djagiello** [Splamy/TS3AudioBot#474]
![image](https://user-images.githubusercontent.com/38032481/50429598-c9dd2580-08bf-11e9-84ee-da72b636d07a.png)
![image](https://user-images.githubusercontent.com/38032481/50429605-ce094300-08bf-11e9-92ab-f915058e1609.png)

This is an idea from a friend

**Comment by Splamy** [comment]
This kinda defeats the purpose of the localisation system.
As you see in line 287. That string is already a format string which writes the "now plaing ..." text localized.
If you want to change it, you can go into the [strings.resx](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Localization/strings.resx#L663-L665) file and change it with either vs or a texteditor and recompile it.

**Comment by Splamy** [comment]
Yeah, I've thought about that too. I don't like it quite either, but resx localization files are more or less the standard and good practice in C# and dotnet.
