### ISSUE TITLE
Commands entfernen

### ISSUE THREAD

**Issue by ptsleon** [Splamy/TS3AudioBot#476]
Hey,
Ich wollte mal nachfragen wo genau in welchen datein ich muss um die Commands zu ändern / entfernen und wo ich die !help message ändern kann.
Danke im voraus :)

**Comment by Flakebi** [comment]
Hi,
you can find all commands in the [MainCommands.cs](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainCommands.cs) file. Just search for `help` in there.

Please try to leave all discussions and questions in english, not everyone here is talking german.

**Comment by ptsleon** [comment]
i mean this: http://prntscr.com/m0cqzw

**Comment by Flakebi** [comment]
Yes, this is generated in `CommandHelp` in the [MainCommands.cs](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainCommands.cs) file. :)

**Comment by ptsleon** [comment]
xD i mean the message from !help

**Comment by Flakebi** [comment]
Oh, if you mean the text, you can change it in the localisation file: [strings.resx](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Localization/strings.resx#L456-L460)
(see also #474)

**Comment by ptsleon** [comment]
thx
