### ISSUE TITLE
insufficient client permission on clientlist

### ISSUE THREAD

**Issue by ghost** [Splamy/TS3AudioBot#477]
Hello.

https://github.com/Splamy/TS3AudioBot/blob/673e0afb19424101304e515ec2d5d15ccf961a3f/TS3AudioBot/Ts3Client.cs#L307-L322

This code area gives me insufficient client permission, but why?

**Comment by Bluscream** [comment]
Does your bot have `b_virtualserver_client_list`?

**Comment by stveOG** [comment]
This is not my server, I want to connect the bot on NeruxVace.net

**Comment by stveOG** [comment]
> bookkeeping was implemented
What does that mean?

**Comment by Bluscream** [comment]
For some reason i could not find any proper explanation/writeup for this, so i'm trying to explain myself as best as i can (@Splamy can do it better probably)

Bookkeeping describes a way of caching. That means that the client doesn't request the whole clientlist from the server (which needs the `b_virtualserver_client_list` permission) but remembers every client on join instead, so the client doesn't have to ask for all clients everytime he needs it but instead knows "I saw client x join in channel y so i know who he is and that he is there" that's what's called bookkeeping (it's more complex ofc)
