### ISSUE TITLE
PlaybackVoiceData in TS3AB

### ISSUE THREAD

**Issue by dzinks2009** [Splamy/TS3AudioBot#479]
Hi, I know this function exists in TeamSpeak3 plugin system, but does it exist in TS3AB?
```
void ts3plugin_onEditPlaybackVoiceDataEvent(uint64 serverConnectionHandlerID, anyID clientID, short* samples, int sampleCount, int channels) {
```
Thank you.

**Comment by Splamy** [comment]
The ts3ab has its own entire audio pipelineing system
see here: https://github.com/Splamy/TS3AudioBot/tree/master/TS3Client/Audio
so you can basically do and modify anything at any point in the pipeline just as you want.

The only point is that all pipe objects currently in the Ts3Client class are set to private
https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Ts3Client.cs#L66-L72
as I didn't completely decided yet how and which of them i want to expose.

This means when you want to modify them with a plugin you'd have to get those with reflection.
Or change the source and compile it yourself.
