### ISSUE TITLE
Channel List Command

### ISSUE THREAD

**Issue by Kroseida** [Splamy/TS3AudioBot#480]
Currently I need an command the get an list of all channels including the channel id.
Can you implement this feature?

**Comment by Flakebi** [comment]
I am not sure if this is possible at the moment in an easy way. It definitely *will* be possible, when book keeping of channels, clients, etc. is implemented (see [this comment](https://github.com/Splamy/TS3AudioBot/issues/477#issuecomment-451773103) for a short explanation).

**Comment by Kroseida** [comment]
Can you implement this into your project?

Or is this a planed feature in future?

**Comment by Splamy** [comment]
Sure i'll add it.
But you can already use it, as is, right now. If you don't need any of the options you can even just call:
`var channels = client.Send<ChannelData>("channellist");` and you're done.

**Comment by Kroseida** [comment]
Okay. Thanks.

I will try to implement it in my clone.

**Comment by Bluscream** [comment]
It was just implemented with the latest commit

**Comment by Splamy** [comment]
No, that's on the wip branch wich noone should every check out, except me, unless you want a bad time with a unstable or broken bot

**Comment by Bluscream** [comment]
> 
> 
> No, that's on the wip branch wich noone should every check out, except me, unless you want a bad time with a unstable or broken bot

Well, usually it only takes a day or two from the wip to the develop branch.
