### ISSUE TITLE
Splamy.de direct download

### ISSUE THREAD

**Issue by CookieCr2nk** [Splamy/TS3AudioBot#481]
Hello Splamy

Is it possible to make your download section on your Splamy.de website direct. So that i can download the zip file with wget from the server and its pretty better, so i can make a script.

Now each version, i must download on my pc and upload to the Server. Or have somebody other ideas for example with "curl".

**Comment by dzinks2009** [comment]
```
https://splamy.de/api/nightly/ts3ab/develop/download

https://splamy.de/api/nightly/ts3ab/master/download
```
Pretty sure these links don't change (?)

**Comment by Bluscream** [comment]
> ```
> https://splamy.de/api/nightly/ts3ab/develop/download
> 
> https://splamy.de/api/nightly/ts3ab/master/download
> ```

```
wget https://splamy.de/api/nightly/ts3ab/develop/download -o ts3ab.zip
```
```

**Comment by Flakebi** [comment]
I guess you meant
```
wget https://splamy.de/api/nightly/ts3ab/develop/download -O ts3ab.zip
```
(note the big `O`).

Yes, this works.

**Comment by Bluscream** [comment]
Sure

**Comment by CookieCr2nk** [comment]
Thx for your help. I Close the Issue Now.
