### ISSUE TITLE
Bot disconnect

### ISSUE THREAD

**Issue by MisterMisiek** [Splamy/TS3AudioBot#486]
How do i save the bots ? Because when i close my putty bots getting time out

**Comment by akizzed** [comment]
maybe open the bots in a screen?

**Comment by MisterMisiek** [comment]
How ? Sorry but im new at this :P

**Comment by MisterMisiek** [comment]
Im opening this like this 
cd /home/TS3AudioBot
mono TS3AudioBot.exe

**Comment by akizzed** [comment]
first install screen: apt-get install screen
open a new screen using screen -S ts3audiobot, then:
cd /home/TS3AudioBot
mono TS3AudioBot.exe

you can exit the screen using ctrl+a, d
and enter back into the screen with screen -x ts3audiobot

**Comment by MisterMisiek** [comment]
Ok thanks, one more how do i take off acces for ID and why my bots reconecting all the time ?

**Comment by MisterMisiek** [comment]
21:50:46.3028| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:50:46.9973| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:50:48.5171| INFO Bot "dope7"(6) connected.
21:50:49.5802| INFO Bot "dope8"(7) connected.
21:53:31.5301| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:53:33.7255| INFO Bot "default"(0) connected.
21:55:51.6795| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:55:53.8684| INFO Bot "dope3"(2) connected.
21:58:37.6316| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:58:37.9760| INFO Trying to reconnect. Delaying reconnect for 1 seconds
21:58:39.8448| INFO Bot "default"(0) connected.
21:58:40.8806| INFO Bot "dope6"(5) connected.

**Comment by MisterMisiek** [comment]
21:58:40.8806| INFO Bot "dope6"(5) connected.
22:01:56.2366| INFO Got interrupt signal, trying to soft-exit.
22:01:56.2366| INFO TS3AudioBot shutting down.
22:01:56.2366| INFO Bot (0) disconnecting.
22:01:56.2446| INFO Bot (1) disconnecting.
22:01:56.2446| INFO Bot (2) disconnecting.
22:01:56.2524| INFO Bot (3) disconnecting.
22:01:56.2591| INFO Bot (4) disconnecting.
22:01:56.2621| INFO Bot (5) disconnecting.
22:01:56.2621| INFO Bot (6) disconnecting.
22:01:56.2672| INFO Bot (7) disconnecting.

**Comment by MisterMisiek** [comment]
And this when i start the bot
22:10:10.0278|ERROR The webserver could not be started

**Comment by Splamy** [comment]
> how do i take off acces for ID

I have no Idea, what that means

> why my bots reconecting all the time

may be various reasons, can't say anything withous logs

> 22:10:10.0278|ERROR The webserver could not be started

change the port or disable it you don't need it. Otherwise you can ignore it.
