### ISSUE TITLE
API without use bot

### ISSUE THREAD

**Issue by vertipl** [Splamy/TS3AudioBot#489]
Hi i'm using ts3ab-php so i've question.
It's possible to connect or setup new instance without using connected bot ?

**Comment by Bluscream** [comment]
ts3ab-php? https://www.google.com/search?client=firefox-b-d&q=ts3ab-php

**Comment by vertipl** [comment]
Solved. If someone would have a similar problem Line 96 and 102 change "request" to "rawRequest.
