### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by CruptexDE** [Splamy/TS3AudioBot#491]
Hallo Splamy,

erstmal vielen Dank für dieses tolle kostenlose Projekt. Ich habe Probleme beim Ändern der Version. Wie kann ich die TeamSpeak Version ändern?

MfG

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#set-the-client-version

**Comment by CruptexDE** [comment]
Okay und noch eine Frage... mein Stream schmiert nach nh paar Stunden einfach ab ^^

**Comment by CruptexDE** [comment]
Bzw. der spielt keine Musik mehr (Stream-URL)

**Comment by Splamy** [comment]
Bitte issues in englisch halten, das hilft damit alle issues wiederfinden können.
Wir haben ggf einen deutschen gitter channel.

Zur frage, ja streams können abbrechen, der beste workaround ist einfach den repeat modus auf 'one' zu stellen: `!repeat one`
