### ISSUE TITLE
Bot disconnecting (Unknown Teamspeak Error)

### ISSUE THREAD

**Issue by akizzed** [Splamy/TS3AudioBot#492]
Hi,
the Bots are disconnecting randomly. Sometimes they connect again to the server, sometimes they stay offline.

There is nothing in the logs, just this: http://prntscr.com/mfymj7

Version is  0.10.0-unstable.73 but this also happened with the stable version

**Comment by akizzed** [comment]
serverlog: 
```
04.02.2019 02:02:20    PktHandler    Info    Dropping client 3 because of ping timeout 19 0 0
04.02.2019 02:02:20    VirtualServerBase    Info    client disconnected 'akzdFM'(id:315) reason 'reasonmsg=connection lost'
```

**Comment by Splamy** [comment]
Might be a firewall or connection issue.
But I can't say a lot from this logs; if possible could you set the log output to [debug](https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs)?

**Comment by akizzed** [comment]
ok, debugging it now. im gonna send the logs soon as the bot disonnects

**Comment by akizzed** [comment]
Now some Bots timed out. Am I right that they disconnect because they can't set the commander mode?
```
2019-02-06 17:25:23.4728|DEBUG|Bot.CallScript Command Error (Cannot set commander mode. (Unknown Teamspeak Error. (Connection closed)))
TS3AudioBot.CommandSystem.CommandException: Cannot set commander mode. (Unknown Teamspeak Error. (Connection closed))
   bei TS3AudioBot.Helper.Util.UnwrapThrow(E`1 r)
   bei TS3AudioBot.MainCommands.CommandBotCommanderOn(Ts3Client ts3Client)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   bei TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   bei TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   bei TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   bei TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   bei TS3AudioBot.Bot.CallScript(ExecutionInformation info, String command, Boolean answer, Boolean skipRights)
```

**Comment by akizzed** [comment]
Here is the complete file of another bot timeout. 
(13:27:47.1054)

[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/2840781/ts3audiobot.log)

**Comment by akizzed** [comment]
[vllt. hier.txt](https://github.com/Splamy/TS3AudioBot/files/2840836/vllt.hier.txt)
This was on a localhost server. Maybe CPU problem?

**Comment by Splamy** [comment]
I've looked through but I couldn't find anything suspicious.
It might be that the cpu is overloaded, some scheduling ploblem, or that the process gets suspended for longer than 20sec or so.
You also might check if it insn't a weird firewall issue, even on localhost.
Does this also happen, when you have less bots running?

**Comment by akizzed** [comment]
found the problem and you're right: CPU overload :3 oops
