### ISSUE TITLE
Unterschied

### ISSUE THREAD

**Issue by CruptexDE** [Splamy/TS3AudioBot#494]
Ich verstehe noch nicht ganz, wie das mit dem connecten klappt... was ist der unterschied zwischen "!bot connect template xyz" und "!bot connect to xyz" Wenn ich nur !bot connect to xyz mache, connected der bot aber wird gelöscht... ich möchte diesen aber gerne behalten.

MfG

**Comment by CruptexDE** [comment]
Wird gelöscht wenn ich ihn stoppe*

**Comment by CruptexDE** [comment]
Und wie kann ich mehreren UIDS Rechte auf den Bot geben?

**Comment by ShadowFM** [comment]
Erstmal Hi!
!bot connect to <ts-addr>: Verbindet einen **neuen** Bot mit der angegebenen Adresse.
!bot connect template <name>: Verbindet einen neuen Bot mit den Einstellungen aus dem Vorlagennamen.

Was hierbei zu beachten ist, wenn der Bot sich mit dem Server verbindet wird dieser noch nicht gespeichert, das müsstest du dann wie folgt tun:
!bot save <name>: Speichert die Konfiguration für den neu verbundenen Bot.

Ich hoffe ich konnte dir etwas helfen.

**Comment by CruptexDE** [comment]
Ja, konntest du. Allerdings habe ich noch eine Frage. Wo finde ich wenn ich die Projektmappe gespeichert habe den Ordner wo die TS3AudioBot Exe uns so drin ist wo ich das ganze auf Linux ausführen kann? @ShadowFM

**Comment by Splamy** [comment]
`TS3AudioBot\bin\Debug\net46\TS3AudioBot.exe` bzw `TS3AudioBot\bin\Release\net46\TS3AudioBot.exe`
