### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FlareNetwork** [Splamy/TS3AudioBot#495]
Hello,

is it possible to create a bot config file with custom permissions, without using the main rights.toml file.

Best Regards

**Comment by Splamy** [comment]
Not quite,
you can setup permissions per bot in the main rights toml, see here: https://github.com/Splamy/TS3AudioBot/issues/341#issuecomment-412493473

but i'm working on some file hierachy improvements on the 'wip' branch which should enable convenient per bot files.

**Comment by FlareNetwork** [comment]
Ok.
