### ISSUE TITLE
Run more than one command on start

### ISSUE THREAD

**Issue by akizzed** [Splamy/TS3AudioBot#496]
Hi,

Is it possible to run more than one command with the onconnect event?

Best Regards.

**Comment by Splamy** [comment]
`!x (!a) (!b) (!play "yo.pm3")` ([wiki](https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem#command-chaining))

**Comment by akizzed** [comment]
But this isn't working....
`onconnect = "!play http://stream.laut.fm/akzdfm (!repeat one) (!bot commander on)"`

**Comment by Splamy** [comment]
no `!x' is a special command, short for `!xecute`, so
`onconnect = "!x (!play http://stream.laut.fm/akzdfm) (!repeat one) (!bot commander on)"`

**Comment by akizzed** [comment]
oh. thanks!
