### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by CruptexDE** [Splamy/TS3AudioBot#499]
Was muss ich tun, dass die Commands weg gehen und nur noch der Text oben steht?
![screenshot 4](https://user-images.githubusercontent.com/47275890/52392535-840ca300-2aa2-11e9-8af0-4f556aead11b.png)

**Comment by CruptexDE** [comment]
I found it -.-

**Comment by Bluscream** [comment]
Oh gott

**Comment by ptsleon** [comment]
Bitte sag auch in welcher Datei man das macht
