### ISSUE TITLE
Nightly setup doesn't work

### ISSUE THREAD

**Issue by DSeeLP** [Splamy/TS3AudioBot#506]
I become a error when I executing simplebot. I've given the file the rights a+x.
Error:

root@srv25043:/opt/TSBot# ./simple-bot        
./simple-bot: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
root@srv25043:/opt/TSBot# 

How can I fix this?

**Comment by Splamy** [comment]
Are you trying to setup the audiobot or the simple-bot? Because that's another prject and you should open the issue there: https://github.com/ReSpeak/SimpleBot

**Comment by DSeeLP** [comment]
Splamy can you help me to setup the TS3AudioBot because I'am stupid.
