### ISSUE TITLE
Install msbuild

### ISSUE THREAD

**Issue by DSeeLP** [Splamy/TS3AudioBot#507]
Hello Splamy

How can I get msbuild the command "apt install nuget msbuild" doesn't works!
I use Ubuntu 16.04
The output of the command is:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package msbuild

PS: Sry for my bad English

LG
DSeeLP

**Comment by Flakebi** [comment]
Hi,
did you install the mono repo like [described here](https://www.mono-project.com/download/stable/#download-lin)?

**Comment by DSeeLP** [comment]
Yes

**Comment by martinaguilar** [comment]
Same problem here with Ubuntu 19.04. 
One of the problem I see is that there are not repos for disco-dingo. Anyways... I could install mono but the error is:
Unable to locate package msbuild

**Comment by Flakebi** [comment]
Did you install the `mono-devel` package? On Ubuntu 18.04 this adds the `msbuild` package and command.
Anyway, you should try the .NET Core version which is also available for 19.04 here: https://dotnet.microsoft.com/download/linux-package-manager/sdk-current
