### ISSUE TITLE
get json result

### ISSUE THREAD

**Issue by MemeEntwickler** [Splamy/TS3AudioBot#512]
**Problem**
I want to get the id from a running bot, by the filename.
I tried it via template, but i did not found a way to do this, now i tried it with a API request like 
localhost:8180/api/bot/list  in php to get a json result.

decoded php line of the list when the bot is online.

[{"Id":0,"Name":"templatename","Server":"censored.com","Status":2}]

so is it possible to list the bot ID (if he is online) in the line of the templatename?

this is a part of my current php code to list all bots inserted in the Database, and the method to list them.

---------------------

     $data = file_get_contents($request);
                                               
     $end = json_decode($data);
                                                
         while($row = $query3->fetch_array()){
                                                    
                                  $partner = $row['partner'];
                                                    
                                   echo "<tr>";
                                   echo "<td>".$row['id']."</td>";
                                   echo "<td>".$row['name']."</td>";
                                   echo "<td>".$partner."</td>";
                                   echo "<td>".$row['adress']."</td>";
                                   echo "<td>".$row['created']."</td>";
                                   echo "<td>" here i want to list the id, ordered by $partner (
                                    in my case is this the templatename) "</td>";
                                                   
                                    echo "</tr>";
                                                    
                                 }

----------------

I hope i can get helpful answers :)

**Comment by MemeEntwickler** [comment]
or is it possible to give a bot a Permanently ID?

**Comment by Splamy** [comment]
I don't quite get the question. If you want the id by template name, it's right there in the answer: `
"Id":0,"Name":"templatename"`, that's the id: `"Id":0`.

> or is it possible to give a bot a Permanently ID?

no, but you don't need that, the template name is already unique.

**Comment by MemeEntwickler** [comment]
I know, but how to i get this in php

**Comment by MemeEntwickler** [comment]
also you said 
"no, but you don't need that, the template name is already unique.", that is right, but its not possible to work with the templatename, like /api/bot/use/templatename/(/etc..

**Comment by MemeEntwickler** [comment]
Is there someone who is able to help me?

**Comment by Splamy** [comment]
I'm sorry, but I can't and wont write your php code for you. The issue tracker is for ts3ab concerning problems, enhancement requests and questions if something is unclear so it can be discussed.
Accessing the bots by name is already planned here #306 but not yet implemented. However it shouldnt be that hard to just request the whole bot list, parse the result and find the bot with the template name.
