### ISSUE TITLE
Repeat/Loop Funktion

### ISSUE THREAD

**Issue by NurLutix** [Splamy/TS3AudioBot#515]
Guten Tag,
Ich würde gerne dauerhaft eine StreamURL abspielen lassen.
Da aber ungefähr jede 6 Stunden der Stream durch den Anbieter unterbrochen wird, wollte ich nun fragen, wie ich dies behebe.
Sodass, falls der Stream abbricht, dieser automatisch wieder startet.

Muss ich dazu wirklich eine Wiedergabeliste mit !list machen, oder gibt es eine andere Möglichkeit?

Liebe Grüße.

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/issues/511#issuecomment-468309467
Yes you have to
