### ISSUE TITLE
YT

### ISSUE THREAD

**Issue by CruptexDE** [Splamy/TS3AudioBot#516]
Hallo,

wenn ich einen YT Link abspiele, spielt er das Lied zwar ab aber manchmal buggt das Lied. Manchmal bei z.B. der Hook wiederholt sich ein Satz aus der Hook. Ein bisschen scheiße erklärt, aber ich hoffe ihr konntet mir folgen.

MfG

**Comment by ShadowFM** [comment]
Hi,
maybe it's an issue from youtube-dl, try to update it first.

Best regards,
Shadow

**Comment by CruptexDE** [comment]
Habs neu installiert, hat nichts gebracht. Trotzdem Danke

**Comment by CruptexDE** [comment]
@Bluscream Wieso ist Maurice Thiel ein Arschloch? ^^

**Comment by CruptexDE** [comment]
#499

**Comment by ShadowFM** [comment]
"Dieser Musikbot ist von Maurice Thiel."
I think this is the reason because the bot isn't from Maurice, the bot is from Splamy :D

**Comment by Splamy** [comment]
Can you check that the server isn't overloaded and that the network connection is stable?

**Comment by Splamy** [comment]
From gitter, as I remembered this bug again:
This should be the old ffmpeg bug. ffmpeg for some reason sometimes loses connection streaming youtube videos and ffmpeg doesn't fix it. I added a feature that it will automatically reconnect when it detects such a drop. That's when you get the pause or stutter. You can check by setting the log level to `Debug` for both `TS3AudioBot.*` logger. You should see `Connection to song lost, retrying at ....` If you do not see this line, the problem might be something else
