### ISSUE TITLE
Bypass channel codec

### ISSUE THREAD

**Issue by Edith445544986** [Splamy/TS3AudioBot#517]
This has nothing to do with the Bot but I would like to know, is it possible to do the same thing as the bot at Opus level but on a normal client?

**Comment by Flakebi** [comment]
In theory yes, this is possible. However, the official TeamSpeak client does not provide any method to do this. The possibilities I see are:
- Write your own client (may take some time ;))
- Use a plugin like the [TS3Hook](https://github.com/ReSpeak/TS3Hook) which can change the content which is sent over connections and use it to spoof the codec of a channel. (Change the codec information in incoming channel information packets)

**Comment by Edith445544986** [comment]
Do you have a tutorial or a command (TS3Hook) to do that?

**Comment by Splamy** [comment]
You'd have to dig into the source code and write it yourself or commission someone to write it for you.

**Comment by Edith445544986** [comment]
Okay, thanks for your answers and help.
