### ISSUE TITLE
API Bot verlässt nach einer Zeit den TeamSpeak

### ISSUE THREAD

**Issue by SMNDM** [Splamy/TS3AudioBot#518]
Guten Abend,
ich habe leider ein Problem mit der API.

Meine System Bots (default) verlassen ohne Error den TeamSpeak. Dadurch geht dann logischerweise auch die API nicht mehr. 

Meine Frage, ist dieser "Fehler" bekannt und wenn ja wie ist die Lösung? 

<17:31:37> "System7" hat die Verbindung getrennt

Mit freundlichen Grüßen
Simon

**Comment by Splamy** [comment]
Please try to keep all discussions and questions in english, not everyone here is talking german.

We have a template which asks for all basic information, so please either use the template or provide all necessary information.
- Which version are you using? (the commit hash is important)
- mono or dotnet core?
- Any source modifications you made /  any plugins?
- Anything in the log? `<17:31:37> "System7" hat die Verbindung getrennt` says nothing and has no context.

When you are running mono, can you compile the bot in Debug mode (`msbuild /p:Configuration=Debug/p:TargetFramework=net46 TS3AudioBot.sln`) and run with `mono --debug TS3AudioBot.exe`.
This will print line numbers in exception stracktraces. This might help idetifying the problem faster in some cases.

**Comment by SMNDM** [comment]
root@smn01:/home/mb# msbuild /p:Configuration=Debug/p:TargetFramework=net46 TS3AudioBot.sln
Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: TS3AudioBot.sln

**Comment by Flakebi** [comment]
There was a space missing in the command, it should be `msbuild /p:Configuration=Debug /p:TargetFramework=net46 TS3AudioBot.sln`

**Comment by SMNDM** [comment]
root@smn02:/home/mb# msbuild /p:Configuration=Debug /p:TargetFramework=net46 TS3                                                                                                                                                             AudioBot.sln
Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 03/11/2019 16:38:38.
Project "/home/mb/TS3AudioBot.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
/home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/TS                                                                                                                                                             3AudioBot/TS3AudioBot.csproj" was not found. [/home/mb/TS3AudioBot.sln]
/home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/TS                                                                                                                                                             3ABotUnitTests/TS3ABotUnitTests.csproj" was not found. [/home/mb/TS3AudioBot.sln                                                                                                                                                             ]
/home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/TS                                                                                                                                                             3Client/TS3Client.csproj" was not found. [/home/mb/TS3AudioBot.sln]
/home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/Ts                                                                                                                                                             3ClientTests/Ts3ClientTests.csproj" was not found. [/home/mb/TS3AudioBot.sln]
Done Building Project "/home/mb/TS3AudioBot.sln" (default targets) -- FAILED.

Build FAILED.

"/home/mb/TS3AudioBot.sln" (default target) (1) ->
(Build target) ->
  /home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/                                                                                                                                                             TS3AudioBot/TS3AudioBot.csproj" was not found. [/home/mb/TS3AudioBot.sln]
  /home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/                                                                                                                                                             TS3ABotUnitTests/TS3ABotUnitTests.csproj" was not found. [/home/mb/TS3AudioBot.s                                                                                                                                                             ln]
  /home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/                                                                                                                                                             TS3Client/TS3Client.csproj" was not found. [/home/mb/TS3AudioBot.sln]
  /home/mb/TS3AudioBot.sln.metaproj : error MSB3202: The project file "/home/mb/                                                                                                                                                             Ts3ClientTests/Ts3ClientTests.csproj" was not found. [/home/mb/TS3AudioBot.sln]

    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.57
root@smn02:/home/mb#

**Comment by SMNDM** [comment]
https://hastebin.com/oqiloyufod.css

This message also comes every 5 min.

**Comment by SMNDM** [comment]
https://hastebin.com/yowegufoju.sql

**Comment by SMNDM** [comment]
https://hastebin.com/oxenudolod.makefile

I have now taken the latest version and also comes an error.

**Comment by Splamy** [comment]
> WARN WebListener exception

This is just a warning which you can safely ignore. If this is happening regularly caused by requests from your backend, make sure that the http connection is properly opened and closed and not interruppted.

To msbuild, can you make sure that you have downloaded the project correctly. (When you moved something, make sure that everything is in the correct place). Otherwise try redownloading the project with the git line from the readme: `git clone --recurse-submodules https://github.com/Splamy/TS3AudioBot.git`
