### ISSUE TITLE
Webinterface Installation

### ISSUE THREAD

**Issue by DiBaDu** [Splamy/TS3AudioBot#519]
Hello,
im trying to install the webinterface of the bot.
But is the Webinterface now ready to use or did i have to use the API?
Is there any documentery where i can find information about how to install the webinterface ?
I hope anybody can help me.
Best wishes and have a nice day

Off Topic:
The latest version is on the Website from Splamy, but where i can find the latest sourcecode? I want to edit the !help message (easier to understand) but where i can find this message?Does anybody can upload the german source language file? Than i can edit it in Virsual Studio. Is there an Upload from German Language Source project?

**Comment by MemeEntwickler** [comment]
Hey,

The Bot already got a Web interface you could use.
To Enable that, edit the ts3audiobot.toml in the main directory.
Now edit the point 
`webinterface.enabled = false` to `webinterface.enabled = true`
and restart the bot.
you now should reach the interface on localhost:yourport

*yourport is the port you can find in the ts3audiobot.toml or in the console when it's starting.

Hope I cloud help :)

**Comment by Splamy** [comment]
All source code is here on github

**Comment by heartles39** [comment]
Where is this file? I can't find the file I downloaded from here Please share the file link with me

https://github.com/Splamy/TS3AudioBot

**Comment by Splamy** [comment]
Where is what file? What link. And why did you link this repo down there

**Comment by heartles39** [comment]
ts3audiobot.toml No such file How do I activate the panel?

**Comment by Splamy** [comment]
The file will be generated on the first start and should be in the same folder as the ts3audiobot.exe/dll
