### ISSUE TITLE
Could not load (ScInvalidLink)

### ISSUE THREAD

**Issue by JABirchall** [Splamy/TS3AudioBot#52]
```
<01:23:27> "DrWhat": !play https://soundcloud.com/viperrecordings/mob-tactics-widowmaker
<01:23:27> "AudioBot": Error: Could not load (ScInvalidLink)
```

This url can not be parsed by the bot, for an unknown reason

Update, These URL's also cant be parsed.

* https://soundcloud.com/theupbeats/the-upbeats-beyond-reality
* https://soundcloud.com/dc-breaks-uk/bambino-friction-fire-bbc-radio-1
* https://soundcloud.com/dc-breaks-uk/liu-dc-breaks-remix

**Comment by Splamy** [comment]
Seems like this is either a [bug](https://stackoverflow.com/questions/36360202) or an [embedding restriction](https://stackoverflow.com/questions/33485387)
I will add a fallback to youtube-dl

**Comment by robotrono** [comment]
Question: The bot can get songs from a playlist of soundcloud?

**Comment by Splamy** [comment]
Not yet, I will add it in the future
