### ISSUE TITLE
Can't load plugins

### ISSUE THREAD

**Issue by Lumpiasty** [Splamy/TS3AudioBot#523]
**Describe the problem**
Hi. I was trying to write some plugins for bot. When I try to load example static plugin I get following errors:
```
WARN Plugin "plugin.cs" [0] compiler notifications:
Error L8/C38: The type or namespace name 'PlayManager' could not be found (are you missing a using directive or an assembly reference?)
Error L6/C5: The type or namespace name 'CommandAttribute' could not be found (are you missing a using directive or an assembly reference?)
Error L6/C5: The type or namespace name 'Command' could not be found (are you missing a using directive or an assembly reference?)
```

**To Reproduce**
Put any [sample](https://github.com/Splamy/TS3AudioBot/wiki/Plugins) plugin to Plugins folder and run `!plugins list`

**System Information**
- **Platform**: Arch Linux
  
- **Mono version**: 
Mono JIT compiler version 5.18.0 (makepkg/5266e6a8f10 Wed Jan 23 01:37:40 CET 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default) 
  
- **Which commit did you download**: (installed with [AUR](https://aur.archlinux.org/packages/ts3audiobot) package)
Version: 0.9.1
Branch: master
CommitHash: ad86914f85f6a9dcea462d79e29f6da00eacef7

Do you have any idea what can be wrong? Thanks in advance for your help.

**Comment by Splamy** [comment]
The plugin examples are somewhat outdated, I will update them today when I have time today

**Comment by Splamy** [comment]
I've updated and tested all examples, as well as updated a lot of the help. Please reopen if any issues still remain.
