### ISSUE TITLE
Bot Follow Me Feature

### ISSUE THREAD

**Issue by germanbeast** [Splamy/TS3AudioBot#525]
Hallo,

ich habe derzeit folgendes Problem ich weiß nicht wie ich auf anderen Teamspeaks wo ich kein Server Admin bin meinen MusikBot in den Channel bekomme. Gibt es da einen Befehl das mir der Bot hinterher joint? Oder muss ich dass mit Channel IDs machen was leider auch nicht funktioniert. Aber eins Vorweg das ganze hier ist ein richtig tolles Projekt und finde es mega cool dass mittlerweile  schon so was großes daraus geworden ist.

**Comment by Bluscream** [comment]
!bot come

**Comment by germanbeast** [comment]
Thank you verry much :)
