### ISSUE TITLE
Client already connectet Error

### ISSUE THREAD

**Issue by germanbeast** [Splamy/TS3AudioBot#526]
Hallo was sagt diese Fehlermeldung genau aus? 

WARN Seems like another client with the same identity is already connected. Waiting 30 seconds to reconnect.

Ich benutze ein Webinterface um die Bots zu erstellen und es sind defenitiv nicht die selben Identitäten. 

Ebenso bekomme ich desweiteren die Meldung:

Could not connect: parameter_invalid_size: the command failed to execute: invalid parameter size

Betrieben wird der Bot auf einer Debian 9 Maschine mit 2GB Ram 

Mfg

**Comment by Bluscream** [comment]
Das kann an ziemlich vielen dingen liegen

**Comment by NurLutix** [comment]
Hey,
Bitte versuche deine Anfrage auf Englisch zu schreiben. Nicht jeder kann hier Deutsch.

Ich erhalte diese Fehlermeldung immer, wenn bereits ein Client mit der UID/Eindeutigen ID online ist. 

Du kannst die TeamSpeak Identität neu generieren lassen, indem Du unter dem Ordner Bots die bot_default.toml bearbeitest. Dort entfernst Du einfach key und offset. Der Bot muss dabei offline sein.

Ich hoffe, ich konnte Dir weiterhelfen.

Liebe Grüße.

---

I always get this Error Message when a Client with the UID/Unique ID is already online. 

You can regenerate the TeamSpeak Identity by editing the bot_default.toml under the Bots folder. There you simply remove key and offset. The Bot must be offline.

I hope I was able to help you.

Greetings.
