### ISSUE TITLE
API via https?

### ISSUE THREAD

**Issue by VocalZero** [Splamy/TS3AudioBot#530]
Hello is there a Way to retrieve the TS3AudioBot API not via http but via a secure Connection?

**Comment by Splamy** [comment]
As EmbedIO does not support SSL on mono(linux) the only way right now is to use a small reverse proxy like nginx, apache, caddy, ... (caddy is by far easiest to set up, with about 2 config lines and you're done)

**Comment by VocalZero** [comment]
I have now tested what you advised me to do now I can use the API with HTTPS but it comes only to a Bad Request error.

**Config:**
[web]
hosts = ["127.0.0.1", "localhost", "api.musikbots.de", "138.201.42.226"]

**Comment by Splamy** [comment]
If you try the lastest develop branch version, the `hosts` entry is gone and will not be used anymore.

**Comment by VocalZero** [comment]
Now using the version of the develop branch and it is working again but I do not understand how to use the token to authorize me. Could you explain that to me?

**Comment by Splamy** [comment]
I'd usually direct you to our [api wiki](https://github.com/Splamy/TS3AudioBot/wiki/WebAPI) but I've heard from someone else already, that authentication might be broken. I'll take a look into that soon.

**Comment by VocalZero** [comment]
Is there a version where the authentication works?

**Comment by Splamy** [comment]
Yes, the current master version, but you will have to configure the hosts entry there

**Comment by VocalZero** [comment]
Do you already know how long it takes to fix the bug with the authentication?

**Comment by Splamy** [comment]
I've pushed a hotfix, but it seems like there are some performance problems which will take a little longer to sort out.

**Comment by VocalZero** [comment]
Why do I always get error ERR_INCOMPLETE_CHUNKED_ENCODING 403 when I call the API?

**Comment by VocalZero** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/20924469/55180765-8ded8100-518a-11e9-954a-eb65e4c4b49c.png)
I only get a Not Found error.

**Comment by Splamy** [comment]
You are missing `/api/` so `...de/api/bot/use/...`

**Comment by marv-th** [comment]
Please dont delete the web.hosts config. Maybe you can programm it so, that when you config it so:
[web]
hosts = ["*"]
than the bot listen for all hosts, like in the develop branch version

and when you specific hosts, only than its available for this apis.

its very neadable for us to config, that the api is maybe only available for intern networks 

hope you understand what i mean

**Comment by VocalZero** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/20924469/55183616-80d39080-5190-11e9-90e0-9d9fc57e615c.png)
Can you also explain to me what this error message means?

**Comment by Splamy** [comment]
`ERR_INCOMPLETE_CHUNKED_ENCODING ` is a HTTP error which can have many reasons across the way, unfortunately I can seem to reproduce that behaviour on my client. A quick google search revealed that this often just happens with chrome. I'll see if I can find something...

**Comment by Splamy** [comment]
@marv-th It's a valid consideration and I've put it back defaulting to `*`
