### ISSUE TITLE
DOTNET CORE BUILD DOES NOT WORK

### ISSUE THREAD

**Issue by ruymb** [Splamy/TS3AudioBot#531]
Hello Splamy,

After reinstalling my machine I still get the same problem with MONO pausing somewhere I decided to test your DOTNET build it says something is missing when i run the commands you gave me before.

root@audiobot:/home/audiobotcore# dotnet TS3AudioBot.dll                                                                        A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/audiobotcore/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/audiobotcore/TS3AudioBot.runtimeconfig.json file specifying the appropriate framework.

**Comment by Flakebi** [comment]
The automated .NET core build should copy the `TS3AudioBot.runtimeconfig.json` file into the zip file.

As a workaround you can create the file `TS3AudioBot.runtimeconfig.json` in the same folder as `TS3AudioBot.dll` with the following content:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    }
  }
}
```

**Comment by ruymb** [comment]
That did not work.

**Comment by Flakebi** [comment]
Why?

**Comment by ruymb** [comment]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'. The system cannot find the file specified.

Aborted
root@audiobot:/home/audiobotcore#

**Comment by Flakebi** [comment]
Ok, looks like there is more missing in the master release, try to download the develop zip file and add the `TS3AudioBot.runtimeconfig.json` from above. That worked for me.

**Comment by Splamy** [comment]
We still have some issues with the build server. I'll see if I can fix it soon

**Comment by Splamy** [comment]
I think after a day of work I finally fixed the build.
**Note** that all changes are still on develop, so if you want to test you'll have to download the `develop_dotnet_core` nightly build
