### ISSUE TITLE
Events(onidle, etc) not found

### ISSUE THREAD

**Issue by RageTimmy** [Splamy/TS3AudioBot#534]
07:09:52.2609| INFO 51.89.18.41 Requested: /api/settings/bot/set/2617/events.onconnect/http%3A%2F%2Fstor.rdbots.de%2FIMYClUGFSYD6AMF.mp3

It's giving me back "No config key matching the pattern found". Is the Command wrong or got the feature removed? I'm Using commit ad86914. 

Thanks a lot!

**Comment by Splamy** [comment]
From Gitter:
The command you posted works just fine. Make sure you have an up to date bot which has the event settings.
And if you wan to play the song you'll have to call it with `play` like `/api/settings/bot/set/2617/events.onconnect/!play%20http%3A%2F%2Fstor.rdbots.de%2FIMYClUGFSYD6AMF.mp3`

**Comment by RageTimmy** [comment]
Yeah, i had a too old version.
