### ISSUE TITLE
Very long API-Requests

### ISSUE THREAD

**Issue by RageTimmy** [Splamy/TS3AudioBot#536]
**Describe the bug**
The Web-API reacts very fast but then it takes so long to complete the request

**Version**
0bc340cf3a68045c7ea2092c9c60c74bdbe8cb88

**Platform**
Debian 8 
Mono JIT compiler version 5.18.0.268

**Comment by iiVoiX** [comment]
Same Version Same Plattform. Using your PHP example. The Bots Changes name quickly but the page is still loading and waiting for a Response from the API.

**Comment by Splamy** [comment]
Yeah, it's a problem that I'm aware of. The new webserver library handles requests diffently and I'm still trying to understand why.

**Comment by iiVoiX** [comment]
Any news? Saw you updated embedio.

**Comment by Splamy** [comment]
I'm waiting on updates here too: https://github.com/unosquare/embedio/issues/267

**Comment by Splamy** [comment]
I think the recent update in embedio fixed the problem (at least it currently seems so on my pc)
You can try the latest develop

**Comment by Splamy** [comment]
As per answer of #544 this seems fixed. If you still encounter the same issue repen this or continue discussion in the referenced thread.
