### ISSUE TITLE
German Language .resx download

### ISSUE THREAD

**Issue by DiBaDu** [Splamy/TS3AudioBot#537]
Hello,

where i can download the german .resx data?

I found the .dll file but not the .resx what i can put into the source code

I found polnish but no german:

https://github.com/Splamy/TS3AudioBot/files/2142145/strings.pl.resx.zip

where i can download the german?

**Comment by Splamy** [comment]
You should be able to download it from transifex here: https://www.transifex.com/respeak/ts3audiobot/stringsresx/de/download/for_use/

**Comment by DiBaDu** [comment]
hello, it worked perfectlöy.

I have 1 other question. What file i have to edit in sourceode to change the default Bot Name what is autogenerated in config file?

**Comment by Flakebi** [comment]
The default settings are written here: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Config/ConfigStructs.cs#L163
