### ISSUE TITLE
Reconnects client

### ISSUE THREAD

**Issue by User-RU** [Splamy/TS3AudioBot#538]
Is it possible to manage the number of bots reconnects at loss of connection with the server in the config?
To not 7 times, and making an endless cycle reconnects.
Thank!)

`reconnect_interval = ["10s", "repeat"]` in `[bot.connect]` - does not react(

**Comment by Splamy** [comment]
Currently there is no config for that.

We have a tracking issue here #484 for this feature, please continue discussion there.
I'll close this as a duplicate therefore
