### ISSUE TITLE
Support for higher security level identities 

### ISSUE THREAD

**Issue by JABirchall** [Splamy/TS3AudioBot#54]
I don't know if I missed it or something, But I can't see any method to tell the musicbot to generate an identity higher then level 8, or even a method to import an identity from my client.

I'm trying to have it connect to a server with security level 24.

**Comment by Splamy** [comment]
Automatically raising the security level should be no problem, I will add it in the next update.

Importing identities on the other hand will not be that esay, since I haven't looked yet into how ts3 stores the identities.

**Comment by LenoxFro** [comment]
is there a way to manually raise the level ?

**Comment by Splamy** [comment]
Well not externally, but the Ts3Crypt class has two static methods:
LoadIdentity(string key, ulong keyOffset, -) to load an identity string in the format the bot uses
ImproveSecurity(IdentityData identity, int toLevel) to raise the level
then you can save the IdentityData.ValidKeyOffset.

**Comment by Splamy** [comment]
Just a short update here, I have added a feature on the dev branch to specify the minimum generated sec level before connection. Hope this helps :)

**Comment by Bluscream** [comment]
Can you create a small exe that can take cmdline arguments to create+/improve sec levels of a ts3 exported ini

**Comment by Bluscream** [comment]
Can you create a small exe that can take cmdline arguments to create+/improve sec levels of a ts3 exported ini

**Comment by Bluscream** [comment]
It should work like this: either you drag and drop the file onto it (equal to `seclvlraise.exe "C:\indentity.ini"`)

**Comment by Bluscream** [comment]
And a server mode like `seclvlraise.exe -s "Idenitity String" -max 32`
Then it should not output anything until it finishes or an error occurs, so a php script could grab its output for example

**Comment by Splamy** [comment]
I could make something like:
```
> tool.exe generate
<base64identitystring>

> tool.exe incerase 20 <base64identitystring> (<last checked number>)
<newoffsetnumber>

> tool.exe incerase 20 <base64identitystring> 
// when cancelled with Ctrl+C
<newoffsetnumber>
<last checked number>
```

**Comment by Bluscream** [comment]
Thats quite bit of a request and if aint nobody got time for that i might do it myself later on. More like a suggestion ^^

**Comment by Bluscream** [comment]
That sounds like smth to work with even though i dont kn0w why someone would need the offset&

**Comment by Splamy** [comment]
the offset effectively determines the sec level of an identity
the <last checked number> would be useful if you want to let the script run for 5 hours but havent found any higher valued offset, that way the next time you start the tool you dont lose any progress by recalculation all old numbers

**Comment by Splamy** [comment]
> Automatically raising the security level should be no problem, I will add it in the next update.
> ~Splamy, 13.03.2017
...and I thought that would be an easy task.

Haha, well over half a year later and many reworks, I think I finally found all weak points, race conditions and dispatcher deadlocks. Everything now works for the autosec feature which needed a reliable reconnect.
This fix should also be a huge step to getting multi-instances running, so every feedback to stability, whether is works well and stuff is appreciated.

**Comment by VerHext** [comment]
How does it look at the moment with the import of default Identitys?

**Comment by Splamy** [comment]
Teamspeak obfuscates stored identities in a somewhat annoying way. So this might still take a while until I start working on that.

**Comment by Splamy** [comment]
Importing teamspeak identities works now
