### ISSUE TITLE
command complexity

### ISSUE THREAD

**Issue by FaulerHund** [Splamy/TS3AudioBot#543]
For what is this setting? command_complexity  i read the information about this setting in the config but i can't understand for what this config is

**Comment by Splamy** [comment]
The command system is pretty powerful, for example you could declare two aliases:
```
!alias add one "!two"
!alias add two "!one"
```
When you now call `!one` you would get an endless loop, but that loop will exit after reaching the maximum command_complexity calls.
This limitation counts for all commands, so for e.g if you write `!x (!x) (!x) (!x) (!x) ...` each subcall would count towards the count.
Basically this settings was introduced to limit endless or too big calls to prevent a dos.
