### ISSUE TITLE
Could not load core config

### ISSUE THREAD

**Issue by NurLutix** [Splamy/TS3AudioBot#545]
Hey,
I was just trying to launch the bot. Unfortunately I get the following error message:

14:47:20.1661| INFO [============ TS3AudioBot started =============]
14:47:20.2078| INFO [=== Date/Time: Friday, 26 April 2019 14:47:20
14:47:20.2108| INFO [=== Version: 0.9.1/master/ad86914f
14:47:20.2108| INFO [=== Platform: Ubuntu 16.04.6 LTS (Xenial Xerus) (64bit)
14:47:20.2108| INFO [=== Runtime: Mono (5.20.1.19 (tarball Thu Apr 11 09:09:21 UTC 2019))
14:47:20.2108| INFO [=== Opus: libopus 1.1.2 (x64)
14:47:20.2108| INFO [==============================================]
14:47:20.2808|ERROR Could not load core config.
14:47:20.2808|ERROR Core initialization failed: Could not create config
14:47:20.2808| INFO TS3AudioBot shutting down.

Can you help me, please?

**Comment by Splamy** [comment]
You probably have misformatted your config file. Look into the log, there sould be a stacktrace and a detailed information where the syntax error is.

**Comment by NurLutix** [comment]
Fixed it, thanks.
