### ISSUE TITLE
IP in rights.toml

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#550]
Is it possible to set up an allowed IP in the rights.toml? For example, that only the IP: '192.168.178.28', can send calls to the api. When yes, than it would be very helpfull, when you will post it :)

**Comment by Flakebi** [comment]
This is currently not possible but is is planned to add that.

**Comment by Splamy** [comment]
Funnily just yesterday I had the same Idea to implement. Expect this feature soon

**Comment by Splamy** [comment]
feature is up on develop
