### ISSUE TITLE
Dupplicate Bots

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#552]
It would be very nice, when you implement a setting, where you can set up, that the same Bots cannot connect multiple times.
It means that you cannot connect for example bot_1 for three times.

Maybe: 
```
[bot.connect]
max = 1 # 2,3 or -1 for endless 
```

Important! I do not mean the instance. Only the Bots.

Hope u understand what you mean :)

**Comment by Splamy** [comment]
What's the difference between a bot and a instance for you?

If you mean that each bot config should only start once, even for consecutive 'bot connect' calls, then yes, that's already planned as it's required for #306 to allow accessing bots by name.
