### ISSUE TITLE
lagging bots (0.10.0-alpha.118)

### ISSUE THREAD

**Issue by akizzed** [Splamy/TS3AudioBot#554]
since the upgrade from 0.10.0-unstable.74 to 0.10.0-alpha.118 the bots start lagging with high ping and latency. 
after a downgrade back to .74 the problem was solved...
there are no strange logs or sth. like that^^
on linux ubuntu 18.04 

igm with the ping | latency
https://i.imgur.com/Mp48jpj.png

**Comment by Splamy** [comment]
We have found a bug in our webserver which can lead to high cpu usage. I have contacted the maintainers. We'll have to wait if the accept the fix or make their own.

In the meantime, can you check if the same bad performance is happening when you disable both the api **and** the webserver?

**Comment by akizzed** [comment]
gonna try it this evening

**Comment by akizzed** [comment]
i think this solved the problem.
but this workaround is very problematic because i need an overview of my bots...

**Comment by akizzed** [comment]
also, if i want to shutdown the bots there comes an error "strem read/write error" and "waiting for ffmpeg"

sreenshot:
https://i.imgur.com/b35M5NT.png

**Comment by Splamy** [comment]
As said, disabling it was just for testing. The maintainers of embedio have already merged the fix and it will be in the next patch, I will update the ts3ab to use the new version as soon as it is out

**Comment by Splamy** [comment]
Ok, I've got an experimental build up on develop which is now based on kestrel, the probably fastest c# server. I've measured perfomance and latency increase by about 2-3x
The rework to kestrel is not 100% done, but everything should work now again, please check if anything broke...
