### ISSUE TITLE
Nightly build is using malformed zip

### ISSUE THREAD

**Issue by F43nd1r** [Splamy/TS3AudioBot#555]
**Describe the bug**
NIghtly builds for TS3AudioBot use zips with **backslashes as path separators** this is against the .ZIP File Format Specification, which states:

> 4.4.17.1 The name of the file, with optional relative path. The path stored MUST NOT contain a drive or device letter, or a leading slash. **All slashes MUST be forward slashes / as opposed to backwards slashes \ for compatibility with Amiga and UNIX file systems** etc. If input came from standard input, there is no file name field.

This causes issues on UNIX systems, e.g. unzip on arch returns 1.

**Expected behavior**
Nightly builds produce well formed zips.

**Version**
TS3AudioBot v0.9.1

**Platform**
Unix systems

**Comment by Splamy** [comment]
Fixed.
Note that currently only the develop and develop_dotnet_core are updated, as the master does not work with the current build pipeline (That's also why there is no master_dotnet_core yet). When the develop gets merged into master, those builds will also be updated and built with the new pipeline.
