### ISSUE TITLE
Executing shell script/command

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#556]
Hello!

Is there command in TS3Audiobot which allows to run a shell command? For example, I have "hello.sh" script:

#!/bin/bash
echo "Hi there!"

and want to run it via TS chat, kind of:

!run_shell_script hello.sh

I've found !xecute and !eval but I don't know if they allow it :-)
Thank you in advance!

**Comment by Splamy** [comment]
That seems awfully dangerous, but the easiest way would be to write a simple plugin.

Take a look at the plugin wiki, this code should get you started on running bash

```csharp
try
{
	using (var p = new Process
	{
		StartInfo = new ProcessStartInfo
		{
			FileName = "bash",
			Arguments = $"-c \"{param}\"",
			CreateNoWindow = true,
			UseShellExecute = false,
		},
		EnableRaisingEvents = true,
	})
	{
		p.Start();
	}
}
catch { }
```

**Comment by zmechu** [comment]
OK, thank you! :-)

**Comment by marv-th** [comment]
But where is the command where the script has to be listen? Sorry for this question but i cant Unserstand what you wrote

**Comment by Flakebi** [comment]
The wiki explains how to write plugins: https://github.com/Splamy/TS3AudioBot/wiki/Plugins

**Comment by marv-th** [comment]
Okay thanks. But one more question. Is it possible to run this commands with the api? Maybe for you an stupid question but i dont want to write an unuseful plugin for me. U know?

**Comment by Flakebi** [comment]
The commands from plugins are integrated into the command system like any other command.
So **yes**, you can call any command that you define in a plugin from the webapi in the same way as any other command.

**Comment by marv-th** [comment]
Okay thanks thats very helpfull for me!
