### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#558]
**Describe the bug**
I can't play some youtube Videos like https://www.youtube.com/watch?v=pv0NWTJdGWc
It loads the Title but didn't play.
**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior (if possible)
!play https://www.youtube.com/watch?v=pv0NWTJdGWc
**Version**
Which commit did you build or download? (mono TS3AudiBot.exe -V or !version in chat)
0.10.0-alpha.126
**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)
Ubuntu 16.04
**Log**
```
2019-05-25 21:04:35.5154| INFO|4|Bot.OnMessageReceived User Clemens requested: !play [URL]https://www.youtube.com/watch?v=pv0NWTJdGWc[/URL]
2019-05-25 21:04:41.1095| INFO|4|PlayManager.StopInternal Song queue ended: No next song could be played.
```

**Comment by Splamy** [comment]
Ubuntu 16.04 ships an antique version of ffmpeg (2.8.X) which is about 3 years old and doesnt understand the new dash format apparently.
Download an up to date static version and redirect the config to it: https://johnvansickle.com/ffmpeg/
