### ISSUE TITLE
Frage - Keine Rechte Nachricht ändern

### ISSUE THREAD

**Issue by Bastih18** [Splamy/TS3AudioBot#559]

**Comment by Bastih18** [comment]
Ich habe es schon alles so Eingerichtet das man keine Rechte hat
Ich will jezt nur noch dass man ne abgeänderte Nachricht bekommt

**Comment by Splamy** [comment]
1. Issues in english
2. faq: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#text-responses

**Comment by Bastih18** [comment]
Okay sry, i am want to change the "You can not execute "play". You are missing the "cmd.play" right.!"

**Comment by Bastih18** [comment]
Message
