### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#563]
Is there a way to play Spotify using TS3Audiobot?
Or plan to do it? :-)

**Comment by Splamy** [comment]
Highly unlikely, spotify's api is pretty much completly shut off, and for playback you need a browser with plugin to decrypt the stream. Unless someone reverse engineers that or makes an tool for this I can't do anything.

**Comment by Cerberooo** [comment]
@Splamy Maybe there is a similiar way to offer spotify support like [Mopidy](https://github.com/mopidy/mopidy-spotify) does?

**Comment by Splamy** [comment]
Someone already created a plugin (linked somewhere in the gitter chat) for spotify based on the https://github.com/librespot-org/librespot community lib. However the usage requies spotify premium, and I don't have an account to test that.
