### ISSUE TITLE
Streams in der Datenbank des Bots speichern

### ISSUE THREAD

**Issue by CruptexDE** [Splamy/TS3AudioBot#565]
Hallo,

ich würde gerne wissen, wie man es machen kann, dass wenn man bei dem Bot ein Stream abgespielt hat und dieser reconnectet oder bzw. neu gestartet wird (natürlich per Interface), der Stream automatisch wieder abgespielt wird. Ich glaube über eine Datenbank klappt das but idk. 
Bitte um Hilfe!

MfG

**Comment by Miyakura** [comment]
Issues pls in english

- #238 `events.onconnect`
