### ISSUE TITLE
Create Bot over Webinterface (Failed)

### ISSUE THREAD

**Issue by CookieCr2nk** [Splamy/TS3AudioBot#566]
**Describe the bug**
I can't create a Bot over the Webinterface, i have give my UUID the full Admin rights.
```
Error: Error creating bot
Info: Could not create config.
```
**Expected behavior**
i expect, that i can create a bot over the webinterface.

**To Reproduce**
1. Go to Webinterface
2. Login with API Key
3. Create Bot
4. Show Error

**Version**
Version: 0.10.0-alpha.129
Branch: develop
CommitHash: 525f4bd9fdbf15d5d9b5231152533def13f8c761

**Platform**
Which platform(-version) are you running on? Ubuntu 18.04.2 LTS (Bionic Beaver) (64bit)
Which runtime(-version) are you using? .NET Core (2.2.5) ServerGC:True GC:Batch)

**Log**
```
18:27:23.8578| INFO|| [============ TS3AudioBot started =============]
18:27:23.9416| INFO|| [ Date/Time: Monday, 03 June 2019 18:27:23
18:27:23.9505| INFO|| [ Version: 0.10.0-alpha.129/develop/525f4bd9
18:27:23.9505| INFO|| [ Platform: Ubuntu 18.04.2 LTS (Bionic Beaver) (64bit)
18:27:23.9505| INFO|| [ Runtime: .NET Core (2.2.5) ServerGC:True GC:Batch
18:27:23.9505| INFO|| [ Opus: libopus 1.1.2 (x64)
18:27:23.9505| INFO|| [==============================================]
18:27:24.5171| INFO|| Bot "default" connecting to "172.17.0.3:9987"
18:27:25.2848| INFO|0| Started Webserver on port 8180
18:27:25.3373| INFO|0| Bot "default"(0) connected.
18:28:09.1678| INFO|| ::ffff:127.0.0.1 Requested: /api/settings/create/123

```

**Comment by Flakebi** [comment]
Hi,
thank you for the report.
I can reproduce this, `!settings create botname` also fails with `Error: Could not create config.`
As a workaround, connecting a new bot from the webinterface and saving it with a name afterwards works.

**Comment by CookieCr2nk** [comment]
Thanks, and i whould be nice, to make a name and rename feature in the Webinterface :)

**Comment by Splamy** [comment]
Fis is up on dev

**Comment by heartles39** [comment]
> **Describe the bug**
> I can't create a Bot over the Webinterface, i have give my UUID the full Admin rights.
> 
> ```
> Error: Error creating bot
> Info: Could not create config.
> ```
> 
> **Expected behavior**
> i expect, that i can create a bot over the webinterface.
> 
> **To Reproduce**
> 
> 1. Go to Webinterface
> 2. Login with API Key
> 3. Create Bot
> 4. Show Error
> 
> **Version**
> Version: 0.10.0-alpha.129
> Branch: develop
> CommitHash: [525f4bd](https://github.com/Splamy/TS3AudioBot/commit/525f4bd9fdbf15d5d9b5231152533def13f8c761)
> 
> **Platform**
> Which platform(-version) are you running on? Ubuntu 18.04.2 LTS (Bionic Beaver) (64bit)
> Which runtime(-version) are you using? .NET Core (2.2.5) ServerGC:True GC:Batch)
> 
> **Log**
> 
> ```
> 18:27:23.8578| INFO|| [============ TS3AudioBot started =============]
> 18:27:23.9416| INFO|| [ Date/Time: Monday, 03 June 2019 18:27:23
> 18:27:23.9505| INFO|| [ Version: 0.10.0-alpha.129/develop/525f4bd9
> 18:27:23.9505| INFO|| [ Platform: Ubuntu 18.04.2 LTS (Bionic Beaver) (64bit)
> 18:27:23.9505| INFO|| [ Runtime: .NET Core (2.2.5) ServerGC:True GC:Batch
> 18:27:23.9505| INFO|| [ Opus: libopus 1.1.2 (x64)
> 18:27:23.9505| INFO|| [==============================================]
> 18:27:24.5171| INFO|| Bot "default" connecting to "172.17.0.3:9987"
> 18:27:25.2848| INFO|0| Started Webserver on port 8180
> 18:27:25.3373| INFO|0| Bot "default"(0) connected.
> 18:28:09.1678| INFO|| ::ffff:127.0.0.1 Requested: /api/settings/create/123
> ```

Can you contact me?

**Comment by CookieCr2nk** [comment]
I can, but where?

**Comment by heartles39** [comment]
> I can, but where?

https://www.facebook.com/profile.php?id=100025938038622 my facebook plss add

**Comment by CookieCr2nk** [comment]
I dont have facebook, add me on twitter @CookieCr2nk

**Comment by heartles39** [comment]
I dont have twitter xd do you use discord?

**Comment by Splamy** [comment]
@heartles39 you are running .129, the version with the fix is .134, so you should update.

**Comment by heartles39** [comment]
> ~@heartles39 you are running .129, the version with the fix is .134, so you should update~
> nvm, you just copied the original post... any reason you cannot just simply ask here?

I want help because I can't :DDD all I want is an advanced webpanel
