### ISSUE TITLE
How to get channel data

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#567]
Hi, I am currently programming a plugin in which I have to call up channel data using the channel ID. So most important is the channel name, but maybe I need more data. I've tried almost all commands and functions and can't get any further. I always get only errors that there is no such function or an empty result. Therefore I ask for help which function I have to call and how to use it correctly

**Comment by Splamy** [comment]
Right now the Bookeeping is not finished, so the easiest way would be to inject a `Ts3FullClient` into your plugin and call `ChannelList`
