### ISSUE TITLE
How can I install it please help

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#569]
https://github.com/Bluscream/TS3AudioBotPlugins/blob/develop/YoutubeSearch/plugin.cs

How can I install it please help

**Comment by Splamy** [comment]
Wi have a wiki entry https://github.com/Splamy/TS3AudioBot/wiki/Plugins

**Comment by heartles39** [comment]
Does the !yts song name work? How can I be active in the web panel? There is no file ts3audiobot.toml
