### ISSUE TITLE
Youtube Search

### ISSUE THREAD

**Issue by M3M4Ti** [Splamy/TS3AudioBot#573]
Im Load Youtube Search Plugins Folder
And !plugin load YoutubeSearchPlugin.dll
and !yt Search music but Error An unexpected error occured: Could not load file or assembly 'YoutubeSearch, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Sistem belirtilen dosyayı bulamıyor.

**Comment by M3M4Ti** [comment]
@Splamy Help Please

**Comment by Splamy** [comment]
See here: https://github.com/Splamy/TS3AudioBot/issues/89#issuecomment-502306596
