### ISSUE TITLE
Channel Client List how

### ISSUE THREAD

**Issue by daffyyyy** [Splamy/TS3AudioBot#574]
HI,
How i can get all clients on specific channel with "channelclientlist"?
I tried add to ts3baseclient =>
```
		public R<ClientData[], CommandError> ChannelClientList(int cid)
			=> Send<ClientData>("channelclientlist",
			new CommandParameter("cid", cid));
```

and use it with

`ts3Client.TsFullClient.ChannelClientList(18).Value.ToArray()`

but returning null

**Comment by Splamy** [comment]
Well `channelclientlist` isn't a valid query command the last time I checked.
```csharp
var result = tsFullClient.ClientList();
if (result.Ok)
{
	var users = result.Value.Where(client => client.ChannelId == cid).ToArray();
}
```
