### ISSUE TITLE
!commandseek

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#575]
I'm bringing TS3Audiobot to my Teamspeak server. i write !commandseek Boots multiply! Is that a bug?

**Comment by Splamy** [comment]
we have a issue templates, please use them

**Comment by heartles39** [comment]
> we have a issue templates, please use them

I do not understand what you're saying

**Comment by Splamy** [comment]
When you click "New Issue", github should show you this page https://github.com/Splamy/TS3AudioBot/issues/new/choose
since you are writing a bug report, select the first one and fill out all fields so I don't have to ask about every little detail to get started on investigating the problem
