### ISSUE TITLE
.NET Core 2.2 Runtime instead of CORE SDK

### ISSUE THREAD

**Issue by CookieCr2nk** [Splamy/TS3AudioBot#577]
**Question**
Hello,

I would like to ask if it is possible to run the TS3Audiobot (version: develop_dotnet_core) with the 
.NET Core 2.2 Runtime on Linux Debian 9 - x64 instead of the 
.NET Core SDK on Linux Debian 9 - x64.

kinds regards

**System Information**
- **Platform**: Debian 9.8

**Comment by Flakebi** [comment]
The .NET Core 2.2 Runtime is fine. You need the SDK only if you want to compile the bot yourself.
