### ISSUE TITLE
radio stations

### ISSUE THREAD

**Issue by szogi1910** [Splamy/TS3AudioBot#579]
Hi, I have a problem with playing internet radio by the bot, I really do not know where to download or add media for the ubuntu system

Error: Could not load. (media: The resource could not be found.)

`[factories]
#The default path to look for local resources.
media = { path = "" }`

**Comment by Splamy** [comment]
I don't under standand your question.
Why not just `!play <link>` ?

**Comment by szogi1910** [comment]
Because it adds as a playlist
My steps:
1. !list created
2. list add http://re2k.radioparty.pl:8000/
3. list save radioparty_1
4. list load radioparty_1
5. List play 
After the last command to just this error
Error: Could not load. (media: The resource could not be found.)

**Comment by Splamy** [comment]
**Version**
Which commit did you build or download? (mono TS3AudiBot.exe -V or !version in chat)

**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)

**Log**
```
Paste the important log parts from the ts3audiobot.log into this code block here.
Try not to paste too little.
At best from the first to last interaction from you which reproduces this problem.
```
