### ISSUE TITLE
Add support for youtube livestreams

### ISSUE THREAD

**Issue by Splamy** [Splamy/TS3AudioBot#58]
The latest commit 13a58181dfde4cc83dac472b15fee3688f4fe12a on develop adds support for Youtube livestreams.
@ Everyone interested please all try it out and give some feedback!

**Comment by blackjack4494** [comment]
Maybe I can contribute something. I recently wrote a little script using youtube-dl and ffmpeg to convert livestreams to audio only and stream them back on my server. This should be doable. I can upload my code smoewhere.

**Comment by Splamy** [comment]
Sure thing, a gist, pull request, anything. If you need any help or explanations how stuff is working internally hit me.

**Comment by Splamy** [comment]
The latest commit 13a58181dfde4cc83dac472b15fee3688f4fe12a on develop adds support for Youtube livestreams.
@ Everyone interested please all try it out and give some feedback!
