### ISSUE TITLE
Visual Studio problem

### ISSUE THREAD

**Issue by M3M4Ti** [Splamy/TS3AudioBot#580]
ı open .sln and ı have same problem
http://prntscr.com/o3deih

**Comment by M3M4Ti** [comment]
http://prntscr.com/o3g0hx

**Comment by Splamy** [comment]
I neither understand turkish, nor can I copy those errors from a screenshot to google. I dont know which vs version you are using...
Try installing the 'dotnet core' and .NET desktop deveopment workload with '.NET framework 4.7.2' then click build, it should restore all missing nuget packages

**Comment by M3M4Ti** [comment]
http://prntscr.com/o3xm8j

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/issues/384#issuecomment-425485096
