### ISSUE TITLE
!system info command error

### ISSUE THREAD

**Issue by dzinks2009** [Splamy/TS3AudioBot#581]
**Describe the bug**
Command "!system info" show's other info than expected (I think?)

**Version**
Version: 0.10.0-alpha.139
Branch: develop
CommitHash: 24892e5d0c392aed14999f6583de91401655ff86

**Log**
```
!system info
"TS3AudioBot": { memory = System.Int64[], cpu = System.Single[], starttime = 6/18/2019 2:43:43 PM }
```

**Comment by Splamy** [comment]
Yeah, this command was not designed to be used from chat, but api only. I don't quit see the use case for that. If there's demand I can maby look into properly formatting it. Otherwise I'd just exclude it from chat usage

**Comment by Bluscream** [comment]
Maybe just let it show the last value, so people can check on their bots current resource usage

**Comment by Splamy** [comment]
That's because on chat it never gets json serialized, it's just a debugger view

**Comment by Splamy** [comment]
I fixed it, it's now readable as suggested by bluscream
