### ISSUE TITLE
Search for songs

### ISSUE THREAD

**Issue by LeiToH** [Splamy/TS3AudioBot#590]
I was reading the wiki to add a command, to search for songs. I did not understand if it is a command to add via bot chat inside the ts3 or a configuration inside the bot files. I could be guided to make it work

**Comment by Flakebi** [comment]
I guess you mean this FAQ entry? https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs

Just write the two alias commands to the bot (in chat or via api, it doesn’t matter). The aliases will be saved across bot restarts.

Afterwards you can use `!ytp cute cats` to hear whatever you like.

**Comment by LeiToH** [comment]
Does it work in any version?

**Comment by Flakebi** [comment]
The youtube search was implemented in 6f1783 (2019-06-14) and it’s not yet on master.
So the current develop version (or the one from two weeks ago) is fine.
