### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by VocalZero** [Splamy/TS3AudioBot#591]
Hello,

I have a small problem with the TS3AudioBot API which I can't solve completely and wanted to find out how to solve this problem. When I try to do something with the API I always get the error "Access to XMLHttpRequest at 'http://localhost:58913/api/bot/use/0/(/bot/connect/template/MB-pctdd)' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status." and I have no idea how to solve it. I hope that I can be helped.

Yours sincerely
Kacper Mura

**Comment by Splamy** [comment]
CORS is a browser security feature; So I guess you have a website running on localhost:3000 with a javascript frontend which does a xmlhttprequest to localhost:58913 where the bot api is running.

This problem should not occour when you use a normal http client on any application which is not a browser.

As a workaround right now you can edit the code and add here https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/Web/Api/WebApi.cs#L61 after something like:
```csharp
response.Headers["Access-Control-Allow-Methods"] = "GET, POST";
response.Headers["Access-Control-Allow-Headers"] = "Content-Type, Authorization, X-Real-IP";
```

note this is untested; I will push a change once I checked if it works.
