### ISSUE TITLE
Disable flood protection

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#595]
I am currently writing a support plugin for the bot, but unfortunately this is a bit slower than desired due to many requests like clientlist, channellist, etc. . Because I think that this was done to prevent the bot from flooting, I wanted to ask if it could be turned off somehow. 

I know for example a Query Api which has a Flood Protection Mode and a &quot;Speed"; Mode and there you can clearly feel the difference. 

Is there a point in the config where you can disable it completely or at least other ways to make it faster

**Comment by Splamy** [comment]
There are currently no such mechanisms like anti-flood or rate limiters in the bot.
Could you give an example what you are doing that is so slow?

**Comment by MoroseCorpse** [comment]
Ok then maybe it's actually because I'm in a foreach loop all the time running clientlist or something like that to get certain data. I guess I'll figure out how to program it differently. 

Is there perhaps a possibility to have several classes like in e. g. Java, which all work separately, but the data is accessible from everywhere?

**Comment by Splamy** [comment]
I don't quite understand your question.
If you think of sometling like a hierachial server structure which can be acessed as objects; yes that already long planned, we call it 'bookkeeping', but it's still work in progess

**Comment by Splamy** [comment]
Just wanted to let you know, the Bookkeeping is on develop and can be accessed on `Ts3FullClient.Book`. Some (small) changes are still planned.
