### ISSUE TITLE
TS3 AudioBot Command description change

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#596]
Hello

Is it possible to change the descriptions of the commands that appear when we type !help?

For example : !play <link> - Odtwarza dowolne źrodło multimedii ( Odtwarza dowolne źrodło multimedii, I want to change the article here.)

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#text-responses

**Comment by heartles39** [comment]
I don't understand anything about this. Can you explain a little?

**Comment by Splamy** [comment]
Ok, short summary, the easiest way is to just use visual studio for all this; you can do all this with a normal text editor and a few command line tool, but thats a lot of work and also took my many attempts to get correctly set up un my server.

Doubleclick the `strings.resx` file in the `Localization` folder, you should see a table with id's on the left and translation on the right.
The basic `strings.resx` is in english;
If you want for example polish, you can download what the community already translated from here  https://www.transifex.com/respeak/ts3audiobot/language/pl/  (or create a blank) and put it in the same folder with the name `strings.pl.resx`.
Now every string which is defined in the .pl.resx file will override the english default from the strings.resx file.
Also when you compile visual studio will create a `/<outputfolder>/pl/strings.dll ` file, you can share tha file or copy to your server and it will have all pl translations, when you put it back into the correct path.
