### ISSUE TITLE
How to use [plugins.load] ?

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#597]
I would like to know how to use the toml setting [plugins.load]. I cannot find any wiki entry or an other issue where this is explained.

My next question is, that i coded an Static Plugin. But i can not call this like so: http://10.10.10.14:544/api/plugin/load/0  Error: {"ErrorCode":10,"ErrorName":"CommandError","ErrorMessage":"Plugin error: PluginNotFound"}. On Plugin list they print out no Plugin.

**Comment by Splamy** [comment]
plugins.load is not implemented yet. It's a placeholder for some tests i did.

Check that you put your cs/dll file in the correct folder. Note that you might have changed the folder in the config. If it is a relative path, it will be relative to the working directory you started the bot in.

**Comment by marv-th** [comment]
Okay thanks. With my second problem. My target is it to load a plugin on the main bot. So when no bot is created that i am able to send plugin commands to the api.

**Comment by Splamy** [comment]
As I said, check that your file is in the correct folder.
If the program is erroneus or could not be loaded for whatever reason, it will still be shown in the plugin list with an error status.
The only reason I see why it's not shown is because the bot doens't see any pluing file.

**Comment by marv-th** [comment]
With the created bot i am able to list and load the plugin. So the folder is correct but with the main bot i am not able to use.

http://10.10.10.14:544/api/bot/use/0/(plugin/list) - Works
http://10.10.10.14:544/api/plugin/list - didnt works

**Comment by Splamy** [comment]
I just tested it and it works just fine here:
> http://localhost/api/plugin/list
```
[
    {
        "Id": 0,
        "Name": "Example1 (BotPlugin)",
        "Status": 5,
        "Type": 1
    },
...
```

Have you tried restarting the bot?

**Comment by marv-th** [comment]
I will try it again and send the resulution

**Comment by marv-th** [comment]
Hey. I found my problem. My Api Url was wrong. I sended the request to the wrong server. Sorry for my mistake

**Comment by Splamy** [comment]
no problem
