### ISSUE TITLE
assembly problem

### ISSUE THREAD

**Issue by daffyyyy** [Splamy/TS3AudioBot#599]
Hi,

I have a little problem with netcore version, I'm trying to get every assembly to dll's to run standalone app, but sometimes there is problem :( 
E.g. i need "system.runtime" but when publish/add nuget package i'll don't get it.
Is there any way to get all dependencies?

**Comment by Splamy** [comment]
As you haven't posted any details what you have done/tried already, I can only give you some hints where to look.

- The dontet core docs have a tutorial for standalone apps: https://docs.microsoft.com/en-us/dotnet/core/deploying/  
Make sure you are following the 'SCA' (Self Contained App) and not 'FDD' or 'FDE', as the other two will still require the dnc framework to be installed on the target machine.

- Note that a SCA does not mean, dependency-less app. You will still need some packages of your linux distro to run it: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x  
Fully depencency less app are targeted for dnc 3.0 which is in preview only right now.

**Comment by daffyyyy** [comment]
I need all / most dependencies as .dll files for other app what uses ts3audiobot, without dlls,  problem is e.g. "Could not resolve assembly: System.Runtime"

Installed nuget packager "system.runtime", added reference to .csproj
" <PackageReference Include="System.Runtime" Version="4.3.1" />" but still nothing ;/

**Comment by Splamy** [comment]
You still haven't provided any information what you are actually doing.

**Comment by daffyyyy** [comment]
For example, tools for code obfuscation like dotfuscator, when used on net (.exe) its works, but when used on netcoreapp nope. I have several people access to my servers and I have modified bot a little and I do not want them to copy what is in it.
The first problem refers to other applications that I want to attach to the bot, but they work on the already compiled code and probably need all dependencies

**Comment by Splamy** [comment]
This seems rather a problem of dotfuscator and dotnet core and it not really ts3ab related, so I'll close this issue.

Oh and by the way, the license requires you to make the source and all changes publicly available If you are distributing the bot, or a modified variant in any way. Just saying...
