### ISSUE TITLE
clear config bot

### ISSUE THREAD

**Issue by multiand001** [Splamy/TS3AudioBot#603]
creating a bot on the webinterface and how it will change something in the config and make a restart in the panel this config is cleaned up
Version: 0.10.0-unstable.144

[commands]

[commands.alias]

[connect]
#The server password. Leave empty for none.
server_password = {  }
#The default channel password. Leave empty for none.
channel_password = {  }
#Overrides the displayed version for the ts3 client. Leave empty for default.
client_version = {  }

[connect.identity]
#||| DO NOT MAKE THIS KEY PUBLIC ||| The client identity. You can import a teamspeak3 identity here too.
key = "MCoDAgbAAgEgAiEAyvhau4yse9Ed9dGq/jbjzn2SpX38/UfzoFLOJu3MWxY="
#The client identity offset determining the security level.
offset = 105

[reconnect]

[audio]
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
volume = {  }

[playlists]

[history]

[events]

it can not be edited because it will clean it anyway

**Comment by Splamy** [comment]
Use `!settings bot reload (<botname>)` if you make changes to the bot config file while it the bot is running.

Alternatively use the `!settings set ...` commands to edit the settings from the chat.

**Comment by multiand001** [comment]
Ok
