### ISSUE TITLE
How to install a Plugin?

### ISSUE THREAD

**Issue by NiclasPe** [Splamy/TS3AudioBot#610]
Hey, I had create the Plugins Folder and i also had configure it in the config. Than i want to install the Plugin. But if I use The Folder the wont wont find this Plugin and if i use the Files the bot will give me an error whive the plugin.cs

System: Ubuntu

Mono Version:  6.0.0.313
TS3 AudioBot Version: newest 

Plugin Informations:
[I want to use this Plugin](https://github.com/Bluscream/TS3AudioBotPlugins/tree/master/NowPlaying)

**Comment by Splamy** [comment]
@Bluscream's plugins are most probably all outdated, and he currently does not updating them.
You'll probably have to fix it yourself or ask anyone to fix it for you.
