### ISSUE TITLE
Multiple botnames

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#611]
**Is your feature request related to a problem? Please describe.**
Is it possible to set for each bot a different bot name? It would make sense if I´ve different bots on the same server with different name like Techno-Music-Bot and RNB-Music-Bot...

**Comment by zmechu** [comment]
Yes. If you want a single instance of ts3audiobot with multiple bots, (for example "Galactic" and "Pevo") do such way:
1. at **ts3audiobot.toml**
`"Pevo" = { run = true }`
`"Galactic" = { run = true }`
2. make directories **bots/Pevo** and **bots/Galactic**
3. create file **bot.toml** under **booth** directories with:
`run = true`
`[connect]`
`name = "Here put bot name"
`
with gave you definitions of booth bots. Thats all :-)

Additionally, if you want to give different permissions for different bots, add under **rights.toml**:
`[[rule]]`
`bot = [ "Galactic" ]`
`        [[rule.rule]]`
`        groupid = [ 178 ]`
`        useruid = [ ]`
`        "+" = [`
`                "cmd.play",`
`                "cmd.pause",`
`                "cmd.stop",`
`                "cmd.seek",`
`                "cmd.volume",`
`                "cmd.list.*",`
`                "cmd.add",`
`                "cmd.clear",`
`                "cmd.previous",`
`                "cmd.next",`
`                "cmd.random.*",`
`                "cmd.repeat.*",`
`                "cmd.history.add",`
`                "cmd.history.from",`
`                "cmd.history.id",`
`                "cmd.history.last",`
`                "cmd.history.play",`
`                "cmd.history.till",`
`          "cmd.history.title",`
`     ]`
`      "-" = [ "cmd.list.save" ]`
`
Villa :-)

**Comment by lgund** [comment]
I wil check that and reopen the issue if I have some questions.

**Comment by Splamy** [comment]
Except Point 1. which doesnt exists anymore (replaced by the `run` in 3.) seems fine.

Also some notes for some understanding:
Each value in the `ts3audiobot.toml` which is in a [bot.*] category can be individually overridden in a `bot.toml` config (The `bot.` prefix is just removed).
So for eg. in the `ts3audiobot.toml`
```toml
[bot.connect]
address = "default.com"
```
you can override it in the `Bots/<botname>/bot.toml` with 
```toml
[connect]
address = "cooldomain.xyz"
```

Same with the commands
`!settings set x y` -> `<current bot>/bot.toml`
`!settings bot set <name> x y` -> `<name>/bot.toml`
`!settings global set x y` -> `ts3audiobot.toml`

I can see why some quirks about the config might be a bit difficult to understand, and config related questions like this have been asked a few times already in the past, so I will make a wiki entry which explains everything in detail; in about two weeks when I had my last exam.

**Comment by rackieMods** [comment]
Hi, so I do have a problem with connecting multiple bots to my server. I have this directory tree:
`bots
------default
------bot1
------bot2`
and I want these bots to all connect under different names, so in each bot's directory there's bot.toml file which contains `run = true` and `name="different name"`, now after I launch the bot only default one connects, do I have to execute any commands to get 2 remaining ones working or is my configuration wrong?
