### ISSUE TITLE
Rights files for each bot

### ISSUE THREAD

**Issue by Warster** [Splamy/TS3AudioBot#612]
I suggest entering the option of downloading permissions for each instance from the new rights.toml file not only globally.

Example:
If in /Bots/default/bot.toml we do not have a fixed path to the rights.toml file in this folder then we download the global one and if it is there then it gets this from /Bots/default/rights.toml

**Comment by Splamy** [comment]
Was already suggested multiple times and is already planned.

However you can still archive per bot permissions in the current system by matching on bots. Example here: https://github.com/Splamy/TS3AudioBot/wiki/Rights#example-1

**Comment by Splamy** [comment]
Closing in favor of the tracking issue #651
