### ISSUE TITLE
Bot info with template name

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#613]
**Is your feature request related to a problem? Please describe.**
I am nearly finished with the splamy music bot interface but it work much smother if it´s possible to add a information into the api /bot/info/client. Can it be possible that the template information will be added?

Otherwise I need always send two api requests to get this simple information. (/bot/info/client and api/bot/list)

**Comment by Splamy** [comment]
You can always simply chain two requests together with `xecute` or `/json/merge`.
- `xecute` will break on the first error.
- `/json/merge` ignores errors and returns `null` for each failed subcall.

For example `/api/bot/use/0/(/xecute/(/bot/info)/(/bot/info/client))`
will return `[{first object}, {second object}]`

By the way `/bot/info` for a running bot should show the same as `/bot/list`, for that instance, so you shouldn't need `/bot/list`.


As an other example in my api I can write
```ts
const res = await bot(jmerge(
	cmd<CmdSong | null>("song"),
	cmd<CmdSongPosition>("song", "position"),
	cmd<RepeatKind>("repeat"),
	cmd<boolean>("random"),
	cmd<number>("volume"),
	cmd<CmdBotInfo>("bot", "info"),
	cmd<CmdServerTreeServer>("server", "tree"),
)).get();
```
which gets translated into
`/api/bot/use/0/(/json/merge/(/song)/(/song/position)/(/repeat)/(/random)/(/volume)/(/bot/info)/(/server/tree))`
The logic is very simple and can be done mechanically; you can look up the source here: https://github.com/Splamy/TS3AudioBot/blob/develop/WebInterface/tssrc/Api.ts that's 44 lines and most of that is just so I get intellisense for the responses

**Comment by lgund** [comment]
Ok I will try xecute. This looks like it could help a bit to make just one request.
