### ISSUE TITLE
Ts3QueryClient: Fix System.IndexOutOfRangeException on RegisterNotifications

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#616]
Hi All,

We have System.IndexOutOfRangeException when we call RegisterNotificationServer because we are trying to match the enum value to an array index.
TargetTypeString array start with 0 and so has values: 0,1,2,3,4
but enum TextMessageTargetMode has vallue 1,2,3 and enum ReasonIdentifier has value 4,5

For fix:
in Ts3QueryClient.cs

line 232:
we should replaces "TargetTypeString[(int)ReasonIdentifier.Channel]" to "TargetTypeString[((int)ReasonIdentifier.Channel) - 1]"

line 235:
we should replaces "TargetTypeString[(int)ReasonIdentifier.Server]" to "TargetTypeString[((int)ReasonIdentifier.Server) - 1]"

P.S.
I tried to make a separate branch and prepare a change request but I do not have rights :)

**Comment by Splamy** [comment]
Pushed a fix.
