### ISSUE TITLE
Ts3QueryClient: System.InvalidOperationException: 'Start may not be called on a promise-style task.'

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#617]
**Describe the bug**
When we call Ts3QueryClient.Connect we get System.InvalidOperationException: 'Start may not be called on a promise-style task.' (on line "NetworkLoop(cts.Token).Start();")
So, we will never get a function "dispatcher.Init" and "OnConnected?.Invoke"

**Expected behavior**
no exception

**To Reproduce**
call Ts3QueryClient.Connect

**Version**
last from developer branch

**Platform**
windows and debian
.NET Core 2.2

**Comment by Splamy** [comment]
Can you give me an example code snippet?

**Comment by Splamy** [comment]
Fixed
