### ISSUE TITLE
Ts3QueryClient and Teaspeak server

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#618]
Hi @Splamy

**Describe the bug**
This bug for Ts3QueryClient only, not Full client

When we connect to Teaspeak server [(https://teaspeak.de)](https://teaspeak.de) we hang
it happens because there is code:

for (int i = 0; i < 3; i++)
	tcpReader.ReadLine();

for a regular server it is actually

response from regular server (total lines: 3, second line is empty):

line 1: TS3
line 2:
line 3: Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

but response from teaspeak server (total lines: 2)

line 1: TS3
line 2: Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

Could you fix it please for query client? 

**I can suggest the following fix:**

instead of
for (int i = 0; i < 3; i++)
	tcpReader.ReadLine();

use

tcpReader.ReadLine();
if (string.IsNullOrWhiteSpace(tcpReader.ReadLine()))
	tcpReader.ReadLine();

Thanks!

**Comment by Splamy** [comment]
Do you have any teaspeak server I can connect to for testing.

**Comment by SomeSpy** [comment]
> Do you have any teaspeak server I can connect to for testing?

yes, I was sent to email splamyn@gmail.com

**Comment by Splamy** [comment]
I don't understand why Wolv has swapped the line ending just once at that position and nowhere else.
But whatever, I applied your fix suggestion
