### ISSUE TITLE
20:41:18.3748|DEBUG Falling back to youtube-dl!

### ISSUE THREAD

**Issue by Seblofs** [Splamy/TS3AudioBot#619]
When i try to start the Bot a error drops into my window:  
```
22:04:47.3355|ERROR You are running a mono version below 5.0.0!
22:04:47.3361|ERROR This version is not supported and will not work properly.
22:04:47.3361|ERROR Install the latest mono version by following http://www.mono-project.com/download/
```
I go to the Mono Site and follow the steps but it always install 3.2.4, not 5.x
How can i fix that shit?

**Comment by zmechu** [comment]
Did you follow instructions?
Mono: Get the latest version by following this tutorial and install mono-complete or mono-devel
Totorial: https://www.mono-project.com/download/stable/#download-lin
?

**Comment by Seblofs** [comment]
Sure i follow this tutorial.
I have installed Debian 8, can this make the error?

**Comment by Splamy** [comment]
I don't know *what* you followed, but I don't see any 'Debian 8' on the mono page, as debian 8 is ot supported by mono, and debian 8 itself is only in long term support mode and does not get any security updates. 

I got this snippet from the wab archive, the lastest version should be 5.18 for debian 8 which is sufficient
```bash
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
sudo apt install apt-transport-https
echo "deb https://download.mono-project.com/repo/debian stable-jessie main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
```

**Comment by Seblofs** [comment]
When i try to build my project this error cames:
```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0029	Der Typ "Nett.TomlObjectFactory.Result<Nett.TomlArray>" kann nicht implizit in "Nett.TomlObject" konvertiert werden.	TS3AudioBot(netcoreapp2.0)	D:\TS3AudioBot-develop\TS3AudioBot\Helper\TomlTools.cs	179	Aktiv
```
and not only once...

**Comment by Splamy** [comment]
Do you just want to use the bot, or do you want to develop it?
If you just want to use it I'd suggest you to download the prebuilts https://splamy.de/Nightly

**Comment by Seblofs** [comment]
i have develop it for a long time, now i will use it again, but the error came:
```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0029	Der Typ "Nett.TomlObjectFactory.Result<Nett.TomlArray>" kann nicht implizit in "Nett.TomlObject" konvertiert werden.	TS3AudioBot(netcoreapp2.0)	D:\TS3AudioBot-develop\TS3AudioBot\Helper\TomlTools.cs	179	Aktiv
```
When i try to build it

**Comment by Splamy** [comment]
Did you run `nuget restore`?

Btw, we are moving from mono/net framework to dotnet core, which means I usually suggest to use dotnet core ([develop readme](https://github.com/Splamy/TS3AudioBot/tree/develop#install)) but same here core 2.2 does not support debian 8 ...

**Comment by Seblofs** [comment]
oh this error came on visual studio 2017 not in my vserver etc

**Comment by Splamy** [comment]
Didn't your issue start with 'Cant install Mono' and 'I have installed Debian 8'; You might at least where you are trying to build...
Anyway tried Clean / Rebuild Solution ?
Btw you will need netcoreapp2.2 to build properly. Alternatively you can remove or change the target to 2.0 in both the ts3audiobot and ts3client project csproj file
(`<TargetFrameworks>net472; *netcoreapp2.2* ;netstandard2.0</TargetFrameworks>`)

**Comment by Seblofs** [comment]
I try to build with Visual Studio 2017, yes is began with it but now this is this problem :D
The crazy thing is, that i cant install this 
![image](https://user-images.githubusercontent.com/40692731/62876054-6b689880-bd24-11e9-9fea-7bfda4a06551.png) the screens blinks and 60 errors came
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	NU1202	Das Paket Microsoft.NETCore.App 2.0.0 ist nicht mit net46 (.NETFramework,Version=v4.6) kompatibel. Paket Microsoft.NETCore.App 2.0.0 unterstützt Folgendes:
  - netcoreapp (.NETCoreApp,Version=v0.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)	TS3Client	D:\TS3AudioBot-develop\TS3Client\TS3Client.csproj	1	
`
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0103	Der Name "TomlTable" ist im aktuellen Kontext nicht vorhanden.	TS3AudioBot(net46), TS3AudioBot(netcoreapp2.0), TS3AudioBot(netstandard2.0)	D:\TS3AudioBot-develop\TS3AudioBot\Config\ConfigEnumerable.cs	21	Aktiv`
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0103	Der Name "TomlTable" ist im aktuellen Kontext nicht vorhanden.	TS3AudioBot(net46), TS3AudioBot(netcoreapp2.0), TS3AudioBot(netstandard2.0)	D:\TS3AudioBot-develop\TS3AudioBot\Config\ConfigEnumerable.cs	21	Aktiv

` and much more

**Comment by Splamy** [comment]
The dotnet core library nuget packet is not the same as the dotnet core runtime.
You'll have to install that aditionally if you wan to build dotnet core apps: https://dotnet.microsoft.com/download/dotnet-core/2.2#sdk-2.2.108 (This is the latest version which still supports vs2017)

**Comment by Seblofs** [comment]
ok
at the moment i use another not self made bot
but now this error came when i try to play music videos:
17:41:12.1827|ERROR youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
and yes it is the newest

**Comment by Splamy** [comment]
the output show that the error happen because the server return an HTTP error code.

>HTTP Error 429: Too Many Requests.

as the [RFC 6585](https://tools.ietf.org/html/rfc6585):

>The 429 status code indicates that the user has sent too many requests in a given amount of time ("rate limiting").

maybe you (or your ip range) are rquesting too many videos from youtube in a short time.

**Comment by Seblofs** [comment]
ok how long does the rate limiting goes?

**Comment by Splamy** [comment]
Nope, youtube-dl and all other stuff is obviously unofficial; only youtube knows what rate limits and timeouts they have.

**Comment by Seblofs** [comment]
20:41:18.3748|DEBUG Falling back to youtube-dl!
20:41:20.2173|ERROR youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
The error dont wanted to go awy qwq

**Comment by Flakebi** [comment]
There is no way we can help you with this error. This is between you and YouTube.
See also this FAQ of youtube-dl: https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required

**Comment by Seblofs** [comment]
13:58:25.6024|DEBUG Got message from Sebl: !play [URL]https://www.youtube.com/watch?v=aCKCWiEKF8s[/URL]
13:58:25.6497|DEBUG Falling back to youtube-dl!
13:58:27.6978|DEBUG youtube-dl succeeded!
13:58:27.6988|DEBUG AudioResource start: youtube ID:aCKCWiEKF8s
13:58:27.7014| WARN parameter_invalid: the command failed to execute: invalid parameter
now the timeban is over but the bot does not play yt

**Comment by Splamy** [comment]
Which ts3ab verison are you running? And did you edit anything?
On the current develop I don't see how this error could be thrown this way.

**Comment by Seblofs** [comment]
no i dont edit smth.
what is ts3ab?
i dont know smth about that

**Comment by Flakebi** [comment]
@Seblofs could you upload the complete log here please: https://gist.github.com
The version should be printed at the beginning, also the log contains some other interesting information for us.
