### ISSUE TITLE
API overview?

### ISSUE THREAD

**Issue by lightgreenwings** [Splamy/TS3AudioBot#620]
Somewhere, Splamy posted a link to all of the API commands(, which was not the Wiki here). 
Does somebody know how this site is called or has a link?

**Comment by Splamy** [comment]
Do you have your own audiobot with webinterface running? Simply go to http://127.0.0.1:58913/openapi/index.html (You replace the ip and port with yours)

This is the one of our bot https://tab.splamy.de/openapi/index.html but it might be down sometimes

**Comment by lightgreenwings** [comment]
Thats what I was looking for. Thanks :3
