### ISSUE TITLE
HTTP Error 429: Too Many Requests | YT-DL

### ISSUE THREAD

**Issue by Warster** [Splamy/TS3AudioBot#622]
**Describe the problem**
YT-DL Error

**To Reproduce**
`!play <link>`

**System Information**
- **Platform**: Ubuntu 16.04  
  
- **Mono version**: Mono JIT compiler version 6.0.0.319 (tarball Mon Aug 12 23:46:26 UTC 2019)  
  
**Logs**

```


21:21:19.5028| WARN|0| Web error: [429] TooManyRequests
21:21:22.2809|ERROR|0| youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by Flakebi** [comment]
`HTTP Error 429: Too Many Requests` means you are hitting the rate limiting of YouTube. There is nothing we can do about this.
See also the comments starting here: https://github.com/Splamy/TS3AudioBot/issues/619#issuecomment-520481906
And the FAQ entry of youtube-dl: https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
