### ISSUE TITLE
API: bot name with space characters in name

### ISSUE THREAD

**Issue by lightgreenwings** [Splamy/TS3AudioBot#623]
Is it possible to name the bot for example "xxx - x1" with the API? 
I havn't found a possibility so far...

**Comment by WrightBlue** [comment]
`http://127.0.0.1:6969/api/bot/use/1/(/bot/name/xxx%20-%20x1`

**Comment by Splamy** [comment]
You should urlencode all parameters ([see here](https://www.w3schools.com/tags/ref_urlencode.asp)) every language should have such functions
