### ISSUE TITLE
Add song via title to playlist queue?

### ISSUE THREAD

**Issue by veroneczek** [Splamy/TS3AudioBot#625]
Hello Splamy, 

I'm a little bit frustrated when i can't add song to playlist via title, can you add command like a automatic youtube search and play but instead it will add song to a playlist queue? i mean about this command: 

https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs

**!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"**

considered solution - search for YouTube by title -> select most accurate title - add to queue first song. like in a play song by title :D

Regards..

**Comment by Flakebi** [comment]
Hm, I think there was an issue somewhere suggesting the same but I cannot find it anymore.
Anyway, we definitely want to have this, I agree that overwriting the current song is sometimes annoying :).

**Comment by Splamy** [comment]
New version is on develop. I've updated the wiki for the new commands and suggested aliases: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs
You might need to remove your previous `!ytp` with `!alias remove ytp`
