### ISSUE TITLE
ChannelData: add "channel_description" field

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#629]
Hi @Splamy 

In Developer branch: 

1. Can you add "channel_description" field to ChannelData class? (via Messages.toml)
2. Can you add "channelinfo" command (by ChannelInfoRequest parameter) to Ts3BaseFunctions class?
3. Can you add "channeledit" command to Ts3BaseFunctions class?

Thanks!

**Comment by Splamy** [comment]
The `ChannelData` you are referring to belongs to `channellist` and has no `channel_description`.
To prevent confusion i renamed the serialization objects to `ChannelInfoResponse` and `ChannelListResponse` to prevent confusion. `ChannelInfoResponse` has the `channel_description` field.

I've also added both requested commands and various other channel commands.

By the way, when you are using the full client you can get a better channel view by accessing the `Ts3FullClient.Book.Channels` dictionary. This makes `channellist` and `channelinfo` superfluous. (You have to request the channel_description manually still tho, some convenience commands are still in work)

**Comment by SomeSpy** [comment]
@Splamy many thanks!
