### ISSUE TITLE
How i add a Youtube URL to a Playlist

### ISSUE THREAD

**Issue by Nevercold** [Splamy/TS3AudioBot#630]
How i add a URL to a Playlist? 
I have /api/bot/use/$json->bottempid/(/list/add/".$link
But it comes {"ErrorCode":17,"ErrorName":"MissingContext","ErrorMessage":"Command 'CommandListAdd' missing execution context 'UserSession'","HelpMessage":"Creating UserSessions via api is currently not implemented yet."}
What is wrong?

**Comment by Splamy** [comment]
Playlist commands don't work over api, I'm currently working on it expect an update the next few days.
For updates check the tracking issue here: #227

**Comment by Nevercold** [comment]
I have one more question: I had built in Repeat, but somehow the song is not repeated

**Comment by Nevercold** [comment]
/api/bot/use/$json->bottempid/(/repeat/all

**Comment by Splamy** [comment]
repeat only works when you play playlists

**Comment by Nevercold** [comment]
And how i can set a Nickname with UTF-8 Symbols?

**Comment by Splamy** [comment]
You should urlencode all parameters ([see here](https://www.w3schools.com/tags/ref_urlencode.asp)) every language should have such functions
