### ISSUE TITLE
Cant connect to Server Version 3.10.0

### ISSUE THREAD

**Issue by cayzradio** [Splamy/TS3AudioBot#631]
**Describe the bug**
Users need at least client version 3.3.0

**To Reproduce**
Try to connect bots to the version 3.10.0 so you can see it

**Version**
I used the newest master version of the nightly bot

**Platform**
Debian 9

https://files.teamspeak-services.com/pre_releases/server/3.10.0-beta1/

**Comment by Splamy** [comment]
Fixed on dev (946f9af334d31b211fa26106c0b3b074f7345df3)
