### ISSUE TITLE
onidle 

### ISSUE THREAD

**Issue by ReapCode** [Splamy/TS3AudioBot#634]
My Config:

$requestpath = "http://Server:Port/api/json/merge/(/settings/bot/set/" . rawurlencode($RAND) . "/" . "connect.name" . "/" . rawurlencode($_POST['MusicBotName']).")/(/settings/bot/set/" . rawurlencode($RAND) . "/" . "events.onidle" . "/!yt" . $endstream .")";

Onidle wird nicht ausgeführt

**Comment by Splamy** [comment]
- Check what you write to the config file.
- Check that the idletime is set to a timespan higher than 0. 0 means disabled.
- `"/!yt" . $endstream ."` this looks like there is missing a space. if `$endstream` contains a text you will generate `!ytserachtext` which is probably not what you want...

**Comment by ReapCode** [comment]
Wir haben dein Command abgeändert und der !yt ist der !play Command
Kleine Frage: Welche Web-Api oder Rest-Api benutzt du Aktuell

**Comment by Splamy** [comment]
What do you mean with ''Welche Web-Api oder Rest-Api' ? The audiobot has only one api.

**Comment by battle03dev** [comment]
I mean. You use "OpenAPI" from Swagger.io. Why use haven't used the Swagger UI or the Server and Client from Swagger. It would be easier and more stable if you have more than 50 Bots which are all playing a song. Also the CPU goad up to 70 percent on all 8 cores with 60 Bots. Do you know why this happens?
LG Reaps Developer

**Comment by battle03dev** [comment]
I like your code and this is an suggestions

**Comment by Splamy** [comment]
@battle03dev I'm sorry, but none of us could understand your question/suggestion. Feel free to open a new issue if you have any problems or join our gitter chat (we have a german channel there if that helps).
