### ISSUE TITLE
 youtube search feature

### ISSUE THREAD

**Issue by casperkral12** [Splamy/TS3AudioBot#638]
!search dj tiesto 
song plays when we search
How can we do this feature

**Comment by Flakebi** [comment]
The last FAQ entry should answer your question: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs

**Q**: Is there a way to search for YouTube songs (`!yt`) or search and play by title (`!ytp`)?

**A**: If you just want a `!yt` and `!ytp` command, simply add those two aliases:  
`!alias add yt "!search from youtube (!param 0)"`  
`!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"`  

then you can use:  

`!yt rammstein sonne` will display the found results  
```
Found the following songs. Use "!select <number>" to play.
0: Rammstein - Sonne (Official Video)
1: Rammstein - Sonne (lyrics) HD
2: Rammstein - Sonne / PROSHOT(Download Festival 2016) HD [GER/ENG/RU/ES/FR]
   ...
```

`!ytp rammstein sonne` will search and automatically play the first result.

**Comment by casperkral12** [comment]
did as described but did not work :(

**Comment by casperkral12** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/17240216/65081872-47484900-d9ad-11e9-8f97-8f6b24273909.png)

**Comment by Splamy** [comment]
Did you change the default `!play` command or possibly renamed it to `!yt` ?
