### ISSUE TITLE
Could not convert "xx" to UInt32.

### ISSUE THREAD

**Issue by casperkral12** [Splamy/TS3AudioBot#642]
Youtube search problem
download and build the latest version
<14:02:34> "Ee!": !ytp dj tiesto
<14:02:34> "TS3AudioBot": Error: Could not convert "tiesto" to UInt32.

[commands.alias]
yt = "!search from youtube (!param 0)"
ytp = "!x (!search from youtube (!param 0)) (!select 0)"

**Comment by Flakebi** [comment]
Weird, which exact version are you using? Develop or master branch?
It works fine for me on the current develop branch, which is commit 7fb8f284.

**Comment by casperkral12** [comment]
> Weird, which exact version are you using? Develop or master branch?
> It works fine for me on the current develop branch, which is commit [7fb8f28](https://github.com/Splamy/TS3AudioBot/commit/7fb8f284e1454bb6274390f14f4f235607d23c55).

"version 0.10.0-alpha.172 | 6e729ec0"

where can I download the source code for this version

**Comment by casperkral12** [comment]
thank you
