### ISSUE TITLE
volume at 100 very quiet

### ISSUE THREAD

**Issue by battle03dev** [Splamy/TS3AudioBot#645]
I got the Develop Bot and built it.
Now I have the problem that if the bot is on volume 100, the bot sounds like it is on volume 30.

LG BattleDEV

**Comment by Splamy** [comment]
Volume seems fine for me.
Can you check that it is actually set to 100 when you ask `!volume`
Have you adjusted the client volume on your side maybe?

**Comment by battle03dev** [comment]
<16:12:55> "BattleDEV | Malcolm": !vol
<16:12:56> "AudioBot": Current volume: 100

And my client volume is standard

**Comment by battle03dev** [comment]
And its not only for my. Some of my friends said too it is so quit

**Comment by Splamy** [comment]
That's weird, does it also get linearly more quiet when you try 90, 80, ... or are there any abrupt volume changes?

**Comment by battle03dev** [comment]
No. From about 30 there is no hearable change in the volume

**Comment by battle03dev** [comment]
I testet something with adding a parameter to the ffmpeg string, that had maked the bot louder. But i dont think this is the solution. it must have a reason why the volume is so quit and other bots so loud

**Comment by Splamy** [comment]
Has anything changed? Have you tried to restart the bot? I'm really kinda out of ideas here...

**Comment by Notakas** [comment]
Could it be related to the channel's codec? Opus voice works fine for me for instance.

**Comment by Splamy** [comment]
No, the bot always sends in opus music, regardles of the channel settings and quality.
