### ISSUE TITLE
Bot description is: <YT - no title : >

### ISSUE THREAD

**Issue by Herobr1ne** [Splamy/TS3AudioBot#649]
**Describe the bug**
The Bot can´t set the right Description for many Youtube Videos (Bsp. https://www.youtube.com/watch?v=XjvjbriIDvs )

**To Reproduce**
!play https://www.youtube.com/watch?v=XjvjbriIDvs

**Version**
Version: 0.10.0-alpha.172
Branch: develop
CommitHash: 6e729ec0ae5c3440cf1af67414dc63f0b13d8653

**Platform**
Debian GNU/Linux 9
Mono JIT compiler version 6.0.0.334
Dotnet  Version:   2.2.402  Commit:    c7f2f96116

**Log**
16:45:18.6102| INFO|6| User Herobr1ne | Steven requested: !play [URL]https://www.youtube.com/watch?v=XjvjbriIDvs[/URL]

**Comment by Splamy** [comment]
Should be already fixed in `0.10.0-alpha.178`

**Comment by Herobr1ne** [comment]
Ok thank you
