### ISSUE TITLE
Play several things at the same time

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#655]
I don't know if that's possible, but if it is, it's mega. 

So my idea is that the bot can play several things at the same time, so that one user hears one thing and another something else and then the next something else and so on. 

And it would be cool if this could work with whisper and the normal voice and be controllable with plugins

**Comment by Flakebi** [comment]
Hi,
playing several things simultaneously and mixing them would be possible but this is not what you want.
Playing different music to different clients does not work unfortunately. We tried combining normal audio and whispering as you say but this only resulted in stuttering so ts does not support this.
