### ISSUE TITLE
Is it possible to define commands in variables? 

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#656]
Question is already in the title

**Comment by Splamy** [comment]
I don't understand that question

**Comment by MoroseCorpse** [comment]
I mean, if you write a plugin and declare command there, whether you have to do it so that the command is in the code or if you can do it with a variable, so that the user can determine the command by himself

Example:

Is that obligatory:
```
[Command("open")]
public void opencommand(InvokerData client, String optional = null)
```

Or can I do something like that:
```
string command = "open"
[Command(command)]
public void opencommand(InvokerData client, String optional = null)
```
I know this doesn't work in this version, but is there another way to do it?

**Comment by Bluscream** [comment]
pretty sure attributes have to be compile-time constants. not sure if there's a alternate way of defining a command that's more dynamic tho

**Comment by MoroseCorpse** [comment]
Ok, if it really doesn't work, then I would like to suggest this as an update :D

**Comment by Splamy** [comment]
You will have to get the `CommandManager` and manually add it with `RegisterCollection`
See here for an example on how to create a bag https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/MainCommands.cs#L47-L53
