### ISSUE TITLE
Old versions

### ISSUE THREAD

**Issue by x-Scripts** [Splamy/TS3AudioBot#657]
Hello, can you download earlier versions of the bot?

**Comment by Splamy** [comment]
The nightly server does not save older versions.
You will have to git clone and manually compile it.
- `git clone https://github.com/Splamy/TS3AudioBot.git`
- `git checkout <hash>`
- then proceed with the installation steps from the readme (they are always included in the repo)

**Comment by x-Scripts** [comment]
Hello, you can specify how you can download the develop alpha 162 version by the git command because I don't know anything about it

**Comment by Splamy** [comment]
`git clone https://github.com/Splamy/TS3AudioBot.git`
`git checkout d72e8f73`

Any particular reason why you are switching back?

**Comment by x-Scripts** [comment]
I get this error: fatal: Not a git repository (or any of the parent directories): .git
The new version has no command! List get and I create a panel for it and that users can use this command so that they do not save the loaded list

**Comment by Splamy** [comment]
You didn't download the repo with git clone, if you get that error message (or you are in the wrong folder with your shell)

also the command just has been renamed to `!list import`, but yeah, you will need to temporarily save the list

**Comment by x-Scripts** [comment]
I downloaded via git clone and I am creating a TS3AudioBot folder right away

**Comment by x-Scripts** [comment]
Issue resolved until closing

**Comment by Splamy** [comment]
> Issue resolved until closing

What do you mean by that?
