### ISSUE TITLE
Bot trying to reconnect

### ISSUE THREAD

**Issue by KoLuBa** [Splamy/TS3AudioBot#658]
Hello,

Bot is constantly trying to connect and fails.
I use nat vps if that has any reason

https://pastebin.com/CL97RvMx

**Comment by Splamy** [comment]
Seems like your firewall/vpn is blocking the packets. The init packet isn't going through

**Comment by KoLuBa** [comment]
Do you have any idea how to fix this?

**Comment by Splamy** [comment]
Nope, I don't have any insight into your system/network. You'll have to try to google your setup and symptoms

**Comment by KoLuBa** [comment]
I changed from ip to localhost and it works normally
