### ISSUE TITLE
AudioBot only playing to channel not users

### ISSUE THREAD

**Issue by Camando** [Splamy/TS3AudioBot#66]
When i'm in say an AFK channel and send a pm to the audio bot to play a file.  It plays to all users in the channel i'm active in.  if i use !pm to start a private session and then !play a file.  It still happens.  Is there a fix for this?

**Comment by Splamy** [comment]
There is an issue which pretty much sums up why it's behaving like that:
https://github.com/Splamy/TS3AudioBot/issues/62

But I will change it soon.
