### ISSUE TITLE
Youtube-dl HTTP Error 429

### ISSUE THREAD

**Issue by KoLuBa** [Splamy/TS3AudioBot#660]
Where can I find yours !Play command or or the line where you call youtube-dl?
I need to add '-4' argument to fix http error for youtube

Sorry for the bad English

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/ResourceFactories/YoutubeDlHelper.cs#L37

**Comment by KoLuBa** [comment]
Can you compile with this pls i have 4 errors  "string param = $"--no-warnings --get-title --get-url --format bestaudio/best -4 --id -- {id}";"
