### ISSUE TITLE
Ts3FullClient.ChannelList strange issue

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#661]
Hi @Splamy 

I am writing a plugin (using the developer's branch) and I want to get a list of channels, and I found a strange issue:

**Case 1: Ts3FullClient with regular TS server (not TeaServer)**
I call _ts3FullClient.ChannelList(ChannelListOptions.topic) - **is OK**

**Case 2: Ts3FullClient and TeaServer(https://github.com/TeaSpeak/TeaSpeak)**
I call _ts3FullClient.ChannelList(ChannelListOptions.topic) - **I get error:  error id=2 msg=not\simplemented**

Log: 

> 2019-10-24 21:21:10.4350|DEBUG||Ts3FullClient.SendCommandBase [O] channellist return_code=12 -topic
2019-10-24 21:21:10.4350|DEBUG||PacketHandler`2.SendOutgoingData [O] Type: Command	Flags: [ _ N _ _ ]	Id: 14
  MAC: 00 00 00 00 00 00 00 00 	  Header: 00 00 00 00 00 
  Data: 63 68 61 6E 6E 65 6C 6C 69 73 74 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 31 32 20 2D 74 6F 70 69 63 
2019-10-24 21:21:10.4876|DEBUG|0|PacketHandler`2.FetchPackets [I] Acking: 14
2019-10-24 21:21:10.4876|DEBUG|0|PacketHandler`2.UpdateRto RTT SRTT:00:00:00.1164532 RTTVAR:00:00:00.1104365 RTO:00:00:00.5581992
2019-10-24 21:21:10.4876|DEBUG|0|PacketHandler`2.FetchPackets [I] Type: Command	Flags: [ _ _ C _ ]	Id: 118
  MAC: 8C 10 61 71 CE 17 B5 46 	  Header: 00 76 42 
  Data: 44 31 2E 65 72 72 6F 72 20 69 64 3D 32 20 6D 73 67 3D 6E 6F 74 5C 73 69 6D 70 6C 65 6D 65 6E 74 65 64 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 31 32 
2019-10-24 21:21:10.4876|DEBUG|0|PacketHandler`2.SendOutgoingData [O] Acking Ack: 118
2019-10-24 21:21:10.4876|DEBUG|0|Ts3FullClient.PacketEvent [I] error id=2 msg=not\simplemented return_code=12

Also I check query client:

**Case 3: Ts3QueryClient and any teamspeak server (regular or TeaServer)**
I call _ts3QueryClient.ChannelList(ChannelListOptions.topic) - **is OK**

I do not know if this is a bot issue or a TeaServer issue?

@Splamy Could you take a look at this?

**Comment by MoroseCorpse** [comment]
I have another error with the command channellist. If I do the following:

````
var channellist = FullClient.Send<ChannelData>("channellist", new CommandOption(ChannelListOptions.topic)).Value;
foreach (var channel in channellist)
{
       Logger.Info(channel.Id);
}
````
then the channel.Id is always 0

I use this version: 0.10.0-alpha.186/develop/e4725752

**Comment by Bluscream** [comment]
It's a teaspesk issue @SomeSpy

**Comment by Splamy** [comment]
@SomeSpy The developer of TeaSpeak decided to not implement the query only commands into the full protocol; which the normal server for some reason still accepts. The normal client isn't using them anyway.
I'd suggest you to use the `FullClient.Book` instead. It basically just does what the normal client does and tracks all commands. `FullClient.Book.Channel` will also be basically free as you don't have to make a request to the server for that.

@MoroseCorpse Yep, there's an error in our packet declaration. Until it's fixed you can call it like in your second example, but add the topic option:
`FullClient.Send("channellist", new CommandOption(ChannelListOptions.topic)).Value`

**Comment by MoroseCorpse** [comment]
Ok, thank you

**Comment by Bluscream** [comment]
Does book work yet?

**Comment by Splamy** [comment]
yes, since quite a while already

**Comment by Bluscream** [comment]
Can you give a example how to get the channellist and do smth with it there?

**Comment by Splamy** [comment]
`FullClient.Book.Channel` is an array of all channels, all information are updated live in ther; that's it.

**Comment by Bluscream** [comment]
Ohh, neato. Do changes made locally to that also affect it?

So `foreach (channel in FullClient.Book.Channels) channel.Name = "Test";`

**Comment by Splamy** [comment]
Not yet; right now it only works in the server -> client direction

**Comment by SomeSpy** [comment]
@Splamy thanks! I'll try it a bit later...
