### ISSUE TITLE
Ich kann keine Streams mehr abspielen

### ISSUE THREAD

**Issue by Onyxzium** [Splamy/TS3AudioBot#662]
**Describe the bug**
Seit dem Update kann ich keine ILoveRadios Streams mehr spielen vorher ging es über !play jetzt geht es nicht mehr sowie funktionieren die erweiterten !help Teile funktionieren auch nicht

**Version**
Neuste

**Platform**
debian-9

**Log**
```
https://www.mediafire.com/file/98t630fft190bl5/ts3audiobot.log/file
```

**Comment by Splamy** [comment]
`!stream add` is not a real command. Also I can play the streams just fine use `!add` or `!play`
The streams a running just fine on my bot; check your network/firewall etc.
