### ISSUE TITLE
Bot Create Deactivation

### ISSUE THREAD

**Issue by Onyxzium** [Splamy/TS3AudioBot#663]
**Is your feature request related to a problem? Please describe.**
Hey! Ich würde mir wünschen wenn man das "Bot erstellen" im Webinterface deaktivieren könnte

**Comment by Splamy** [comment]
Configure your permission file to not give the `cmd.settings.create` and `cmd.bot.save` to the user. (also `cmd.bot.connect.to` to not create temporary bots)

**Comment by Onyxzium** [comment]
Ehm, könnte ich alle Permissions bekommen (Eine Liste) damit ich das richtig einstellen kann damit ich auch den Bot einstellen kann

**Comment by Onyxzium** [comment]
Oder kann ich einzelne Permissions entfernen obwohl ich * benutze

**Comment by Splamy** [comment]
Each command corresponds to a permission like `!bot name` = `cmd.bot.name`.
Yes, you can also remove permissions within a group with 
```toml
[[rule]]
   "+"="*"
    "-"=["cmd.bot.save", ...]

**Comment by Onyxzium** [comment]
Kann ich auch irgendwo die maximalen Instanzen einstellen,
sowie wäre ein Online "ts3audiobot.tmol" Editor nice

**Comment by Splamy** [comment]
> Kann ich auch irgendwo die maximalen Instanzen einstellen,

No, not possible.

> sowie wäre ein Online "ts3audiobot.tmol" Editor nice

most bot settings can already be configured in the web. More will come over time, when I get to implement them.
