### ISSUE TITLE
General Question: ts3audiobot.db

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#665]
Hey. Can you tell me, for what the ts3audiobot.db is for?
Can you tell me all functions, from the bot where the db file is needed. Is it possible to deactivate the file?
This issue isn't important but i want to learn something about db file.
Thanks :-)

**Comment by Splamy** [comment]
Right now, auth tokens and history.
But I want to use it for a few other settings in the future, like tracking previous version and making updates based on that.

Also, no, you can't disable the file.

**Comment by marv-th** [comment]
Okay. Thanks for this information.
