### ISSUE TITLE
Bot stops playing music after some time

### ISSUE THREAD

**Issue by RageTimmy** [Splamy/TS3AudioBot#666]
**Describe the bug**
After some time the ts3audiobot stops playing music. Is this a simple configuration error or a bug? The onidle event is empty.

**To Reproduce**
/

**Version**
Latest Develop Version at Oct 15, 2019 from splamy.de/nightly

**Platform**
Ubuntu 18.04 with Dotnet core

**Log**
I searched the log for error details, but i could not find anything according to the problem.

**Comment by Splamy** [comment]
Can you give an example what you are playing? Like youtube songs, radio streams, etc ?

**Comment by RageTimmy** [comment]
Radio Stream, e.g. https://listen.reyfm.de/original_192kbps.mp3

**Comment by Splamy** [comment]
Set `!repeat one` and it will automatically restart
