### ISSUE TITLE
Remove this message

### ISSUE THREAD

**Issue by Simon1509** [Splamy/TS3AudioBot#668]
I have changed the Help massage but now this is coming:                                                
TS3AudioBot1": add, alias, api, bot, clear, command, eval, from, getmy, getuser, help, history, if, info, json, kickme, list, next, param, pause, play, plugin, pm, previous, print, quiz, random, repeat, rights, rng, search, seek, server, settings, song, stop, subscribe, system, take, unsubscribe, version, volume, whisper, xecute

How i can remove this Message

**Comment by Splamy** [comment]
You are running an old version. This text has been moved to `help command`. So get the latest version then change it.

**Comment by Simon1509** [comment]
I have the latest version but yes

**Comment by Splamy** [comment]
But this text never gets printed on `!help`

**Comment by Simon1509** [comment]
sry !help all

**Comment by Splamy** [comment]
It's just below the other

**Comment by Simon1509** [comment]
What i must change

**Comment by Splamy** [comment]
just delete it

**Comment by Simon1509** [comment]
i already did it but the command not removed

**Comment by Simon1509** [comment]
I must remove more code ? or only this https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainCommands.cs#L413-L425 ?

**Comment by Bluscream** [comment]
Lukas warum hilfst du solchen leuten überhaupt noch? Issue close + ban from repo feddich

**Comment by Simon1509** [comment]
wieso

**Comment by Simon1509** [comment]
Habe grad gemerkt das ich den Falschen code gelöscht hatte sry
