### ISSUE TITLE
Playlists from youtube and add perm by command

### ISSUE THREAD

**Issue by ElPolako** [Splamy/TS3AudioBot#669]
Hello, does it possible to play playlists from youtube?
!help doesn't help at all, wiki on github is not updated, most playlists command is unknown for me,
and there is second question, does it possible to add play song rights to specific client via command to bot?

**Comment by Splamy** [comment]
`!list import <name> <url>` then `!list play <name>` to download and play any supported playlist type like youtube.
I'll try to update the wiki shortly.
Rights via cmd/api is planned but work hasn't started on it yet. The tracking issue for that is here: 651
