### ISSUE TITLE
Problem mit Webinterface

### ISSUE THREAD

**Issue by Thilo187Strassenschande** [Splamy/TS3AudioBot#671]
Wenn ich das Webinterface aufsetzt kommt die Meldung das es gestartet ist so weit so gut aber wenn ich auf die website gehe ist bloß ein weißes Bild und oben steht sogar TS3AudioBot das kann glaube nicht stimmen bitte um hilfe

**Comment by Splamy** [comment]
1. Issues in english please
2. Some more information (Use our issue template), like version, log, maybe your file structure in this case, browser console log, network tab log, anything ...
