### ISSUE TITLE
!bot come didn't (?) work

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#673]
Old version (0.9.1/master/bf376396) works fine. Command "!bot come" results with bot comes into user's channel.

New version (0.11.0-alpha.24/develop/adbdd1b8) with user's command "!bot come" results with "Error: No target channel found."

Configuration file moved from 0.9.1 int 0.11.0, so it seems to kind of configuration error - where to find source of problems? :-)

Regards!

**Comment by Splamy** [comment]
Yeah lol, I messed that up (7e07520272c24ef426df9f5ddda4d92ed7170b48), is fixed on dev
