### ISSUE TITLE
"Watching channels" feature

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#677]
Draft idea:
1. Bot is configured. 
2. There is new config option, for example "channel_to_watch=/100"
3. Where this channel (100) is empty, bot is disconnected and "watching" presence of clients there
4. When someone enter channel 100, bot connects and serve
5. When channel is empty, bot disconnects and and starts "watching" channel 

Too much hardcore? :-)

**Comment by Splamy** [comment]
How should the bot 'watch' a channel if it is not connected?

**Comment by GiliceJani** [comment]
> How should the bot 'watch' a channel if it is not connected?

Query maybe? idk

**Comment by 07artem132** [comment]
> > How should the bot 'watch' a channel if it is not connected?
> 
> Query maybe? idk
Perhaps you mean this:  https://github.com/Splamy/TS3AudioBot/issues/278

**Comment by Flakebi** [comment]
Hi @zmechu,
I understand what you want to do, but not why.
Do you want to reduce CPU load? An idling bot should not use much CPU anyway, at least not more than a query client.
Do you want to reduce the number of clients/occupied slots on the server? This would be more interesting.

**Comment by Bluscream** [comment]
>  Do you want to reduce the number of clients/occupied slots on the server? This would be more interesting.

That's most likely the case. I would suggest him to keep 1 bot connected at all times and let him watch the channels with a plugin and connect the others when there's someone in them

**Comment by zmechu** [comment]
First - reduce slots occupied by bots. There is no needs to keep, for example, 10 bots connected when nobody uses them. Bot will connect - kind of - "on demand". Where is no one on "watched" channel (or servergroup, or section) bot is disconnected, and automatically connects when someone join channel (or section, or from selected servergroup).

Also, it will reduce CPU/memory load, when unused bots "sleeps".

I don't know if it is possible. Maybe one musicbot "always online" and watching channels/groups and give other bots on orders to connect/disconnect?

**Comment by Bluscream** [comment]
> I don't know if it is possible. Maybe one musicbot "always online" and watching channels/groups and give other bots on orders to connect/disconnect?

I made plugins for that once (would have to be updated)

- https://github.com/Bluscream/TS3AudioBotPlugins/tree/develop/BotAutoStart
- https://github.com/Bluscream/TS3AudioBotPlugins/tree/develop/BotAutoStartQuery

**Comment by zmechu** [comment]
> 
> 
> > I don't know if it is possible. Maybe one musicbot "always online" and watching channels/groups and give other bots on orders to connect/disconnect?
> 
> I made plugins for something similar once
> 
>     * https://github.com/Bluscream/TS3AudioBotPlugins/blob/master/BotAutoStart/Plugin.cs#L99

Could you shortly describe what this plugin do and how to use/configure it?
