### ISSUE TITLE
Change Client Version

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#68]
Have a config value like `MainBot::Version=1.3.1` Which would need a ```ts3client::getVersionHash(string formattedVersion)``` function. Ideally you have a enum for `versionHash|versionBuild|formattedVersion` and functions to convert between them.

**Comment by Bluscream** [comment]
I found `public VersionSign VersionSign { get; set; } = VersionSign.VER_WIN_3_1;` in the ConnectionData.cs and would like to request this getting parsed from the config somehow :3

**Comment by Splamy** [comment]
Not really useful, but why not. I will add it to the backlog
