### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by RealPwned** [Splamy/TS3AudioBot#682]
Hello,
i installed the TS3AudioBot on Debian 9 and now
im here (https://prnt.sc/pylcvo) and dont know what to do.
Can someone help?

Thanks!

**Comment by Flakebi** [comment]
Write `!api token` to the bot on a TS server and paste the response into the login field.
This allows you to control the bot via the website.

**Comment by RealPwned** [comment]
Thank you!

**Comment by rgk11** [comment]
"TS3AudioBot": Error: You cannot execute 'api token'. You are missing the 'cmd.api.token' right!



help me

**Comment by Flakebi** [comment]
You need to configure permissions in the `rights.toml` file. E.g. add an admin group you are in or allow `cmd.api.token` for everyone.

**Comment by ghost** [comment]
> You need to configure permissions in the `rights.toml` file. E.g. add an admin group you are in or allow `cmd.api.token` for everyone.

how to set?  i dont know
