### ISSUE TITLE
List of commands removed from wiki

### ISSUE THREAD

**Issue by punsii** [Splamy/TS3AudioBot#685]
The [latest revision](https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem/9e7e5373766326be0bf078e16bf9be4a548a1bff) of the wiki page for the CommandSystem removed the list of available commands and now only links to the [WebAPI](https://github.com/Splamy/TS3AudioBot/wiki/WebAPI) wiki page. The WebAPI page however only refers back to the 'Existing commands' section and I could not find another page where the list might have moved to.

**Version**
[https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem/9e7e5373766326be0bf078e16bf9be4a548a1bff](https://github.com/Splamy/TS3AudioBot/wiki/CommandSystem/9e7e5373766326be0bf078e16bf9be4a548a1bff)

**Comment by Splamy** [comment]
I've updated both wiki pages
