### ISSUE TITLE
The bot stops playing my stream if the stream restart

### ISSUE THREAD

**Issue by JonaxGames** [Splamy/TS3AudioBot#686]
Hi,

im playling my favorite livestream on my bot, but the stream provider often restarts his stream and then the bot stops playing. How can i stop this? Is there any loop option to play the stream every time?

Greetings Jonax

**Comment by bennetgallein** [comment]
`events.onidle` in the bot config. There you can execute a command.
`events.idletime` is time time in minutes the bot has to idle before the command gets executed

**Comment by Flakebi** [comment]
As mentioned in #666, you can also set `!repeat one` and it will automatically restart the stream.
