### ISSUE TITLE
Stream Stopss after some hours / Play on Idle function ?

### ISSUE THREAD

**Issue by RealPwned** [Splamy/TS3AudioBot#687]
Is there a function, like Sinusbot "Play on Idle". After some hours the Bots stop playing music.

Thanks!

**Comment by bennetgallein** [comment]
`events.onidle` in the bot config. There you can execute a command.
`events.idletime` is time time in minutes the bot has to idle before the command gets executed

**Comment by Flakebi** [comment]
As mentioned in #666, you can also set `!repeat one` and it will automatically restart the stream.
Also, this issue sounds a lot like #686.
