### ISSUE TITLE
TS3Audiobot can't build in VS

### ISSUE THREAD

**Issue by DustinHinze** [Splamy/TS3AudioBot#688]
Hello,

My problem is that when I press "Create Bot" or "Start" the bot does not create itself in the specified folder (TS3Audiobot/bin/Debug/..).

I just reconfigured a few things in ConfigStructs.cs.

My system is Windows 10 Home and I used Visual Studio 2019 (v16.3.10).
  
  
Visual Studio Error (German): [prntscr.com/q1962k](https://prntscr.com/q1962k)

I hope I can be helped. (:

**Comment by Splamy** [comment]
You can remove the `GitVersionTask` nuget package from the Ts3AudioBot project, then this error won't come anymore
https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#uninstalling-a-package
