### ISSUE TITLE
plugin problem

### ISSUE THREAD

**Issue by 9ofe** [Splamy/TS3AudioBot#691]
**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
Steps to reproduce the behavior

**System Information**
- **Platform**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **Mono version**: (`mono -V`)  
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by 9ofe** [comment]
so i used this plugin https://github.com/9ofe/autofollow

but when i do !plugin list
it says on the terminal 

`14:06:56.5288| INFO|0| User !                         9ofe requested: !plugin list
14:06:56.6799| WARN|0| Right "cmd.list.save" is not registered.
14:07:00.2780| WARN|0| Plugin "Plugin.cs" [0] compiler notifications:
Error L11/C6: The type or namespace name 'TS3Client' could not be found (are you missing a using directive or an assembly reference?)
Error L12/C6: The type or namespace name 'TS3Client' could not be found (are you missing a using directive or an assembly reference?)
Error L13/C6: The type or namespace name 'TS3Client' could not be found (are you missing a using directive or an assembly reference?)
Error L14/C6: The type or namespace name 'TS3Client' could not be found (are you missing a using directive or an assembly reference?)
Error L15/C6: The type or namespace name 'IniParser' could not be found (are you missing a using directive or an assembly reference?)
Error L16/C6: The type or namespace name 'IniParser' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Flakebi** [comment]
On the develop branch, the library `TS3Client` was renamed to to `TSLib` in eba64d4. Also, `Ts3FullClient` got renamed to `TsFullClient`.
The **class** `TS3Client` is part of the audio bot project and was not (yet) renamed, it stays the same.
If you rename them in your plugin, it should work again.

By the way, the issue template is there for you to fill out the requested information.
