### ISSUE TITLE
Consistent youtube-dl error

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#693]
Hello

I always get youtube-dl error on my servers. I've tried different locations I changed the rope address. After a while, I start to get this error again. Is there no definitive solution to this error?

Is it possible to extract Youtube data from another site? If this happens, maybe we won't get the youtube-dl error again.

For example : www.asd.com We will build an infrastructure for the site When we open a song from the music bot, www.asd.com will get the song from youtube and open it

VDS O.S : ubuntu 16

**Comment by heartles39** [comment]
Youtube-dl version : 28.11.2019

**Comment by Flakebi** [comment]
Which error do you get?
If it is `429 Too Many Requests`, you hit the rate limiting of YouTube.
See this faq entry for more info: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#429-too-many-requests

**Comment by heartles39** [comment]
> Which error do you get?
> If it is `429 Too Many Requests`, you hit the rate limiting of YouTube.
> See this faq entry for more info: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#429-too-many-requests

Error: Yüklenemedi. (youtube-dl failed to load the resource.)


I don't think there's a limit. On a different Vps. 15 AudioBot is installed and I haven't received this error for 20 days. Today I installed vps in france and now I get this error I tried this location in Germany again I got this error

**Comment by Splamy** [comment]
try `youtube-dl <url>` in your console, it will show you the youtube-dl error directly.
Often youtube blocks some ip's / regionlocks some videos. In that case we can't do anything

**Comment by heartles39** [comment]
> try `youtube-dl <url>` in your console, it will show you the youtube-dl error directly.
> Often youtube blocks some ip's / regionlocks some videos. In that case we can't do anything

What's a console? SSH?

**Comment by heartles39** [comment]
There's a funny situation. Problem solved for now. I still get this error on another server

SSH Output

root@ubuntu:~# youtube-dl https://www.youtube.com/watch?v=pCLbQVGo5bo
[youtube] pCLbQVGo5bo: Downloading webpage
[youtube] pCLbQVGo5bo: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: pCLbQVGo5bo: YouTube said: Unable to extract video data

This server has been giving an error for 5 days.
