### ISSUE TITLE
CentOS 7 youtube dl

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#694]
**Describe the bug**
I´ve problems using the bot on CentOS 7. Every song I wanna play fail with the message `Fehler: Konnte nicht geladen werden. (youtube: Youtube-dl konnte nicht gefunden werden. Der Song/Video kann aufgrund von Einschränkungen nicht wiedergegeben werden.)`. I am not sure why this happen youtube dl is installed with the version `2019.11.28`.

Currently I cant play no youtube links via the bot.

**Version**
Which commit did you build or download?
dotnet 3.0.101 (bot is currently running on the system)
mono 6.6.0.167 (just installed)

**Platform**
CentOS 7

**Log**
```
youtube-dl www.youtube.com/watch?v=6zTc2hD2npA
WARNING: The url doesn't specify the protocol, trying with http
[youtube] 6zTc2hD2npA: Downloading webpage
[youtube] 6zTc2hD2npA: Downloading video info webpage
[youtube] 6zTc2hD2npA: Downloading js player vflBn9SNT
[youtube] 6zTc2hD2npA: Downloading js player vflBn9SNT
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Pirates of the Caribbean (Auckland Symphony Orchestra) 1080p-6zTc2hD2npA.f137.mp4
[download] 100% of 158.21MiB in 00:09
[download] Destination: Pirates of the Caribbean (Auckland Symphony Orchestra) 1080p-6zTc2hD2npA.f251.webm
[download] 100% of 6.59MiB in 00:00
[ffmpeg] Merging formats into "Pirates of the Caribbean (Auckland Symphony Orchestra) 1080p-6zTc2hD2npA.mkv"
Deleting original file Pirates of the Caribbean (Auckland Symphony Orchestra) 1080p-6zTc2hD2npA.f137.mp4 (pass -k to keep)
Deleting original file Pirates of the Caribbean (Auckland Symphony Orchestra) 1080p-6zTc2hD2npA.f251.webm (pass -k to keep)
```

The Bot has no errors. But here you can see that the youtube-dl works.

**Comment by Splamy** [comment]
> Youtube-dl konnte nicht gefunden werden

this message indicates not that youtube-dl could not resolve the song, but that the bot could not find the youtube-dl binary/project to run.
Check your `tools.youtube-dl.path` entry.
If you leave it empty the bot will check the default installation path `/usr/local/bin/youtube-dl`, otherwise you'll have to specify it.
I don't think the bot will find it if it is in PATH only. You can find the binary location with `which youtube-dl` and set this path in the config.
