### ISSUE TITLE
dns fehler

### ISSUE THREAD

**Issue by noawinzp** [Splamy/TS3AudioBot#701]
**Version**
last master

**Platform**
linux

**Log**
Socket forcibly closed when checking 'ts.nxtbots.de', reason One or more errors occurred. (Connection refused)

and a lot of teamspeak mistakes

**question**
Since my English is really kake and I work with a translator please answer in German and English

**Comment by Splamy** [comment]
Seems to work on my pc. Check that you are maybe not blocked or can reach the ip. (`ping ts.nxtbots.de`)
You should also make sure that your firewall is not blocking access to the dns servers. The bot by default uses google, cloudflare, opendns and freenom iirc
