### ISSUE TITLE
About Youtube copyright

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#702]
Hello

I install music bots without problems but after a while I get Youtube-dl error. I searched and this error was due to youtube copyright. Is there a way to overcome this error? I don't want to change the ip address. Because it's the same again. Do you know a site that will run the !search command?

VDS OS : Ubuntu 16 64 Bit

**Comment by Splamy** [comment]
As far as I know there is no way of bypassing region blocked content in youtube other than with a proxy.
I'm planning to add more streaming options in future, but there's nothing I can do with youtube about that
