### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by x-Scripts** [Splamy/TS3AudioBot#704]
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". [/opt/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj]

help?

**Comment by Splamy** [comment]
Since this has been asked so many times already I added an FAQ:
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#gitversiontask
