### ISSUE TITLE
Timeouts 

### ISSUE THREAD

**Issue by officialLucas** [Splamy/TS3AudioBot#705]
Guten Mittag,

ich habe momentan das Problem, dass alle meine Musikbots auf allen TeamSpeak-Servern auf welchen sie drauf sind immer kurz austimen, aber nach 30 Sekunden wieder erscheinen. 
Ich nutze die TS3AudioBot Version 0.10.1+2 .
Auf meinem Server laufen ca. 47 Musikbots.

Wie kann ich das Problem beheben, dass die Musikbots die ganze Zeit austimen?

Mit freundlichen Grüßen
Lucas

--------------------

Good afternoon,

I currently have the problem that all my music bots on all TeamSpeak servers on which they are on are always briefly timed out, but reappear after 30 seconds.
I use the TS3AudioBot version 0.10.1 + 2.
There are about 47 music bot running on my server.

How can I fix the problem that the music bots are timing out all the time?

Sincerely yours
Lucas

**Comment by Splamy** [comment]
The description is pretty vague so I can't really give you any specific help.
Usually a bot times out when a packet is sent which doensn't get acknowledged by the server (30 seconds is the default for the TSAB, normal TS3 servers time a client out faster if a packet is missing)
You might want to check if your firewall is doing anything weird (mostly looking for outgoing packets again here)
For this you can enable the detailed packet logging output (see [here](https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting#more-logs) how to; only the 'TS3Client related logs', )
*Careful*: This produces *a lot* of output, so dont leave it running for too long.
If some packes really get lost/blocked there will be some warning like 'RESEND' multiple times, try to look for those and post those log parts here.
