### ISSUE TITLE
Bot flooding when it playing

### ISSUE THREAD

**Issue by Mentisekk** [Splamy/TS3AudioBot#707]
When Bot plays music it starts to flooding.
(WARN|0|Util.UnwrapToLog Unknown Teamspeak Error. (client is flooding)
Can it be changed somehow?
I will add that the bot is not on my server and I have no way to give it antyflood

Sorry for my English.

**Comment by Splamy** [comment]
Currently there are no features to prevent antiflood.A few users already have requested something like this (or in a similar way)
I'm planning to add some rate limiting options (In both ways, User -> TSAB and TSAB -> Server), but currently there are other things on top of my todo list.
