### ISSUE TITLE
Failed to load library "libopus".

### ISSUE THREAD

**Issue by RealPwned** [Splamy/TS3AudioBot#708]
Hey,
when i run "dotnet TS3AudioBot.dll" i'll get this error. Anyone know a solution?

root@RealPwned:/home/TS3AudioBot v.0.11.0-alpha.32# dotnet TS3AudioBot.dll
16:08:16.2152|ERROR|| Failed to load library "libopus".
16:08:16.3420|ERROR|| Couldn't find libopus. Make sure it is installed or placed in the correct folder.

**Comment by teol** [comment]
Hi,

Sorry for bumping this issue but I'm trying to run it on Debian 10, after having installed all the dependencies, and dotnet core 2.2 (also tried with dotnet core 3.1).

I always have the same error:
"Failed to load library "libopus"."

But the libopus in already installed:
libopus-dev is already the newest version (1.3-1).

I tried multiple versions from "master" and "develop" but on develop it seems to require the dotnet SDK and not just the core.

So what am I missing here?

Thanks

**Comment by Flakebi** [comment]
Works fine for me.
I installed the audiobot (develop version for dotnet core 3.1), the listed dependencies (`sudo apt-get install libopus-dev ffmpeg`) and dotnet core 3.1 in a fresh debian docker container and it played songs correctly.
Maybe try downloading the bot again into a new directory.

If it still doesn’t work, please create a new issue. Comments on already closed issues will easily get lost.

**Comment by vc221b** [comment]
can you install the vc++ redistributable 2015 for x64: https://www.microsoft.com/en-us/download/details.aspx?id=48145
