### ISSUE TITLE
FFMPEG Binary in README is not working

### ISSUE THREAD

**Issue by CookieCr2nk** [Splamy/TS3AudioBot#710]
**Describe the bug**
In the Readme the FFMPEG 64Bit link is respond with a 404 not found.
https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz

The 32Bit variant is working fine.
https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-latest-win32-static.zip
Can you replace this link?

**To Reproduce**
Go to https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz

**Version**
It doesnt matter

**Platform**
It doesnt matter

**Log**
```
Page not found
```

**Comment by Flakebi** [comment]
Thanks for the heads up, the ffmpeg links for Linux should be working again.
