### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by DustinHinze** [Splamy/TS3AudioBot#715]
Good afternoon,

i have a problem or i don't know if it is the server or the TS3Audiobot. It is a clean instance where nothing has been changed in the code.

Error:

14:39:33.4423| WARN|| Socket forcibly closed when checking 'domain.de', reason One or more errors occurred. (Connection refused ip_adress)

Thanks for the help in advance!

**Comment by Flakebi** [comment]
Hi,
please tell us the version of the bot you are using, this makes it a lot easier to provide help.

The warning originates in the DNS resolving code, however it looks very weird.
I cannot find the error message anywhere, also `adress` should be written address in english, this is strange.

So, I don’t really have an idea how to debug this.
Anyway as this is DNS related, can you try out `host domain.de`?
And if you have `dig` installed, `dig domain.de @8.8.8.8` (uses Google DNS)?

**Comment by BastiGER** [comment]
Problem also here, might the upgrade of many servers to the TS3 version 3.10.2 makes this problem?

**Comment by Flakebi** [comment]
@BastiGER Can you provide more information please? The address of the server that is not working would be helpful.

**Comment by Splamy** [comment]
Last time I checked connecting to 3.10.x worked just fine.
Also which version are you running?
Make sure it's at least at up to date master-ver.
