### ISSUE TITLE
ChannelOp: incorrect order of arguments

### ISSUE THREAD

**Issue by SomeSpy** [Splamy/TS3AudioBot#718]
Hi @Splamy , 
I found a mismatch between the arguments sent and accepted
when you call ChannelOp you have mixed up the order of arguments
please see attchments

![channelop](https://user-images.githubusercontent.com/9878728/72680011-5ad7fd80-3ace-11ea-9ece-19a208b18831.jpg)
![incorrect3](https://user-images.githubusercontent.com/9878728/72680013-5f041b00-3ace-11ea-966d-b44c41db63d4.jpg)
![incorrect2](https://user-images.githubusercontent.com/9878728/72680014-5f041b00-3ace-11ea-89ac-a64bfa5c4170.jpg)
![incorrect1](https://user-images.githubusercontent.com/9878728/72680016-5f9cb180-3ace-11ea-9d1d-8eec158e40a4.jpg)

**Comment by Splamy** [comment]
Nice catch, I pushed a fix
