### ISSUE TITLE
TooManyRequests

### ISSUE THREAD

**Issue by Heisz457** [Splamy/TS3AudioBot#724]
22:06:11.1990| WARN|5| Web error: [429] TooManyRequests
22:06:12.6034|ERROR|5| youtube-dl failed to load the resource:
ERROR: Kwdhzk0tGiM: YouTube said: Unable to extract video data

**Comment by Flakebi** [comment]
`HTTP Error 429: Too Many Requests` means you are hitting the rate limiting of YouTube. There is nothing we can do about this.
See also the comments starting here: https://github.com/Splamy/TS3AudioBot/issues/619#issuecomment-520481906
And the FAQ entry of youtube-dl: https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required

**Comment by Heisz457** [comment]
What should I do?

**Comment by Flakebi** [comment]
You have to wait until YouTube unblocks your IP.
