### ISSUE TITLE
About the setup file

### ISSUE THREAD

**Issue by farfik** [Splamy/TS3AudioBot#725]
Hello

Can you transmit TS3AudioBot files that I can directly upload to the server and run? I would be glad if it can be open source.

**Comment by Splamy** [comment]
I don't understand your question. The AudioBot is open source. You can follow the instructions in the readme to build it yourself or download the prebuilds and run.

**Comment by farfik** [comment]
I could not. If you can, please share it with me

https://github.com/Splamy/TS3AudioBot I want the files here to be exe.

**Comment by Flakebi** [comment]
As Splamy already said, that is described in the readme here: https://github.com/Splamy/TS3AudioBot#download
You can download the files from the nightly server, e.g. the master_dotnet_core version, install the dotnet runtime and then you can run it.

**Comment by farfik** [comment]
I tried something but it stays like this, what should I do?

![ddd](https://user-images.githubusercontent.com/60569080/74492567-f8f59280-4ed7-11ea-815b-3435cf13d135.png)
