### ISSUE TITLE
Error return from player: Unable to create icy-stream (The operation has timed out.)

### ISSUE THREAD

**Issue by NSN-Scripts** [Splamy/TS3AudioBot#727]
Habe folgenden Fehler:
Error return from player: Unable to create icy-stream (The operation has timed out.)

System: Debian 10

Hoster: Tube-Hosting.de

Version die neuste

**Comment by ChronoBrake** [comment]
I wanna ping i get same error when trying play youtube songs etc. all youtube content have that error.

"2020-02-10 10:29:59.9907| WARN|0|FfmpegProducer.StartFfmpegProcessIcy Unable to create icy-stream (The operation was canceled.)
System.OperationCanceledException: The operation was canceled.
   at System.Net.HttpWebRequest.GetResponse()
   at TS3AudioBot.Audio.FfmpegProducer.StartFfmpegProcessIcy(String url) in /root/TS3AudioBot/TS3AudioBot/Audio/FfmpegProducer.cs:line 224"
