### ISSUE TITLE
it says i have the wrong teamspeak Version.

### ISSUE THREAD

**Issue by Rizitrix** [Splamy/TS3AudioBot#730]
**Describe the problem**
It says i need to have teamspeak version 3.3+ and my currently one is 3.11.0, and its my own server, what can i do??
.
**To Reproduce**
Steps to reproduce the behavior

**System Information**
- **Platform**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **Mono version**: (`mono -V`)  
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by Rizitrix** [comment]
https://gyazo.com/d48c26ec84d6f7d61207f695a3517174

**Comment by Flakebi** [comment]
Hi @Rizitrix,
you created an issue for the wrong bot. Your screenshot is from [SinusBot](https://www.sinusbot.com) but this repository is for the **TS3AudioBot**.
