### ISSUE TITLE
How bot commands change?

### ISSUE THREAD

**Issue by farfik** [Splamy/TS3AudioBot#732]
Hello

I compiled the files via ubuntu, However, I cannot adjust settings such as avatars, command changes, etc. where did i make a mistake ?

![bin](https://user-images.githubusercontent.com/60569080/74595325-b0111b80-5048-11ea-85e6-9163aa2bc92d.png)
![bin2](https://user-images.githubusercontent.com/60569080/74595328-b1424880-5048-11ea-8703-7ad62032e2fd.png)

**Comment by Flakebi** [comment]
Sorry, I don’t understand your question.
What do you mean with "I cannot adjust settings"? What do you expect that should work?

**Comment by farfik** [comment]
I compiled the files in ubuntu. Files came to bin/Release /netcore folder. I tried modifying !help commands and it didn't work. Photos show where the files are. How can I fix this problem

**Comment by Flakebi** [comment]
1. I guess you compiled with `dotnet build` and you are using dotnetcore 3?
1. What did you modify in the `!help` command? Can you show your current code?
1. Did you recompile after your change?
1. What is the answer of your compiled bot if you write `!help`?

**Comment by farfik** [comment]
!.There must be dotnet 2.2 on the server. I couldn't build on dotnet 3
2.I wanted to make the explanation language in Turkish
3.I did not recompile after the change. (I just restarted the bot xd)
4. !help says old commands when I type

Is there a place where I can contact you?

**Comment by Flakebi** [comment]
Thanks for the information.
You need to recompile the bot after you change the message. Then it should work.

Also, we would appreciate translations here: https://www.transifex.com/respeak/ts3audiobot/
Then you can simply set the language and it will work.

Re contact: GitHub issues are fine, it allows other people to chime in.

**Comment by farfik** [comment]
dotnet build --framework netcoreapp2.2 --configuration Release TS3AudioBot. I ran the command again and got errors

![1111](https://user-images.githubusercontent.com/60569080/74608391-3d0bb180-50e9-11ea-8779-3d57898338ba.png)

**Comment by farfik** [comment]
> Thanks for the information.
> You need to recompile the bot after you change the message. Then it should work.
> 
> Also, we would appreciate translations here: https://www.transifex.com/respeak/ts3audiobot/
> Then you can simply set the language and it will work.
> 
> Re contact: GitHub issues are fine, it allows other people to chime in.

Is there any other place where I can contact you?

Please help m
