### ISSUE TITLE
I can't find the "bin" folder in the "ts3audio bot"

### ISSUE THREAD

**Issue by haroldrc** [Splamy/TS3AudioBot#735]
**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
Steps to reproduce the behavior

**System Information**
- **Platform**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **Mono version**: (`mono -V`)  
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by Flakebi** [comment]
Hi @haroldrc, did you follow the [readme](https://github.com/Splamy/TS3AudioBot#install)?
If so, at which step are you and which `bin` folder are you searching?

**Comment by haroldrc** [comment]
TS3AudioBot/bin/Release/netcoreapp2.2

Il mar 25 feb 2020, 19:19 Seebi <notifications@github.com> ha scritto:

**Comment by haroldrc** [comment]
TS3AudioBot/bin/Release/netcoreapp2.2

**Comment by Splamy** [comment]
- Which version did you download
- What did you execute
- What were the outputs

**Comment by haroldrc** [comment]
I installed the latest version, it's when I open the "ts3audiobot"
folder I can't find the "bin" folder

[image: image.png]



Il giorno gio 27 feb 2020 alle ore 10:34 Splamy <notifications@github.com>
ha scritto:

**Comment by Splamy** [comment]
The image you tried to attach isn't showing.

> I installed the latest version

What did you install?
Did you download the nightly build from splamy.de or did you download the source code and are trying to compile it yourself?
If you don't have any programming experience please just follow the readme and download the binaries.

**Comment by haroldrc** [comment]
Open the archive and copy the ffmpeg binary from
ffmpeg-latest-winXX-static/bin/ffmpeg.exe to
TS3AudioBot/bin/Release/netcoreapp2.2


I can't find "TS3AudioBot / bin / Release / netcoreapp2.2"

Il giorno gio 27 feb 2020 alle ore 19:37 Splamy <notifications@github.com>
ha scritto:
