### ISSUE TITLE
Default Channel wird nicht gesetzt

### ISSUE THREAD

**Issue by JonaxGames** [Splamy/TS3AudioBot#737]
Hallo,

ich habe des Problem ich möchte einen Standard-Channel setzen, aber der joint nicht in den Channel obwohl ich das richtig angegeben habe

Beispiel: Channel ID ist 52
```
#Default channel when connecting. Use a channel path or "/<id>".
#Examples: "Home/Lobby", "/5", "Home/Afk \\/ Not Here".
channel = "/52" 
```

**Comment by Splamy** [comment]
Does the bot have permission to move into that channel?
If it is password protected make sure to add in into the config too (`connect.channel_password`)

**Comment by JonaxGames** [comment]
yes, the bot have premissions. The Channel also do not have a password

**Comment by Splamy** [comment]
Did you set it for the correct bot?
You can check by writing `!settings get connect.channel` to the bot
