### ISSUE TITLE
[Announcement] Youtube api shutdown | YouTube API Compliance Review

### ISSUE THREAD

**Issue by Splamy** [Splamy/TS3AudioBot#738]
## What happened
As some of you may know the TS3AudioBot uses the youtube api to fetch some data fast and efficiently like playing by search term or loading playlists.
To make operations smoother we shipped our own youtube api key with the bot and this worked very well until we now got an email for the 'YouTube API Compliance Review'.
This means that the api has probably reached a certain usage threshold (currently 50k-80k requests per day) where youtube wants to verify the correct use of their services.
While we are happy about these usage numbers this means we will have to remove the key since as you may imagine the TS3AB's usage of the youtube api is not quite so compilant with the youtube terms of service.

## What now
I will shutdown our youtube-api key this evening.  
This means loading youtube playllists, searching for youtube songs, and youtube thumbnail loading will not work anymore.

## What will happen
I have found another project with the same problem: https://github.com/natumbri/mopidy-youtube/issues/92
The solution will be to simply rewrite our loader to use youtube-dl for everything where we used the api before.
This will maybe make a few calls marginally slower (probably <1sec) but we shouldn't need any youtube api keys anymore.

## Notes
- You can compile the project and use your own api key until we get everything back to work
- I am considereing whether to keep the youtube-api functions as a second alternative in the code so users can still just use their own youtube-api key, however this means more maintaining work for the youtube loader when something changes.

## Update

Alright, the new dev build (starting with 0.11.0-alpha.47) can now search and import playlists again.
You will need youtube-dl for those features to work now.
I've left the old api functions in for now, but without any guarantees that it might break. The bot will use the youtube api if you have set a API key in the config. Otherwise it will use the new youtube-dl based loader.

**Comment by zmechu** [comment]
80k requests per day - it seems TS3AudioBot is a great project :-)

Where is in bot source code (file and line) API key to exchange for own one?

**Comment by Splamy** [comment]
Yeah, as requested in #741 I will add a config value, so people can still use the old functions until everthing is switched to youtube-dl

**Comment by zmechu** [comment]
Dev dotnet version works fine with ty API key in config file. Thanks!

**Comment by Splamy** [comment]
Alright, the new dev build can now search and import playlists again.
You will need youtube-dl for those features to work now.
I've left the old api functions in for now, but without any guarantees that it might break. The bot will use the youtube api if you have set a API key in the config. Otherwise it will use the new youtube-dl based loader.
