### ISSUE TITLE
Set YouTube API Key in Plugin

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#741]
Hello
How to set YouTube API Key in Plugin?
We don't want to set an own YouTube API in a custom Plugin file.
Can u tell how to do that?
Thanks 😀

**Comment by Splamy** [comment]
I don't understand your question. Do you, or do you not want to use an own api key?
Also I've opened a pinned issue yesterday for all youtube api related questions and discussions: #738

**Comment by marv-th** [comment]
We want to use an own Key. But we dont want to compile the Project. We want to set the Key in a Pluginfile and I ask you to tell me how to do (function, variables). 
This would help us and other users. 
I hope u understand me now :)

**Comment by Splamy** [comment]
Ah, yes, as noted in #738, when eveything is done you won't need any api key anymore but I can definitely addan config value for setting your own key until everything is done.

**Comment by ChronoBrake** [comment]
When update will be available?

**Comment by Splamy** [comment]
it already is, see the linked commit above your comment.

**Comment by marv-th** [comment]
Thanks. Thats fine:)
