### ISSUE TITLE
‎Error: No connection could be established. (Error with youtube search feature)

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#746]
**Describe the bug**

When i try to use youtube search feature i have this error (Error: No connection could be established.)
!play command works, but youtube search not.

**Version**
Version: 0.10.1+7
Branch: master
CommitHash: 65aa9a18ca5f72f0be9adc6aa93571b9291a9398

**Platform**
Ubuntu 16.04
Latest mono

**Log**
Will add log if i have to add it.

**Other**

That works before, 2 days ago i getting this bug.
Everything others works okay.

**Comment by Splamy** [comment]
See #738
