### ISSUE TITLE
WebInterface Problem

### ISSUE THREAD

**Issue by Fantasia2222** [Splamy/TS3AudioBot#750]
**Describe the problem**
Hello, i've installed the bot but i can't see the webinterface, there is just a white screen and there are no errors

**System Information**
- **Platform**: Ubuntu 18.04

**Comment by Fantasia2222** [comment]
resolved

**Comment by Fantasia2222** [comment]
resolved

**Comment by Splamy** [comment]
Oh, alright, what was the problem?
