### ISSUE TITLE
Full configuration option list

### ISSUE THREAD

**Issue by F43nd1r** [Splamy/TS3AudioBot#752]
Is there any place where I can view all available configuration options?

**Comment by Splamy** [comment]
The `ts3audiobot.toml` is automatically generated and contains all options together with the documentation

**Comment by F43nd1r** [comment]
Ah, I searched in the bot.toml file, which only has used options.

**Comment by Splamy** [comment]
Exactly, if you need more info er examples we also have a wiki page for this topic: https://github.com/Splamy/TS3AudioBot/wiki/Configuration#overwriting
