### ISSUE TITLE
Support more Streams

### ISSUE THREAD

**Issue by paradoxos** [Splamy/TS3AudioBot#753]
**Is your feature request related to a problem? Please describe.**
Doesn't support some streams 
For example this webradio !play http://5.63.151.52:7082/stream
gives this Error: Could not load. (media: Unknown request error.)

**Describe the solution you'd like**
On the other hand this one is supported
http://94.130.113.214:8000/chill

is this a server side issue?

**Comment by Splamy** [comment]
Seems to play just fine on my bot. Is it possible that you have a lot of streams to this server open? Does the log file give any additional information?

**Comment by paradoxos** [comment]
@Splamy that port was blocked from the firewall. Now it works.

Thank you for your help and your time.
