### ISSUE TITLE
Where to find, setup, and use Plugins?

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#755]
Hi,

Where to download plugins for TS3AudioBot, i need AntiVPN/Proxy and more.
And when i download it how to setup it and use it.
I need "Tutorial" for that, or explain it to me. 
And don't forget, give me link to download Plugins.

King Regards,
Hazze

**Comment by DoMaxiHa** [comment]
[Here](https://github.com/Splamy/TS3AudioBot/wiki/Plugins)

**Comment by Splamy** [comment]
As DoMaxiHa wrote we only have a wiki, there is a request for an online store (see #756) you can read futher details there.
