### ISSUE TITLE
 I wanted to reprogram the TS3AudioBot

### ISSUE THREAD

**Issue by SaveOriginal** [Splamy/TS3AudioBot#758]
**Describe the problem**
Hi there, i have downloaded the sourcecode of the ts3audiobot. Now i want to reprogram 
the bot.

Then i have opened the project with Visual Studio, i clicked to "Build" to Build the Bot and now comes this errors:

![image](https://user-images.githubusercontent.com/61278114/77827112-1727f280-7114-11ea-812c-e41b9804d59c.png)

How can i fix this?

**Comment by Flakebi** [comment]
I already answered that on [Gitter](https://gitter.im/TS3AudioBot/Lobby) (I guess these questions are connected).
> This should not happen anymore for the newest develop version (yay), you can also apply one of these fixes: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#gitversiontask
>
> As you want to change the code of TS3AudioBot, please have a look at the license. In short, you can change everything as long as you give credit (a link to github is enough) and if you host the bot for others, you have to make your changes open source (e.g. in a fork on github) :)
