### ISSUE TITLE
Can't run latest develop commit with mono

### ISSUE THREAD

**Issue by antoniuszp** [Splamy/TS3AudioBot#762]
**Describe the bug**
I downloaded latest develop commit [a4ef020](https://github.com/Splamy/TS3AudioBot/commit/a4ef0208c6c41b01228b8a5aebaec881effd941b) due to YT problems, then I made some changes to the code to my own requirements and compiled. I can't run a compiled version on VPS with Ubuntu using mono. Mono returns an error: File does not contain a valid CIL image. 

**Platform**
Ubuntu 18.04.3
Mono 6.8.0.105

**Log**
```
Cannot open assembly 'TS3AudioBot.exe': File does not contain a valid CIL image.
```

**Comment by Flakebi** [comment]
The latest (develop) version only supports dotnet core 3.1, so you need to use this to compile and run the bot.

**Comment by antoniuszp** [comment]
Thank you for your help @Flakebi !
