### ISSUE TITLE
API error: "Could not copy config" while copying templates

### ISSUE THREAD

**Issue by Wruczek** [Splamy/TS3AudioBot#763]
**Describe the bug**
Error 10 "Could not copy config" is returned when trying to copy config with API:
`/api/settings/copy/template/newbot`

**Version**
I have tested it on two versions:
- `0.12.0-alpha.11 (f913536594129656f9758b4332555a207d9dc09c)`
- `0.11.0-alpha.48 (cca3deaef221bdab59ad424b4f5cddfc65c1131f)`

**Log**
No errors are displayed in the log, only the API call:
`20:54:06.7392| INFO|| 192.10.10.1 Requested: /api/settings/copy/template/newbot`

**Comment by Splamy** [comment]
Yup, that's definitely broken, should be easy to fix.
