### ISSUE TITLE
Is it possible for the bot to write in the chat which song is playing

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#765]
Is it possible for the bot to write in the chat which song is playing?
Like when i play some song from youtube (etc. Despacito), bot send message in channel like:
<14:02:10> "Music Bot": Now Playing: Despacito

And when i play Stream Link too.

**Comment by zmechu** [comment]
you want to do it automatically?

If not, use !song function

**Comment by hazzeee** [comment]
> you want to do it automatically?
> 
> If not, use !song function

but I want the bot to automatically write  what song is when the song starts, not just when I type !song function

**Comment by hazzeee** [comment]
when song starts, bot send message automatically

**Comment by Splamy** [comment]
You could use the `audio.send_mode`, it's bit hacky, but it works:
```toml
[audio]
send_mode = "!xecute (!whisper off) (!pm channel (!info))"
```

I'll add to my todos to add an track_chagned event to the event config list, I think some users could use that

**Comment by hazzeee** [comment]
> You could use the `audio.send_mode`, it's bit hacky, but it works:
> 
> ```toml
> [audio]
> send_mode = "!xecute (!whisper off) (!pm channel (!info))"
> ```
> 
> I'll add to my todos to add an track_chagned event to the event config list, I think some users could use that

Where to add that code, and when i add it how to apply it,  like (etc. !rights reload)..

**Comment by Splamy** [comment]
You can set it with `!settings set audio.send_mode "!xecute (!whisper off) (!pm channel (!info))"` to the bot where you want to set it

**Comment by hazzeee** [comment]
> You can set it with `!settings set audio.send_mode "!xecute (!whisper off) (!pm channel (!info))"` to the bot where you want to set it

One more question, can i customize the !song and !info message? And how.

**Comment by Splamy** [comment]
Currently there's no option for that, what would you like to change?
