### ISSUE TITLE
WebInterface not working

### ISSUE THREAD

**Issue by krikos** [Splamy/TS3AudioBot#768]
**Describe the bug**
Web pages shows error and everything is empty.
Browser console shows CORS-error:
`Fetch API cannot load file:///C:/api/version. URL scheme must be "http" or "https" for CORS request.`
I think they changed file protocols behavious last year due to security vulnerability?

**Version**
Version: 0.12.0-alpha.19
Branch: develop
CommitHash: 14da67fc09a9df5d76620baee67e61f1251e5087

**Platform**
win10
Firefox 75.0
Chrome 80.0

**Comment by Flakebi** [comment]
You have to open the page with the address, http://localhost:58913 instead of opening the file directly.

**Comment by krikos** [comment]
Thank you.
