### ISSUE TITLE
Anonymous/Admin key WebAPI

### ISSUE THREAD

**Issue by MrBn100ful** [Splamy/TS3AudioBot#77]
Hello, when do you think Anonymous/Admin key for the webapi will be integrated ?

**Comment by Splamy** [comment]
It may take a week, it may take a month, I have no idea or plan.
You can always look in the https://github.com/Splamy/TS3AudioBot/projects/2 project for an overwiew of my todo roadmap.
I cant make progress faster but if there is a demand I can switch priorities for a certain feature

**Comment by MrBn100ful** [comment]
## I'm on the project to do a web interface.
## But i can  make it without an _admin token_.
##  **Made it please !**

**Comment by lgund** [comment]
There are more, that want to do a webinterface with he bot, but please give the develloper a biz time :)

**Comment by Splamy** [comment]
If you just need an api key with admin equivalent rights, just create a key for a user with admin rights.  
The only real use for an admin key (or anonymous key, how it's supposed to be) is if you want an automated setup where you cant get a user apikey before.  
Also I have set this task to the top of the workqueue, but it depends on the new rights system so I will have to get that done first.

**Comment by TheCrealm** [comment]
Do you have a more detailed plan about how the new right system should work? Maybe you could link your Kanban tasks with issues which describes their process. Also this allows a bit of interaction to other developers who maybe want to contribute or support this epic bot 💯 By the way, I requested something similar like this in #35 :P

**Comment by Splamy** [comment]
@TheCrealm yes indeed i have a few plans already. Maybe for a better insight I will open a new issue for that shortly to decribe it and give opportunity for suggestions, as well as giving some structure/documentation also for myself.

> Maybe you could link your Kanban tasks with issues which describes their process.

Nice idea, will do that.

**Comment by Mareczin** [comment]
Hey Splamy, how progress about permament token api?

**Comment by Splamy** [comment]
Good news is the database i've been faiting for some fixes has finally release a new version.
Now I have to rework stuff implement it, soo depending on when I have time I can try to get some progress done.

**Comment by Splamy** [comment]
Ok tokens are now persistenly saved, as well as can be matched in the permission file.
Simply generate a token and match your uid or the token like that, to grant full permissions.

```
[[rule]]
  # either or both, as you want
  useruid = [ "uA0U7t4PBxdJ5TLnarsOHQh4/tY=" ]
  apitoken = [ "asdfVILDyaTYrOXh29XJXivxIqxaIDjf" ]

  "+" = "*"
```
