### ISSUE TITLE
How to use the WebInterface and run Youtube Songs?

### ISSUE THREAD

**Issue by Silencesteal** [Splamy/TS3AudioBot#771]
Hello my name is Federico,

i would try to run the WebInterface but i dont know how to log in?
![webinterface](https://user-images.githubusercontent.com/63858091/79573399-e3127280-80be-11ea-8dde-1bcdeff1a253.png)

If the bot is Connected on Teamspeak i use the Command
!play youtube link
<15:01:11> "TS3AudioBot": Error: Could not load. (youtube: Youtube-Dl could not be found. The song/video cannot be played due to restrictions.)

need help please :O

**Comment by Flakebi** [comment]
Hi Federico,
1. To login to the webinterface, you need to write `!api token` to the bot in a private chat. You can just paste the result into the login field.
2. For youtube, as the error says, you need to install an up-to-date version of [youtube-dl](https://github.com/ytdl-org/youtube-dl#installation) and tell the bot about it with `!settings global set tools.youtube-dl "/path/to/youtube-dl"`

**Comment by Silencesteal** [comment]
Im sorry but i dont get it .. :(

![untitled](https://user-images.githubusercontent.com/63858091/79582600-4787fe80-80cc-11ea-887d-92ec629e3e3f.png)

First i write the Bot: 
!api token
I copy the api und paste on the Webinterface -> Auth Failed

Second i Download for Windows des youtube-dll exe 
i put it on the TS3AudioBot folder and write the bot:
!settings global set tools.youtube-dl "C:\Users\Federico\Downloads\TS3AudioBot\youtube-dl.exe"

**Comment by Flakebi** [comment]
1. You need to go to the real website, opening the `.html` file doesn’t work. http://localhost:58913
2. That happens when I try to guess commands without trying them. Sorry, the right one is `!settings global set tools.youtube-dl.path "/path/to/youtube-dl"` (I missed the `.path` in the end)

**Comment by Silencesteal** [comment]
Wich is right?
!settings global set tools.youtube-dl.path "C:\Users\Federico\Downloads\TS3AudioBot\youtube-dl.exe"
!settings global set tools.youtube-dl.path "C:/Users/Federico/Downloads/TS3AudioBot/youtube-dl.exe"

its enough the youtube-dl.exe or i need to download the whole folder and get the path of the youtube-dl?

**Comment by Flakebi** [comment]
I think the exe is enough, but I’m not a specialist on youtube-dl. If it works, it works :shrug:

Re the right path: Try it ;) As far as I know Windows, both should work

**Comment by Silencesteal** [comment]
Perfect, Thanks for the help mate <3
