### ISSUE TITLE
Why lots of 0.12 Versions?

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#776]
Why the developer Version have different versions?

develop_linux_arm
develop_linux_arm64
develop_linux_x64
develop_win_x64

Thanks for your answer

**Comment by Flakebi** [comment]
These are native builds, so they depend on the operating system and hardware architecture of your machine.
If I want to run the audiobot on a raspberry pi for example, I can pick develop_linux_arm,  develop_win_x64 won’t work there.
Usually, servers and PCs are x64, so pick develop_win_x64 for windows and develop_linux_x64 for linux.
The build `develop` without anything else is the dotnet core 3.1 version.

**Comment by marv-th** [comment]
okay. it means i can use the `develop` version for debian and ubuntu or can i use for them an other version?
And need the others version no dotnet?

**Comment by Flakebi** [comment]
Right, for `develop` you need to have dotnet core 3.1 installed.
For the others you don’t need much installed, I think on linux openssl and opus are still required, but no dotnet. You can simply start it with `./TS3AudioBot`.

For linux you can either use `develop` with dotnet core or `develop_linux_x64` without dotnet core.

**Comment by marv-th** [comment]
Okay Thank you very much and very nice feature! :)

**Comment by marv-th** [comment]
what is the new namespace for IPlayerConnection? Maybe IPlayerSource ? But there are no values like stopped
