### ISSUE TITLE
Load Bot Config

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#777]
Version: current 0.12 develop

When I create manually a new bot.toml the ts3ab can not load or list the toml. I must restart the ts3ab to use this

**Comment by Splamy** [comment]
works just fine for me. Did you create the path correctly? Should look like `bots/<name>/bot.toml`

**Comment by marv-th** [comment]
Hey.

I fixed the Bug. Mainly the bug was based on that Static Plugins are not
supported anymore.
But one question because i dont want to test. Can Commands execute in Core
Plugins too, when NO Bot was created. In Static Plugins it was possible.



Splamy <notifications@github.com> schrieb am Do., 23. Apr. 2020, 02:12:

**Comment by marv-th** [comment]
Hey.

I fixed the Bug. Mainly the bug was based on that Static Plugins are not
supported anymore.
But one question because i dont want to test. Can Commands execute in Core
Plugins too, when NO Bot was created. In Static Plugins it was possible.
