### ISSUE TITLE
Question about the File System

### ISSUE THREAD

**Issue by ProxyPing** [Splamy/TS3AudioBot#778]
Hello where do you create the folders for the bots I don't need a folder I only need the files I would like to change that...

**Comment by zmechu** [comment]
Please be more precise, I don't understand your question...

**Comment by ProxyPing** [comment]
ok, in the old bot there was just files no folder i just want files bzw default.toml not /default/default.toml for my bot hosting.....

**Comment by Flakebi** [comment]
Thanks for the further explanation. Sorry you can’t change the way the config files are stored.
The reason that this change was made is to allow multiple files for each bot in the future.

**Comment by ProxyPing** [comment]
But i can change it in the code or not

**Comment by Splamy** [comment]
If you can program, sure, it's open source. But those folders hold other files too, so you'll have to find a solution where to move/retrive them from.
