### ISSUE TITLE
Issues with VPN

### ISSUE THREAD

**Issue by Generalas** [Splamy/TS3AudioBot#781]
When using you bot, trying to connect to specific servers with a VPN there is a one to five minute delay before I am able to connect to the server.

Version: 0.12.0-alpha.19
OC Windows

**Comment by Splamy** [comment]
That seems like a weird problem with your VPN. The bot doesn't even try to send packets for 5 minutes straight. It will try to send the init packet about 10 times within 30 seconds then wait for the retry delay amount in the config and start again. When you can't connect for 5 minutes it means the packets arent going through your vpn.
Unfortunately I don't have any VPN I could try this with., so there's not much I can help you here with
