### ISSUE TITLE
Groups in rights.toml not working - develop branch

### ISSUE THREAD

**Issue by Athavar** [Splamy/TS3AudioBot#784]
**Describe the bug**
If a group is added to a rule with "include", the error "\<include> Field has invalid data." appears in the console.

**To Reproduce**
define a group in the rights.toml

**Version**
Version: 0.12.0-alpha.31
Branch: develop
CommitHash: 311972b4f183b53d17a5b07be5323b612b847c47

**Log**

> 12:39:39.6204|ERROR|| \<include> Field has invalid data.
12:39:39.6204| WARN|| Group "$name" is never included in a rule

**Solution**
negate the "if". https://github.com/Splamy/TS3AudioBot/blob/311972b4f183b53d17a5b07be5323b612b847c47/TS3AudioBot/Rights/RightsDecl.cs#L51

**Comment by Splamy** [comment]
Yup, that's indeed broken. Thanks, fix should be up shortly
