### ISSUE TITLE
Can i change !info output?

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#786]
Hi, 

How can i change the output of !info command

![image](https://user-images.githubusercontent.com/60288878/80910608-69e16500-8ce5-11ea-8133-db5c269e180e.png)

How to change that message to my own?

**Comment by Flakebi** [comment]
What would you like to change there?

The strings can be found like described here: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#text-responses
For other changes you need to look into the code
