### ISSUE TITLE
Other language is problem

### ISSUE THREAD

**Issue by Generalas** [Splamy/TS3AudioBot#790]
When trying to send non-English letters as a massage for every letter typed the bot sends a “?” instead of the letter that I want to send. How could I solve this?

**Comment by Splamy** [comment]
I've just tested it and it seems just fine:
```
<16:15:39> "Splamy": !print "(╯‵□′)╯︵┻━┻"
<16:15:39> "DefaultyBot": (╯‵□′)╯︵┻━┻
```

- which bot version are you running?
- which server version?
- Maybe you have an incompatible font set up in teamspeak?

**Comment by Generalas** [comment]
Version: 0.12.0-alpha.19/develop/14da67fc
Build: Release
Platform: Windows 6.1.7601.65536 (64bit)
Runtime: .NET Framework 3.1.2 
Verison TeamSpeak server 3.11.0
When I send a HTTP request to the bot thought the API which uses non English symbols I get the “?” instead of the symbols that I’m sending. How do I fix this?

**Comment by Splamy** [comment]
You need to urlencode your text. Every language usually has a feature for that.
For example my previous commans like `!pm channel "(╯‵□′)╯︵┻━┻"`
should look like this urlencoded: 
`api/bot/use/0/(/pm/channel/%28%E2%95%AF%E2%80%B5%E2%96%A1%E2%80%B2%29%E2%95%AF%EF%B8%B5%E2%94%BB%E2%94%81%E2%94%BB)`

**Comment by Generalas** [comment]
Thank You a lot for the help
