### ISSUE TITLE
Getting started example for plugins invalid

### ISSUE THREAD

**Issue by zumoshi** [Splamy/TS3AudioBot#792]
**Describe the bug**
Commit dad9127df9 renamed `AfterResourceStopped` to `PlaybackStopped`, but the example in wiki still uses AfterResourceStopped resulting in an error.

**To Reproduce**
Follow steps in wiki's getting started section for [Command Plugins](https://github.com/Splamy/TS3AudioBot/wiki/Plugins#command-plugins).

**Version**
Version: 0.11.0
Branch: master
CommitHash: c7e44e4dfd5d5240cd5d8cbe4fa1f20a0315aca4

**Platform**
N/A

**Log**
```
Error L23/C20: 'PlayManager' does not contain a definition for 'AfterResourceStopped' and no accessible extension method 'AfterResourceStopped' accepting a first argument of type 'PlayManager' could be found (are you missing a using directive or an assembly reference?)
```

P.S. `var self = Ts3Client.GetSelf();` on line 27 also seems to need to change to `var self = ts3Client.GetSelf();` (using instance property instead of static class).

**Comment by Splamy** [comment]
Thanks for the notice, I've updated all examples
