### ISSUE TITLE
Can't play a youtube playlist unless importing it

### ISSUE THREAD

**Issue by jinjeul** [Splamy/TS3AudioBot#794]
Hello everyone !

**Describe the bug**
When trying to play a youtube playlist using it's url, the bot can't handle it : 

> [B][COLOR=red]Erreur: [/B]La longueur du nom de la playlist doit être de moins de 64 caractères.

As the output is in french, here's a translation : 

> The length of the playlist's name have to be below 64 characters.

**To Reproduce**

`!list play ￼https://www.youtube.com/playlist?list=PLzWNzbGP_UNBhZbxTDYuL81nhMYb7EQDQ`

**Version**

```
Version: 0.11.0
Branch: master
CommitHash: c7e44e4dfd5d5240cd5d8cbe4fa1f20a0315aca4
```

**Platform**

Docker image using Dockerfile : 

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y ffmpeg wget p7zip-full gpg libopus-dev python

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list \
  && apt-get update \
  && apt-get install -y mono-complete \
  && rm -rf /var/lib/apt/lists/* /tmp/*

RUN wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl && chmod a+rx /usr/local/bin/youtube-dl

WORKDIR /app
RUN wget -O TS3AudioBot.zip https://splamy.de/api/nightly/ts3ab/master/download && 7z x TS3AudioBot.zip && rm -f TS3AudioBot.zip

CMD  ["mono", "TS3AudioBot.exe", "--non-interactive", "-c", "/config/TS3AudioBot.config"]
```

**Log**
```

12:53:05.6141| INFO|1| User Jinjeul requested: !list play [URL]https://www.youtube.com/playlist?list=PLzWNzbGP_UNBhZbxTDYuL81nhMYb7EQDQ[/URL]


```
Nothing else, sure it's INFO level, but I can't make it more verbose because changing the setting in the NLog.config file is reverted when restart the docker container..

I manage to counter this issue by doing the following steps : 

```
!list create myplaylist
!list import myplaylist ￼https://www.youtube.com/playlist?list=PLzWNzbGP_UNBhZbxTDYuL81nhMYb7EQDQ
!list play myplaylist
```

But this is hard to handle for other users and thus is not used.
Making an alias to seamlessly do that don't seem to work neither.

Many thanks, for your work on this project, it's really cool, especially during lockdown..

Stay safe

**Comment by Splamy** [comment]
This is the intended behaviour to keep playlist access consistent with the api.
`!list play <name>` does not take a url to play.

> Making an alias to seamlessly do that don't seem to work neither.

Yeah I can see this being wonky to create a compound alias. `!list clear` doesn't exist and `!list delete` requires confirmation.
My target for this would be to make an alias like `!x (!clear) (!list import .mix (!param 0)) (!jump 0)` but right now `!jump` is also missing.
The `.mix` is a special list which is the current playback queue, so this would require no temporary list on disk.

Unfortunately I can't give you a nice alias which does exactly that, right now. And often I needed such commands myself, but I hope to add those essetial functionality commands so people can build more useful aliases around them

**Comment by Splamy** [comment]
Just a quick notice, the new dev branch has two new commands `!list clear <name>` to clear a list and `!jump <index>` to jump+play to a index in the current queue.
This means an alias like `!alias add llp "!x (!clear) (!list import .mix (!param 0)) (!jump 0)"` (as in me previous post) should now just work.
