### ISSUE TITLE
OnError Event

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#795]
Hello. Is there any event that, when the Bot run into an error, the event will called?
Thanks

**Comment by Splamy** [comment]
What do you consider an error event? and with 'bot', do you mean a single bot or the entire instance?

**Comment by marv-th** [comment]
Hello. I mean the single bot and instance.
For example, if the Console print an Error like the Webserver could not start or something else, than an Event should be call, that i can interact (save, or something else) with that error.
Maybe it is allready possible with nlog

**Comment by Splamy** [comment]
You can use the [NLog memory target](https://github.com/NLog/NLog/wiki/Memory-target).
It will behave a like a console or file target which you can retrieve by code

**Comment by marv-th** [comment]
Hey. So i dont understand if this can react with the ts3ab nlog. Can you maybe explain it more how to use this in a plugin?

**Comment by Splamy** [comment]
Well I can just repeat what the documentation says:
In your `NLog.config`:
- put a new `<target xsi:type="Memory" name="NLogMemory" />` into the `<targets>` group
- Add a rule what you want to log: for eg `<logger name="TS3AudioBot.*" minlevel="Info" writeTo="NLogMemory" />` into the `<rules>` group
- get all logs in the code:
```cs
var target = LogManager.Configuration.FindTargetByName<MemoryTarget>("NLogMemory");
var logEvents = target.Logs;
```

**Comment by snakefoot** [comment]
You can also make NLog call a static method on a custom type of your choice:

https://github.com/NLog/NLog/wiki/MethodCall-target

**Comment by marv-th** [comment]
@snakefoot Thanks. That was helpfull :)
