### ISSUE TITLE
TeamSpeak Functions doesnt work

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#797]
I think it could be something to do with #793 
In Plugins teamspeak functions doesnt work.
When i do the getself command or do clientlist and check with result.OK the bot stops accept api or chat commands.
Thank you

Version: 
develop_linux_x64 | 0.12.0-alpha.36

**Comment by Splamy** [comment]
Can you give an example snippet?

**Comment by marv-th** [comment]
Yes. I dont post the full function but the relevant part.
for example, "hier" will be print in the log or console but "Could get Clientlist {}" or "Could not get Clientlist {}" wont be print or something else. And after that, the bot doesnt process any command.

```csharp
public void checktopause() {
                                var clientlist = Client.ClientList();
                                Logger.Info("hier");
                                if (clientlist.Result.Ok)
                                {
                                    Logger.Info("Could get Clientlist {}");
                                    //CODE
                                } else
                                {
                                    Logger.Info("Could not get Clientlist {}");
                                }
}
```

**Comment by Splamy** [comment]
Don't use `.Result` it will result in a deadlock.
Declare your function async and await the task:
```csharp
public async Task checktopause() {
                                var clientlist = await Client.ClientList();
                                Logger.Info("hier");
                                if (clientlist.Ok)
                                {
                                    Logger.Info("Could get Clientlist {}");
                                    //CODE
                                } else
                                {
                                    Logger.Info("Could not get Clientlist {}");
                                }
}
```

**Comment by marv-th** [comment]
Thanks. I will try it in the next days

**Comment by marv-th** [comment]
No i am hanging on this error. Sorry, the errormessage is german
'Der Rückgabetyp von "Task NowPlaying.OnEachClientMovedAsync(object, ClientMoved)" ist falsch.'
I allready try int, TResult and string

**Comment by Flakebi** [comment]
`async` means the return type is always a `Task`.
Return types map as follows:
`void` -> `Task`
`int` -> `Task<int>`
`string` -> `Task<string>`
any type `T` -> `Task<T>`

If you mark a function as `async` and you want to return a `string`, you need the return type `Task<string>`.

**Comment by marv-th** [comment]
Hey. It doesnt work. I send you some snippets..
I tried a lot but i only get error messages in the console. "Checktopause()" has no return
```csharp
public void Initialize()
        {
            //CODE
            Client.OnEachClientMoved += OnEachClientMovedAsync;
            Client.OnEachClientEnterView += OnEachClientEnterViewAsync;
            Client.OnEachClientLeftView += OnEachClientLeftViewAsync;
            //CODE
        }

public async Task Checktopause()
        {//CODE}

private async Task OnEachClientMovedAsync(object sender, ClientEnterView e)
        {
            await Checktopause();
        }

```

**Comment by Splamy** [comment]
> I tried a lot but i only get error messages in the console. "Checktopause()" has no return

I guess you are trying to return something in the `Checktopause` methods, but you shouldn't. I can't tell more without seeing more code

**Comment by marv-th** [comment]
Thanks for your respond.
Here is the Checktopause function. I allready tried to write ``return "ok";`` and change ``Task`` to ``Task<string>`` but this doesn't worked.

```csharp
public async Task Checktopause()
        {

            string bot_id = ConfBot.Name;
            string ispause = config_values_songinfo[bot_id]["ispause"];
            Logger.Info("ispause: " + ispause);
            if (ispause == "0")
            {
                Logger.Info("checkto pause ausgeführt");
                if (bot_id == null)
                {
                    //player.Paused = false;
                    Logger.Info("No Botid set");
                }
                else
                {
                    string autopause = config_values_songinfo[bot_id]["autopause"];

                    if (autopause == "1")
                    {
                        Logger.Info("autopause aktiv");
                        ChannelId? own_channelid = null;
                        own_channelid = book.Self().Channel;
                        Logger.Info("channel" + own_channelid);

                        if (own_channelid != null)
                        {
                            Logger.Info("clid: " + book.Self().Id);
                            if (book.Self().Id == null)
                            {
                                player.Paused = false;
                                Logger.Info("Could not get Client.WhoAmI");
                            }
                            else
                            {
                                int clientsinownchannel = 0;
                                var clientlist = await Client.ClientList();
                                if (clientlist.Ok)
                                {

                                    Logger.Info("Could get Clientlist {}");
                                    int own_client_found = 0;
                                    Logger.Info("4");
                                    foreach (var client in clientlist.Value)
                                    {
                                        if (client == null)
                                        {
                                            Logger.Info("Client ist null");
                                        }
                                        else
                                        {
                                            Logger.Info("Client ist nicht null");
                                            Logger.Info("client channel: " + client.ChannelId);
                                            if (client.ChannelId == own_channelid)
                                            {
                                                if (client.ClientId == book.Self().Id)
                                                {
                                                    own_client_found = 1;
                                                }
                                                else
                                                {
                                                    clientsinownchannel++;
                                                }
                                            }
                                        }

                                    }
                                    if (own_client_found == 1)
                                    {
                                        if (clientsinownchannel == 0)
                                        {
                                            player.Paused = true;
                                        }
                                        else
                                        {
                                            player.Paused = false;
                                        }
                                    }
                                    else
                                    {
                                        Logger.Info("Could not fetch client in channel {" + own_channelid + "}");
                                        player.Paused = false;
                                    }

                                }
                                else
                                {
                                    Logger.Info("Colud not get clientlist");
                                }


                            }

                        }
                        else
                        {
                            player.Paused = false;
                            Logger.Info("could not get own channel id");
                        }


                    }

                }
            }
            else
            {
                Logger.Info("check to pause wird nicht ausgeführt, da pause aktiv ist.");
            }
        }
```

**Comment by Splamy** [comment]
Does this code try to check if the bot is alone in a channel?
Because there's already a event that tacks exactly that: `Ts3Client.OnAloneChanged` and in the eventargs you can get `.Alone` which indicates whether the bot is alone in a channel or not

Also you don't need `ClientList`, `TsFullClient.Book` is a serialized view of the entire server. Basically everthing that the normal teamspeak3 client also sees that you are using

And the exact error text from the console/log would be helpful incase you want to continue on your codebase here. I can't find anything obvious wrong

**Comment by marv-th** [comment]
Hey. So i worked now with the OnAloneChanged Event but this doesnt worked. 
``Ts3Client.OnAloneChanged += (s, e) => Checkalone();`` and ``Ts3Client.OnAloneChanged += Checkalone;`` doesn't work. 
In the function i tried the result method ``throw new NotImplementedException();``, ``return null;``, ``return "abc";`` and set the ``Task`` to ``Task<string>``. 
But this doesn't worked.

Errormessages are:
- Nicht alle Codepfade geben einen Wert zurück




```csharp

public void Initialize()
        {
            global_bot_id = ConfBot.Name;
            config_values_songinfo.Add(global_bot_id, new Dictionary<string, string>());

            Logger.Info("Plugin geladen");

            config_values_songinfo[global_bot_id]["ispause"] = "0";

            Client.OnEachClientPoke += (s, e) => eclimove();
            Ts3Client.OnAloneChanged += Checkalone;

        }


private Task Checkalone(object sender, AloneChanged value)
        {
            string bot_id = ConfBot.Name;
            string ispause = config_values_songinfo[bot_id]["ispause"];
            string autopause = config_values_songinfo[bot_id]["autopause"];

            Logger.Info("ispause: " + ispause);

            if (bot_id==null)
            {
                if (autopause=="1")
                {
                    if (ispause == "0")
                    {
                        if (value.Alone)
                        {
                            player.Paused = true;
                        } else
                        {
                            player.Paused = false;
                        }
                    }
                    
                }
                throw new NotImplementedException();
            }
        }
```

**Comment by Flakebi** [comment]
`Checkalone` has the return value `Task` but neither returns a `Task`, nor is async. You need to
1. either change the return type to `void`
2. or mark `Checkalone` as `async` (this implicitly returns a `Task`)
3. or create and return a Task.

**Comment by marv-th** [comment]
When i do it so, than i get the error message, that the await operator are missed, but when i change ``player.Paused = true`` to ``await player.Paused = true``, than i get the message, that bool has no defination for GetAwaiter();
When i change ``private async Task Checkalone(object sender, AloneChanged value)`` to ``private void Checkalone(object sender, AloneChanged value)`` vs says "Der Rückgabetyp von [//Function//] ist falsch"
```csharp

public void Initialize()
        {
            global_bot_id = ConfBot.Name;
            config_values_songinfo.Add(global_bot_id, new Dictionary<string, string>());

            Logger.Info("Plugin geladen");

            config_values_songinfo[global_bot_id]["ispause"] = "0";

            Client.OnEachClientPoke += (s, e) => eclimove();
            Ts3Client.OnAloneChanged += Checkalone;

        }


private async Task Checkalone(object sender, AloneChanged value)
        {
            string bot_id = ConfBot.Name;
            string ispause = config_values_songinfo[bot_id]["ispause"];
            string autopause = config_values_songinfo[bot_id]["autopause"];

            Logger.Info("ispause: " + ispause);

            if (bot_id==null)
            {
                if (autopause=="1")
                {
                    if (ispause == "0")
                    {
                        if (value.Alone)
                        {
                            player.Paused = true;
                        } else
                        {
                            player.Paused = false;
                        }
                    }
                    
                }
                //throw new NotImplementedException();
            }
        }
```

**Comment by Splamy** [comment]
Ok, some C# basics:

A normal Function returning a `void` or `int` will look like
`void FuncVoid() { /*code*/ }` or `int FuncInt() { /*code*/ return 42; }`
Now in async terms:

When a function returns a `Task` or `Task<T>` this means the function returned an asynchroneous operation to you.
You can either discard/ignore the `Task`/`Task<T>` and it will just run in the backround until it's completed.
Or you can `await` the task.

To do so you will have to mark your method `async`, for example with the previous two functions:
`async void FuncVoid() { /*code*/ }` or `async Task FuncVoid() { /*code*/ }`
But the compiler won't let us do this:
`async int FuncInt() { /*code*/ return 42; }`
because it woudn't make sense. The `async` makes this run in the background, but the function does not return a `Task` or `Task<T>` which means you can't `await` it, so the `int` returned could never get read anywhere.
So you will have to declare it like this `async Task<int> FuncInt() { /*code*/ return 42; }`

Lets get back to the `FuncVoid`, if you declare it the first way the `async` will make it run in the background, but since it returns `void` you can't await it. Example:
```csharp
bool hasLoaded = false;

public async void DoStuff() {
    MyAsyncLoader(); // We can't await it, the function will run in the background when we call it.
    Console.Write(hasLoaded) // This will print false !!!
}

public async void MyAsyncLoader() {
    await DownloadWebsite("google.de");
    hasLoaded = true;
}
````

The problem of `async void` it you can't write `await` it in `DoStuff` since `void` has no information of the asyncroneous operation.
Now lets redeclare our functions:
```csharp
bool hasLoaded = false;

public async void DoStuff() {
    await MyAsyncLoader(); // MyAsyncLoader returns a 'Task', we can now await it
    Console.Write(hasLoaded) // This will print true
}

public async Task MyAsyncLoader() {
    await DownloadWebsite("google.de");
    hasLoaded = true;
}
````

Now to get to events:
A normal event will take with `+=`  a function of the form
`void FuncName(object sender, EventArgs e)`

This means we can't pass a function returning a `Task`, but we can still mark our function async:

```csharp
myEvent += MyFunc;

async void MyFunc(object sender, EventArgs e) {
    // stuff
}
```

The `async void` will make the function non-awaitable, but we don't care since the event has no reason to wait for the completion of the registered functions.

So in your case:
```csharp
Ts3Client.OnAloneChanged += Checkalone;

private async void Checkalone(object sender, AloneChanged value){
    // Stuff
}
// If you don't use any 'await's in your code you can also remove your 'async'
private void Checkalone(object sender, AloneChanged value){
    // Stuff
}
```

**Comment by marv-th** [comment]
Thanks for the description but i think i found the misstake.
The method is now so declared: ``Task Checkalone(object sender, AloneChanged value)`` and i missed to add at the end of the method ``throw new NotImplementedException();``. The only thing is, that i dont know, what this method do.

**Comment by Splamy** [comment]
I forgt you are using develop. Well I'm trying some experimental async event handlers. `OnAloneChanged` is one of them.
You can either declare your function `async Task Checkalone(object sender, AloneChanged value)`
or declare it `async Task Checkalone(object sender, AloneChanged value)` and return `return Task.CompletedTask;` at the end.

**Comment by marv-th** [comment]
Thanks for the information. I will try it in the next time and tell you more.
