### ISSUE TITLE
Its not playing Youtube non-music categorized videos

### ISSUE THREAD

**Issue by WebShark025** [Splamy/TS3AudioBot#798]
**Describe the bug**
So, The bot is not playing any kind of youtube links which is not categorized as 'Music'. For example, it wont play videos which are under 'People & Blogs' category
Sometimes, it won't play any videos at all, even music. I think this is due to the high amount of requests, so no complaints.

I've tried switching the server's location, from Germany to the UK to Singapore, with no differences.

**Version**
Version: 0.11.3
Branch: master
CommitHash: 24c92032b61bf8bb663f379e64b812de818218ed

**Platform**
Ubuntu 18 dotnet 2.2  &  Windows 10 

**Log**
In the console, it shows this:
```
11:33:22.9941| INFO|0| Song queue ended: No next song could be played.
```
Tried !stop !play ing , no differences.

**Comment by Fredwuz** [comment]
Had the same problem updated the youtube-dl and it worked again

**Comment by WebShark025** [comment]
> Had the same problem updated the youtube-dl and it worked again

Im on the latest version I guess. Pulled directly from the GitHub repo

**Comment by Fredwuz** [comment]
hmm ok I downloaded it from the website http://ytdl-org.github.io/youtube-dl/download.html maybe try this

**Comment by WebShark025** [comment]
> hmm ok I downloaded it from the website http://ytdl-org.github.io/youtube-dl/download.html maybe try this

Yeap just confirmed, Im on the exact same version.

**Comment by Splamy** [comment]
have you tried clearing the youtube-dl cache `youtube-dl --rm-cache-dir`
Also what happens when you just try to get a link like `youtube-dl -g <link>`

**Comment by WebShark025** [comment]
> have you tried clearing the youtube-dl cache `youtube-dl --rm-cache-dir`
> Also what happens when you just try to get a link like `youtube-dl -g <youtube-link>`

Hmm... tried downloading any video with youtube-dl cmd, it failed with 'Youtube said: Invalid Parameters' but the bot is working

On my other server in Germany, which is running on windows 10, all of the videos download, even those ones which won't play in the bot.

**Comment by Splamy** [comment]
If youtube-dl can't load a video there's nothing much we can do.
If it loads but the bot doesn't play it it might be a bot bug.

**Comment by oscsystemx** [comment]
i have that problem too
