### ISSUE TITLE
Problem install Linux Debian

### ISSUE THREAD

**Issue by DvnBthlo** [Splamy/TS3AudioBot#80]
Hello I have a problem with installation on linux : http://prntscr.com/f90hyc 

If i write xbuild /p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln ->
http://prntscr.com/f90ioq

**Comment by lgund** [comment]
You need to install nuget over apt-get command :)

**Comment by DvnBthlo** [comment]
I install nuget via apt-get install nuget

**Comment by Splamy** [comment]
You could try one of these:
```
$ sudo mozroots --import --sync
```
```
$ sudo mozroots --import --sync --url https://hg.mozilla.org/mozilla-central/raw-file/tip/security‌​/nss/lib/ckfw/builti‌​ns/certdata.txt
```
```
$ sudo mozroots --import --machine --sync
$ sudo certmgr -ssl -m https://go.microsoft.com
$ sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net
$ sudo certmgr -ssl -m https://nuget.org
```
as described [here](stackoverflow.com/a/16589218/2444047) and [here](http://stackoverflow.com/a/30970569/2444047)

**Comment by LEpEX** [comment]
![screenshot 31](https://cloud.githubusercontent.com/assets/28847472/26404364/efcb8d6a-4091-11e7-96d2-4c5410c773d5.png)
Funktioniert Irgendwie auch nicht

**Comment by LEpEX** [comment]
![screenshot 32](https://cloud.githubusercontent.com/assets/28847472/26464010/8e551646-4186-11e7-80c3-f3f407f75096.png)
Ich glaube ich bin einfach zu unfähing kann das sein xd

**Comment by Splamy** [comment]
probier bitte nochmal:
`sudo mozroots --import --sync --url https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt?raw=1`
Ja der code sieht identisch zu der einen vorher aus, allerdings hatte der vorhin anscheinend einen encodingfehler

**Comment by LEpEX** [comment]
![screenshot 33](https://cloud.githubusercontent.com/assets/28847472/26467143/9c3b892e-4191-11e7-8865-3b45876e741c.png)
will auch nicht

**Comment by Splamy** [comment]
@DvnBthlo Hey can you give me your current mono version? You can get it with `mono -V`. Please notice that the current master branch requires a mono verison of 4.0.0 or higher, and the current develop branch 5.0.0 or higher. Debian by default only offers a very old mono version so you probably have to upgrade manually or change to a faster updating linux distro like ubuntu etc..

**Comment by NeoChontrix** [comment]
I can run it with mono 5.0.1.1 but not with 5.0.0.0 
(I have to recheck it since the different versions where on two different machines with two different linux distros)

**Comment by Splamy** [comment]
thats strange we had mono 5.0.0.100 too and it worked fine

**Comment by NeoChontrix** [comment]
Just rechecked all stuff and it is not mono that caused the problem, will investigate it tomorrow how to fix it

**Comment by NeoChontrix** [comment]
@LEpEX 

von https://github.com/yar229/WebDavMailRuCloud/issues/56

Yeah, this helps, thanks!
`
# cat /etc/ssl/certs/* >ca-bundle.crt
# cert-sync ca-bundle.crt
# rm ca-bundle.crt
`

**Comment by Splamy** [comment]
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.
