### ISSUE TITLE
How can I add a Youtube search command to TS3AudioBot?

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#800]
Hello

How can I add a Youtube search command to TS3AudioBot?

11:50:25.3105|ERROR|| Could not save new bot. Ensure that the bot has access to the directory.
11:50:25.3105|ERROR|| Can't find a WebInterface path to host. Try specifying the path to host in the config
11:50:25.3359|ERROR|| Can't find a WebInterface path to host. Try specifying the path to host in the config
11:50:25.5409| INFO|| Started Webserver on port 58913

Help me

**Comment by Splamy** [comment]
You mean this: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs ?
Also how is this log related to the problem?
