### ISSUE TITLE
Plugins hinzufügen

### ISSUE THREAD

**Issue by xElten** [Splamy/TS3AudioBot#805]
Ich habe dieses Plugin (https://github.com/Birk3n/TS3Spotify) hinzugefügt, jedoch wird es nicht in der Plugin liste angezeigt.

**Comment by Splamy** [comment]
Did you compile it as an dll and put it in the plugin folder? You haven't provided any useful information

**Comment by xElten** [comment]
yes https://prnt.sc/sn828o https://prnt.sc/sn82mg https://prnt.sc/sms711

**Comment by Flakebi** [comment]
Uppercase and lowercase makes a difference, so either rename the folder from `plugins` to `Plugins` or rename the config entry from `Plugins` to `plugins`.

**Comment by xElten** [comment]
I have already renamed the folder in config

**Comment by xElten** [comment]
https://prnt.sc/sn9a38

**Comment by Flakebi** [comment]
I guess there is an error message in the log?

**Comment by Flakebi** [comment]
Please comment or reopen if the issue is still unsolved.
