### ISSUE TITLE
Change bot name

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#814]
Hello

Can I turn off the change of bot name from the settings of an installed bot? For example, through the rights.toml file

**Comment by Flakebi** [comment]
Sure, every command has an associated permission, so if you remove the `cmd.bot.name` permission (or don’t grant it in the first place), nobody can change the name.

More information can be found in the wiki: https://github.com/Splamy/TS3AudioBot/wiki/Rights

**Comment by farfik1** [comment]
These are written in the rights file. Which exactly do I need to delete?

"+" = [
	# Basic stuff
	"cmd.help.*",
	"cmd.pm",
	"cmd.subscribe",
	"cmd.unsubscribe",
	"cmd.kickme.*",
	"cmd.version",
	
	# Getting song info
	"cmd.song",
	"cmd.repeat",
	"cmd.random",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
	"cmd.xecute",
	"cmd.getmy.*",
	"cmd.json.*",
	"cmd.bot.use",
	"cmd.rights.can",

"+" = [
		# Play controls
		"cmd.play",
		"cmd.pause",
		"cmd.stop",
		"cmd.seek",
		"cmd.volume",
		"cmd.yt",

		# Playlist management
		"cmd.list.*",
		"cmd.add",
		"cmd.clear",
		"cmd.previous",
		"cmd.next",
		"cmd.random.*",
		"cmd.repeat.*",

		# History features
		"cmd.history.add",
		"cmd.history.from",
		"cmd.history.id",
		"cmd.history.last",
		"cmd.history.play",
		"cmd.history.till",
		"cmd.history.title",

**Comment by Flakebi** [comment]
I don’t see `cmd.bot.name` in the excerpt you posted, so people should not be able to change the bot name.
(Did I misunderstand your question?)

**Comment by farfik1** [comment]
You got my question right. it doesn't have a name command, but it can change it. What should I do ?

**Comment by Flakebi** [comment]
Are you in the admin group?
By default there is a rule that allows `*` (everything), if that matches for you, you are allowed to change the name.

**Comment by farfik1** [comment]
# Admin rule
[[rule]]
	# Set your admin Group Ids here, ex: [ 13, 42 ]
	groupid = [2216]
	# And/Or your admin Client Uids here
	useruid = [ "" ]
	# By default treat requests from localhost as admin
	ip = [ "127.0.0.1", "::1" ]

I guess I had tried userid before and the commands didn't work

**Comment by Flakebi** [comment]
So, do you still have a problem?

And if so, are you in the admin group? And can you upload your whole rights.toml, e.g. on https://gist.github.com?

**Comment by farfik1** [comment]
Yeah I'm still having the problem

https://gist.github.com/farfik1/d900a5a1c51bc2893b18b7d760f96dce

I uploaded the rights file

**Comment by Flakebi** [comment]
Thanks, I tried out your rights.toml. Line 41 in there grants all rights (`"+" = "*"`).
So the people that have rights to rename the bot (and do everything else) fulfill *at least* one of the following points (block from line 41 onwards):
- `groupid = [ 4273 ]`: Members of the group 4273: I guess you are in that group
- `useruid = [ "" ]`: People with an empty userid: That makes no sense, you can change that to `useruid = []` or just remove this line
- `ip = [ "127.0.0.1", "::1" ]`: Api requests from localhost: Allowed by default
- `isapi = true`: All api requests: You need to have a firewall that disallows outside requests to the bot, otherwise, you should **remove this line**. It means everyone that can access the api interface of the bot can completely control it. Access from localhost are allowed by the line above

So, with your current settings, people can change the bot name over api or over TS if they are in group 4273.

**Comment by farfik1** [comment]
I did not understand anything. Can you set the rights file that I throw at you accordingly? I just want the users not to change the Bot name. They can use other standard commands

**Comment by Flakebi** [comment]
Ok, do you want that people in group 4273 can change the name?
If not, you can just delete line 41 (`"+" = "*") and changing the bot name is not possible any more.

**Comment by farfik1** [comment]
I did this, yes, it does not work, change name but it is closed in many command. For example, youtube search does not work

**Comment by Flakebi** [comment]
Not sure if I understood you, changing the name still works? How do you change the name?

For youtube search, you need to add `"cmd.search.*", "cmd.param"` to your `rights.toml` so it looks like this:
```toml

"+" = [

...

	"cmd.json.*",
	"cmd.bot.use",
	"cmd.rights.can",
	"cmd.search.*",
	"cmd.param",
]
```

**Comment by farfik1** [comment]
The name has not changed. However, the youtube search command was also canceled. I will try the commands you gave

**Comment by farfik1** [comment]
Yes, thank you for your help. But I have one more question. How can I give a user the right to change their name? When I open a song, it opens the song, but it says I am not authorized. We need to solve this too :) I share the current rights file with you

https://gist.github.com/farfik1/c333caafd00cb05c142378472ebcefcd

@Flakebi

**Comment by Bluscream** [comment]
This looks like its going to get a lost-in-translation issue

**Comment by farfik1** [comment]
Another problem is that I can't login to the bot panel when I set this setting

"Error getting bot list"

@Bluscream @Flakebi

**Comment by Flakebi** [comment]
"Error getting bot list" can be solved by adding the `cmd.bot.list` permission. You probably also want `cmd.system.info` for the webinterface.

What do you mean with ‘change their name’? And what means ‘it says I am not authorized’?

**Comment by farfik1** [comment]
I haven't tried what you said but it's still the same. What am I doing wrong?

https://gist.github.com/farfik1/a074a457c3cdd30374e8b2e2bfefe68e

**Comment by Flakebi** [comment]
I guess the “have not” in your sentence is a translation error.

Can you try to remove this whole section?
```toml
# Admin rule
[[rule]]
	# Set your admin Group Ids here, ex: [ 13, 42 ]
	groupid = [ 4273 ]
	# And/Or your admin Client Uids here
	useruid = [ "K+eJlnYaLh8jBaty+NoBlfJn6M4=", ]
	# By default treat requests from localhost as admin
	ip = [ "127.0.0.1", "::1" ]
    isapi = true
	"-" = "*"
```

**Comment by farfik1** [comment]
I did what she said but this didn't happen

**Comment by farfik1** [comment]
After making these settings, the bot does not announce the songs. How can I fix this? Shows the song that plays only when I use this command !song
