### ISSUE TITLE
Change disconnect message

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [Splamy/TS3AudioBot#816]
I want to change the message when my bot is leaving the TeamSpeak3-Server. For example: "Bot (Test)" hat die Verbindung getrennt (I'm outta here).

**Comment by Flakebi** [comment]
Hi, you need to change the code for this, so roughly
1. Download the code
1. Search the codebase for `I'm outta here`
1. Change the messages you find there to your liking
1. Compile the bot
1. Have fun
