### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [Splamy/TS3AudioBot#817]
Hey,

I want to change the language myself. I dont won't to download the present I want to change everything myself can I find the language files anywhere in the code?

**Comment by Flakebi** [comment]
Hi, this faq entry should get you started: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#text-responses

**Comment by GlaubeKeinemDev** [comment]
This faq entry does not help me

**Comment by Flakebi** [comment]
Ok, if you want to change messages for yourself, you need to
1. download the source code from GitHub, preferably with git,
2. change the messages in [TS3AudioBot/Localization/strings.resx](https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Localization/strings.resx),
3. compile the bot,
4. the bot will have the changed messages now.

If you want to help translate the bot, see the translation section in the readme: https://github.com/Splamy/TS3AudioBot#localization

If I misunderstood what you want to do, please correct me.
