### ISSUE TITLE
Remove API token

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [Splamy/TS3AudioBot#818]
Hey there,

I want to remove the api token function, so you do not need a api token anymore. Is there any option I can do for that? And thank you for the helpful answers in the past.

**Comment by Flakebi** [comment]
Hi, I’m not completely sure if I understand what you want to achieve in the end, so if my answer goes in the wrong direction, please correct me.

The `rights.toml` has a matcher for the source ip, so you can allow e.g. all api requests from localhost:
```toml
# Admin rule
[[rule]]
	# Treat requests from localhost as admin
	ip = [ "127.0.0.1", "::1" ]
	"+" = "*"
```

You can also allow all api request, **this allows every person on the internet to take control over the bot** unless you forbid access with a firewall, so you should only allow uncritical commands.
```toml
[[rule]]
	isapi = true
	"+" = [
		"cmd.help.*",
		"cmd.song",
	]
```

**Comment by Bluscream** [comment]
I think he wants api access without actually using a token to log in. something like a "guest account" maybe?

**Comment by GlaubeKeinemDev** [comment]
Bluscream yeah I want Something Like this. I want to have an Admin Access to the web Panel and the web api without generating an API Key. If i have a Static API Key die the Panel that would be also ok but I dont want to generate an API Key by texting with the bot on TeamSpeak.

**Comment by Flakebi** [comment]
The my answer should be the right one, the first snippet allows you to do everything with the api from localhost without any api key.

Api keys that are not bound to a TeamSpeak user are not yet implemented.

**Comment by GlaubeKeinemDev** [comment]
I just want to remove this feature, so I can work with the web API without authorize with any api key.

**Comment by Flakebi** [comment]
That’s what the snippets I posted allow you to do. They allow using the api without any api key.

For the sake of completeness, a third variant that allows anyone from any ip to use any command:
```toml
[[rule]]
	isapi = true
	"+" = "*"
```

**Comment by GlaubeKeinemDev** [comment]
Ah nice worked fine for me. And my next question is how can I remove bot commands (teamspeak) where is the code for it

**Comment by Splamy** [comment]
All commands are in the `TS3AudioBot/MainCommands.cs`

**Comment by Bluscream** [comment]
Why not just deny permissions to commands you dont want to be able to use?
