### ISSUE TITLE
youtube-dl error - ERROR: Unable to download webpage: HTTP Error 429:

### ISSUE THREAD

**Issue by JonaxGames** [Splamy/TS3AudioBot#819]
**Describe the bug**
Youtube-dl does not work since some days. I bought a new vps to host more bots. I'm using this provider since years and didn't had any problems. At the first moment, all worked fine, but since 2 days, i cant play any youtube videos. It tried a lot, but i didn't find any soloution. Does somebody know how to fix this?

**Version**
Version: 0.10.1+4
Branch: master
CommitHash: cdf0318b0a86d4c2fb88d5f3ef0a251185f65c88

**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
debian 10 buster
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)

Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Log**
```

18:49:04.0083| INFO|| [============ TS3AudioBot started =============]
18:49:04.0443| INFO|| [ Date/Time: Monday, June 29, 2020 6:49:04 PM
18:49:04.0490| INFO|| [ Version: 0.10.1+4/master/cdf0318b
18:49:04.0496| INFO|| [ Platform: Debian GNU/Linux 10 (buster) (64bit)
18:49:04.0496| INFO|| [ Runtime: Mono (5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)) ServerGC:False GC:Interactive
18:49:04.0496| INFO|| [ Opus: libopus 1.1.3 (x64)
18:49:04.0496| INFO|| [==============================================]
18:49:04.5731| INFO|| Bot "default" connecting to "next4gamers.de:9987"
18:49:05.1812| INFO|0| Bot "default"(0) connected.
18:49:25.6692| INFO|0| User Jonax requested: !play https://www.youtube.com/watch?v=m2Y73luWCuo
18:49:25.7402| WARN|0| Right "cmd.list.save" is not registered.
18:49:25.9955| WARN|0| Web error: [429] 429
18:49:27.7354|ERROR|0| youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Flakebi** [comment]
Hi, we have an faq entry for this: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#429-too-many-requests
Unfortunately you hit the rate limiting of youtube, there is not much we can do about this. There are some people who are proxying requests to circumvent this error (but I never did this myself, so I cannot help there).
I *think* in theory the blocking can be lifted by solving captchas from the blocked ip.

If you manage to get something working, we would be interested to add it to the faq. There are a couple of people with frequented bots that face this problem.

**Comment by JonaxGames** [comment]
Alright.  I will do my best 👍

**Comment by JonaxGames** [comment]
> Hi, we have an faq entry for this: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#429-too-many-requests
> Unfortunately you hit the rate limiting of youtube, there is not much we can do about this. There are some people who are proxying requests to circumvent this error (but I never did this myself, so I cannot help there).
> I _think_ in theory the blocking can be lifted by solving captchas from the blocked ip.
> 
> If you manage to get something working, we would be interested to add it to the faq. There are a couple of people with frequented bots that face this problem.

Hey,

i fixed it. I just used a proxy. Some http/socks proxys doesn't worked for me. The most proxys with Port: 8080 are working fine for me. Choose an proxy which is pingable from your source-server. Another option would be to buy a proxys from an proxy-provider. I will host my own proxy from my home connection. So there shouldn't be any trouble.

Free HQ Proxy Homepages:

https://www.sslproxies.org/
https://www.socks-proxy.net/
http://spys.one/en/
