### ISSUE TITLE
nuget Problem

### ISSUE THREAD

**Issue by LEpEX** [Splamy/TS3AudioBot#82]
![screenshot 30](https://cloud.githubusercontent.com/assets/28847472/26364624/3cf2c85e-3fe5-11e7-9a2a-211352af8450.png)
Weiß du warum das kommt ?

**Comment by Splamy** [comment]
Wenn du ubuntu/debian verwendest könntest du das testen:
https://github.com/Splamy/TS3AudioBot/issues/80#issuecomment-302225719

**Comment by LEpEX** [comment]
![screenshot 31](https://cloud.githubusercontent.com/assets/28847472/26456249/d32576b8-416c-11e7-98bc-6cfda8022bfa.png)
Funktioniert irgendwie nicht

**Comment by Splamy** [comment]
nun all die befehle helfen nicht wenn du mozroots nicht vorher installierst,
es sollte im `mono-devel` paket mit drinnen sein:
`sudo apt-get install mono-devel`

**Comment by Splamy** [comment]
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.
