### ISSUE TITLE
TS3AudioBot setup error

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#822]
Hello, TS3Audiobot setup I get the error below. How can I solve it?

Commands I use : 

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-2.1

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y aspnetcore-runtime-2.1

sudo apt-get install -y dotnet-runtime-2.1

VPS OS : 16.04.6 LTS

/usr/share/dotnet/sdk/2.1.807/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [/home/TS3AudioBot/TSLib/TSLib.csproj]
/usr/share/dotnet/sdk/2.1.807/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [/home/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj]

**Comment by Flakebi** [comment]
You installed dotnet core 2.1 but as the error message tells, you need 2.2 for the version you downloaded.

**Comment by farfik1** [comment]
I use Ubuntu 16 and ubuntu 18. Can you pass the necessary codes?

**Comment by Flakebi** [comment]
You can also use the native version (only the develop is supported at the moment), then you don’t need to install a framework: https://splamy.de/api/nightly/ts3ab/develop_linux_x64/download

**Comment by farfik1** [comment]
Which is the development version? I am installing dotnet 2.2 but I get an error. Can you pass dotnet commands exactly?

**Comment by Flakebi** [comment]
You can run these commands to get and run the bot:
```bash
curl -o AudioBot.tar.gz https://splamy.de/api/nightly/ts3ab/develop_linux_x64/download
tar xf AudioBot.tar.gz
./TS3AudioBot
```

**Comment by farfik1** [comment]
@Flakebi 

./TS3AudioBot
13:28:10.8036|ERROR|Core| Failed to load library "libopus".
13:28:11.2874|ERROR|Core| Couldn't find libopus. Make sure it is installed or placed in the correct folder.

**Comment by Flakebi** [comment]
You need to install the dependencies too: https://github.com/Splamy/TS3AudioBot#install
(`sudo apt-get install libopus-dev ffmpeg`)

**Comment by farfik1** [comment]
@Flakebi 

Yeah that's good for speed. But I have to upload open source code files. I've done it before. But microsoft's website has changed a little. I get an error when I install dotnet core 2.2


wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

The commands I installed are respectively:

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-2.2

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y aspnetcore-runtime-2.2

sudo apt-get install -y dotnet-runtime-2.2


dotnet build --framework netcoreapp2.2 --configuration Release TS3AudioBot


/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/home/TS3AudioBot/TSLib/TSLib.csproj]
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/home/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj]

**Comment by farfik1** [comment]
@Flakebi 

OK, I took care of everything. All I need is to change the description of the Bot's commands, where can I do this?

**Comment by Flakebi** [comment]
Good to hear. Here is an faq entry to change the descriptions: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#text-responses

**Comment by farfik1** [comment]
@Flakebi 

Ok I already found this. Now the problem. There is an instant interruption while playing a song. This is momentary but very frustrating how can I fix this?

**Comment by Splamy** [comment]
Sorry this issue seems to got buried; does the issue still persist? If yes could you describe what you mean with
> There is an instant interruption while playing a song

**Comment by Flakebi** [comment]
I hope this issue is resolved now. If not, please comment or reopen.
