### ISSUE TITLE
Import of youtube playlist

### ISSUE THREAD

**Issue by JonaxGames** [Splamy/TS3AudioBot#824]
**Describe the bug**
I can't import youtube playlists

**To Reproduce**
- Add Proxy to Youtube-dll
- apt upgrade/update

**Version**
Version: 0.10.1+4
Branch: master
CommitHash: cdf0318b0a86d4c2fb88d5f3ef0a251185f65c88

**Platform**
debian 10 buster

Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
root@v2257 ~ # dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
**Log**
```
17:45:47.4521| INFO|0| User Jonax requested: !list
17:45:55.1481| INFO|0| User Jonax requested: !List create ncs
17:46:17.1637| INFO|0| User Jonax requested: !list import ncs https://www.youtube.com/playlist?list=PLhy8TB5U6n17R78U7usaLQfCC8nbnG8Nc
17:46:17.3223| WARN|0| Web error: [400] BadRequest


from logfile
2020-07-02 17:39:05.3223| INFO|0|Bot.OnMessageReceived User Jonax requested: !list import ncs https://www.youtube.com/playlist?list=PLhy8TB5U6n17R78U7usaLQfCC8nbn$
2020-07-02 17:39:05.4579| WARN|0|WebWrapper.ToLoggedError Web error: [400] BadRequest
System.Net.WebException: The remote server returned an error: (400) Bad Request.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x0017e] in <a9a08$
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`$
  at System.Net.HttpWebRequest.GetResponse () [0x00019] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
  at TS3AudioBot.Helper.WebWrapper.DownloadString (System.String& site, System.Uri link, System.ValueTuple`2[System.String,System.String][] headers) [0x0006d] in $

```

**Comment by Splamy** [comment]
Do you have set a youtube-api key set in your config by any chance? If yes you should remove it or make sure it's valid

**Comment by JonaxGames** [comment]
Hi,
where can i set/remove this key?

**Comment by Splamy** [comment]
In the ts3audiobot.toml under `factories.youtube.youtube_api_key`

**Comment by JonaxGames** [comment]
`factories.youtube.youtube_api_key` is missing in my ts3audiobot.toml

**Comment by Splamy** [comment]
Oh, I see, your version is too old, you should update to 0.10.3 (current master) there's a patch for resolving youtube stuff
