### ISSUE TITLE
Problems with Compilation

### ISSUE THREAD

**Issue by Shadowdevil2** [Splamy/TS3AudioBot#83]
I can´t do the last step, because i don´t have a binary folder in TS3AudioBot. I do have one in TS3Client. Should i copy it there?
Im talking about this step:
"Get the ffmpeg binary from ffmpeg-git-*DATE*-64bit-static\ffmpeg and copy it to TS3AudioBot/bin/Release/"

**Comment by Splamy** [comment]
There should definitely be a folder when everything went right.
What is the output of the build command?

**Comment by Shadowdevil2** [comment]
i got some errors in the previous steps. I will try it again tomorrow. Thank you for your help.

**Comment by Splamy** [comment]
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.
