### ISSUE TITLE
[API] multiple settings request

### ISSUE THREAD

**Issue by AgentSlim** [Splamy/TS3AudioBot#831]
DE:
Hallo, 
ich wollte mal fragen, ob der Befehl xecute auch geht, wenn ich nur was mit Settings mache also z.b. url:port/api/(/xecute/(%commands%)

Geht darum, ich möchte über die API ein Boterstellen und gleichzeitig die Settings setzen so das ich nicht mehrere Anfragen senden muss.

EN:
Hello, 
I wanted to ask if the command xecute works if I only do something with settings, e.g. url:port/api/(/xecute/(%commands%)

Is that I want to use the API to create a bot and set the settings at the same time so that I don't have to send multiple requests.

Branch: master
Version: 0.11.0
CommitHash: 4f17b29

**Comment by Splamy** [comment]
the command structure works the same in chat and from api. So yes you can chain any commands together with it. There is also a second similar command called `json merge` which is only available from api, which basically does the same as execute, but does not stop executing when one command failed and instead just returns `null` in the returned array for that command.
Here an example from our wiki: `https://github.com/Splamy/TS3AudioBot/wiki/WebAPI#json-merge`

**Comment by AgentSlim** [comment]
okey 

i have this url

http://host:port/api/json/merge/(/settings/create/TestBot0002)/(/settings/bot/set/TestBot0002/connect.address/127.0.0.1)

Result:
[ null, null]

is the url wrong?

**Comment by Splamy** [comment]
no, the two commands just don't have any return value

**Comment by AgentSlim** [comment]
but the bot has not been created

**Comment by AgentSlim** [comment]
Ohh thanks, I didn't see there was a second page with the bot on it.
