### ISSUE TITLE
How to bot respond on command?

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#837]
Hello,

I want to make bot respond on commands like !play, !volume, !stop, etc etc..
Like this:
![image](https://user-images.githubusercontent.com/60288878/88401639-469cf200-cdca-11ea-9b85-5649161143bf.png)

How to do that?

**Comment by hazzeee** [comment]
@Splamy anyone?

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Bot.cs#L480-L481
You could change these two lines to:
```csharp
if (!string.IsNullOrEmpty(s))
	s = "Ok";
info.Write(s).UnwrapToLog(Log);
```

**Comment by hazzeee** [comment]
> https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Bot.cs#L480-L481
> You could change these two lines to:
> 
> ```cs
> if (string.IsNullOrEmpty(s))
> 	s = "Ok";
> info.Write(s).UnwrapToLog(Log);
> ```

@Splamy and then how to compile bot, and install it, for linux?

**Comment by Splamy** [comment]
it's all in the readme

**Comment by hazzeee** [comment]
I dont see readme bruh ahah, can you give me link please?

**Comment by hazzeee** [comment]
Oh i saw it, thanks!
