### ISSUE TITLE
whisper issue

### ISSUE THREAD

**Issue by davlast** [Splamy/TS3AudioBot#84]
Hi, just want to say thanks for all your hard work, i have managed to get it to run on my raspberry pi, which is the only bot i could find which would run on arm or x86

i have a problem with the whisper function, sometimes when guests connect, they hear the music, which ever channel i move them to it just plays for them, and because of the settings i have put in they cannot see or talk to the bot and therefor they cannot unsubscribe or mute it, so i have to give them user access for them to mute the bot, is this normal.
Also if i subscribe channel and then unsubscribe channel, when the next song plays it will sometimes play in the channel i just told it to unsubscribe from and then also be playing to everyone on the server,

Also just a suggestion/issue, when  you submit the "!play" or "!list play" command it plays in that channel u submitted it from, is there a way to stop it from doing that, as if i wanted it to play to that channel i would use the "!subscribe channel" command, cause there are other people in the channel who dont want the music, and the people who want to listen to the music just use the "!subscribe" command

**Comment by Splamy** [comment]
This is issue I've seen rising a few times lately and it is already in planning to rework it. The reason why it's so clunky is because it's tailored to our own ts3 server preferences and usage habits. Over the time the bot has gained some attention and we see that this might not be the way how eveyone wants to use it. We will (hopefully) provide an exhaustive possiblity to configure it to each ones preferences.
Until then you can read here _why_ it is behaving the way it does right now:
https://github.com/Splamy/TS3AudioBot/issues/62#issuecomment-292378220

**Comment by Splamy** [comment]
`!unsubscribe channel reset` doesnt exist, thats what my other comment was suggesting

**Comment by Splamy** [comment]
There now is a new setting available on the dev branch
`AudioFramework::AudioMode`
to customize where the bot should play.
For your case I'd recommend setting it to an empty command or so like
`AudioFramework::AudioMode=!x` <- this should do nothing.
Then you can go ahead an manually subscribe channels with `!su c` for your current channel or `!su c <channelid>` for other channel or `!su` to sub to yourself

**Comment by davlast** [comment]
thanks so much, so far working great, will keep testing

**Comment by davlast** [comment]
i tried AudioFramework::AudioMode=!x
the bot still whispers to people when they join the ts server who dont subscribe to it, so not sure what is happening there, so i have set up the needed whisper permissions on again so the bot cannot whisper to guests, and cannot whisper to certain channels at all

At the moment am using the voice setting, so it plays in the music channel for everyone who joins and then you can subscribe to it if u want to listen in another channel, which works well for me, thanks

**Comment by Splamy** [comment]
I think I know why he might whisper to wrong people. Just to poke a bit around: do people subscribe and leave without unsubscribing?

**Comment by robotrono** [comment]
Same problem

>  do people subscribe and leave without unsubscribing?

I think that's why

**Comment by Splamy** [comment]
Yeah, for some reason I disabled clearing left users, but I don't know why.. When I see no problems I will simply re-enable it...

**Comment by davlast** [comment]
the setting on my system is that guests cannot even see the bot and therefore cannot even talk to it, so they cannot subscribe to it, and then when it does whisper/play to them they cannot unsubscribe from it unless i give them music permission so they can see the bot and then unsub. Its seems like it plays to everyone cause i think people with normal user just mute the bot and dont say anything to me, only sometimes they say something.

if i am subscribed and then leave and come back in i have to subscribe again, it doesnt carry on playing for me (serveradmin) but tried it with a guest now, changed settings so the guest can see the bot, i subscribed and then unsub, left the server and when i came back in, it was playing for the guest again,

**Comment by Splamy** [comment]
I don't think this has anything to do with visibility. The ids from teamspeak are not given linearly but freed and reused when people leave and join. So in the few tests you did you probably one time didn't get the same id so the bot didn't play to you, and the other time you received and id which was still subbed...
Just a question, why do you not allow people to see the bot? Wouldn't it be easier to just set up a right group with the audiobot and assign in to that group for that? The template rights file that comes with the bot makes it very easy.

**Comment by davlast** [comment]
since you have added the rights permission, i have allowed everyone now to see the bot, people were just sending commands to the bot and screwing around with it so thats why i hid it,

what you say makes sense, i thought the bot would play to the users unique ID, didnt know it played like you said, problem is now that new users who dont know how the bot works connects and then they get music blastered to them, which is now why i have added needed whisper power to guest so the bot cant play to them, and then if i give them the music permission or if they go into the music channel they can listen which works fine, thanks for the rights file

**Comment by Splamy** [comment]
I will make a fix shortly

**Comment by JABirchall** [comment]
Maybe don't have the bot in the default channel???

**Comment by Splamy** [comment]
the channel is not the problem when in whisper mode, read the conversation ;)

**Comment by Splamy** [comment]
Ok I pushed an update on the dev branch which should hopefully fix this problem

**Comment by davlast** [comment]
thanks, will test

**Comment by davlast** [comment]
It seems like it is still playing to people who dont subscribe, i have "voice" setting on so it plays in the channel it is in and people can subscibe to it. When i connect, the bot plays music to me in all channels i go to, and if i go into the channel the bot is in and then go out to another channel it stops playing. Anything I should try or change

**Comment by Splamy** [comment]
Can you ensure that the bot can see everybody?
So `i_channel_subscribe_power` should be high enough to see everybody.
If the bot looses vision to you he has to assume you disconnected.

On the other hand I cant explain why he should still whisper to wrong people, maybe I will add a few more logs to diagnose that problem better

**Comment by davlast** [comment]
i_channel_subscribe_power is 75 for the bot. Dont really have a problem with it not playing anymore when you leave the channel the bot is in, you can just subscribe to it again, just thought i let you know.

Had a problem now though, i could not subscribe to the bot but if i go into the channel it was playing, had to restart the bot for it to work again, hopefully it was just a once off

**Comment by Splamy** [comment]
On a side note here, I did some changes recently to the subscriptions mode, can you test if this problem still persists?

**Comment by davlast** [comment]
hi, thanks, i am away for 2 weeks, but will test and let you know

**Comment by Splamy** [comment]
whenever you have time...

**Comment by davlast** [comment]
thanks, haven't had any problems so far, 
was wondering is there a way to view who and what channels are subscribed to the bot

**Comment by Splamy** [comment]
hmm yes can do that. I will add something like `whisper list`
