### ISSUE TITLE
How to change command prefix in TS3AudioBot source?

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#841]
Hello,

How to change command prefix in TS3AudioBot source?

Thanks!

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/c7e44e4dfd5d5240cd5d8cbe4fa1f20a0315aca4/TS3AudioBot/CommandSystem/CommandParser.cs#L19

note that changing this can and will break internal commands if you don't also update them (Like aliases and commands in config files, or defaults in Bot.cs)
