### ISSUE TITLE
Cant compile bot on linux

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#842]
Hello,

i tried to compile bot on linux with .NET core 3.3, but it says i need 2.2,
can you please give me link or commands to install it on ubuntu 18 and debian 10, i tried with readme but i cant

**Comment by Splamy** [comment]
There is no `.NET core 3.3`
You will need to install `dotnet-sdk-2.2` if you want to compile the current master. Alternatively you can checkout develop an compile with (i presume you have installed 3.1) your version.

**Comment by hazzeee** [comment]
@Splamy 

![image](https://user-images.githubusercontent.com/60288878/89229740-4f6ba000-d5e2-11ea-9981-a9b6361e86b6.png)

**Comment by hazzeee** [comment]
fixed!

**Comment by robotrono** [comment]
@hazzeee what is the fix? I get same error.

**Comment by Splamy** [comment]
Did you include the `--framework netcoreapp2.2` as shown in the readme https://github.com/Splamy/TS3AudioBot#linux-1 ?
