### ISSUE TITLE
How to adjust Youtube search?

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#844]
Hello

How to adjust Youtube search? Which file will I include these commands in?

Needed something relaxing to implement today, so I did this; have fun.
The raw commands works like !search from <factory> <search query>
It might seem a bit clunky, but that is by design as it is automatically generated for factories.

If you just want a !yt and !ytp command, simply add those two aliases:
!alias add yt "!search from youtube (!param 0)"
!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"

then you can use:

!yt rammstein sonne will display the found results

Found the following songs. Use "!select <number>" to play.
0: Rammstein - Sonne (Official Video)
1: Rammstein - Sonne (lyrics) HD
2: Rammstein - Sonne / PROSHOT(Download Festival 2016) HD [GER/ENG/RU/ES/FR]

**Comment by Splamy** [comment]
You execure these two command simply be sending them to the bot you want them to add to:
`!alias add yt "!search from youtube (!param 0)"`
`!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"`

Then they are stored in the bot.toml and can be used on that bot as described with `!yt stuff...`
