### ISSUE TITLE
Set default channel via cfg and commandsystem?

### ISSUE THREAD

**Issue by eliassjogreen** [Splamy/TS3AudioBot#85]

**Comment by Splamy** [comment]
Latest dev branch has an option to specify the default channel.
You can eiter use a path like `Home/Lobby` or `Home/Afk \\/ Not Here`
Or specify the channel by id with `/<id>` like that: `/42`
You can get the channel id you are currently in with `!getuser channel`, and you can set the config value at runtime with `!settings QueryConnection::DefaultChannel "<value>"` (Dont forget to quote your value string if it has spaces!)
