### ISSUE TITLE
Does the bot now also support default channels via the web interface?

### ISSUE THREAD

**Issue by NiclasPe** [Splamy/TS3AudioBot#850]
Hey, mal eine kleine Frage:

Unterstützt der Bot jetzt die defaut Channel Funktion beim joinen?

Thanks for Help and this cool Projekt!

**Comment by Splamy** [comment]
Setting the default channel via interface does not work yet.
However you can set it by command:
`!settings set connect.channel "/5"` for example to join the channel with id 5
from the config help:
```ini
#Default channel when connecting. Use a channel path or "/<id>".
#Examples: "Home/Lobby", "/5", "Home/Afk \\/ Not Here".
```

**Comment by NiclasPe** [comment]
Hey, thanks for your Support. It works fine!
