### ISSUE TITLE
Is it possible to create users to control panel and limit number of instances for that user?

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#854]
Hello,

I want to sell music bots, and i wanted to ask is it possible etc if customer buy 1 bot, to create user for him on control panel and limit it for only 1, and etc if someone buy 4 bots, create panel for him and limit it for 4 bot instances.

Thanks!

**Comment by Splamy** [comment]
That would first require a proper user management system as well as something like an 'ownership' relation between bots and users. Neither of those are currently implementes or planned. For now you will have to manage something like this via your own backend/management system
