### ISSUE TITLE
Web interface not working

### ISSUE THREAD

**Issue by Bezolowsky** [Splamy/TS3AudioBot#856]
Hi,
I have installed the bot and i don't have the WebInterface, when i go to page <myip>:58913, that doesn't work. There is screen:
![image](https://user-images.githubusercontent.com/30776820/91462073-0ed21000-e88a-11ea-8f34-37c751c79a64.png)

**Comment by Flakebi** [comment]
Did you start the bot?
Does it show anything in the log?

**Comment by Bezolowsky** [comment]
@Flakebi, Yes, when I start the bot, logs are okey, there is screen:
![image](https://user-images.githubusercontent.com/30776820/91496190-fb3f9d00-e8bb-11ea-8c39-586752686ba1.png)

**Comment by Bezolowsky** [comment]
@Flakebi Yes, when I start the bot, I think that logs are okey, there is screen:
![image](https://user-images.githubusercontent.com/30776820/91496320-380b9400-e8bc-11ea-8c09-3a95b2f565ad.png)

**Comment by MateuszLas421** [comment]
I have similar problem. I moved the bot from another server to the server with tsapps and mariadb & phpmyadmin. TS3Audiobot  the bot works but web server not working. 
![image](https://user-images.githubusercontent.com/36116587/91503705-7bb9ca00-e8cb-11ea-9d29-3c4ef39a44f2.png)
![image](https://user-images.githubusercontent.com/36116587/91503728-8aa07c80-e8cb-11ea-8c74-ed634d079462.png)

**Comment by KredensKuchenny** [comment]
hmmm web interface works fine 
![obraz](https://user-images.githubusercontent.com/61777542/91504030-4661ac00-e8cc-11ea-95af-0c8b064c72f1.png)

**Comment by Bezolowsky** [comment]
Can someone know, what of php, apache, etc. must I have? I have installed only php7 and apache, I don't have this oders

**Comment by Splamy** [comment]
You need none of that, make sure that no firewall is blocking ports.
You can also try to send `!bot diagnose` to the bot, it can check whether your local files are ok

**Comment by Bezolowsky** [comment]
@Splamy with bot is everythink okay, i was addet to iptables this port, but that doesn't work after all.
There are screens:
![image](https://user-images.githubusercontent.com/30776820/91637207-2682d300-ea07-11ea-9829-fbd45f6d8294.png)
![1](https://user-images.githubusercontent.com/30776820/91637210-2b478700-ea07-11ea-94b1-5a728e3b3a4a.png)

**Comment by Bezolowsky** [comment]
There is another screen, from iptables
![image](https://user-images.githubusercontent.com/30776820/91637363-2df6ac00-ea08-11ea-9705-95e3ee43bfd0.png)

**Comment by Flakebi** [comment]
Can you show the output of `netstat -tlpn` please?
That lists all currently listening servers.

**Comment by Bezolowsky** [comment]
@Flakebi Yes, please:
![image](https://user-images.githubusercontent.com/30776820/91638072-24237780-ea0d-11ea-8ae3-225dec8da3a8.png)

**Comment by Flakebi** [comment]
Thanks, looks like the server is running. Looking at the error message again, it’s only a 404 Not Found error, the server can be reached fine.
I guess only the web interface is not enabled (web api should be working). Can you set `web.interface.enabled` to true in the config? Should look somehow like this:
```toml
[web.interface]
#If you want to enable the webinterface.
enabled = true
#The webinterface folder to host. Leave empty to let the bot look for default locations.
path = ""
```

**Comment by Bezolowsky** [comment]
![image](https://user-images.githubusercontent.com/30776820/91638276-7d3fdb00-ea0e-11ea-8a5f-9f8faf7fb8eb.png)
As can you see, the web.interface is enabled. Maybe I should write the path of this folder with webinterface?

**Comment by Bezolowsky** [comment]
> As can you see, the web.interface is enabled. Maybe I should write the path of this folder with webinterface?

I checked it out, and unfortunately listing the folder location didn't help me either.

**Comment by Flakebi** [comment]
Did you compile the Audiobot yourself? Then you need to also compile the webinterface with npm.
Alternatively, download one of the packaged builds and copy the WebInterface folder from there.

**Comment by Bezolowsky** [comment]
No, I downloaded everything here from github and then followed the installation instructions. Everything works, but WebInterface won't work.

**Comment by Flakebi** [comment]
You will need to download nodejs/npm and run `npm run build:publish` then move the `Webinterface/build` folder in the same folder as the `TS3AudioBot.exe` and rename it to `Webinterface`. Or you can get the already built webinterface files from the nightly server.
(copied from https://github.com/Splamy/TS3AudioBot/issues/381#issuecomment-424864148)

**Comment by Bezolowsky** [comment]
Okey, now works, but how can i log in? Where can I get an auth token?
![image](https://user-images.githubusercontent.com/30776820/91639253-8ed8b100-ea15-11ea-9013-60e80609d31e.png)

**Comment by Flakebi** [comment]
Nice. Write `!api token` to the bot in a private chat and paste the answer into the login field on the website.
