### ISSUE TITLE
Branch: develop 2cae1819 - playlist CurrentPlayData

### ISSUE THREAD

**Issue by xpiREC** [Splamy/TS3AudioBot#857]
**Describe the bug**
No data in CurrentPlayData for next track in a playlist.

**How did I get there?**

1. !list import 1 https://www.youtube.com/watch?v=Nj2U6rhnucI&list=PLyORnIW1xT6waC0PNjAMj33FdK2ngL_ik
Importing a sample playlist.
2. !list play 1
I played a sample playlist.
3. !song
I checked the length of the song.
4. !seek 3:45
I rewound the song to advance to the next song in the playlist - it has no impact, I listened to the whole song and it's the same.
5. !info
I check if the transition has been made.
6. !song
I want to check the currently played song I get "There is nothing on right now ...".

**Version**

- 0.12.0-alpha.51/develop/2cae1819

**Platform**

- Windows 6.2.9200.0 (64bit)
- Debian GNU/Linux 9 (stretch) (64bit)

**Log**
-  No data in logs.

**Comment by Flakebi** [comment]
Thanks for the instructions on how to reproduce this.
For me, the first song is 3:08 long, so `!seek 3:45` lets the bot complain: `Error: The point of time is not within the song length.`
`!seek 3:08` works, the next song is started and as you describe, the bot changes to a sleeping avatar and tells `There is nothing on right now...` though it plays the song.

Skipping to the next song with `!next` works correctly by the way.

**Comment by Flakebi** [comment]
Should be fixed by 0c6f301
