### ISSUE TITLE
Unknown license type 9

### ISSUE THREAD

**Issue by MrSteelMiner** [Splamy/TS3AudioBot#860]
When trying to connect to a TeamSpeak server with a sponsorship licence, the bot aborts with error
`16:32:04.1920| WARN|0| Could not connect: custom_error: the command failed to execute: Failed to calculate shared secret: Unknown license type 9`

Could you please add support for the new sponsorship licence? :)

**Comment by Flakebi** [comment]
I pushed a fix to the develop branch, it should work now.

**Comment by MrSteelMiner** [comment]
Many thanks!
