### ISSUE TITLE
 undefined init error

### ISSUE THREAD

**Issue by xElten** [Splamy/TS3AudioBot#863]
16:10:49.0013| INFO Bot disconnecting.
16:10:49.0013| WARN Internal error (me==null)
16:10:49.9983| INFO Bot connecting...
16:10:51.0614| WARN Got undefined init error: 167903232
16:10:51.0614|DEBUG Bot disconnected. Reason: LeftServer
16:10:51.0614| INFO Bot disconnecting.
16:10:51.0614| WARN Internal error (me==null)
16:10:52.0526| INFO Bot connecting...
16:10:53.1183| WARN Got undefined init error: 167903232
16:10:53.1183|DEBUG Bot disconnected. Reason: LeftServer
16:10:53.1209| INFO Bot disconnecting.
16:10:53.1209| WARN Internal error (me==null)
16:10:54.1153| INFO Bot connecting...
16:10:55.1515| WARN Got undefined init error: 167903232
16:10:55.1541|DEBUG Bot disconnected. Reason: LeftServer
16:10:55.1541| INFO Bot disconnecting.
16:10:55.1584| WARN Internal error (me==null)
16:10:56.1498| INFO Bot connecting...
16:10:57.2024| WARN Got undefined init error: 167903232
16:10:57.2116|DEBUG Bot disconnected. Reason: LeftServer
16:10:57.2137| INFO Bot disconnecting.
16:10:57.2137| WARN Internal error (me==null)
16:10:58.2015| INFO Bot connecting...
16:10:59.2425| WARN Got undefined init error: 167903232
16:10:59.2425|DEBUG Bot disconnected. Reason: LeftServer
16:10:59.2454| INFO Bot disconnecting.
16:10:59.2454| WARN Internal error (me==null)
16:11:00.2408| INFO Bot connecting...
16:11:01.3202| WARN Got undefined init error: 167903232
16:11:01.3227|DEBUG Bot disconnected. Reason:

**Comment by Flakebi** [comment]
Do you have a way to reproduce this? E.g. does it always happen when connecting to a specific server?
