### ISSUE TITLE
About Dotnet

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#869]
Hello

I'm trying to install Dotnet to compile TS3AudioBot but I get an error. I'll talk about the error below. Can you specify the setup codes for Ubuntu 16 and 18?

Am I entering the code dotnet incorrectly?

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-2.2

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y aspnetcore-runtime-3.1

/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/home/TS3AudioBot/TSLib/TSLib.csproj]
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/home/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj]

**Comment by farfik1** [comment]
// Closed

**Comment by zumoshi** [comment]
On ubuntu 20.04 I used these:

To run:
```bash
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt update
sudo apt install dotnet-runtime-3.1
```
To compile:
```bash
sudo apt install dotnet-sdk-3.1
```
More info: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
