### ISSUE TITLE
User ID and no Whispering

### ISSUE THREAD

**Issue by derquno** [Splamy/TS3AudioBot#87]
Dear Splamy,

Is it possible to bind the bot to an user id and not to an group id?
i think that would be really nice.
And is it possible to set the talk mode to normal not to whispering?

regards from Germany

Adrian

**Comment by Splamy** [comment]
I assume with
> bind the bot to an user id

you mean instead of assigning an admin group, assigning an client. In that case: soon, I'm currently working on it and it's almost finished (I hope in 1-2 days)
And about
> And is it possible to set the talk mode to normal not to whispering?

Well this is on the todo list up next, if you need it right now and dont mind a few lines source code editing I can give you a short guide.

**Comment by derquno** [comment]
No Problem, i cant wait a few days thats no Problem.
Is there any way to contact you private?

**Comment by Splamy** [comment]
Sure! You can email me (see profile page) or hit me up on our ts3 server splamy.de

**Comment by MrBn100ful** [comment]
Hi Slamy,
i would like to now how to set to normal talk.

Thanks

**Comment by Splamy** [comment]
Sure thing:
In this file: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Ts3Full.cs#L282-L285
Remove lines 282, 284, 285 and recompile the project

**Comment by JABirchall** [comment]
If you mean client Uid, you can set the clients specific permissions without setting a group.

**Comment by Splamy** [comment]
There now is a new setting available on the dev branch
`AudioFramework::AudioMode=voice`
to tell the bot to use normal voice for playing.

**Comment by Splamy** [comment]
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.
