### ISSUE TITLE
Do you really want to quit? !(yes|no)

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#870]
Hello

I get such a warning at the !yt command. If I say yes the bot quits teamspeak. How can I turn this off? I don't want the bot to leave.  open the song with !yt

!yt https://youtu.be/V-qMVrCAhxQ

Music Bot
Do you really want to quit? !(yes|no)

**Comment by MateuszLas421** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ 
"
Q: Is there a way to search for YouTube songs (!yt) or search and play by title (!ytp)?

A: If you just want a !yt and !ytp/!yta command, simply add those two aliases:
!alias add yt "!search from youtube (!param 0)"
!alias add ytp "!xecute (!search from youtube (!param 0)) (!search play 0)"
!alias add yta "!xecute (!search from youtube (!param 0)) (!search add 0)"
"

**Comment by farfik1** [comment]
> https://github.com/Splamy/TS3AudioBot/wiki/FAQ
> "
> Q: Is there a way to search for YouTube songs (!yt) or search and play by title (!ytp)?
> 
> A: If you just want a !yt and !ytp/!yta command, simply add those two aliases:
> !alias add yt "!search from youtube (!param 0)"
> !alias add ytp "!xecute (!search from youtube (!param 0)) (!search play 0)"
> !alias add yta "!xecute (!search from youtube (!param 0)) (!search add 0)"
> "
> You must to write a private message to the bot by sending him this alias.


I have not been able to use the search command for 4-5 days. Does it work for you? I'm getting a youtube-dl error. But it works with links

**Comment by Flakebi** [comment]
The original issue has been solved. Please try to update youtube-dl if it doesn’t work, there is not much the audiobot can do if youtube-dl fails.
