### ISSUE TITLE
Cant create playlist

### ISSUE THREAD

**Issue by ghost** [Splamy/TS3AudioBot#874]
Hi, 

I cant create playlist...

![image](https://user-images.githubusercontent.com/60288878/98266824-059ca800-1f8b-11eb-842b-b784e06a1699.png)

How to fix this?

**Comment by Flakebi** [comment]
Sorry for the late answer, `!list create <list id> <title>` takes two parameters (see also here: https://tab.splamy.de/openapi/#/list/get_list_create__listId___title_), so it should work with `!list create mylist mylist`.
The id is used as a filename, so it is quite restrictive with respect to the characters that can be used. The title can be anything (i.e. contain spaces, slashes, etc.).
