### ISSUE TITLE
Website Offline 

### ISSUE THREAD

**Issue by xyz-scripts** [Splamy/TS3AudioBot#875]
Wieso ist die Website nicht mehr erreichbar? TS3AudioBot ist nicht mehr downloadbar 😕

**Comment by ShadowFM** [comment]
Try again. I tried the website splamy.de and for me it works fine

**Comment by Splamy** [comment]
Same, site is up and availble. Maybe our network provider had some hiccups yesterday...

**Comment by Flakebi** [comment]
Seems to work fine atm
