### ISSUE TITLE
Play music when a specific user joins

### ISSUE THREAD

**Issue by kinvaris** [Splamy/TS3AudioBot#877]
**Is your feature request related to a problem? Please describe.**
It is related to a similar issue that was solved with the event.onparty https://github.com/Splamy/TS3AudioBot/issues/464

**Describe the solution you'd like**
Maybe this is already possible through if else and such. But how do I get the id of the user that just joined the channel where the bot is present. 
I would like to play a song for a certain user when he/she joins the channel.

**Describe alternatives you've considered**
Using existing getuser command and if command to check who joined and play a certain sound.

**Comment by Flakebi** [comment]
This cannot be done with commands because there is no way to get the user that joined. I think the best solution is to write a plugin for that.
