### ISSUE TITLE
No match for argument:opus-devel

### ISSUE THREAD

**Issue by HappyWangzy** [Splamy/TS3AudioBot#878]
Centos8

**Comment by Flakebi** [comment]
According to this site, there should be an opus-devel package on CentOS 8: https://centos.pkgs.org/8/okey-x86_64/opus-devel-1.3-0.4.beta.el8.x86_64.rpm.html

**Comment by Flakebi** [comment]
I hope this is solved. If there are still problems, please reopen or create a new issue.
