### ISSUE TITLE
Commands available

### ISSUE THREAD

**Issue by Americanu** [Splamy/TS3AudioBot#879]
Hello, i would like to know where can i see all the commands the bot has by default. There is no page that has all the parameters and subparameters especially the api one

**Comment by Splamy** [comment]
https://tab.splamy.de/openapi/#/
The same list is also available when you run your own own ts3ab, at <webaddress:port>/openapi/

**Comment by Americanu** [comment]
thank you! also im not sure if it is related, i can ask this separately. what flags/commands do i need to allow so another users sees a specific bot on the webpanel?

**Comment by Splamy** [comment]
You can't specify viewability of bots per user right now. But you can filter acces per user/bot/etc. You can take a look the the permission examples here: https://github.com/Splamy/TS3AudioBot/wiki/Rights#examples
