### ISSUE TITLE
Simplify the token

### ISSUE THREAD

**Issue by MrBn100ful** [Splamy/TS3AudioBot#88]
Hello, first thanks for all the work on TS3AudioBot !
Can you please make it or give me the piece of code i have to change to make the token simple.

token simple = only the ts client id 

exemple:
Authorization: Basic base64( < username > ) 

Thanks

**Comment by Splamy** [comment]
That can be highly insecure, you can easily get clientids from all other users on a server and could execute commands as them.
Changing the code also might get a little complex.

I'm sorry but for now I will have to reject this request.

**Comment by MrBn100ful** [comment]
Hello, If you can't remove the random token. Can i make this token not random ?

Thanks

**Comment by JABirchall** [comment]
What do you mean simple token? do you mean the client Unique ID?

**Comment by Splamy** [comment]
I have thought about this and the admin/anoymous token should solve this problem
You will be able to declare a token which is not bound to a user but to a rule in the rights system

**Comment by Mareczin** [comment]
> I have thought about this and the admin/anoymous token should solve this problem
You will be able to declare a token which is not bound to a user but to a rule in the rights system

Any progress on this issue because something could not be changed what to restart? admin token in rights system.

**Comment by Splamy** [comment]
I'm currently working on a database rework, when the new DB works, all tokens can be saved permanently

**Comment by Splamy** [comment]
Ok tokens are now persistenly saved, as well as can be matched in the permission file.
Simply generate a token and match your uid or the token like that, to grant full permissions.

```
[[rule]]
  # either or both, as you want
  useruid = [ "uA0U7t4PBxdJ5TLnarsOHQh4/tY=" ]
  apitoken = [ "asdfVILDyaTYrOXh29XJXivxIqxaIDjf" ]

  "+" = "*"
```
