### ISSUE TITLE
Radio stream is not working (anymore)

### ISSUE THREAD

**Issue by cracker0dks** [Splamy/TS3AudioBot#880]
**Describe the bug**
This Radio stream was working till some days ago (And still playing in the browser): http://re2k.radioparty.pl:8000/ 
Other radio streams are working without problems -.-

**To Reproduce**
!play http://re2k.radioparty.pl:8000/

**Version**
Version: 0.11.0
Branch: master
CommitHash: c7e44e4dfd5d5240cd5d8cbe4fa1f20a0315aca4

**Platform**
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Log**
Ts3 Output:
```
<01:03:26> "theuser": !play http://re2k.radioparty.pl:8000/
<01:03:26> "MusicBot ♪": Error: Could not load. (media: Unknown request error.)
```
Bot Log: 
```
2020-12-03 00:03:26.0785| INFO|0|Bot.OnMessageReceived User theuser requested: !play [URL]http://re2k.radioparty.pl:8000/[/URL]
```
Bot logs shows no errors or something else. Thanks for help.

**Comment by Flakebi** [comment]
I can reproduce it on 0.11.0, the develop version works fine though.

**Comment by cracker0dks** [comment]
Thanks, I will try this!

**Comment by cracker0dks** [comment]
Sadly this didn't work for me. I did:
```
git checkout develop
dotnet build --framework netcoreapp3.1 --configuration Develop TS3AudioBot

dotnet /home/TS3AudioBot/TS3AudioBot/bin/Develop/netcoreapp3.1/TS3AudioBot.dll --non-interactive
17:26:07.7412| INFO|Core| [============ TS3AudioBot started =============]
17:26:07.8164| INFO|Core| [ Date: Sunday, 06 December 2020 17:26:07
17:26:07.8758| INFO|Core| [ Version: <?>/<?>/<?>
17:26:07.8758| INFO|Core| [ Build: <?>
17:26:07.8771| INFO|Core| [ Platform: Ubuntu 18.04.5 LTS (Bionic Beaver) (64bit)
17:26:07.8771| INFO|Core| [ Runtime: .NET Core (3.1.10) ServerGC:True GC:SustainedLowLatency
17:26:07.8771| INFO|Core| [ Opus: libopus 1.1.2 (x64)
17:26:07.8771| INFO|Core| [==============================================]
```
Still the same msg: ``17:26:11.1106| WARN|Core| Skipping: media: http://re2k.radioparty.pl:8000/ because Could not load. (Unknown request error.)``

Can you give me some hints please on how you build the dev version to get it working?

**Comment by Flakebi** [comment]
Seems like this server does not like user agents without a version. It should be fixed on the develop branch now. Can you try again?

**Comment by cracker0dks** [comment]
Thanks! Working!
