### ISSUE TITLE
Connect with hostname

### ISSUE THREAD

**Issue by Caaruzo** [Splamy/TS3AudioBot#885]
**Describe the bug**
Bot cant connect to ts server in local network when using hostname instead ip.

**To Reproduce**
be sure you have a hostname that successfully can be resolved into an ip, run the tsserver on it.
use this hostname instead an ip in bot.toml like:
address = "ts3server-app:9902"

**Version**
 Version: 0.11.0/master/c7e44e4d

**Platform**
Debian 10 x64
**13:44:05.6996| INFO|| Bot "Musikbot01" connecting to "ts3server-app:9902"
13:44:06.4803|ERROR|| There is either a problem with your connection configuration, or the bot has not all permissions it needs.
13:44:06.5400| INFO|| Bot (0) disconnecting.
13:44:06.5649|ERROR|| Could not instantiate bot: Bot failed to connect (Connect error)
13:44:07.0636| INFO|| Started Webserver on port 58913**

```

**Comment by Flakebi** [comment]
Can you try out the develop branch? Resolving hostnames changed there and should work as far as I see.

On the develop branch, hostname resolving happens here:
https://github.com/Splamy/TS3AudioBot/blob/508694c02e35f49582a50dda5bdd6b4836100698/TSLib/TsDnsResolver.cs#L243-L244

The documentation of `Dns.GetHostEntryAsync` claims to look into the `hosts` file and query a dns server only if the address is not found there.

If using the develop branch does not work:
Can you turn on the `Trace` log level in `NLog.config` and look for a line saying `Lookup dns: …`?

**Comment by Flakebi** [comment]
I hope this is solved. If there are still problems, please reopen or create a new issue.
