### ISSUE TITLE
I want to add a function

### ISSUE THREAD

**Issue by Mats324** [Splamy/TS3AudioBot#887]
I download this project and I Need ti add a function to ban users. How should i do it? 
I must use the plugins or commands?
Besides have you any documentation?

**Comment by Flakebi** [comment]
The wiki has some documentation: https://github.com/Splamy/TS3AudioBot/wiki
You need to write a plugin to ban users, there are no commands for that. Beware that you need to know C# to write plugins.

**Comment by Mats324** [comment]
I know C# but where must I write the plugin?

Il mer 16 dic 2020, 21:08 Sebastian Neubauer <notifications@github.com> ha
scritto:

**Comment by Mats324** [comment]
We haven't finish yet

**Comment by Mats324** [comment]
> The wiki has some documentation: https://github.com/Splamy/TS3AudioBot/wiki
> You need to write a plugin to ban users, there are no commands for that. Beware that you need to know C# to write plugins.

Where must I write the plugin? What folder?
