### ISSUE TITLE
Add support to search and play song name instead of link

### ISSUE THREAD

**Issue by davlast** [Splamy/TS3AudioBot#89]
is it possible to play/search song name instead of url/link of the song
so if you type in a name it will search youtube and it plays the first result it comes up with or it replies with top 3 results and you can choose which one you want

**Comment by JABirchall** [comment]
I would say no, since the library used [Youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#readme) Doesn't have this functionality and Ts3Audiobot supports multiple different sources, not just youtube.

**Comment by Splamy** [comment]
At the moment there is no such functionality.
Our AudioBot comes preconfigured with a youtube api key. This means we could use features like `v3/youtube.search.list` easily for a feature like that. I will add this idea to the backlog 👍

**Comment by Splamy** [comment]
//TODO add a search for media playlists (see #329)

**Comment by Bluscream** [comment]
https://github.com/Bluscream/TS3AudioBotPlugins/blob/develop/YoutubeSearch/plugin.cs

**Comment by heartles39** [comment]
How do we do this, please help

**Comment by Splamy** [comment]
Needed something relaxing to implement today, so I did this; have fun.
The raw commands works like `!search from <factory> <search query>`
It might seem a bit clunky, but that is by design as it is automatically generated for factories.

If you just want a `!yt` and `!ytp` command, simply add those two aliases:
`!alias add yt "!search from youtube (!param 0)"`
`!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"`

then you can use:

`!yt rammstein sonne` will display the found results
```
Found the following songs. Use "!select <number>" to play.
0: Rammstein - Sonne (Official Video)
1: Rammstein - Sonne (lyrics) HD
2: Rammstein - Sonne / PROSHOT(Download Festival 2016) HD [GER/ENG/RU/ES/FR]
   ...
```

`!ytp rammstein sonne` will search and automatically play the first result.

Oh and usually you'd have to add quotes (like "rammstein sonne") around stuff with spaces, but i also added another feature in the last patch, which will just take everything if there is only parameter. This should make a lot of calls more convenient.

**Comment by heartles39** [comment]
> Needed something relaxing to implement today, so I did this; have fun.
> The raw commands works like `!search from <factory> <search query>`
> It might seem a bit clunky, but that is by design as it is automatically generated for factories.
> 
> If you just want a `!yt` and `!ytp` command, simply add those two aliases:
> `!alias add yt "!search from youtube (!param 0)"`
> `!alias add ytp "!x (!search from youtube (!param 0)) (!select 0)"`
> 
> then you can use:
> 
> `!yt rammstein sonne` will display the found results
> 
> ```
> Found the following songs. Use "!select <number>" to play.
> 0: Rammstein - Sonne (Official Video)
> 1: Rammstein - Sonne (lyrics) HD
> 2: Rammstein - Sonne / PROSHOT(Download Festival 2016) HD [GER/ENG/RU/ES/FR]
>    ...
> ```
> 
> `!ytp rammstein sonne` will search and automatically play the first result.
> 
> Oh and usually you'd have to add quotes (like "rammstein sonne") around stuff with spaces, but i also added another feature in the last patch, which will just take everything if there is only parameter. This should make a lot of calls more convenient.

Do we have to set this to the files, is it set in your files?

**Comment by Splamy** [comment]
Set what to what files? There is nothing set in any files.
Just download the latest dev version, execute bot alias commands to create them, and you can use yt and ypt. Aliases will be saved in the config and loaded on startup

**Comment by heartles39** [comment]
> Set what to what files? There is nothing set in any files.
> Just download the latest dev version, execute both alias commands to create them, and you can use yt and ypt. Aliases will be saved in the config and loaded on startup

Can you please give me a link to the latest version?

**Comment by Splamy** [comment]
It's right in the readme: [![Download](https://img.shields.io/badge/Download-develop-green.svg)](https://splamy.de/api/nightly/ts3ab/develop/download)

**Comment by heartles39** [comment]
> It's right in the readme: [![Download](https://camo.githubusercontent.com/9c98a00010088fae8bc7e846506acd3c406daa3a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f446f776e6c6f61642d646576656c6f702d677265656e2e737667)](https://splamy.de/api/nightly/ts3ab/develop/download)

How do I install it on a ubuntu server? Is there an article about it?

**Comment by Splamy** [comment]
Yes also readme: https://github.com/Splamy/TS3AudioBot/tree/develop#install

**Comment by BOLESNI** [comment]
You can also add to add song to queue beside !select

**Comment by Splamy** [comment]
Almost forgot this...
yeah, I kinda want something too to add a song from the result list to the queue instead of directly playing. But I can't come up with a good name for a command that feels intuitive to use; maybe any of you have an idea.
