### ISSUE TITLE
Running bot on dotnet 3.1

### ISSUE THREAD

**Issue by lgund** [Splamy/TS3AudioBot#891]
**Describe the problem**
I am using Ubuntu 20.04 LTS and can´t install dotnet-sdk-2.2 anymore. But I can install 2.1, 3.1 and 5,0. All of them are installed but the script need version 2.2 is there a simply way to start the bot with a newer version?

**To Reproduce**
Start the bot with: `dotnet TS3AudioBot.dll`

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      2.1.23 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      3.1.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=ubuntu.20.04-x64

**System Information**
- **Platform**: Ubuntu 20.04 LTS
  
- **Which commit did you download**: Currently latest version

**Comment by Flakebi** [comment]
You need to download the dotnet 3.1 version then: https://splamy.de/TSAudioBot/Home
(Or use the Linux native version)

**Comment by lgund** [comment]
Worked fine for me 👍
