### ISSUE TITLE
Do you have documentation on the teamspeak voice protocol

### ISSUE THREAD

**Issue by schoeppi5** [Splamy/TS3AudioBot#893]
Hi there,
I have been looking into implementing a voice client for teamspeak myself using golang. In order to do that, I would need atleast a basic understanding of how the teamspeak server and client talk to each other.

Now I could go ahead and try to understand how you implemented it, but I was hoping you could point me to some form of a documentation of the protocol. Maybe you created something like this while working on this project?

Thanks in advance for any kind of help you can offer me.

**Comment by Flakebi** [comment]
The basics of the protocol are written down here: https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md
On the audio side, it’s opus in 48 000 kHz, a voice packet without audio data signals the end of a stream (though of course this packet can get lost, so don’t rely on it).

FYI, once you have a working client that can connect, sending audio is simple. If you want to go further, receiving and playing audio without stuttering is a more involved (there are some explaining comments in ReSpeak/tsclientlib#15).

**Comment by Flakebi** [comment]
In case you do not want to do all the ground work yourself, there are some libraries that implement the protocol.

- [TSLib](https://github.com/Splamy/TS3AudioBot/tree/master/TSLib) (C#), which is used in the AudioBot
- [tsclientlib](https://github.com/ReSpeak/tsclientlib/) (Rust)
- [ts3j](https://github.com/Manevolent/ts3j/) (Java)
