### ISSUE TITLE
 Continuous bot restarts

### ISSUE THREAD

**Issue by rosja1337** [Splamy/TS3AudioBot#894]
**Describe the problem**

Hello. Weird things started to happen with the bots for the last few hours. They keep coming in and out.
All I was doing was restarting the VPS

**System Information**
Ubuntu 16.04 LTS
  
- **Mono version**: (`mono -V`)  
   version 6.12.0.107 (tarball Thu Dec 10 05:25:45 UTC 2020)

- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
 Nightly Server
Version: 0.11.3
Branch: master
CommitHash: 24c92032b61bf8bb663f379e64b812de818218ed

**Additional Logs, Exceptions, etc**
[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/5829798/ts3audiobot.log)

**Comment by Bluscream** [comment]
Well, if you restart the VPS its obvious that the bots are also all restarting

**Comment by rosja1337** [comment]
I also know that much: p Maybe I misspelled the problem. After rebooting, VPS started crashing bots. They'll stay a minute, connection lost over and over again

**Comment by Flakebi** [comment]
Do you have a way to reproduce this by chance?
Could you collect a trace log of when that happen?
You can collect such a log file by editing the `NLog.config` (replace Debug/Info with `Trace`): https://github.com/Splamy/TS3AudioBot/wiki/Troubleshooting

**Comment by Flakebi** [comment]
I hope this is solved. If there are still problems, please reopen or create a new issue.
