### ISSUE TITLE
Bot startup onload problem

### ISSUE THREAD

**Issue by froland20** [Splamy/TS3AudioBot#896]
Hello,

I have a problem when I starting the bots.
Sometimes it manages to pass commands to the bot and sometimes it doesn’t

**Log warns:**
09:27:26.2740| WARN|2| Command Error (Cannot move there. (Ismeretlen TS3 hiba. (Connection closed)))
09:27:26.4582| WARN|3| Command Error (Cannot move there. (Ismeretlen TS3 hiba. (Connection closed)))
09:27:26.5813| WARN|4| Command Error (Cannot move there. (Ismeretlen TS3 hiba. (Connection closed)))

I added this commands to all bot template (**5 template**) and the bots starts **at once** when I start the ts3audiobot:

[events]
onconnect = "!x (!bot move '62195') (!vol '50') (!bot commander 'on')"

I attach a picture of what the problem is on my TeamSpeak 3 server.
(For example MusicBot - Radio 1, and MusicBot -1  bot is got bot commander on commands but the others not got it sadly.)

Maybe we should slow down the commands for the ts3audiobot? (they have b_client_ignore_antiflood permission on my ts3 server)

How should I slow down the commands for the ts3audiobot?

Anyone know what the problem might be?

Thanks,
froland20
![warns_on_ts3](https://user-images.githubusercontent.com/58860010/105474833-fc27ff80-5c9e-11eb-8dca-e8ce87594e0f.PNG)

**Comment by Flakebi** [comment]
Hi,

Can you try to set `channel = "/62195"` in the `[connect]` block of the bot configs instead of `!bot move` in onconnect? That should be more stable.
There could be a bug in the bot, that it tries to send the move command before it is completely connected.

**Comment by froland20** [comment]
> Hi,
> 
> Can you try to set `channel = "/62195"` in the `[connect]` block of the bot configs instead of `!bot move` in onconnect? That should be more stable.
> There could be a bug in the bot, that it tries to send the move command before it is completely connected.

Hi, now the commander and the connections is works well but theese are not:
Play, and vol is not working.
onconnect = "!x (!vol '50') (!bot commander 'on') (!play 'http://188.165.11.30:8080/risefm_hq') (!bot repeat 'all')"

**Comment by Flakebi** [comment]
Works fine for me on the `develop` branch (6fce0d95afd9e3d54ae5bb18d4687eeeb8312383).
Btw, it’s `!repeat all` (`!bot repeat all` does not exist).

**Comment by froland20** [comment]
Thanks.
