### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by ProxyPing** [Splamy/TS3AudioBot#897]
Hi, i have a Question.. how can i get the status from a bot from the api.. like online/offline...

**Comment by Flakebi** [comment]
There is a `!bot list` command, so the api url looks like this: `http://localhost:58913/api/bot/list`
The `Status` in the json response is this enum (0 = Offline, 1 = Connecting, 2 = Connected): https://github.com/Splamy/TS3AudioBot/blob/4f17b2971e03bee94d1e630a2b5ce37d8a15e5ca/TS3AudioBot/Bot.cs#L610-L615

The response looks like this:
```json
[
    {
        "Id": 0,
        "Name": "default",
        "Server": "loc",
        "Status": 2
    },
    {
        "Id": null,
        "Name": "new-server",
        "Server": "localhost:9988",
        "Status": 0
    }
]
```
