### ISSUE TITLE
YTDL error

### ISSUE THREAD

**Issue by peglasy** [Splamy/TS3AudioBot#899]
YTDL is constantly not working for me, I uninstalled ytdl and installed it again, updated it and it will not work again, when I go! Play and url from yt throw it out to me (Error: Could not load. (Youtube: youtube-dl failed to load the resource.)

**Comment by Flakebi** [comment]
You can try running `youtube-dl -xg '<youtube-link>'` on the server. If that fails, there is nothing the audiobot can do.
