### ISSUE TITLE
Simplified version of the bot

### ISSUE THREAD

**Issue by luzzbe** [Splamy/TS3AudioBot#90]
Hello,
I would like to know if it was possible to have a simplified version of the bot.
For my project I will only need commands !play !pause !stop and !exit.
I do not know much in C # so I can not edit the bot to remove all that I do not use.
I would like to make the bot as light as possible.
I'm sorry for my very bad English.

Thank you in advance for your help,
Luzzbe

**Comment by Splamy** [comment]
You can set up the rights file that only those few commands are available to everyone.
Removing all other commands from the code will give you little to no benefit at all. 
Most modules are essential for the bot so I can't disable them either, but they also almost need nothing.
The only somewhat bigger module with memory/io impact is the history, which indeed not everybody might need. I will see I can add an option to disable it.

**Comment by luzzbe** [comment]
Thank you for your reply.
If time permits, adding an option to disable the history would help me a lot.

**Comment by luzzbe** [comment]
Thank you very much <3
