### ISSUE TITLE
Help about dotnet

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#900]
Hello, I want to compile TS3Audiobot but I am getting this error. Can you pass me dotnet commands for ubuntu 16 and 18? When I try 2.2 I get this warning.

sudo apt-get install -y dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.1.11 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=ubuntu.20.04-x64

**Comment by deathbull** [comment]
install libicu then install dotnetcore
