### ISSUE TITLE
Restart BOT via API

### ISSUE THREAD

**Issue by MikkelDK** [Splamy/TS3AudioBot#901]
**Is your feature request related to a problem? Please describe.**
It could be nice if it was possible to restart "BOT" via API 

**Describe the solution you'd like**
Setup API/bot/restart (so BOT will disconnect/connect) - without needed to click: Stop and Start after few seconds.

**Describe alternatives you've considered**
N/A

**Comment by Flakebi** [comment]
If I understand that right, you can already do that with `!bot disconnect` and `!bot connect template default`.
The api request looks like this: `http://localhost:58913/api/xecute/(/bot/use/0/(/bot/disconnect/)/)/(/bot/connect/template/default`

**Comment by MikkelDK** [comment]
Hmmm. I was just thinking, about it was possible to make so "separate" bot can disconnect/connect like a "restart" button.

Is that possible?
Example:
```
 $.get("{ :app_url }api/bot/restart/" + id, function (data) {
```
or will I need to re-code, so it's possible?

**Comment by Flakebi** [comment]
Restarting a bot by id is not possible, once a bot is gone, it can’t be resurrected. But it works with bot template names.
So you can do `http://localhost:58913/api/xecute/(/bot/default/default/(/bot/disconnect/)/)/(/bot/connect/template/default`.
Or add an alias (though beware that aliases cannot be global atm, so they are bound to a bot (template)) like `!alias add "bot restart" "!xecute (!bot template (!param 0) (!bot disconnect)) (!bot connect template (!param 0))"`.

Why do you want to restart a bot?

**Comment by MikkelDK** [comment]
It's because; It could be a feature, so I don't need to stop the bot, and after few seconds start it again via "control-panel"

So I will need to make a "template" for each bot?

**Comment by Flakebi** [comment]
Yes.

Although, I still don’t get why you want a restart button. What is its purpose? Can’t you achieve the same result with other commands while the bot is running?

**Comment by MikkelDK** [comment]
Hmm, is there not other way, to make automatic bot template, so it's set automatic for each new bot i creating. Without to enter command manual om ts3?

Btw, because I want the function more. So it's possible to restart the bot, if it's stuck/crashed.

**Comment by Flakebi** [comment]
Currently, the only ways to create a bot template are `!bot save` or creating the folder and bot file manually.
If the bot got stuck or crashed, you should report that as a bug :)
