### ISSUE TITLE
Connection to database fails when restarting the bot

### ISSUE THREAD

**Issue by Sneakometer** [Splamy/TS3AudioBot#906]
**Describe the bug**
When restarting the TS3AudioBot on a freshly installed debian 10 system after the initial setup, it fails to connect to the database with a "database error". Tried reinstalling the the bot, dotnet core and ffmpeg/libopus multiple times with the exact same result.

**To Reproduce**
I can consistently reproduce this by just restarting the bot after the initial setup.
The first time (with the cli setup) the bot works fine, but when i restart it, it stops working.
It does not depend on what i enter during configuration. (like leaving the admin uid empty)

**Version**
0.11.0 
dotnet core 3.1.12

**Platform**
Debian 10 (buster)

**Log**
```
11:39:27.3111| WARN|0| Could not connect: database: the command failed to execute: database error
11:39:27.3129| INFO|0| Trying to reconnect because of Error. Delaying reconnect for 30 seconds
11:39:57.3405| WARN|0| Could not connect: database: the command failed to execute: database error
11:39:57.3405| INFO|0| Trying to reconnect because of Error. Delaying reconnect for 30 seconds
```
Full log is attached.
[ts3audiobot.log](https://github.com/Splamy/TS3AudioBot/files/6090259/ts3audiobot.log)

**Comment by Flakebi** [comment]
Hi,
I can unfortunately not reproduce this.
I tried the Dockerfile below and it works fine:
```dockerfile
FROM debian

RUN apt-get update && apt-get install -y wget libicu63 libopus-dev unzip
WORKDIR /root

# Install dotnet core
RUN wget https://download.visualstudio.microsoft.com/download/pr/6880db3b-a4fe-4801-8e80-bbbec045f7c0/283b70d5e263c0341f011adf5a2ea5b1/dotnet-runtime-3.1.13-linux-x64.tar.gz
RUN tar xf dotnet-runtime-3.1.13-linux-x64.tar.gz

# Install audiobot
RUN wget https://splamy.de/api/nightly/ts3ab/master_dotnet_core_3_1_preview/download && mv download audiobot.zip
RUN unzip audiobot.zip

CMD ./dotnet TS3AudioBot.dll
```

Steps I did:
1. Build docker image with `docker build . -t ts3ab`
2. Create container and start with `docker run -it ts3ab` and configure the bot.
3. Quit with ctrl+c
4. Find container id of new container with `docker ps --all` (first column)
5. Restart container with `docker start <container id or name>`

The bot connects fine the first and second time and does not show any errors (e.g. in `docker logs <container id or name>`).

**Comment by Sneakometer** [comment]
I did some further testing and it seems to be related to my teamspeak server. With another freshly installed server, the bot works fine. I'm not sure yet what causes the issue, but for now i think i can close the issue.
Thanks!
