### ISSUE TITLE
Loop Repeat function is broken

### ISSUE THREAD

**Issue by Rene-Roscher** [Splamy/TS3AudioBot#908]
Hello, maybe you have never noticed this bug, but there is a bug with the loop function and that is when the song repeats, it is no longer shown as current and the bot or API tells me that nothing is playing.

Would be happy if you could fixx this problem soon.  

**To Reproduce**
play a song and enable the loop function

**Version**
develop

**Platform**
Ubuntu 20.04

**Log**
```
nothing to log
```

**Comment by Flakebi** [comment]
Hi, this should be fixed since fcc3ab5eaacce3e2d448a2cb4e1891317aff3ff4. Can you try this or some later version on the `develop` branch?
Note that this commit did not make it to the splamy.de download page, so you need to build the bot yourself.

**Comment by Rene-Roscher** [comment]
Thanks for the quick reply, I already used the Develop and there it does not work unfortunately.

**Comment by Flakebi** [comment]
Can you post the output of `!version` please?
With loop do you mean the `!repeat one` command?

I tested
```
!play <something short>
!repeat one
<wait a few repeats>
!song
```
on commit fc47b01b4e86e7bd32cd381c6e45a598e4fc4a2f and it worked fine.

**Comment by Flakebi** [comment]
I hope this issue is solved. If not, please comment or reopen it.
