### ISSUE TITLE
Playlist import not working master branch.

### ISSUE THREAD

**Issue by rackieMods** [Splamy/TS3AudioBot#910]
**Describe the bug**
After I try to import list from youtube it shows this: Error: Could not load. (youtube: youtube-dl failed to load the resource.)

**Version**
Version: 0.11.3
Branch: master
CommitHash: 24c92032b61bf8bb663f379e64b812de818218ed

**Platform**
CentOS7
dotnet 2.2

**Log**
Logs don't show anything unusual, just bots connecting and disconnecting after I close it on machine.

**Comment by Flakebi** [comment]
Importing playlists works fine here on `develop` (I tried `!lis imp lis https://www.youtube.com/playlist?list=PLMmGHnPc3uPchkennqSDXZRjhryd2L57r`).
The error message suggests that it is a youtube/youtube-dl problem. Can you try updating youtube-dl?

**Comment by rackieMods** [comment]
Seems like it's up to date, I'll try on develop branch later.

**Comment by rackieMods** [comment]
I can't build the latest develop version. It seems like it also fails to build on main appveyor https://ci.appveyor.com/project/Splamy/ts3audiobot/branch/develop

How do I proceed now?

**Comment by Flakebi** [comment]
Good to hear that you got normal playlists working. The mix playlists were fixed recently in develop (5bcc8faa819db4c973fdfa3cd0423d03c984db01), they are not fixed in master.
The appveyor build is (almost) succeeding, only uploading the build artifacts to [splamy.de](https://splamy.de/TSAudioBot/Home) in the end fails. You need dotnetcore 3.1 to build develop (this branch does not support 2.2 anymore), maybe that’s the problem?

What is your build error?

**Comment by rackieMods** [comment]
Dotnetcore 3.1 did the thing, I compiled it but now I can't execute any command, there's this: 
`10:52:00.1287|ERROR|0| The rights file could not be parsed`
The path in ts3audiobot.toml for rights.toml is fine, don't see a reason why this happens.

**Comment by rackieMods** [comment]
Reopening because (unfortunately) another issue, not related to playlists (if I should create another issue then I'll close this one).
So on master branch I've had onidle event set to !bot move 33, which should move my bot to channel id 33 after 20 minutes of being idle (idletime set to 20m). However, it moves in random ways, all by itself or after executing command that doesn't make it play anything.

`11:23:24.2373| WARN|2| Command Error (Cannot move there. (already member of channel) ())
11:23:24.2535| WARN|1| Command Error (Cannot move there. (already member of channel) ())
11:23:24.2689| WARN|0| Command Error (Cannot move there. (already member of channel) ())
11:24:38.6434| WARN|1| Command Error (Cannot move there. (already member of channel) ())
11:24:38.6486| WARN|0| Command Error (Cannot move there. (already member of channel) ())
11:24:51.1774| WARN|0| Command Error (Cannot move there. (already member of channel) ())
11:24:51.1838| WARN|1| Command Error (Cannot move there. (already member of channel) ())
11:25:06.4720| WARN|0| Command Error (Cannot move there. (already member of channel) ())
`

**Comment by Flakebi** [comment]
We found some timer problems, linux seems to use a different scaling factor than windows in some places. It should work better now.

**Comment by rackieMods** [comment]
All good now, thanks!
