### ISSUE TITLE
How to setup the credentials to use with youtube-dl?

### ISSUE THREAD

**Issue by SR-Lut3t1um** [Splamy/TS3AudioBot#911]
**Describe the problem**
I cannot figure out where to store the youtube login credentials.

**To Reproduce**
Steps to reproduce the behavior

**System Information**
-  RHEL 8
 
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
- develop

**Comment by rackieMods** [comment]
You don't need any login information for youtube-dl to work.

**Comment by SR-Lut3t1um** [comment]
Does it also work on vids that would require premium to download?

**Comment by rackieMods** [comment]
No idea, you gotta try it yourself.

**Comment by SR-Lut3t1um** [comment]
No it is not possible without the login, there is also a open PR on youtube-dl to improve the bitrate while logged in to premium, so I guess being able to login / import the youtube cookie would be a nice touch :)

**Comment by Flakebi** [comment]
If youtube-dl has an option for that, you can just set in in the youtube-dl config file in `~/.config/youtube-dl/config` (https://github.com/ytdl-org/youtube-dl/#configuration).

**Comment by SR-Lut3t1um** [comment]
Thanks! I was able to setup the bot to use the youtube-dl with my login credentials!

**Comment by mhashirshah** [comment]
there is not issue for that thanks

**Comment by mhashirshah** [comment]
my name is hashir shah 
I am a web developer 
thanks for you.

**Comment by mhashirshah** [comment]
I have one year experience in html5  css3  bootstrap 
also in jquery

**Comment by mhashirshah** [comment]
please give a website design for working

**Comment by mhashirshah** [comment]
my gmail account : m.hashirshah@gmail.com

**Comment by meikmenzel** [comment]
@mhashirshah Cool, I have over 8 years experience. Thanks for you.

**Comment by Splamy** [comment]
@meikmenzel Idk, but that user really seems just like an automated spam bot, and if he doesn't answer I think I'll delete the comments

**Comment by meikmenzel** [comment]
@Splamy Thanks!

**Comment by SR-Lut3t1um** [comment]
Why would you spam Github issues tho? 🤔
