### ISSUE TITLE
API Simple Call

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#92]
Im trying to use the api with a simple call:

http://web.com:8180/api/history/last/10

But I get: `{"ErrorCode":2,"ErrorName":"Unauthorized","ErrorMessage":""}`

Console: 

```
[22:51:55]   Info: x.x.x.x Requested: /api/history/last/10
[22:51:55]  Debug: Not authorized!
[22:51:55]   Info: x.xx.x Requested: /favicon.ico
```

I need authorization to make this call?

Edit: I need https? Im trying to use a script in php to show the last 10 songs.

**Comment by Splamy** [comment]
You won't need https, but you will need an api-token to authenticate yourself.
Our (wiki)[https://github.com/Splamy/TS3AudioBot/wiki/WebAPI#authentication] has a good documentation about how to get started and use everything.  
If you run everything on the same machine (eg. localhost) there should be no problem using the basic auth (which is a lot simpler).
But if you access the api from two different locations you should either use the digest auth or proxy everthing with https + basic (both are good options dependig on your security needs)

**Comment by robotrono** [comment]
Hmm I see, this is my little script in php:

```
<?php
$login = 'uniqueid';
$password = 'token';
$url = 'http://localhost:8180/api/history/last/10';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, "$login:$password");
$result = curl_exec($ch);
curl_close($ch);  
echo($result);
?>
```
But I get: 

```
[19:55:48]   Info: 127.0.0.1 Requested: /api/history/last/10
[19:55:48]  Debug: Not authorized!
```

**Comment by Splamy** [comment]
I dont know exacly how this php script works but "$login:$password" must be base64 encoded afterwards

**Comment by robotrono** [comment]
Im trying this too:

curl -H "Authorization: Basic tokenBASE64" http://localhost:8180/api/history/last/10

but dont work

**Comment by Splamy** [comment]
No it's a problem on the bot side I found it, gimme a sec

**Comment by Splamy** [comment]
Dev branch update is out, this should work now. Please note that api token are not yet stored persistently, so if you restart the bot you'll have to get a new token.
(I hope my patch works; it works here on my side, and I'm going to bed now it's late :P)

**Comment by robotrono** [comment]
I will try, good night @Splamy

**Comment by robotrono** [comment]
Works fine now, thanks!

 http://i.imgur.com/3SYYoFi.png
