### ISSUE TITLE
How to update the bot from a develop build to the latest develop build?

### ISSUE THREAD

**Issue by Ammar7347** [Splamy/TS3AudioBot#920]
**Describe the problem**
I would like to know how can I update the bot to the latest develop build. I looked at the FAQs and tried finding it in the issues tab before opening this issue. Kindly guide me with comprehensive details since I'm not a Linux guru.

**System Information**
- **Platform**: (Ubuntu 20.04.1)
   
  
- **Which commit did you download**:  
Version: 0.12.0-alpha.52
Branch: develop
CommitHash: 6fce0d95afd9e3d54ae5bb18d4687eeeb8312383

Thanks

**Comment by Flakebi** [comment]
Hi, you can just overwrite the executable and webinterface files with the new version. So, if you downloaded the binaries from https://splamy.de/TSAudioBot/Home, simply download a new version, extract it and copy the files over your old ones.
