### ISSUE TITLE
Changing music in youtube playlist

### ISSUE THREAD

**Issue by Darktortue** [Splamy/TS3AudioBot#921]
**Describe the problem**
When launching a youtube playlist, the bot stays on the first music forever.

**To Reproduce**
- Launch bot
- Play a youtube playlist with `!play URL`
- Wait for the end of the music or do `!next`

**System Information**
- **Platform**: Debian 10 
  
- **Which commit did you download**: Prebuilt version **0.12.0** _TS3AudioBot_linux_x64.tar.gz_
  
I have not been able to launch a playlist with the playlist URL like [https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10](https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10) I'm getting an error : `Error: Could not load. (youtube: The id could not get parsed.)` I have to use the URL of the first video [https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10&index=1](https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10&index=1) but then it stays forever on the video as I said before.

I might be missing a command but I don't see anything related to playlists here : [https://tab.splamy.de/openapi/index.html#/](https://tab.splamy.de/openapi/index.html#/)

**Comment by MateuszLas421** [comment]
I think playlists(Youtube) are unsupported.

**Comment by Flakebi** [comment]
The playlist commands are those starting with `!list`.
So `!list import myplaylist https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10` and `!list play myplaylist` should work.
