### ISSUE TITLE
Can't stop quiz mode

### ISSUE THREAD

**Issue by Darktortue** [Splamy/TS3AudioBot#922]
**Describe the problem**
I can't stop quiz mode, I'm getting the error : `Error: No cheating! Everybody has to see it!`

**To Reproduce**
- Launch the bot
- `!quiz on`
- `!quiz off`

**System Information**
- **Platform**: Debian 10  
  
- **Which commit did you download**: Prebuilt version 0.12.0 TS3AudioBot_linux_x64.tar.gz 

By the way, I was alone on the server when I tested this, that's why I don't understand the error.

**Comment by Flakebi** [comment]
You need to write `!quiz off` in the channel or server chat, private chat is forbidden :)

**Comment by Darktortue** [comment]
Oh okay thank you :)
