### ISSUE TITLE
Do you really want to quit? !(yes|no)

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#924]
Hello

I get such a warning at the !yt command. If I say yes the bot quits teamspeak. How can I turn this off? I don't want the bot to leave. open the song with !yt

!yt https://youtu.be/V-qMVrCAhxQ

Music Bot
Do you really want to quit? !(yes|no)

**Comment by Flakebi** [comment]
You need to add these commands as aliases before you can use `!yt`: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs

**Comment by farfik1** [comment]
https://prnt.sc/153sf1q How can I compile the webpanel? I am getting an error like this

**Comment by Flakebi** [comment]
As the error message says, you need to install webpack.
