### ISSUE TITLE
Failed to load library "libopus"

### ISSUE THREAD

**Issue by adrian-abit** [Splamy/TS3AudioBot#925]
**Describe the problem**
I tried to start the bot but get this message:

21:40:59.8744|ERROR|Core| Failed to load library "libopus".
21:40:59.9280|ERROR|Core| Couldn't find libopus. Make sure it is installed or placed in the correct folder.

**To Reproduce**
I cloned the Repository into Rider and tried to run it via the run button.

that does a dotnet build and executes ../TS3AudioBot/bin/Debug/netcoreapp3.1/TS3AudioBot

**System Information**
- **Platform**: (Solus Budgie 10.5.3)  
  
- **Mono version**: (`mono -V`)  
```
 Mono JIT compiler version 6.12.0.122 (tarball Fri 23 Apr 2021 02:56:09 PM UTC)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
master : 4c6be03646d78cdbfe007ecc697596256ec23617

**Additional Logs, Exceptions, etc**
I couldn't download libopus-dev since it isn't available in the solus packet manager. So i went with opus and opus-devel

I also tried the InstallOpus.sh and got this log after extracting:

```
checking whether make supports nested variables... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/adrian/opus-1.3.1':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
'/urs/lib/libopus.so' already exists, will not be overwritten
Done
```

**Comment by Splamy** [comment]
Since you are running the current master I don't think you are actually using mono.
Try running `dotnet --info` and check that you have any dotnet core 3.1 sdk installed.
You also shouldn't need the InstallOpus script if you have installed it via your package manager already.
I have no experience with the Solus linux distribution, so I cannot tell why the library resolution fails. The ts3ab just uses normal runtime loading via dotnet which seems to work fine on the most common distros.
If nothing helps maybe try copying the `/usr/lib/libopus.so` in the same folder as the ts3ab binary

**Comment by Flakebi** [comment]
Some more ideas to debug library loading:

Do you have an up-to-date version of libopus installed? (1.2 or 1.3 are known to work)
Maybe it works when you set `LD_LIBRARY_PATH=/usr/lib` when running the bot?
If not, setting `LD_DEBUG=libs` should give some debug output and tell if and where libopus is searched for.
