### ISSUE TITLE
Play a specific list, if nothing else is playing

### ISSUE THREAD

**Issue by TrickShotMLG02** [Splamy/TS3AudioBot#927]
Am i able to set a default list which will be played, when the bot connects and if no other songs are playing/queued?

**Comment by Splamy** [comment]
You could set the idle event with a low trigger timer to play something.
For example
`!settings set events.idletime 5s` <- Trigger action when doing nothing for 5 seconds
`!settings set events.onidle "!play song.mp3"` <- Play a song
or
`!settings set events.onidle "!list play best_hits"` <- Play a playlist
You can set the event to anything you can also use in the chat when interacting with the bot directly.
