### ISSUE TITLE
Need Animated Channel Commander For TS3AudioBot

### ISSUE THREAD

**Issue by NetworkDir** [Splamy/TS3AudioBot#929]
I tried to do this with AutoChannelCommander.dll but when loading the plugin I encounter an unknown error, and I encounter TS3Client Assembly error console
Can you fix this error or send me the correct version of AutoChannelCommander.dll?
Excuse me for my English :(
-------------------------
TS3AudioBot Version : .NET Core (5.0.7) [0.12.2 Release]
-------------------------
Error In Loading : Plugin error: UnknownError
-------------------------
Error In Bot Console : 
5:06:29.1870| WARN|0| Any source or binary plugin file must contain at least on
e plugin or factory. ("TS3Client.dll (Unknown)")
15:06:29.1958|ERROR|0| Plugin 'AutoChannelCommander (BotPlugin)' failed to load:
 Could not load file or assembly 'TS3Client, Version=1.0.0.0, Culture=neutral, P
ublicKeyToken=null'. The system cannot find the file specified..
-------------------------
Of course, I had to use .net core to load the plugin. If possible, give me this plugin for Linux.

**Comment by Flakebi** [comment]
This is a problem of the plugin, not the audiobot.
It looks like the [plugins](https://github.com/Bluscream/TS3AudioBotPlugins) are not updated anymore and do not work with the current version of the audiobot, so you can only try to fix them yourself.

**Comment by NetworkDir** [comment]
umm you can fix?
