### ISSUE TITLE
Webinterface login didn't work 

### ISSUE THREAD

**Issue by DennisAncelotti** [Splamy/TS3AudioBot#932]
Hello together,

((Sry for bad English bdw))

I type to the bot !api token and geht the token, but if I try to login it's says me invailed token, did I forgot anything?
Installed on a windows Server

**Comment by DennisAncelotti** [comment]
ok, api token works now but this happens if i try to log in, cant get Bot List or any other informations: 

![grafik](https://user-images.githubusercontent.com/44170131/128599001-1100f432-8eaa-439b-8f1a-c0b62dc5ac5d.png)

**Comment by Splamy** [comment]
How is your permission configuration (`rights.toml`)?
You should make sure that the uid you are using the interface with has all permissions to use it.
The easiest rule for example to set this up is:
```toml
[[rule]]
useruid = [ "<YourUID>" ]
"+" = "*"
```

**Comment by DennisAncelotti** [comment]
oh, i just tryed it with my Server Group ID, not with my Identity...
works now.. :)
