### ISSUE TITLE
SSL compatibility

### ISSUE THREAD

**Issue by KutaroKazuki** [Splamy/TS3AudioBot#939]
Since i try to get everywhere an SSL connection on my side i would be glad to see a way you could implement it too :)

**Comment by KutaroKazuki** [comment]
Never mind solved it with a reverse proxy

**Comment by Splamy** [comment]
That's what i'd recommend anyway. While asp supports ssl it's usually not that good since it makes everything more complicated than a comparable setup with a reverse proxy.

**Comment by Vafin84** [comment]
> That's what i'd recommend anyway. While asp supports ssl it's usually not that good since it makes everything more complicated than a comparable setup with a reverse proxy.

Hi! When using an SSl connection, I found that the API partially loses its functionality. For example, the Get request stops working.
 Get {{baseUrl}}/bot/template/:botName/(/play/http%3A%2F%2Fep256.hostingradio.ru%3A8052%2Feuropaplus256.mp3/)

{
    "ErrorCode": 10,
    "ErrorName": "CommandError",
    "ErrorMessage": "Could not load. (media: The resource could not be found.)"
}
