### ISSUE TITLE
Disabling bots

### ISSUE THREAD

**Issue by amommd** [Splamy/TS3AudioBot#940]
Hi
There is a problem with my bots
Music bots stop working after 1 to 3 hours and must be given the command! Next or! Py to start singing
Do you have a solution to this problem?
(The bots are running on Windows)

**Comment by Flakebi** [comment]
Hi,
Streams sometimes stop, you can use `!repeat one` or playlists to restart them if they stopped. See also this faq entry: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#streams-stop

**Comment by amommd** [comment]
I did, unfortunately, the problem still exists
Can you send me a config that the user will send a message like! Py or! Next after joining the channel to start reading
A friend has done this and his bots are never interrupted and are always running.
I do not know myself, thank you for helping me solve this problem.
(I mean, after logging in, the bot will restart and start reading again from the beginning)
thank you
