### ISSUE TITLE
Yesterday everything work, today by bot is gone.

### ISSUE THREAD

**Issue by davidbaric** [Splamy/TS3AudioBot#941]
Today i tried to play a song on my bot and i got back this on teamspeak:
Error: Could not load. (youtube: No youtube-dl response)
I tried to setup a config file to download default .mp4 files and then i got another error in console:
20:25:58.0974| INFO|0| User .Dávid requested: !play [URL]https://www.youtube.com/watch?v=AtHsQV0_iBE[/URL]
20:26:10.1201| WARN|0| file_invalid_path: the command failed to execute: invalid file path
20:26:25.0653| INFO|0| Song queue ended: No next song could be played.
20:26:25.2342| WARN|0| custom_error: the command failed to execute: Avatar upload failed: permission_invalid_size: the command failed to execute: invalid size

**Comment by Splamy** [comment]
Please use our [issue templates](https://github.com/Splamy/TS3AudioBot/issues/new/choose) and fill out all necessay information for us to know the context of the problem.
