### ISSUE TITLE
Tell me where to configure for the bot to connect to a specific channel ?

### ISSUE THREAD

**Issue by Angarsk3** [Splamy/TS3AudioBot#946]
Tell me where to configure for the bot to connect to a specific channel ?

**Comment by Flakebi** [comment]
You can either set it by command: `!settings set connect.channel "/5"` to connect to the channel with id 5
or in the config file that is somewhere in the `bots/` folder (there should be a commented out entry in the `[connect]` block that accepts the same format, e.g. `channel = "/5"`).

**Comment by Angarsk3** [comment]
That's how I have
`#The language the bot should use to respond to users. (Make sure you have added the required language packs)
language = "ru"
#Starts the instance when the TS3AudioBot is launched.
run = true

[commands]

[commands.alias]

[connect]
#The server password. Leave empty for none.
server_password = {  }
#The default channel password. Leave empty for none.
channel_password = { pw = "", hashed = false, autohash = false }
#Overrides the displayed version for the ts3 client. Leave empty for default.
client_version = { build = "5.0.0-test-192 [Build: 1555445179]", platform = "Windows", sign = "2***************H9LPbergYHKASwWc+Sj6iBO3Y/jSzCaw***********JcFtyku4DN08mCDg==" }
#The address, ip or nickname (and port; default: 9987) of the TeamSpeak3 server
address = "8***********48"
#Client nickname when connecting.
name = "Kiss FM"

[connect.identity]
#||| DO NOT MAKE THIS KEY PUBLIC ||| The client identity. You can import a teamspeak3 identity here too.
key = "MCkDAgbAA***********5BoUsHkIluDfAGTCt9niN5KC5Mw=="
#The client identity offset determining the security level.
offset = 42

[reconnect]

[audio]
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
volume = { default = 68.0 }

[playlists]

[history]

[events]
`

**Comment by Flakebi** [comment]
You can try to add a `channel = "/5"` line to the `[connect]` block (replace 5 with the channel id you want or specify a full path like `"parent channel/middle channel/channel name to join"`).

**Comment by Angarsk3** [comment]
When restarting deletes the line channel = "/5"

**Comment by tobias-dietz** [comment]
Had the same problem. In my case, the bot had not enough permissions to join the selected channel, so he stayed in the default channel. In my case it was at least b_channel_join_permanent that was missing. Try to assign the "Normal" servergroup to the bot or make a dedicated group with the required permissions.
