### ISSUE TITLE
problem with building plugin

### ISSUE THREAD

**Issue by ghost** [Splamy/TS3AudioBot#952]
**Describe the bug**
Many ts3audiobot depencies missing

**To Reproduce**
build example plugin from ts3audiobot docs with visual studio 2019 (Windows)
**Version**
lastest
**Platform**
Windows
.Net 2.1

![image](https://user-images.githubusercontent.com/69220487/144218088-7f879608-57f0-4ba4-b3d5-0ff9e0948cf5.png)

**Comment by kevingroeger** [comment]
This comment https://github.com/Splamy/TS3AudioBot/issues/803#issuecomment-719984506 helped me out here, it might help you as well. Good luck!

**Comment by ghost** [comment]
> This comment [#803 (comment)](https://github.com/Splamy/TS3AudioBot/issues/803#issuecomment-719984506) helped me out here, it might help you as well. Good luck!

it helped me thanks
