### ISSUE TITLE
Plugin assign group to user

### ISSUE THREAD

**Issue by TrickShotMLG02** [Splamy/TS3AudioBot#956]
I am creating a little group assigner and i can't find out how to get the dbid from a users uid for the ServerGroupAddClient() Method.

```
public string CommandAssignRoleMember(InvokerData invoker)
{
	tsClient.ServerGroupAddClient(memberServerGroupId, tsClient.GetClientDbIdFromUid(invoker.ClientUid).Result.Value.ClientDbId);
	return "success";
}
```

The code above doesn't work. Could anybody help me?

**Comment by Splamy** [comment]
You will need to make your command async:

```csharp
public async Task<string> CommandAssignRoleMember(Ts3Client ts3client, TsFullClient ts3FullClient, InvokerData invoker)
{
	var uid = await ts3client.GetClientDbIdByUid(invoker.ClientUid);
	await ts3FullClient.ServerGroupAddClient(memberServerGroupId, uid);
	return "success";
}
```

If you are confused why I'm using two different client classes:
- `Ts3Client` is a conveniece wrapper around `TsFullClient` to make common functions easier, like the `GetClientDbIdByUid` method.
- `TsFullClient` is the raw full connection of the `TSLib` project.
