### ISSUE TITLE
change command function

### ISSUE THREAD

**Issue by ulasbynr** [Splamy/TS3AudioBot#958]
The !yt command allows the bot to confirm "yes - no" from the server.
How can I set this command as !yt youtube link? I would really apreciate if you help.

For example : search = "!x (!search from youtube (!param 0)) (!search play 0)"

How can I do the same thing so that it opens youtube links, not !yt? :)

Note: I don't know English, I wrote it here as google translate, sorry if I made a mistake.

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs
