### ISSUE TITLE
Libopus issue

### ISSUE THREAD

**Issue by Amarthurin** [Splamy/TS3AudioBot#959]
Hello,
I have installed windows server 2019 on my server. I get the following error when I try to open Ts3AudioBot.

`2022-01-19 13:34:09.1788|ERROR|Core|NativeLibraryLoader.DirectLoadLibrary Failed to load library "libopus", error: 0
2022-01-19 13:34:09.2466|ERROR|Core|Setup.SetupLibopus Couldn't find libopus. Make sure it is installed or placed in the correct folder.
`

How can i fix this ?

**Comment by vc221b** [comment]
can you install the vc++ redistributable 2015 for x64: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by vc221b** [comment]
from https://github.com/Splamy/TS3AudioBot/issues/191
