### ISSUE TITLE
 The rights file could not be parsed

### ISSUE THREAD

**Issue by MOU12138** [Splamy/TS3AudioBot#961]
**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
Steps to reproduce the behavior

**System Information**
- **Platform**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **Mono version**: (`mono -V`)  
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by MOU12138** [comment]
I can't !api token because he told me You cannot execute 'api token'. You are missing the 'cmd.api.token' right!

**Comment by MOU12138** [comment]
I need help

**Comment by MOU12138** [comment]
I found in other questions that the permission needs to be added but the permission cannot be added

**Comment by Splamy** [comment]
Since you didn't add a lot of information i can only guess from your title, that you have a syntax error in your rights.toml file.
Can you post the content of the file?
Also the exception should give you a hint where the error is.
