### ISSUE TITLE
How to add !play link command in queue?

### ISSUE THREAD

**Issue by RewLoad** [Splamy/TS3AudioBot#971]
This is the command I use to queue up the song name.
y = "!xecute (!search from youtube (!param 0)) (!search add 0)"

What if I want to queue a song with a link?
I've been searching for this method for a long time, help me please.

**Comment by Flakebi** [comment]
There is the `!add <link>` command for that.
(`!play` <-> `!search play` and `!add` <-> `!search add`)

**Comment by RewLoad** [comment]
@Flakebi Where do I have to put it?

**Comment by Bartek200219** [comment]
Just use !add <link>
