### ISSUE TITLE
Feature: Change audio codec when connecting to a channel

### ISSUE THREAD

**Issue by xelantro** [Splamy/TS3AudioBot#976]
**Is your feature request related to a problem? Please describe.**
All of our channels have opus voice (and Quallity 8) to make the experience better for users with bad internet.
But when you want to listen to music we would like to switch to opus music (and Quallity 10)

**Describe the solution you'd like**
Make the bot change the audio codec to opus music and the Quallity to 10 when joining a channel (and add configuration options for that for other users)
It would also be nice if the bot changes the settings back to before (or to configurable default) when leaving the channel

Alternativly you could just add a command ("!channel codec "opus-music", !channel quality 10) to change theese settings and add onChanneljoin and onChannelleave events (wich also trigger when the bot gets moved) and rest can setup by users even better.

**Describe alternatives you've considered**
An alternative would of cause be to change it manually, but not everyone has rights to do that.
And we dont want to change all channels to opus music as described above

**Comment by Flakebi** [comment]
Hi, the bot ignores the audio codec on the channel and uses the opus music codec anyway. So, you can leave your codec on opus voice, even when a bot is present.
The audio quality of the bot can be changed with the `bot.audio.bitrate` setting.

**Comment by 5trubel** [comment]
I think he means the channel codec and not the codec that the bot uses to play the music.
The part in the Picture.
![image](https://user-images.githubusercontent.com/45943082/159937340-65351e5e-4d97-4f0c-b567-6502ff5b8daf.png)

**Comment by Sneakometer** [comment]
> I think he means the channel codec and not the codec that the bot uses to play the music. The part in the Picture. ![image](https://user-images.githubusercontent.com/45943082/159937340-65351e5e-4d97-4f0c-b567-6502ff5b8daf.png)

The bot ignores the channel codec and plays in opus music. The codec a client is sending is not validated by the teamspeak server and not reencoded too so the bot's effective quality your are hearing as a user is completly independent from the channels codec settings and thus changing the channel codec is not required. Thats a really neat feature if you ask me.

**Comment by xelantro** [comment]
Awesome, I did not know that that was even possible in Teamspeak.
Our old bot hadn't had this feature.
Thank you for the fast responses! - closing
