### ISSUE TITLE
Rights.toml not created.

### ISSUE THREAD

**Issue by AnaLepic** [Splamy/TS3AudioBot#978]
I have a problem where rights.toml isnt created so I was wondering if you could help with it. Is it something I did wrong or ?

**Comment by Flakebi** [comment]
It’s difficult to help without having much information. Could you please fill out the issue template? The info asked there is valuable for us to find problems.

The `rights.toml` files is created in the directory where you start the bot.
I.e. if you are in `/tmp/` and start `/path/to/TS3AudioBot`, it will create a `/tmp/rights.toml` file.
Also, you need to start the bot interactively from a terminal on the first time, it will ask some questions like your TeamSpeak client uid and the address to connect to.
