### ISSUE TITLE
Teamspeak 5 Server compatibility

### ISSUE THREAD

**Issue by Timon0586** [Splamy/TS3AudioBot#982]
Hello,

teamspeak has a teamspeak 5 Server (beta.voice.teamspeak.com) and actually the ts3audiobot cant connect to the teamspeak 5 Server. Can you check and update this please? or if you're a teamspeak 3 alpha tester so you can connect with the teamspeak 3.6.0 alpha and yeah .. i hope you can update this.

Best regards

**Comment by Flakebi** [comment]
Thanks for the heads-up, there seems to be a new block in the license. This should be supported with 35300d1 (just pushed to the `develop` branch).
