### ISSUE TITLE
[Linux] The bot does not start

### ISSUE THREAD

**Issue by Snogard** [Splamy/TS3AudioBot#986]
**Describe the bug**
The bot does not start and gives out an error

**To Reproduce**
1. download the last release
2. install all the dependencies (dotnet is installed from archlinux community repositories)
3. try to run the bot

**Version**
0.12.0

**Platform**
Archlinux, kernel 5.17.6 zen 

dotnet:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.120
 Commit:    6f5755c372

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.120/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.120 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
mono: 
```
Mono JIT compiler version 6.12.0 (makepkg/ed0788bf61f Sun Apr 24 04:25:18 PM UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

**Log**
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at TS3AudioBot.Setup.Main(System.String[])
[1]    24178 IOT instruction (core dumped)  ./TS3AudioBot

```

**Comment by Splamy** [comment]
Try installing the `icu` package https://archlinux.org/packages/core/x86_64/icu/

**Comment by Snogard** [comment]
i had it already installed, this is what "pacman -Qs icu" returns:
![image](https://user-images.githubusercontent.com/23384960/168897474-73978484-d94a-4767-b05f-ca501696751c.png)

**Comment by Flakebi** [comment]
I tried to reproduce this problem, but it works fine for me. What I tried:
```
# Start arch
docker run --rm -it archlinux
# … update packages, install wget and unzip
# Install dependencies
pacman -S opus ffmpeg
# Install dotnet 3.1
pacman -S dotnet-runtime-3.1
# Download master version (0.12.2)
wget -o ts3audiobot.zip https://splamy.de/api/nightly/projects/ts3ab/master/download
unzip ts3audiobot.zip
dotnet TS3AudioBot.dll
# Starts as expected

# Also tried the native version
wget -o ts3audiobot.tar.gz https://splamy.de/api/nightly/projects/ts3ab/develop_linux_x64/download
tar xf ts3audiobot.tar.gz
./TS3AudioBot
# Starts as expected
```

Where did you get your dotnet sdk?
Can you try with the latest master or develop version please? (0.13.0 or 0.12.2)

**Comment by Snogard** [comment]
Retested 0.12.0 (linux version) downloaded from github: same icu error
Tested 0.12.2 downloaded from your first link: it starts up
Tested 0.12.2 dowloaded form [this link](https://splamy.de/api/nightly/projects/ts3ab/master_linux_x64/download): same icu error
Tested 0.13.0 dowloaded from [this link](https://splamy.de/api/nightly/projects/ts3ab/develop_linux_x64/download): it starts up

I'll be testing the bot functionality next (the 0.13.0 linux version) to see if everything works.

Note: The linux download links from the readme return a 404 error

**Comment by Snogard** [comment]
0.13.0 is missing "package.json" i cannot build the web interface
![image](https://user-images.githubusercontent.com/23384960/169061308-831e3d44-4d03-4428-8db6-fe91894d0f59.png)

**Comment by Snogard** [comment]
Well is seems that the bot is working as intended so i'll close this issue. Thanks for your help.
