### ISSUE TITLE
How do I reboot a bot via command?

### ISSUE THREAD

**Issue by MYSTICWIND1** [Splamy/TS3AudioBot#987]
I want to reboot the bot and get back into the server automatically, is there a command?

**Comment by Flakebi** [comment]
Hi, there is no command that does exactly that, but it’s possible to get close with other commands.

`!bot connect to <server>` connects a new bot to the given server. One could create a new bot and let the old one leave afterwards.
Chaining commands, this can be done pretty instantly: `!x (!bot disconnect) (!bot connect to <server>)`

If this does not fit what you want, can you describe your case in more detail?
