### ISSUE TITLE
Error getting bot list

### ISSUE THREAD

**Issue by itseyup** [Splamy/TS3AudioBot#988]
Hello, I couldn't manage to enter bot list or Overview in Web Interface. In bot list I get this error "Error getting bot list", In Overview I get this error "Failed to get system information".

**Comment by NaphtholMizuha** [comment]
how did you make it?

**Comment by Splamy** [comment]
Most commonly a permission issue, check this comment https://github.com/Splamy/TS3AudioBot/issues/932#issuecomment-894799839
