### ISSUE TITLE
Setup Problems/Youtubedl

### ISSUE THREAD

**Issue by msebastian100** [Splamy/TS3AudioBot#989]
Hello,
First of all, thank you for this music offer.

I have installed the bot according to the instructions
But unfortunately I have problems setting it up.

I have in the rights.toml
I added the admin group & user.

Unfortunately I get a "!bot setup 30mMCW6sI6H1Z0L7bKiNenwPIuyd5pD3W4QSMkvL" when I use the command.
returns the error: "[B][COLOR=red]Error: [/B]You cannot execute 'bot setup'. You are missing the 'cmd.bot.setup' right!"

I attach the log files with
[ts3audiobot_2022-05-29_11_28_22(Public).log](https://github.com/Splamy/TS3AudioBot/files/8793171/ts3audiobot_2022-05-29_11_28_22.Public.log)
[ts3audiobot_2022-05-29_11_25_42 (Public).log](https://github.com/Splamy/TS3AudioBot/files/8793172/ts3audiobot_2022-05-29_11_25_42.Public.log)

**Comment by msebastian100** [comment]
Error fixed For 

Important: in the Rights.toml
Write UserID in "".

Existing problem:

Youtube Dl does not work after installation

Error:
"[B][COLOR=red]Error: [/B]Could not load. (youtube: youtube-dl could not load the resource.)"

Config: ts3audiobot.toml
Youtube-dl = { path = "/usr/local/bin/youtube-dl" }

**Comment by Flakebi** [comment]
`youtube-dl could not load the resource`

This is a problem of YouTube and youtube-dl. Updating youtube-dl usually fixes those errors.
