### ISSUE TITLE
Specify the path of the config file

### ISSUE THREAD

**Issue by luzzbe** [Splamy/TS3AudioBot#99]
Hello,
I wanted to know if it was possible to specify the path of the config file.
An option like TS3AudioBot.exe -q -p "configs/config1.cfg". And if that's not possible give me a clue to add this featureality.
Thank you in advance,
Tim

----
sorry for my English

**Comment by JABirchall** [comment]
Clue: https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/MainBot.cs#L112

**Comment by Splamy** [comment]
At the moment there's no possibility, but this feature seems pretty straight forward and easy to do, so I will add it shortly

**Comment by luzzbe** [comment]
Again thanks for your reactivity and your listening!
