### ISSUE TITLE
Encrypted login to TS3Audiobot panel

### ISSUE THREAD

**Issue by farfik1** [Splamy/TS3AudioBot#997]
Hello,

Is it possible to login to the TS3Audiobot panel with a Password, not an Api key? If possible, how can I install it?

**Comment by itseyup** [comment]
I'm currently searching it too. If you find any results, just let me know...

**Comment by farfik1** [comment]
Arayüz kodlamasını kendime göre kodlayarak bazı kodları da internetten alarak aktif ettim. Api yerine şifre ile giriyorum

**Comment by itseyup** [comment]
@farfik1 Bunu discord'dan konuşabilir miyiz? Eyüp#7527

**Comment by farfik1** [comment]
Mükemmel Bir İnsan#2452

**Comment by Flakebi** [comment]
> Is it possible to login to the TS3Audiobot panel with a Password, not an Api key?

No, only api keys are supported.
