### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by carbon2001** [Splamy/TS3AudioBot#999]
What is the reason for the slow song ordering bot?

**Comment by Splamy** [comment]
Can you explain more detailed what you mean? What did you call?

**Comment by ShadowFM** [comment]
Hi @carbon2001, 
with such a message nobody can help you.

Please use and fill out one of the templates Splamy provided unless they are not applicable or you have a good reason not to.
This helps anyone getting through the technical stuff faster.
